### ISSUE TITLE
设置wi'd'h't

### ISSUE THREAD

**Issue by htfcumt2004** [OpenFlutter/flutter_ScreenUtil#10]
Container(
                  width: ScreenUtil().setWidth(375),
                  height: ScreenUtil().setHeight(375),
                  color: Colors.blue,
                  child: Text('我的宽度:${ScreenUtil().setWidth(375)}dp',
                      style: TextStyle(
                        color: Colors.white,
                        fontSize: ScreenUtil().setSp(24, false),
                      )),
                ),
在 iphone XR  还有部分安卓上 显示长方形？

**Comment by lizhuoyuan** [comment]
Duplicate of 11#
