### ISSUE TITLE
在项目中使用时报错获取screenutil组件库异常

### ISSUE THREAD

**Issue by daydreamerx9** [OpenFlutter/flutter_screenutil#100]
![image](https://user-images.githubusercontent.com/36780925/76695137-a8c84680-66b6-11ea-9e83-616b6e45ad2f.png)

**Comment by lizhuoyuan** [comment]
应该在home里的homepage中初始化

**Comment by YDJSZY** [comment]
@lizhuoyuan 如果没有设置homepage呢，路由的形式

**Comment by lizhuoyuan** [comment]
> @lizhuoyuan 如果没有设置homepage呢，路由的形式

那就用路由中的第一个页面
