### ISSUE TITLE
我是用fish_redux做的页面，请问如何初始化啊？

### ISSUE THREAD

**Issue by 4pxzhou** [OpenFlutter/flutter_screenutil#102]
RT，我是用fish_redux做的页面，请问如何初始化啊？

**Comment by lizhuoyuan** [comment]
在第一个要展示的页面里初始化

**Comment by 4pxzhou** [comment]
> 在第一个要展示的页面里初始化
网上没有找到和fish_redux结合的，下面是我第一个页面view.dart部分：
import 'package:fish_redux/fish_redux.dart';
import 'package:flutter/material.dart';
import 'package:jdzh/utils/IconUtils.dart';
import 'action.dart';
import 'state.dart';

Widget buildView(HomeState state, Dispatch dispatch, ViewService viewService) {
  return Container(
    color: Color.fromRGBO(255, 200, 200, 1),
    padding: EdgeInsets.fromLTRB(0, 100, 0, 20),
    child: Flex(
      direction: Axis.vertical,
      children: <Widget>[
        Expanded(
          flex: 1,
          child: Text("_Don't miss_",
          style: TextStyle(
              color: Colors.black87,
              fontFamily: 'logo',
              decoration:TextDecoration.none,
            )
          ),
        ),
        Expanded(
          flex: 6,
          child: Container(
            color: Colors.green,
            child: Column(
              //排除Column默认居中对齐的干扰
              crossAxisAlignment: CrossAxisAlignment.start,
              children: <Widget>[
                Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: <Widget>[
                    Icon(IconUtils.cellphone,color: Colors.black87),
                    Text("手机号码" ,
                        style: TextStyle(
                          fontFamily: "chineses",
                          color: Colors.black87,
                          decoration:TextDecoration.none,
                          fontSize: 18
                       )
                    )
                  ],
                ),
              ],
            ),
          ),
        ),
        Expanded(
          flex: 2,
          child: Container(
            color: Colors.blue,
          ),
        ),
      ],
    ),
  );
}

你看看在哪里写呢？

**Comment by lizhuoyuan** [comment]
return Container( 上面那一行写试试?
不是很确定.

初始化的时机就是拿到context,并且在页面UI渲染前.

**Comment by 4pxzhou** [comment]
> return Container( 上面那一行写试试?
> 不是很确定.
> 
> 初始化的时机就是拿到context,并且在页面UI渲染前.
试了，没有context，不行，，头疼着呢。。刚开学习，源码没看多少，我们以前用过吗？

**Comment by lizhuoyuan** [comment]
> > return Container( 上面那一行写试试?
> > 不是很确定.
> > 初始化的时机就是拿到context,并且在页面UI渲染前.
> > 试了，没有context，不行，，头疼着呢。。刚开学习，源码没看多少，我们以前用过吗？

我并没有用过fish_redux . . .

**Comment by 4pxzhou** [comment]
> > > return Container( 上面那一行写试试?
> > > 不是很确定.
> > > 初始化的时机就是拿到context,并且在页面UI渲染前.
> > > 试了，没有context，不行，，头疼着呢。。刚开学习，源码没看多少，我们以前用过吗？
> 
> 我并没有用过fish_redux . . .

希望作者有空看看，，我是毫无头绪，，，

**Comment by Ycong** [comment]
@4pxzhou 

1.在"viewService.context"可以获取到.
2.建议是在"effect.dart"中进行初始化.

```
Effect<HomeState> buildEffect() {
  return combineEffects(<Object, Effect<HomeState>>{
    Lifecycle.initState: _init,
  });
}

void _init(Action action, Context<HomeState> ctx)  {
    print(ctx.context);
}
```

**Comment by 4pxzhou** [comment]
> @4pxzhou
> 
> 1.在"viewService.context"可以获取到.
> 
> ```dart
> Widget buildView(HomeState state, Dispatch dispatch, ViewService viewService) {
>   print(viewService.context);
>   return Container();
> }
> ```
> 
> 2.建议是在"effect.dart"中进行初始化.
> 
> ```dart
> Effect<HomeState> buildEffect() {
>   return combineEffects(<Object, Effect<HomeState>>{
>     Lifecycle.initState: _init,
>   });
> }
> 
> void _init(Action action, Context<HomeState> ctx)  {
>     print(ctx.context);
> }
> ```

非常感谢，我试试
