### ISSUE TITLE
横竖屏切换的问题

### ISSUE THREAD

**Issue by Chanow** [OpenFlutter/flutter_screenutil#103]
竖屏切换横屏时，宽高能自动适应横屏，但是再切换回竖屏时宽高还是横屏时的大小

**Comment by JElaine** [comment]
怎么自动适应横屏

**Comment by Chanow** [comment]
如果你的宽高和字体大小都是用的ScreenUtil()来设置的话，那么在切换横屏的时候，应该是会自动改变样式的，屏幕的高会变为宽，宽会变为高，ScreenUtil()的计算也就会用新的屏幕宽高来计算，虽然是适应了横屏，但是宽度会被拉伸，最好还是横屏单独做一套样式。

至于我横屏再切换竖屏时样式没有改变的问题，我是在视频播放退出全屏时有的这个问题，目前在有视频的页面的build里加上ScreenUtil.init()退出全屏时重新初始化一次就没问题了

**Comment by arieslee** [comment]
> 如果你的宽高和字体大小都是用的ScreenUtil()来设置的话，那么在切换横屏的时候，应该是会自动改变样式的，屏幕的高会变为宽，宽会变为高，ScreenUtil()的计算也就会用新的屏幕宽高来计算，虽然是适应了横屏，但是宽度会被拉伸，最好还是横屏单独做一套样式。
> 
> 至于我横屏再切换竖屏时样式没有改变的问题，我是在视频播放退出全屏时有的这个问题，目前在有视频的页面的build里加上ScreenUtil.init()退出全屏时重新初始化一次就没问题了

ScreenUtil.init()方法无效!!!

**Comment by Chanow** [comment]
> > 如果你的宽高和字体大小都是用的ScreenUtil()来设置的话，那么在切换横屏的时候，应该是会自动改变样式的，屏幕的高会变为宽，宽会变为高，ScreenUtil()的计算也就会用新的屏幕宽高来计算，虽然是适应了横屏，但是宽度会被拉伸，最好还是横屏单独做一套样式。
> > 至于我横屏再切换竖屏时样式没有改变的问题，我是在视频播放退出全屏时有的这个问题，目前在有视频的页面的build里加上ScreenUtil.init()退出全屏时重新初始化一次就没问题了
> 
> ScreenUtil.init()方法无效!!!

不知道你是怎么写的，这是我的部分代码，因为在这个页面有视频全屏播放，所以就在build方法里再写了一句ScreenUtil.init(context, width: 375, height: 667);进行初始化，问题就解决了，同理我的其他页面也是这样。

`class _HomeState extends State<Home> {

  @override
  Widget build(BuildContext context) {
    ScreenUtil.init(context, width: 375, height: 667);
    return Scaffold(
        //code...
    );`

**Comment by JElaine** [comment]
> > 如果你的宽高和字体大小都是用的ScreenUtil()来设置的话，那么在切换横屏的时候，应该是会自动改变样式的，屏幕的高会变为宽，宽会变为高，ScreenUtil()的计算也就会用新的屏幕宽高来计算，虽然是适应了横屏，但是宽度会被拉伸，最好还是横屏单独做一套样式。
> > 至于我横屏再切换竖屏时样式没有改变的问题，我是在视频播放退出全屏时有的这个问题，目前在有视频的页面的build里加上ScreenUtil.init()退出全屏时重新初始化一次就没问题了
> 
> ScreenUtil.init()方法无效!!!

可以抽象一个初始化的方法，在build中直接调用此方法就行
// 初始化设计稿尺寸
void ScreenInit(BuildContext context) {
  MediaQueryData mediaQuery = MediaQuery.of(context);
  if (mediaQuery.size.width > mediaQuery.size.height) {
    ScreenUtil.init(context, width: 1334, height: 750, allowFontScaling: true);
  } else {
    ScreenUtil.init(context, width: 750, height: 1334, allowFontScaling: true);
  }
}

**Comment by lizhuoyuan** [comment]
> > 如果你的宽高和字体大小都是用的ScreenUtil()来设置的话，那么在切换横屏的时候，应该是会自动改变样式的，屏幕的高会变为宽，宽会变为高，ScreenUtil()的计算也就会用新的屏幕宽高来计算，虽然是适应了横屏，但是宽度会被拉伸，最好还是横屏单独做一套样式。
> > 至于我横屏再切换竖屏时样式没有改变的问题，我是在视频播放退出全屏时有的这个问题，目前在有视频的页面的build里加上ScreenUtil.init()退出全屏时重新初始化一次就没问题了
> 
> ScreenUtil.init()方法无效!!!

```
 ScreenUtil.init(context,
              width: 1500, height: 1334, allowFontScaling: false);
          setState(() {});
```
重置init之后调用一下setState试试
