### ISSUE TITLE
平板适配问题

### ISSUE THREAD

**Issue by cn-Meepo** [OpenFlutter/flutter_screenutil#107]
你好，请问为什么在平板和手机上效果不一呢？在手机上没超出边距，平板上就可能超出。

**Comment by lizhuoyuan** [comment]
看一下具体的代码

**Comment by cn-Meepo** [comment]
![image](https://user-images.githubusercontent.com/28797329/79830641-71953580-83d8-11ea-9945-a048240b4cf2.png)
![image](https://user-images.githubusercontent.com/28797329/79830710-94bfe500-83d8-11ea-81eb-f4de7d2f4c8e.png)
像这样的，平板和手机显示就会不一致

**Comment by lizhuoyuan** [comment]
应该是text的宽度不同导致的吧 
限制一下外层container的宽度试试

**Comment by cn-Meepo** [comment]
高度适配也有问题，设计尺寸是375x667，手机像素是1920x1080，平板是2560 x 1600，比如手机上设置500.h高度正好到底，在平板上要么超出，要么就不到底

**Comment by lizhuoyuan** [comment]
我回头试一下，看能否发现问题

**Comment by love626947341** [comment]
> 高度适配也有问题，设计尺寸是375x667，手机像素是1920x1080，平板是2560 x 1600，比如手机上设置500.h高度正好到底，在平板上要么超出，要么就不到底

我再ipadAir上发现同样的问题。手机上没有问题。高度返回的偏小。导致UI控件溢出了

**Comment by Zzy0706** [comment]
好像是对于默认横屏的平板来说，竖屏后宽和高识别反了😳，把溢出的setWidth和setHeight调换一下就不会溢出了

**Comment by lizhuoyuan** [comment]
默认较短的是宽， 也就是 宽 < 高 

![image](https://user-images.githubusercontent.com/15923901/87110962-d86d1100-c29a-11ea-8e84-4b295d4b4a70.png)
