### ISSUE TITLE
在华为HONOR20 PRO中，使用ScreenUtil.screenHeightDp获得高度，2次不一样。

### ISSUE THREAD

**Issue by inprise1980** [OpenFlutter/flutter_screenutil#108]
在华为HONOR20 PRO中，使用ScreenUtil.screenHeightDp获得高度，2次不一样。
在A界面的initState()方法，使用ScreenUtil.screenHeightDp方法获取屏幕高度，第一次_currentScreenHeight=739.3333333333334；
第二次以后
_currentScreenHeight=744.0；

这是bug吗？使用的是0.5.1版本

**Comment by lizhuoyuan** [comment]
看一下是否是因为后者的类型是int呢？

**Comment by inprise1980** [comment]
是指_currentScreenHeight？ _currentScreenHeight是double类型;
class _xxxxPageState extends BaseState<xxxxPage>{
    double _currentScreenHeight;
    initState(){
        _currentScreenHeight=ScreenUtil.screenHeightDp;
        print("_currentScreenHeight=$_currentScreenHeight");
    }    
}
第一次打印_currentScreenHeight=739.3333333333334；
第二次以后_currentScreenHeight=744.0；

**Comment by inprise1980** [comment]
直接在initState方法中用print("高${ScreenUtil.screenHeightDp}");也是一样的结果，第一次与后面不一样。

**Comment by lizhuoyuan** [comment]
我还没有这个手机
其他的我还没有复现这个bug。
暂时搁置吧
