### ISSUE TITLE
设置widt'h

### ISSUE THREAD

**Issue by htfcumt2004** [OpenFlutter/flutter_ScreenUtil#11]
Container(
                  width: ScreenUtil().setWidth(375),
                  height: ScreenUtil().setHeight(375),
                  color: Colors.blue,
                  child: Text('我的宽度:${ScreenUtil().setWidth(375)}dp',
                      style: TextStyle(
                        color: Colors.white,
                        fontSize: ScreenUtil().setSp(24, false),
                      )),
                ),
在 iphone XR  还有部分安卓上 显示长方形？

**Comment by lizhuoyuan** [comment]
统一使用setWidth 就好了
setHeight是为了在高度上进行适配来用的~
