### ISSUE TITLE
初始化按1242*2208设置，则两块Container拼接会出现一条白线

### ISSUE THREAD

**Issue by yhz199132** [OpenFlutter/flutter_screenutil#112]
初始化按1242*2208设备，则两块Container拼接会出现一条白线，而按照默认1080初始化则没有，
示例：ScreenUtil.init(context, width: 1242, height: 2208);
ListView(
        children: <Widget>[
          Container(
            color: color_main,
            height: 100.h,
          ),
          Container(
            color: color_main,
            height: 100.h,
          ),
          Container(
            color: color_main,
            height: 100.h,
          ),

        ],
      )
所用版本:1.1.0

**Comment by lizhuoyuan** [comment]
你是说哪里的白线

**Comment by lizhuoyuan** [comment]
先关了
暂时认为是其他问题 有问题再开
