### ISSUE TITLE
ScreenUtil in ThemeData throws error

### ISSUE THREAD

**Issue by talatkuyuk** [OpenFlutter/flutter_screenutil#113]
Normally I use ScreenUtil and it works very well. But,

When I use screenutil features in ThemeData, the app throws error: "The method 'setSp' was called on null" or "The method 'setHeight' was called on null", respectivle when i use forexample 24.sp and 32.h in TextTheme of ThemeData.

This happens because I have to initialize the ScreenUtil before MaterialApp some how before ThemeData be set. But when I initialize the ScreenUtil before MaterialApp, in build method of MyApp, then it throws another error:  MediaQuery.of() called with a context that does not contain a MediaQuery. I have also tried to initialize the ScreenUtil in MaterialApp builder, again I received the same error.

Actually I want to use ScreenUtil in ThemeData, because I would like to set TextStyles of all texts which I use in my program in one and entry place.

I am sure that it works very well when I set it in the page in the MaterialApp's home, no problem. The problem is that I suppose the ThemeData be constructed and set before MaterialApp's home page. So, it prevents me to use ScreenUtil in ThemeData.

I couldn't figure out the solution. I need to use ScreenUtil in ThemeData.

**Comment by lizhuoyuan** [comment]
I think I understand what you mean,  ScreenUtil relies on Context, but you want to set some font styles before this.
I think you can try to give a parameter assuming an initial value such as textSize = 10. Of course, I know that 10 is not what you need, but you can update the textSize to the value you want after getting the context, that is, after initializing ScreenUtil, I think this should work.
