### ISSUE TITLE
屏幕适配，真的适配吗？

### ISSUE THREAD

**Issue by xiejibiao** [OpenFlutter/flutter_screenutil#116]
以下是代码：
![image](https://user-images.githubusercontent.com/30366768/82906366-b7c15400-9f97-11ea-829a-b85f8d9cea78.png)

以下是效果：
![image](https://user-images.githubusercontent.com/30366768/82906201-76c93f80-9f97-11ea-842d-ea75593c3925.png)

有点看不懂的操作，头部我已经固定是240.h ，但是做出来的效果，差距有点大

**Comment by GimiZhang** [comment]
我这边也是这问题，适配效果不好

**Comment by lizhuoyuan** [comment]
给sizebox个背景看一下,确认一下间距的确是它的高度 . 
然后再看看是不是P20太长? 还是什么原因?
