### ISSUE TITLE
字体跟随系统缩放出问题

### ISSUE THREAD

**Issue by deng2573** [OpenFlutter/flutter_screenutil#121]
当我在 constants.dart 文件定义 final titleSize  = 28.sp;
然后在 page.dart 使用
 `Text(
                  'title',
                  style: TextStyle(
                    color: Color(0xFF333333),
                    fontSize: titleSize,
                  ),
                )`
文本就会跟随系统更改字体大小

如果这样写就不会出问题
`Text(
                  'title',
                  style: TextStyle(
                    color: Color(0xFF333333),
                    fontSize: 28.sp,
                  ),
                )`

**Comment by CuoJue21** [comment]
我也遇到同样的问题

**Comment by JanusKun** [comment]
在页面文件中定义全局变量也会存在这个问题，如果是在页面
`@override
  Widget build(BuildContext context) {
    final titleSize = 28.sp；
}`
则不会出现文字跟随系统缩放得问题。

**Comment by deng2573** [comment]
找到原因了
这样写 final titleSize = 28.sp ，titleSize 会无法重新计算 和 赋值，就会按照系统显示字体大小
解决办法 
constants.dart文件定义 final titleSize = 28;
然后在page.dart中使用
Text( 'title', style: TextStyle( color: Color(0xFF333333), fontSize: titleSize.sp, ), )
