### ISSUE TITLE
setSp  null

### ISSUE THREAD

**Issue by Gslvr** [OpenFlutter/flutter_screenutil#122]
The method 'setSp' was called on null.
Receiver: null
Tried calling: setSp(24, allowFontScalingSelf: true)

when I use  screenutil on some fontsize value;

var kMainCardTitle =TextStyle(
    fontSize: ScreenUtil().setSp(24,allowFontScalingSelf: true),
    fontWeight: FontWeight.bold,
    color: Colors.black);  ==> this is title textstyle...;  This have no error

var  kButtonTextStyle = TextStyle(fontSize: 25,color: Colors.redAccent); => this is button 's text textstyle
==> if I use setSp for fontsize in this  I have error  setSp null

**Comment by dynacorp** [comment]
Getting the same error

**Comment by lizhuoyuan** [comment]
Are you sure to use it after tool initialization。
Or provide the case code
