### ISSUE TITLE
Things need to be adjusted on every different phone

### ISSUE THREAD

**Issue by ab-dev-github** [OpenFlutter/flutter_screenutil#124]
Hello,

I have 4 different Android devices and I am trying to use flutter_screenutil to make the UI responsive, but for all 4 different devices, I need to manually adjust the font, widget size etc. Is this how it is expected to work?

I was under impression that if I set UI on one of the phone size correctly, it should work correctly on any other phone or Screensize & all the UI will be responsive.

Please correct me if my understanding is wrong or if I am doing something wrong. It doesn't make sense to make adjustment for all different device as I think it beats the purpose of this utility. I am also new to Flutter - so if something basic is missing, please correct me.

I have following 4 devices:

Nokia:
I/flutter (15670): Device width px:1080.0
I/flutter (15670): Device height px:2154.0
I/flutter (15670): Device pixel density:2.625

TAB:
I/flutter (31840): Device width px:600.0
I/flutter (31840): Device height px:976.0
I/flutter (31840): Device pixel density:1.0

Mi Phone 1:
I/flutter ( 6127): Device width px:720.0
I/flutter ( 6127): Device height px:1280.0
I/flutter ( 6127): Device pixel density:2.0

Mi Phone 2:
I/flutter (24742): Device width px:1080.0
I/flutter (24742): Device height px:1920.0
I/flutter (24742): Device pixel density:3.0

Thanks for your help
- AB

**Comment by ab-dev-github** [comment]
This is how it is set, used the first phone width and height for reference. 

 Widget build(BuildContext context) {
    ScreenUtil.init(context,
        width: 1080, height: 2154, allowFontScaling: false);

**Comment by lizhuoyuan** [comment]
ScreenUtil.init(context,
width: (UI Design Width) , height: (UI Design Height), allowFontScaling: false);
It’s not the size of your phone, the size of the design draft is used here
