### ISSUE TITLE
给个建议

### ISSUE THREAD

**Issue by zzdota** [OpenFlutter/flutter_screenutil#127]
MediaQueryData mediaQuery = MediaQueryData.fromWindow(ui.window);

可以这样拿到媒体查询，这样初始化函数，还有其他地方，就不需要context参数了

**Comment by lizhuoyuan** [comment]
确实是的，之前考虑到即使没有context，但这两个获取到屏幕参数的时机是一样的，但有可能当前没有context来使用，但屏幕参数已经可以获取到，比如flutterboost，是我之前没有想到这个方法，感谢提醒
