### ISSUE TITLE
ScreenUtil.methodName(16) returning the same value 

### ISSUE THREAD

**Issue by ganger1** [OpenFlutter/flutter_screenutil#128]
I am initializing the ScreenUtil like
`ScreenUtil.init(
            height: MediaQuery.of(context).size.height,
            width: MediaQuery.of(context).size.width,
            allowFontScaling: true);`
then i use  `double textSize = ScreenUtil().setSp( 16.0);` 
but returning the same value that i passed in setSp() method for all screens. like i passed 16.0 that is returning 16.0

**Comment by lizhuoyuan** [comment]
```
ScreenUtil.init( height: MediaQuery.of(context).size.height, width: MediaQuery.of(context).size.width, allowFontScaling: true);
```
not mobile height or width
you should use UI Design 's mobile height and width
