### ISSUE TITLE
给作者个建议

### ISSUE THREAD

**Issue by Dboy233** [OpenFlutter/flutter_screenutil#129]
有很多地方用到的都是比例。按比例更能适配屏幕的大小。
在加几个方法和扩展方法，
.widthPercent(0.2)  0.2.wp   20%的屏幕宽度大小。
.heightPercent(0.2)  0.2.hp 20%的屏幕高度大小
.appWidthPercent(0.2)  0.2.awp app所占设备宽度的20%大小
.appHeightPercent(0.2)  0.2.ahp app所占设备高度（除去状态栏和底部虚拟导航栏 所占高度）20%的高度大小

**Comment by lizhuoyuan** [comment]
了解

**Comment by Dboy233** [comment]
辛苦了。老哥。
