### ISSUE TITLE
x系列设备显示效果不一致

### ISSUE THREAD

**Issue by changeyan** [OpenFlutter/flutter_screenutil#13]
我在使用该库时,发现iphone X/XS/XS max /XR中与其他屏幕的设备显示不一致,其中也包括字体问题.
具体表现为,较其余设备widget更高,间距更大,字体缺没有太大变化,导致像被左右挤压了一样.
设计稿使用sketch,画板为iphone8,大小为750*1334,除以上设备以外,其余均比较正常,求解决方法.

**Comment by changeyan** [comment]
刚刚看到了一个被关闭的问题,让统一使用width,那么这样会不会有什么问题呢.比如两个部件的上下间距也使用width.

**Comment by lizhuoyuan** [comment]
统一使用setWidth的缺点就是 设计稿上 可能一个屏幕显示出来的  实际并没有显示完全
如果是滚动页面我觉得没有影响
如果是万全塞满的静态页面 可能会有显示异常 
如果在测试的时候多注意一下 我觉得没有什么问题

**Comment by changeyan** [comment]
感谢解答，以后测试会额外注意的，谢谢。
