### ISSUE TITLE
font size gets zero in release mode.

### ISSUE THREAD

**Issue by Timus23** [OpenFlutter/flutter_screenutil#130]
Flutter version : 1.17.5
Library version: 2.1.0
till version 1.1.0 where context was used it was working fine. after that i upgraded to version 2.1.0 than in debug mode it is working fine but when i build release apk all the font size turns into zero.

**Comment by lizhuoyuan** [comment]
2.1 I have tested it in the release test, and see if some necessary steps have not been performed.Because the version difference is too large, please take a look at the api

**Comment by Pilaba** [comment]
Same issue, maybe is beacuse the use of **MediaQueryData.fromWindow(window)** instead of **MediaQuery.of(context)** in recent versions.

https://github.com/flutter/flutter/issues/14113#issuecomment-357864964

**Comment by lizhuoyuan** [comment]
Because the underlying code is the same, there should be no problem if the location of the call remains unchanged.But I will continue to test and see the possible problems

**Comment by agent3bood** [comment]
I had the same issue, the fix was to move my `ScreenUti.init()` from `main()` to inside the `build()`

**Comment by dufei816** [comment]
me too, in the first widget appBar not displayed，second widget no problem

**Comment by lizhuoyuan** [comment]
> me too, in the first widget appBar not displayed，second widget no problem

Can you show the code?

**Comment by dufei816** [comment]
`void main() {
  Catcher(
    MyApp(),
    debugConfig: Constants.debugOptions,
    releaseConfig: Constants.releaseOptions,
  );
  if (Platform.isAndroid) {
    SystemUiOverlayStyle systemUiOverlayStyle =
        SystemUiOverlayStyle(statusBarColor: Colors.transparent);
    SystemChrome.setSystemUIOverlayStyle(systemUiOverlayStyle);
  }
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  submitPrivacyGrantResult() {
    SharesdkPlugin.uploadPrivacyPermissionStatus(1, (bool success) {
      if (success == true) {
      } else {}
    });
  }

  @override
  void initState() {
    submitPrivacyGrantResult();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
        providers: [
          ChangeNotifierProvider<LoginViewModel>(
            create: (_) {
              LoginViewModel model = LoginViewModel();
              model.initUser();
              return model;
            },
          ),
          ChangeNotifierProvider<ThemeViewModel>(
            create: (_) => ThemeViewModel(),
          )
        ],
        child: Consumer2<ThemeViewModel, LoginViewModel>(
            builder: (context, model1, model2, __) {
          return MaterialApp(
            title: "LOXEN",
            onGenerateRoute: (settings) => Routes.configRoutes(settings),
            navigatorObservers: [routeObserver],
            localizationsDelegates: [
              GlobalMaterialLocalizations.delegate,
              GlobalWidgetsLocalizations.delegate,
            ],
            supportedLocales: [
              const Locale('zh', 'ZH'),
              const Locale('en', 'EN'),
            ],
            theme: model1.themeData,
            home: HomePageWidget(),
          );
        }));
  }
}`


`class HomePageWidget extends StatelessWidget {


  HomePageWidget({Key key}) : super(key: key) {
    .....
  }

  @override
  Widget build(BuildContext context) {
    SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle.light);
    ScreenUtil.init(context, width: 750, height: 1334);
    return MultiProvider(
      providers: [
        .....
      ],
      child: Scaffold(
        body: Builder(
            builder: (context) => Stack(
                  children: <Widget>[
                    Offstage(
                      offstage: context.watch<int>() != 0,
                      child: const InspirationListWidget(),
                    ),
                    Offstage(
                      offstage: context.watch<int>() != 1,
                      child: const MaterialIndexWidget(),
                    ),
                    Offstage(
                      offstage: context.watch<int>() != 2,
                      child: const StudyIndexWidget(),
                    ),
                    Offstage(
                      offstage: context.watch<int>() != 3,
                      child: const MasterIndexWidget(),
                    ),
                    Offstage(
                      offstage: context.watch<int>() != 4,
                      child: minePageWidget,
                    ),
                  ],
                )),
        bottomNavigationBar: Builder(
            builder: (context) => BottomNavigationBar(
                  currentIndex: context.watch<int>(),
                  onTap: (index) {
                    if (index == 3) {
                      if (context.read<LoginViewModel>().isLogin()) {
                        Navigator.of(context).pushNamed(Routes.login_page);
                        return;
                      }
                    }
                    _bottomIndex.value = index;
                  },
                  type: BottomNavigationBarType.fixed,
                  items: <BottomNavigationBarItem>[
                    BottomNavigationBarItem(
                        icon: Image.asset(
                          'images/tab0_default.png',
                          width: 40.w,
                          height: 40.h,
                        ),
                        activeIcon: Image.asset(
                          'images/tab0_active.png',
                          width: 40.w,
                          height: 40.h,
                        ),
                        title: Text(StringResources.shou_ye,
                            style: TextStyle(
                                fontSize: 17.sp,
                                color: context.watch<int>() != 0
                                    ? defaultColor
                                    : activeColor))),
                    BottomNavigationBarItem(
                        icon: Image.asset(
                          'images/tab1_default.png',
                          width: 40.w,
                          height: 40.h,
                        ),
                        activeIcon: Image.asset(
                          'images/tab1_active.png',
                          width: 40.w,
                          height: 40.h,
                        ),
                        title: Text(StringResources.su_cai,
                            style: TextStyle(
                                fontSize: 17.sp,
                                color: context.watch<int>() != 1
                                    ? defaultColor
                                    : activeColor))),
                    BottomNavigationBarItem(
                        icon: Image.asset(
                          'images/tab2_default.png',
                          width: 40.w,
                          height: 40.h,
                        ),
                        activeIcon: Image.asset(
                          'images/tab2_active.png',
                          width: 40.w,
                          height: 40.h,
                        ),
                        title: Text(StringResources.xue_xi,
                            style: TextStyle(
                                fontSize: 17.sp,
                                color: context.watch<int>() != 2
                                    ? defaultColor
                                    : activeColor))),
                    BottomNavigationBarItem(
                        icon: Image.asset(
                          'images/tab3_default.png',
                          width: 40.w,
                          height: 40.h,
                        ),
                        activeIcon: Image.asset(
                          'images/tab3_active.png',
                          width: 40.w,
                          height: 40.h,
                        ),
                        title: Text(StringResources.da_shi_zhuo,
                            style: TextStyle(
                                fontSize: 17.sp,
                                color: context.watch<int>() != 3
                                    ? defaultColor
                                    : activeColor))),
                    BottomNavigationBarItem(
                        icon: Image.asset(
                          'images/tab4_default.png',
                          width: 40.w,
                          height: 40.h,
                        ),
                        activeIcon: Image.asset(
                          'images/tab4_active.png',
                          width: 40.w,
                          height: 40.h,
                        ),
                        title: Text(StringResources.wo_de,
                            style: TextStyle(
                                fontSize: 17.sp,
                                color: context.watch<int>() != 4
                                    ? defaultColor
                                    : activeColor)))
                  ],
                )),
      ),
    );
  }

  void openSplash(BuildContext context) async {
    var data = await SharedPreferencesUtil.getData(Constants.FIRST);
    if (data == null) {
      Navigator.push(context, MaterialPageRoute(builder: (_) => SplashPage()));
      SharedPreferencesUtil.putData(Constants.FIRST, true);
    }
  }
}
`

BottomNavigationBarItem not displayed，appBar InspirationListWidget

`class InspirationListWidget extends StatelessWidget {
  const InspirationListWidget({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: PreferredSize(
        preferredSize: Size.fromHeight(80.h),
        child: .......,
      ),
      body:.........,
    );
  }
}
`

**Comment by Timus23** [comment]
i also used it in main. and added it in the theme but it didn't work. i guess we have to use it after the material app in next widget like in 2nd widget after material app as before than only it works even if it don't required the context.

**Comment by lizhuoyuan** [comment]
> i also used it in main. and added it in the theme but it didn't work. i guess we have to use it after the material app in next widget like in 2nd widget after material app as before than only it works even if it don't required the context.

Yes, although the context parameter is not needed, it actually needs to wait until dart obtains the screen data, generally this is when the context is obtained

**Comment by lizhuoyuan** [comment]
@dufei816 
It looks ok, but I can't run it so I can't debug  .  So sad

**Comment by An-uking** [comment]
@lizhuoyuan 我也是遇到了 测试机型 iphone 11 pro max .  手机上只有布局 没有文字  布局上的文字一个也显示不了

**Comment by An-uking** [comment]
@lizhuoyuan  加延时运可以解决此问题  
void main() {
  Future.delayed(Duration(milliseconds: 100)).then((value){
      runApp(MyApp());
  });
}

**Comment by lizhuoyuan** [comment]
Hello everyone, I already have a plan to use ScreenUtil in MyApp. 
And it should solve the problem that the screen parameters cannot be obtained.
After the test, I will organize the documents and submit the code. 
A new version will be released this week.

**Comment by lizhuoyuan** [comment]
I resolved this at 2.3

**Comment by kenNg1** [comment]
@Timus23 did you do this? `await ScreenUtil.ensureScreenSize();`

I had the same issue as you but after doing this, it was fixed in release mode.

**Comment by Abdulah-butt** [comment]
simply use
flutter_screenutil: 5.8.4

This version works well
