### ISSUE TITLE
字体大小问题

### ISSUE THREAD

**Issue by sxd1140** [OpenFlutter/flutter_screenutil#131]
设计稿
![F19AC03F1E0D8676247BA2F931F2D65C](https://user-images.githubusercontent.com/541212/87004264-bbc7cf00-c1ef-11ea-9990-bc0c659703b8.jpg)

```dart
ScreenUtil.init(width: 750, height: 1334);
Text('我的资料',style: TextStyle(color: Color(0xFF999999), fontSize: 14.sp),
```

ios11
![F59EC24ACA4D6C17BB3AD6CC035E30BA](https://user-images.githubusercontent.com/541212/87004438-fc274d00-c1ef-11ea-8ae3-16f3f9a3a6fe.jpg)

**Comment by lizhuoyuan** [comment]
输入的单位为px ， 所以这里你要看字号是多少px 把这个值穿进去

**Comment by sxd1140** [comment]
哦 `.sp`我以为单位是`sp`呢 谢谢
