### ISSUE TITLE
Screen Util need context

### ISSUE THREAD

**Issue by RomanSoviak** [OpenFlutter/flutter_screenutil#132]
Hi! Thanlks for nice lib! 
Where we should put this line of code with `context`?
`ScreenUtil.init(context, height: 667, width: 375, allowFontScaling: true);
`

**Comment by lizhuoyuan** [comment]
like this
![image](https://user-images.githubusercontent.com/15923901/87763471-6f137200-c847-11ea-9083-9a694165a032.png)
you can see example too.

**Comment by RomanSoviak** [comment]
That's will not working in this case
![image](https://user-images.githubusercontent.com/26696190/87765557-9efb4f00-c820-11ea-97d6-584f49b646cd.png)

**Comment by lizhuoyuan** [comment]
yes.
Because at this time, the screen data of the mobile phone has not been obtained

**Comment by RomanSoviak** [comment]
I understand. Should I init library before building `MaterialApp()`?

**Comment by lizhuoyuan** [comment]
now, you should not use `sp` in the textTheme.
I think you can define the text theme later

**Comment by RomanSoviak** [comment]
@lizhuoyuan but I can define overall theme only in `MaterialApp` class

**Comment by lizhuoyuan** [comment]
> @lizhuoyuan but I can define overall theme only in `MaterialApp` class
Maybe you can give an initial value first and wait for the screen data to be changed
