### ISSUE TITLE
can i init ScreenUtil in app  main () method theme

### ISSUE THREAD

**Issue by philos3** [OpenFlutter/flutter_screenutil#134]
can i init ScreenUtil in app  main () method，

what is the right time to  ScreenUtil.init when i need to set MaterialApp ThemeData，

![image](https://user-images.githubusercontent.com/8424317/88164017-162c4b00-cc46-11ea-9703-71110148272b.png)
![image](https://user-images.githubusercontent.com/8424317/88164085-2f34fc00-cc46-11ea-9dbc-2bdc3a01a833.png)
![image](https://user-images.githubusercontent.com/8424317/88164198-660b1200-cc46-11ea-83d7-2dae8a39a5b3.png)

**Comment by GursheeshSingh** [comment]
https://github.com/OpenFlutter/flutter_screenutil/issues/132

**Comment by lizhuoyuan** [comment]
I see that you use a provider, maybe you can also use a provider for the theme, and update the information after confirming that the screen data is obtained

**Comment by lizhuoyuan** [comment]
A beta version will be launched soon, this method is supported, but flutter beta or newer version is required

**Comment by lizhuoyuan** [comment]
3.0.0-beta.1

**Comment by philos3** [comment]
> 3.0.0-beta.1

Thanks for your help~
