### ISSUE TITLE
screenUtils的获取尺寸的方法，为啥又从原来的window方式获取改为了MediaQuery的方式

### ISSUE THREAD

**Issue by BayMikyou** [OpenFlutter/flutter_screenutil#139]

**Comment by lizhuoyuan** [comment]
因为不用context的话, 只有flutter的beta分支才能正常使用 所以正式版需要context
如果版本>1.17可以使用beta版
pub: https://pub.flutter-io.cn/packages/flutter_screenutil/versions/3.0.0-beta.2
github : https://github.com/OpenFlutter/flutter_screenutil/tree/beta

**Comment by wumeixinjiazu** [comment]
> 
flutter的beta分支才能正常使用是什么意思

**Comment by lizhuoyuan** [comment]
> > 
> 
> flutter的beta分支才能正常使用是什么意思

年代过于久远,  有什么新问题
