### ISSUE TITLE
无法使用全局主题

### ISSUE THREAD

**Issue by sdta25196** [OpenFlutter/flutter_screenutil#140]
在home里初始化宽高，无法在MaterialApp 的theme里使用宽高字号的设置。这导致全局主题就不能用了

**Comment by lizhuoyuan** [comment]
可以使用v3版本，支持外部使用
切换到beta分支 可以看一下。

[v3](https://github.com/OpenFlutter/flutter_screenutil/tree/beta)可用于`flutter> = 1.19.0`  
[v2](https://github.com/OpenFlutter/flutter_screenutil)用于当前Flutter的`stable`版本。
