### ISSUE TITLE
app第一次启动时 没有生效

### ISSUE THREAD

**Issue by JunevaYang** [OpenFlutter/flutter_screenutil#142]
第一次打开app时，screenutil没有其作用，布局全乱了。  用的是2.3.1   ScreenUtil.init是在MaterialApp下

**Comment by lizhuoyuan** [comment]
上代码 ，看一下

**Comment by niugengyun** [comment]
relese模式吧 ？  debug模式没问题

**Comment by niugengyun** [comment]
初始化问题不是bug，我已经处理好了：https://github.com/OpenFlutter/flutter_screenutil/issues/80

**Comment by JunevaYang** [comment]
`
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    final router = Router();
    Routes.configureRoutes(router);
    Application.router = router;

    //全局使用Toast
    return OKToast(
        child: MaterialApp(
          //去除debug标志
          debugShowCheckedModeBanner: false,
          title: 'Flutter Demo',
          onGenerateRoute: Application.router.generator,
          theme: ThemeData(
            primarySwatch: Colors.blue,
            visualDensity: VisualDensity.adaptivePlatformDensity,
          ),
          home: MyHomePage(),
        ),

        /// Toast 配置
        backgroundColor: Colors.black54,
        textPadding:
            const EdgeInsets.symmetric(horizontal: 16.0, vertical: 10.0),
        radius: 20.0,
        position: ToastPosition.bottom);
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    //ScreenUtil 布局适配的初始化  不跟随系统字体变化
    ScreenUtil.init(context, width: 750, height: 1334, allowFontScaling: false);
    return LoginPage();
  }
}
`

确实是debug没有问题， release出现的

**Comment by JunevaYang** [comment]
好的  我试下

**Comment by weichongchong** [comment]
> 第一次打开app时，screenutil没有其作用，布局全乱了。 用的是2.3.1 ScreenUtil.init是在MaterialApp下

怎么解决的？

**Comment by weichongchong** [comment]
> 初始化问题不是bug，我已经处理好了：#80

试了没用

**Comment by lizhuoyuan** [comment]
看看v3版本适不适合你

**Comment by JunevaYang** [comment]
> > 初始化问题不是bug，我已经处理好了：#80
> 
> 试了没用

我是按demo里的 初始化3次

**Comment by weichongchong** [comment]
> 看看v3版本适不适合你

不行，debug没问题，release有问题，偶现的

**Comment by lizhuoyuan** [comment]
> > 看看v3版本适不适合你
> 
> 不行，debug没问题，release有问题，偶现的

flutter 版本是多少？
然后看一下main，myapp  和 初始化部分的代码
