### ISSUE TITLE
您好我是想问您下该插件改在app的什么地方初始化

### ISSUE THREAD

**Issue by bing127** [OpenFlutter/flutter_screenutil#143]
该插件该在app的什么地方进行初始化，可以在MaterialApp 所在的build方法里面进行初始化么，还是在MaterialApp 所在的home对应的页面进行初始化，还是在所有页面的build方法中进行初始化？麻烦给答疑解惑下

**Comment by lizhuoyuan** [comment]
v2版本在home里初始化一次即可
v3可在app之外初始化

具体可看对应分支的example
