### ISSUE TITLE
ScreenUtil.instance | For every Page

### ISSUE THREAD

**Issue by NiranjanShah** [OpenFlutter/flutter_screenutil#146]
Is it mandatory to call ScreenUtil.instance on every page or we can set it at the App level. 
if it can be set @ app level, kindly guide how to do so.

**Comment by lizhuoyuan** [comment]
If you want to set at the application level, you can refer to the example of the beta branch.
If you use the master branch, you can initialize it in the home or initRoute of the MaterialApp, and you only need to initialize it once
