### ISSUE TITLE
Font scaling on orientation change

### ISSUE THREAD

**Issue by onurgunes** [OpenFlutter/flutter_screenutil#149]
Hi,

Font scaling works correctly for different devices but does not work when the orientation changes. The font, which is the desired size in portrait, looks larger in landscape.

I used the library like this:
`Widget build(BuildContext context) {`
`    ScreenUtil.init(context, width: 750, height: 1334, allowFontScaling: true);
    ...
   Text(
         title,
            style: TextStyle(
            fontSize: ScreenUtil().setSp(32, allowFontScalingSelf: true),
            ...
`

Thanks in advance.

**Comment by lizhuoyuan** [comment]
I think you want to keep the original font size even after the horizontal screen (maybe this is the correct idea), but it seems that the font size is now bigger. I will try to make it as expected

**Comment by onurgunes** [comment]
Unfortunately, it didn't work. 

In beta version, I see that parameters that shown in example project like device width, device height etc remains the same both vertical and horizontal. This may cause the problem I mentioned before.

**Comment by lizhuoyuan** [comment]
Maybe we should confirm the effect you want,
To make an analogy:
Assuming the vertical screen, the font size is 20,
In landscape mode, you want the font size to be 30,
do you mean this?

**Comment by onurgunes** [comment]
If we go through the example you have given, I want the font size of 20px in vertical screen to be 15px in landscape mode.
While 20px gives the result I want in vertical, it looks like 30px in landscape mode, which is much bigger than I wanted.

**Comment by lizhuoyuan** [comment]
The current effect is that the vertical and horizontal text sizes are the same.
Even if I make the corresponding correction, I am afraid that it will not be able to achieve the perfect size you want. I think the best way may be to judge the screen orientation to specify the size.

**Comment by cqllzp** [comment]
If you use width: 0.5.wp, height: 200.h as in the example, this value is not refreshed when the screen is flipped, causing the control to be out of scale. Therefore this position needs to be adjusted. Or is there any other way to deal with it. Because this kind of problem is easy to appear in actual projects, if it is not solved, it will affect everyone's normal use.

**Comment by cqllzp** [comment]
![v](https://user-images.githubusercontent.com/3725186/94630951-c5963580-02f9-11eb-9b25-04d27fa860fc.png)
![h](https://user-images.githubusercontent.com/3725186/94630957-c929bc80-02f9-11eb-9b05-2d3e80902c63.png)
I am using the latest routine. This is a cut in different directions under the same device. It seems that the horizontal layout of the processing room is fine. But the font size needs to be adjusted above.

**Comment by hikmawanaz** [comment]
i have same issue, when i rotate my device, everything gonna be bigger (font that use extension .sp and widget thath use extension .w), i think because screenutil will read width of screen that is the height of device when orientation changed to landscape.

How best practice to handle this issue?

**Comment by lizhuoyuan** [comment]
please try 4.0.0-beta1.
maybe it will work

**Comment by lizhuoyuan** [comment]
There is no reply for a long time, so I closed it first, and can reopen it if there is a problem
