### ISSUE TITLE
文档和你的代码不匹配啊

### ISSUE THREAD

**Issue by sunwgit** [OpenFlutter/flutter_screenutil#15]
```dart
ScreenUtil({
    this.width = 1080,
    this.height = 1920,
    this.allowFontScaling = false,
  });
```
以上是你的源码，但你的文档中说allowFontScaling默认为true,而且setSp只有一个参数，文档中还传了allowFontScaling。。。。

**Comment by lizhuoyuan** [comment]
allowFontScaling
我没有说默认为true啊. ..
我说的是false , 
可以全局设置为false/true, 
可以在某个位置单独设置成false/true

**Comment by sunwgit** [comment]
> 文档确有疏忽 已改动

有些还是setSp(14,false)，建议你把你的代码粘贴到vscode，没错误了再粘贴到markdown.

**Comment by lizhuoyuan** [comment]
真是细致. . .
我新版重写了代码结构  有部分没注意到...
