### ISSUE TITLE
调试包正常，正式包高度无法计算

### ISSUE THREAD

**Issue by silentchild** [OpenFlutter/flutter_screenutil#153]
调试包正常，正式包由于高度无法计算页面空白

**Comment by silentchild** [comment]
3.0.2  flutter  1.20.4

**Comment by silentchild** [comment]
正式包返回的值都是0.0

**Comment by lizhuoyuan** [comment]
晚上我用装有1.20的电脑调试一下

**Comment by silentchild** [comment]
好的，么么哒&nbsp; github上那个就是我提的，高度返回的都是0.0




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "LiZhuoyuan"<notifications@github.com&gt;; 
发送时间: 2020年9月23日(星期三) 下午3:59
收件人: "OpenFlutter/flutter_screenutil"<flutter_screenutil@noreply.github.com&gt;; 
抄送: "分寸"<1051918608@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [OpenFlutter/flutter_screenutil] 调试包正常，正式包高度无法计算 (#153)





 
晚上我用装有1.20的电脑调试一下

**Comment by lizhuoyuan** [comment]
![image](https://user-images.githubusercontent.com/15923901/94022438-ad00b980-fde7-11ea-8a64-bbe2a3a32601.png)
我运行了示例代码,么有问题
你看一下是不是初始化少了步骤?
另外机型是什么

**Comment by silentchild** [comment]
> ![image](https://user-images.githubusercontent.com/15923901/94022438-ad00b980-fde7-11ea-8a64-bbe2a3a32601.png)
> 我运行了示例代码,么有问题
> 你看一下是不是初始化少了步骤?
> 另外机型是什么
![360截图20200923220156612](https://user-images.githubusercontent.com/29771808/94023263-99a21e00-fde8-11ea-9017-5789081b430f.jpg)
机型是红米k20

**Comment by lizhuoyuan** [comment]
运行一下我刚上传的apk? 我刚拿一个mate30尝试了一下,硬该不存在手机性能太好导致拿不到数据的问题

**Comment by silentchild** [comment]
好的&nbsp; 我试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "LiZhuoyuan"<notifications@github.com&gt;; 
发送时间: 2020年9月23日(星期三) 晚上10:07
收件人: "OpenFlutter/flutter_screenutil"<flutter_screenutil@noreply.github.com&gt;; 
抄送: "分寸"<1051918608@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [OpenFlutter/flutter_screenutil] 调试包正常，正式包高度无法计算 (#153)





 
运行一下我刚上传的apk? 我刚拿一个mate30尝试了一下,硬该不存在手机性能太好导致拿不到数据的问题

**Comment by silentchild** [comment]
全是0.0




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "LiZhuoyuan"<notifications@github.com&gt;; 
发送时间: 2020年9月23日(星期三) 晚上10:07
收件人: "OpenFlutter/flutter_screenutil"<flutter_screenutil@noreply.github.com&gt;; 
抄送: "分寸"<1051918608@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [OpenFlutter/flutter_screenutil] 调试包正常，正式包高度无法计算 (#153)





 
运行一下我刚上传的apk? 我刚拿一个mate30尝试了一下,硬该不存在手机性能太好导致拿不到数据的问题

**Comment by silentchild** [comment]
> 运行一下我刚上传的apk? 我刚拿一个mate30尝试了一下,硬该不存在手机性能太好导致拿不到数据的问题

测试了，全是0  硬件再不好运行这个肯定没问题啊，毕竟也是2000的手机  才买了一年  运行个小demo应该没啥问题吧，是不是方法不兼容

**Comment by lizhuoyuan** [comment]
之前有过机器性能太好加载过快拿不到屏幕数据的问题,但是flutter新版其实解决了.

你这问题 ... 
我现在复现不出来.

你试试v2版本呢?

**Comment by silentchild** [comment]
> 之前有过机器性能太好加载过快拿不到屏幕数据的问题,但是flutter新版其实解决了.
> 
> 你这问题 ...
> 我现在复现不出来.
> 
> 你试试v2版本呢?

v2版本因为有context  所以没啥问题

**Comment by silentchild** [comment]
> 之前有过机器性能太好加载过快拿不到屏幕数据的问题,但是flutter新版其实解决了.
> 
> 你这问题 ...
> 我现在复现不出来.
> 
> 你试试v2版本呢?

调试模式是好的  这就很诡异，哎呦好烦

**Comment by lizhuoyuan** [comment]
看一下flutter doctor 的输出

**Comment by silentchild** [comment]
> 看一下flutter doctor 的输出
PS D:\work\flutter_base_framework> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.3, on Microsoft Windows [Version 10.0.18363.1110], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.49.1)
[√] Connected device (1 available)

• No issues found!

**Comment by silentchild** [comment]
> 看一下flutter doctor -v 的输出

顺便说一下  手机的安卓版本是10

**Comment by lizhuoyuan** [comment]
明天我看看能不能找个安卓10看看..

**Comment by fine1021** [comment]
我也遇到了，经过一系列的排查，初步确定了原因，我把你那个screenutil.dart下载下来了，加了一些日志，在Profile模式下运行！！！
修改如下：
![image](https://user-images.githubusercontent.com/8346972/94096171-06073680-fe56-11ea-931d-1ad8b286a5fa.png)
打印的结果如下：
![image](https://user-images.githubusercontent.com/8346972/94096287-4cf52c00-fe56-11ea-9c08-14c0432f9c9b.png)
项目初始化代码如下：
![image](https://user-images.githubusercontent.com/8346972/94096328-672f0a00-fe56-11ea-9fb0-478ef5bca109.png)
但是我在某个Route的build函数中WidgetsBinding.instance.window，是可以获取到屏幕相关参数的，测试机型华为Mate20 Pro Android 10，在iPhone 8 Plus上测试也是有这个问题，之前一直使用v2版本，任何模式下都一切正常

得出的初步结论：**初始化接口依旧过早，WidgetsFlutterBinding.ensureInitialized()并不能保证window信息已经拿到**，debug模式下没问题，在profile或者release模式下，window信息如截图所示

运行环境如下：

![image](https://user-images.githubusercontent.com/8346972/94096680-3ef3db00-fe57-11ea-9668-7609a8d3e64e.png)

另外说一下 作者提供的demo测试结果，第一次安装的时候启动能拿到屏幕信息展示，后续再启动就全部是0了

**Comment by fine1021** [comment]
如果使用v3，我这边测试的一种可行方案就是把初始化调换下位置，以demo为例
![image](https://user-images.githubusercontent.com/8346972/94097427-110f9600-fe59-11ea-8162-792116d63373.png)

移动到MaterialApp初始化的地方

**Comment by silentchild** [comment]
> 如果使用v3，我这边测试的一种可行方案就是把初始化调换下位置，以demo为例
> ![image](https://user-images.githubusercontent.com/8346972/94097427-110f9600-fe59-11ea-8162-792116d63373.png)
> 
> 移动到MaterialApp初始化的地方

这样就失去了3.0的意义，我就是希望在build之前使用，不依赖context

**Comment by fine1021** [comment]
> > 如果使用v3，我这边测试的一种可行方案就是把初始化调换下位置，以demo为例
> > ![image](https://user-images.githubusercontent.com/8346972/94097427-110f9600-fe59-11ea-8162-792116d63373.png)
> > 移动到MaterialApp初始化的地方
> 
> 这样就失去了3.0的意义，我就是希望在build之前使用，不依赖context

这是顶级的MaterialApp的build函数，一般来说也只会执行一次，主要还是要延迟等window拿到屏幕信息。
初始化方式的话暂时可以沿用3.0不需要context

**Comment by LaoHuan** [comment]
我也遇到了。今天打包了有些机型显示不行

**Comment by lizhuoyuan** [comment]
现在看还是不依赖context很难保证能获取到屏幕数据,
建议使用v2,
我会继续寻找办法来解决

**Comment by JarvanMo** [comment]
emmm，我也遇到了这个问题。debug好用，release算不出来。

**Comment by lizhuoyuan** [comment]
> emmm，我也遇到了这个问题。debug好用，release算不出来。

用v2吧， 看来v3还是不成熟

**Comment by seekcx** [comment]
几天前装的 beta 版本，一直在debug，没打release包，今天打了release 包全乱了，都不知道发生了啥，一个 commit 一个 commit 的排查，才排到这个插件的问题。
