### ISSUE TITLE
初始化失败

### ISSUE THREAD

**Issue by gstory0404** [OpenFlutter/flutter_screenutil#154]
最新的版本发现在runapp前初始化init()时，app在运行后台被杀，重新打开发现 ScreenUtil.init()并未初始化，app正常运行，但所有使用 ScreenUtil设置了大小的widget均无法显示，andorid必现。 ScreenUtil.init()在main build()中初始化无任何问题。是我使用问题吗？大佬帮忙解决一下

**Comment by lizhuoyuan** [comment]
先使用v2版本吧， 我会看一下这个问题
