### ISSUE TITLE
关于宽高

### ISSUE THREAD

**Issue by lauwen** [OpenFlutter/flutter_screenutil#156]
ScreenUtil().setWidth(200)  (sdk>=2.6 : 200.w) //根据屏幕宽度适配尺寸
ScreenUtil().setHeight(200) (sdk>=2.6 : 200.h) //根据屏幕高度适配尺寸

你好，想问同一设备下200.h是否等于200.w   不等于两者有什么换算关联吗？感谢！

**Comment by lizhuoyuan** [comment]
h 代表height， 是设备的高度
w 代表width， 是设备的宽度

一般都用w就可以 ，而且可以保证不变形

在需要高度也完全匹配设计稿的高度的时候可以使用h ， 一般不需要

**Comment by moujunqiang** [comment]
> 

您好 用w进行适配 着小屏幕和小屏幕显示效果不一样 应该怎么处理呢。有时候固定高度大屏幕可以显示完整，小屏幕就超出范围了

**Comment by lizhuoyuan** [comment]
如果想要高度完全匹配,高度上应该都使用.h
另外,一般推荐用滚动组件包裹这种有可能超出范围的情况

> > 
> 
> 您好 用w进行适配 着小屏幕和小屏幕显示效果不一样 应该怎么处理呢。有时候固定高度大屏幕可以显示完整，小屏幕就超出范围了
