### ISSUE TITLE
Apply extension on double instead of num

### ISSUE THREAD

**Issue by sidrao2006** [OpenFlutter/flutter_screenutil#157]
When enabling strong mode, errors are thrown as num cannot be assigned to double. Since num is extended by double and int and int is not used for sizes, extension on double directly will allow strong type checks to succeed

**Comment by lizhuoyuan** [comment]
If you directly expand on double, the int class will not have this method.
Is it feasible to only change back to double?

**Comment by sidrao2006** [comment]
@lizhuoyuan , thanks for replying
Sorry, I didn't get you. Could you please explain what do you mean by change back to double.

Also, sizes are never `int` in flutter. Even in packages.

**Comment by lizhuoyuan** [comment]
Sorry, the previous reply was wrong, I mean is it possible to change the return value to double?
If only the double function is extended, then the usage will be: 100.0.w,
I hope it can be written as 100.w

**Comment by sidrao2006** [comment]
I think you could try applying extensions on both int and double separately . Try using the same names for both. Dart should automatically apply the extension  as necessary.

**Comment by lizhuoyuan** [comment]
Maybe I can try to do this, it just feels a bit redundant

**Comment by EugenePisotsky** [comment]
@lizhuoyuan there's also an error when null safety is enabled:

> The argument type 'num*' can't be assigned to the parameter type 'double'.
