### ISSUE TITLE
请教一下，我的dart是2.9.2，但是为什么没法使用50.w的方式

### ISSUE THREAD

**Issue by 515445681** [OpenFlutter/flutter_screenutil#160]
请教一下，我的dart是2.9.2，但是为什么没法使用50.w的方式。

```
➜  ~ dart --version
Dart SDK version: 2.9.2 (stable) (Wed Aug 26 12:44:28 2020 +0200) on "macos_x64"
➜  ~ 
```

android studio 里面报错

![image](https://user-images.githubusercontent.com/11323678/94951949-c0163680-0517-11eb-8dbf-f478ba3045e9.png)

**Comment by aikangs** [comment]
请问下你是怎么解决的吗？我也遇到这个问题

**Comment by 515445681** [comment]
在dart文件上面上面引入extension就可以了。
```import 'package:flutter_screenutil/size_extension.dart';```
android studio插件没做extension的自动引入

**Comment by lizhuoyuan** [comment]
可以引入 flutter_screenutil

**Comment by yaochangliang159** [comment]
添加如下引入，即可解决
import 'package:flutter_screenutil/flutter_screenutil.dart';
