### ISSUE TITLE
ver 3.1.1

### ISSUE THREAD

**Issue by NiranjanShah** [OpenFlutter/flutter_screenutil#161]
does the init function still required context ?

ScreenUtil.init(designSize: Size(750, 1334), allowFontScaling: false);

with 3.1.1 it still needs context. Android Studio shouts back stating missing parameter

**Comment by ganeshchenniah** [comment]
Yeah, facing same issue . Any update ?

**Comment by lizhuoyuan** [comment]
need context :
```
ScreenUtil.init(context,designSize: Size(750, 1334), allowFontScaling: false);


```
