### ISSUE TITLE
setWidth and setHeight are not matching the screen

### ISSUE THREAD

**Issue by ganeshchenniah** [OpenFlutter/flutter_screenutil#162]
Hi, 

I have taken your example with 3.1.1 library . The mobile oneplus5 with resolution 1080x1920 px
Container( padding: EdgeInsets.all(10.w), width: 0.5.wp, height: 200.h,) height 200.h is giving 109.65 dp. The same experiment on POCOX2 with resolution 1080x2400 px  is giving 90.90 dp . It should be more than 109 dp right ? 

design reference is ScreenUtil.init(context,designSize: Size(1080, 1920), allowFontScaling: false);

Can you help in finding out root cause ?

Regards,
GaneshC

**Comment by lizhuoyuan** [comment]
`.h` is adapted according to the height, so there will be a gap, if your height: 200.w should be the value will not change.

**Comment by ganeshchenniah** [comment]
Correction , with 3.1.1 version  with 200.h 
1080x1920 is giving 76.19 => (872) deviceHeight in dp / 1920 * 200 
1080x2400 is giving 72.72 . => (731) deviceHeight in dp / 2400 * 200

Ideally Container(200.h) if the device screen height is more , the value should be more right ?

**Comment by lizhuoyuan** [comment]
If the initial size does not change, 200.h will become larger on a longer screen
