### ISSUE TITLE
screenutil获取屏幕高宽错误

### ISSUE THREAD

**Issue by stoneLee81** [OpenFlutter/flutter_screenutil#163]
web h5情况下，获取屏幕高宽还是电脑屏幕高宽
![image](https://user-images.githubusercontent.com/18001708/95701819-29671980-0c7d-11eb-856d-6cda67488397.png)
前面2个是screenutil获取，后面一个mediaquery获取正确
![image](https://user-images.githubusercontent.com/18001708/95701735-fd4b9880-0c7c-11eb-8dd8-1cb85d80aa07.png)

**Comment by lizhuoyuan** [comment]
用錯方法了
```
ScreenUtil().screenWidth   (sdk>=2.6 : 1.wp)    //Device width
```

**Comment by stoneLee81** [comment]
ScreenUtil().setSp 如果用这个函数，默认好像获取的还是1080,是需要自己在设置么？

**Comment by stoneLee81** [comment]
@lizhuoyuan

**Comment by lizhuoyuan** [comment]
需要初始化設置
請參考文檔

**Comment by stoneLee81** [comment]
了解了谢谢
