### ISSUE TITLE
10月22日上午突然报错

### ISSUE THREAD

**Issue by 01BAI** [OpenFlutter/flutter_screenutil#166]
之前在调试，一切正常，突然报错，错误如下

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building Builder:

Ensure to initialize ScreenUtil before accessing it.
'package:flutter_screenutil/screenutil.dart':
Failed assertion: line 31 pos 7: '_instance != null'

The relevant error-causing widget was
MaterialApp
lib/main.dart:15
When the exception was thrown, this was the stack
#2      new ScreenUtil
package:flutter_screenutil/screenutil.dart:31
#3      duSetFontSize
package:group_gate/…/utils/screen.dart:20
#4      new _SignInPageState
package:group_gate/…/sign_in/sign_in.dart:316
#5      SignInPage.createState
package:group_gate/…/sign_in/sign_in.dart:14
#6      new StatefulElement
package:flutter/…/widgets/framework.dart:4716
...
════════════════════════════════════════════════════════════════════════════════

**Comment by 01BAI** [comment]
Flutter 1.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 84f3d28555 (6 days ago) • 2020-10-15 16:26:19 -0700
Engine • revision b8752bbfff
Tools • Dart 2.10.2

**Comment by lizhuoyuan** [comment]
版本号是多少

**Comment by 01BAI** [comment]
> 版本号是多少
> 看起来是没有初始化

flutter_screenutil: ^3.1.0

**Comment by lizhuoyuan** [comment]
在进入的第一个页面里调用初始化方法 `ScreenUtil.init()`
可参考example或者看一下文档

**Comment by 01BAI** [comment]
![image](https://user-images.githubusercontent.com/45509044/96823453-20393200-145f-11eb-88ac-52483f59b084.png)
有调用初始化方法

**Comment by 01BAI** [comment]
找到问题了，是我自己页面上的东西影响的初始化，谢谢了！
