### ISSUE TITLE
Android 全面屏和刘海屏情况下高度偏高

### ISSUE THREAD

**Issue by 1244752609** [OpenFlutter/flutter_screenutil#167]
Android 全面屏和刘海屏情况下高度偏高，我试了华为小米都是这样子，只有在不是全面屏和非刘海屏的手机才正常显示
设计图
![image](https://user-images.githubusercontent.com/16891671/96989649-966d8f80-1558-11eb-8416-4c3c79cd17b8.png)
全面屏
![image](https://user-images.githubusercontent.com/16891671/96989869-e0567580-1558-11eb-93fe-533cabacd7b4.png)

**Comment by lizhuoyuan** [comment]
如果高度上使用了根据高度适配的方法可以考虑使用根据宽度适配
即：
```
height: 20.w
width:20.w
```
