### ISSUE TITLE
ScreenUtil not work in the theme of  MaterialApp widget

### ISSUE THREAD

**Issue by TalebRafiepour** [OpenFlutter/flutter_screenutil#168]
I want to create LightTheme, DarkTheme for MaterialApp, but i can not use ScreenUtill in the Theme because ScreenUtil need a MediaQuery which created after MaterialApp .
How can i use ScreenUtil in the Theme of MaterialApp?

**Comment by lizhuoyuan** [comment]
Based on the current flutter has not been able to do not rely on context, so it does not support direct use. Maybe you can make sure that the context is not null and then modify or create a theme and use it, I am also sorry

**Comment by alvindrakes** [comment]
@TalebRafiepour just specify themes in the theme class and screenutil in a custom textTheme class for now.

**Comment by lizhuoyuan** [comment]
please use 4.0.0-beta.
The result of my test can.

**Comment by TalebRafiepour** [comment]
> please use 4.0.0-beta.
> The result of my test can.

Thank you so much , It's work for me 
You are the best 👍
