### ISSUE TITLE
DP or PX

### ISSUE THREAD

**Issue by tazik561** [OpenFlutter/flutter_screenutil#169]
Hi friend.
in init method :
```
  void init(BuildContext context) {
    MediaQueryData mediaQuery = MediaQuery.of(context);
    _mediaQueryData = mediaQuery;
    _pixelRatio = mediaQuery.devicePixelRatio;
    _screenWidth = mediaQuery.size.width;
    _screenHeight = mediaQuery.size.height;
    _statusBarHeight = mediaQuery.padding.top;
    _bottomBarHeight = _mediaQueryData.padding.bottom;
    _textScaleFactor = mediaQuery.textScaleFactor;
  }
```
You mentioned 
```
  ///Current device width px
  static double get screenWidth => _screenWidth;
 ///Current device width dp
  static double get screenWidthDp => _screenWidth;
```

but `_screenWidth` achieved from   _screenWidth = mediaQuery.size.width;
They are not difference, Are thay not px?
Why one of them you wrote dp?
Sorry for my stupid question.I am confused

**Comment by lizhuoyuan** [comment]
By default, the result unit you get is dp.
There are some places where the value in px is provided, but generally there are instructions

**Comment by tazik561** [comment]
My last question :
`ScreenUtil().setWidth(540)  (sdk>=2.6 : 540.w) //Adapted to screen width`

 540.w means 540 px?
Imagine i have a container like this , Whit out using you library:
```
                child: Container(
                  height: 34.0,  
```

34 is a px ! Right?
Now if i want to use your library, How could i do that ?Because I am using like this:
```
              child: Container(
                height: 34.h,
```
The height of container 34.h is different with 34.0!!
Thanks so much
