### ISSUE TITLE
关于初始化设备大小的问题！

### ISSUE THREAD

**Issue by winsonet** [OpenFlutter/flutter_screenutil#17]
想请问一下，如果我有多个页面相互跳转，每个页面都会有自己的 `Scaffold`，那这时候我是否需要在每个页面加载时都进行一次初始化呢？还是说我只需要在 `main` 这个整体入口初始化一次就OK？

另我还有个问题，就是我想做一个独立的控件出来，比如一个独立的按钮放到一个 `util` 的类里调用，这时我需要设置按钮的宽和高，但我想直接在 `util` 里调用 `screenutil` 来设置，此时我是否还需要初始化？如果要的话那莫非每次调用这个方法创建按钮的时候都要初始化一次吗？

谢谢啦！

**Comment by winsonet** [comment]
咦？我刚发现你的新版已默认设置好了这个初始化的值，那是否表示现在已不需要再在使用中去设置和初始化设备的宽高啦？

**Comment by lizhuoyuan** [comment]
建议根据你的设计稿的实际尺寸来设置，如果没有尺寸上的问题可以不设置

在 2019/2/13，Winson<notifications@github.com> 写道：
> 咦？我刚发现你的新版已默认设置好了这个初始化的值，那是否表示现在已不需要再在使用中去设置和初始化设备的宽高啦？
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/OpenFlutter/flutter_screenutil/issues/17#issuecomment-463101683


-- 
I wish you happy every day

**Comment by winsonet** [comment]
哦，其实我还有些不太明白，你这个设置了一个固定值，所有设备将按此值去按比例缩放，如果设备本身宽高相差很大，那出来的效果也不一定能保证可适应所有设备，对吗？如我按 320x400 大小设置，那在 iphone 8 plus上看留出来的空间就会大很多了，因此如果我按大设备尺寸设置，在小设备上可能也会显示不全，不知我理解有错吗？

**Comment by winsonet** [comment]
换句话说，如果能在app启动时自动获取设备的宽高以初始化，那是否就完美了？

**Comment by winsonet** [comment]
我做了一个小小的测试，分别使用flutter原生数值和ScreenUtil来设置：
  设备宽度：360
  1. 设置 container width to 180，这时可以非常正常显示 container 只占用了屏幕一半的空间
  2. 使用 ScreenUtil 设置宽度，由于初始化宽度为 1080，因此我设置其宽度就为 540, 如： `ScreenUtil().setWidth(540)`
  结果： 方法1使用 flutter 直接设置效果正确，但通过 ScreenUtil 设置后，明显并不是占据了屏幕一半的效果，而是偏左缩小了，感觉大概只是占用了 40% 左右 
  疑惑： 其实我也不太确定以上测试逻辑是否正确，因此真心希望作者能解答一下，谢谢啦！

**Comment by lizhuoyuan** [comment]
不是按照设备大小,是按照设计稿的大小来设置
这个工具可以获取到当前设备的大小 然后根据设计稿的数据来适应
显示最优的效果
至于你说的显示不正确的问题我会再测试
也建议你运行一下事例中的代码查看是否正常

**Comment by lizhuoyuan** [comment]
不好意思
是调用方式的问题
please use `ScreenUtil.getInstance()` instead of `ScreenUtil()` , for example: ScreenUtil.getInstance().setHeight(25) instead of `ScreenUtil().setHeight(25)`
我在更新日志中做了补充， 是我的失误 。
应该这么用：
根据屏幕宽度适配 `width: ScreenUtil.getInstance().setWidth(540)`,

根据屏幕高度适配 `height: ScreenUtil.getInstance().setHeight(200)`,

可以全局替换 
造成的影响深表歉意

**Comment by winsonet** [comment]
哦，謝謝啦！这样就感觉比较合逻辑了，这段时间我也比较忙，所以没去试，现在这样就是明显的单态模式了，但对于 flutter 来说，如果直接使用两点调用，是否也是直接实例化了呢？即写成以下是否同样效果？
`height: ScreenUtil..setHeight(200),`

这只是我感觉理论上一样，但实际上以上写法出来会有问题，提示类型不正确，以上返回的是 dynamic，但height只能接收 double，不过如果我用 `ScreenUtil.getInstance().setHeight(200)` 的话，就不会有错误，但实际上 setHeight 方法返回的是一樣的啊，所以这里也不明白...

**Comment by lizhuoyuan** [comment]
因为那是个对象方法  不是类方法， 所以还是要实例化一个对象
你得加个()来创建一个实例。

再有就是，我测试的话ScreenUtil()和ScreenUtil.getInstance的setWidth结果是一样的，因为好像并没有用到初始化时传入的值   我现在有点蒙 正在调试

**Comment by winsonet** [comment]
哦，我一直以为 flutter 加两点后出来的就是已实例化后的方法。。。

你意思是，其实并不需要加 getInstance ，就是按以前的调用也是可以了？呵，其实我也有点晕了，其实你里面获取 width 的时候，就是用了 instance 去计算的对吧(如下代码)，所以之后不需再调用 instance了？

` get scaleWidth => _screenWidth / instance.width;`

**Comment by lizhuoyuan** [comment]
对的
我当时为了能简化代码 ， 在这个地方处理了一下

刚才看到前面调用逻辑发现有点不对 觉得ScreenUtil()和ScreenUtil.getInstance()不应该是一样的
后来看到这里才想起来 内部处理了。 我现在正在想是否改一下

**Comment by lizhuoyuan** [comment]
根据屏幕宽度适配 `width: ScreenUtil.getInstance().setWidth(540)`,

根据屏幕高度适配 `height: ScreenUtil.getInstance().setHeight(200)`,

也可以使用 `ScreenUtil()` 替代 `ScreenUtil.getInstance()`,
例如：`ScreenUtil().setHeight(200)`

无需使用连接符号一个“.”就够了

**Comment by winsonet** [comment]
明白，关于我之前的测试，应该是初始化设置设备宽高的值有问题，现在我再试一次就可以了，非常感谢你的耐心解答！！
