### ISSUE TITLE
Difference numberH with just number on UI at screen

### ISSUE THREAD

**Issue by tazik561** [OpenFlutter/flutter_screenutil#170]
Hi.

`ScreenUtil().setWidth(540)  (sdk>=2.6 : 540.w) //Adapted to screen width`

 540.w means 540 px? as you mentioned on document . Right?
Imagine i have a container like this , Without using of you library:
```
                child: Container(
                  height: 34.0,  
```

34 is a px ! Right?
Now if i want to use your library, How could i do that ?Because I am using like this:
```
              child: Container(
                height: 34.h, // returns 9.147619047619047
```
The height of container 34.h is different with 34.0!!

This is height: 34.0:
https://pasteboard.co/JxKBmlt.png

height: 34.h:
https://pasteboard.co/JxKBBCN.png

I initialized like this: 
```
 ScreenUtil.init(context,
        designSize: Size(1440, 2880), allowFontScaling: false);
```
Designer ask us that container's height at  Size(1440, 2880) device size must be 34, but 34.h is not right.

https://pasteboard.co/JxKSLln.png
34 pixel converted in to 9.1

**Comment by lizhuoyuan** [comment]
34 is a dp ! 
```
child: Container(
                  height: 34.0,  
```

xx.h
xx.w
The unit of xx is px on the design draft.

The input unit is px, and the returned result unit is dp

**Comment by tazik561** [comment]
Thank. I think i got it.
The designer give us design draft with adobe xd that units is px but flutter unit is dp. 
When we add height: 34.0, means I added 34 **dp** not **px**. 
If i want to achieve **px** must **34 dp** multiplied with `pixelRatio` .Right?

**Comment by lizhuoyuan** [comment]
Yes, it returns dp.
And, if there is no additional description, generally dp is returned
