### ISSUE TITLE
在column中上下排列container，并使用90.h高度，container之间有间隙。

### ISSUE THREAD

**Issue by XinleZhou2018** [OpenFlutter/flutter_screenutil#175]
在column中上下排列container，container设置90.h高度，container之间有间隙。一旦把container高度改成固定的，比如45，间隙就没有了。

**Comment by XinleZhou2018** [comment]
@lizhuoyuan 我使用的是fish redux

**Comment by lizhuoyuan** [comment]
能不能具體描述一下

**Comment by XinleZhou2018** [comment]
@lizhuoyuan 加我微信
<img width="296" alt="WX20201125-160157@2x" src="https://user-images.githubusercontent.com/39542071/100199070-a271b600-2f37-11eb-8c3b-7f6bc3528b8a.png">

**Comment by XinleZhou2018** [comment]
@lizhuoyuan 加我微信吧13616108739

**Comment by lizhuoyuan** [comment]
![image](https://user-images.githubusercontent.com/15923901/100305948-30ec4300-2fdd-11eb-832b-0aea2c426ea2.png)
这个是因为container默认是有边界的，所以边界用decoration包裹 然后设置border的颜色和背景色想通就可以。
希望其他有这个问题的人能看到这里。
