### ISSUE TITLE
Font too much small on Mobile Devices

### ISSUE THREAD

**Issue by laksithakumara** [OpenFlutter/flutter_screenutil#176]
Hello, Font size too much small on Mobile Devices. if increasing the size Ipad will too much.

```
ScreenUtil.init(constraints,
          designSize: Size(1080, 1920), allowFontScaling: true);
```

```
Text("Privacy",
                style: TextStyle(
                    fontFamily: 'ProximaNova',
                    fontSize:
                        ScreenUtil().setSp(30, allowFontScalingSelf: false)))
```

<img width="890" alt="Screenshot 2020-11-29 at 12 51 14" src="https://user-images.githubusercontent.com/20724138/100535786-f7684180-3241-11eb-94b9-fec6bd06a382.png">

**Comment by lizhuoyuan** [comment]
Can you print the value of this code

().setSp(30, allowFontScalingSelf: false)))

**Comment by lizhuoyuan** [comment]
Can you print the value of this code

().setSp(30, allowFontScalingSelf: false)))

**Comment by laksithakumara** [comment]
Hi 

I got below numbers.

For IPad Pro(9.7 Inch): 21.333333333333336
For Iphone 12 Pro Max : 11.88888888888889

**Comment by lizhuoyuan** [comment]
I will find the problem and solve it as soon as possible.
And I hope there are pictures of the design draft size comparison

**Comment by malvinpratama** [comment]
you can try to * 2.75
i try running with the device same size in init
and i get the size is 5.090909090909091 and the correct is should be 14
i try with the different font size like 48 and the library print 17.454545454545453
if you divide actual size with the library print you can get always 2.75

**Comment by lizhuoyuan** [comment]
> you can try to * 2.75
> i try running with the device same size in init
> and i get the size is 5.090909090909091 and the correct is should be 14
> i try with the different font size like 48 and the library print 17.454545454545453
> if you divide actual size with the library print you can get always 2.75

When you initialize, is the unit of size used in px?

**Comment by malvinpratama** [comment]
> > you can try to * 2.75
> > i try running with the device same size in init
> > and i get the size is 5.090909090909091 and the correct is should be 14
> > i try with the different font size like 48 and the library print 17.454545454545453
> > if you divide actual size with the library print you can get always 2.75
> 
> When you initialize, is the unit of size used in px?

i think that's our bad
what you use is dp, right?
we are always do right this fontSize : 24
this wrong. because the flutter use is logical pixels, not physical pixels.
and you are right because 24 / aspect ratio. so your result is fontSize : 12 (ex : aspect ratio 2.0).
that's why the fontSize is smaller than the normal we code.
i think we need notes this in documentation.
what's look like the with and without library.

**Comment by lizhuoyuan** [comment]
> > > you can try to * 2.75
> > > i try running with the device same size in init
> > > and i get the size is 5.090909090909091 and the correct is should be 14
> > > i try with the different font size like 48 and the library print 17.454545454545453
> > > if you divide actual size with the library print you can get always 2.75
> > 
> > 
> > When you initialize, is the unit of size used in px?
> 
> i think that's our bad
> the initialize screen size should be use design dp.
> but we are use the testing device screen resolution. that's why the font going to small

should use design px.
We will support dp in the future.
Because some design software does not support dp.

**Comment by lizhuoyuan** [comment]
You can try 4.0.1, use dp as the unit initialization
