### ISSUE TITLE
The project cannot be started and there are no error messages；

### ISSUE THREAD

**Issue by ron-zhao** [OpenFlutter/flutter_screenutil#178]
![image](https://user-images.githubusercontent.com/34527495/101600137-d8359500-3a35-11eb-9070-0de7b4e5d946.png)
![image](https://user-images.githubusercontent.com/34527495/101600181-e4215700-3a35-11eb-8e27-1c5527bb1bdf.png)

flutter version 1.24.0-8.0.pre.344

The project cannot be started and there are no error messages；

**Comment by ron-zhao** [comment]
hope your help, thank

**Comment by ron-zhao** [comment]
![image](https://user-images.githubusercontent.com/34527495/101602589-56476b00-3a39-11eb-958c-5bfd1f84225b.png)

**Comment by lizhuoyuan** [comment]
没有错误提示比较难搞
怎么定位到screenutil的问题的？
可以用flutter run -v试试 看一下日志

**Comment by ron-zhao** [comment]
![image](https://user-images.githubusercontent.com/34527495/101604942-8b08f180-3a3c-11eb-9a83-f942d249fac6.png)
这个错误 帮忙看看呢  谢谢

**Comment by lizhuoyuan** [comment]
知道了，可以先依赖github ，
之前有个改动没有提到pub上。

原因是dev分支最新的改动
