### ISSUE TITLE
Null safety 

### ISSUE THREAD

**Issue by Overman775** [OpenFlutter/flutter_screenutil#179]
Hi! thanks for your package. Can you publish null-safety to prerelease in pub.dev like other packages? Thanks )

**Comment by lizhuoyuan** [comment]
I have paid attention to this issue, it may be implemented in the beta version, thank you for your attention

**Comment by lizhuoyuan** [comment]
> I have paid attention to this issue, it may be implemented in the beta version, thank you for your attention.

https://pub.dev/packages/flutter_screenutil/versions/5.0.0-nullsafety.0

thank you for your support.
