### ISSUE TITLE
mian函数直接初始化

### ISSUE THREAD

**Issue by liguande** [OpenFlutter/flutter_screenutil#18]
你好，我直接在main `ScreenUtil.instance = ScreenUtil(uiWidth: 375.0,uiHeight: 667.0)..init();`然后其余的地方只要用`ScreenUtil.instance.setSp`这种，开发时没问题，但是一旦生成了apk就不行了，请问是为什么。
我是看了你的博客来的，我用的是ui，然后没用context，因为在main中没有context。

**Comment by lizhuoyuan** [comment]
博客内容有些过时。。
建议你看github上的文档 有中文版
初始化还是用这种方式 不然就会在release环境下无法获取到数据
`ScreenUtil.instance = ScreenUtil.getInstance()..init(context);`

**Comment by liguande** [comment]
我又尝试了许久，我发现用你的可以在release中获取数据，而我用dart.ui获取的则不行。但是你的方法无法一次性声明，必须每个Widget build里面声明（请问是我理解错误了吗？）

**Comment by lizhuoyuan** [comment]
不需要每个widget里声明 只要在入口文件处声明即可.
![image](https://user-images.githubusercontent.com/15923901/53215271-dba63380-368a-11e9-81dc-60d6ae1aca05.png)
![image](https://user-images.githubusercontent.com/15923901/53215293-faa4c580-368a-11e9-9b1d-f40df94b99f9.png)
其他地方直接使用就可以了
你也可以参考 https://github.com/lizhuoyuan/flutter_study 
这是我的一个学习flutter的项目
里面有flutter_screenutil的使用
你可以参考如何引用的

**Comment by liguande** [comment]
非常感谢！通过看你的博客我get到了方法，然后有积极的回答我的问题。我把声明写在了闪屏那里就可以了。star已给。
