### ISSUE TITLE
运行example报了这个错误

### ISSUE THREAD

**Issue by garrickvan** [OpenFlutter/flutter_screenutil#184]
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
 lib/main.dart
Unhandled exception:
Crash when compiling file:///Users/Garrick/Downloads/flutter_screenutil-master/example/lib/main.dart,
at character offset 1012:
type 'InvalidType' is not a subtype of type 'InterfaceType'
[38;5;248m#0      computeConstructorReturnType (package:front_end/src/fasta/kernel/internal_ast.dart:59:5)[39;49m
[38;5;248m#1      InferenceVisitor.visitFactoryConstructorInvocationJudgment (package:front_end/src/fasta/kernel/inference_visitor.dart:727:9)[39;49m
[38;5;248m#2      FactoryConstructorInvocationJudgment.acceptInference (package:front_end/src/fasta/kernel/internal_ast.dart:684:20)[39;49m

[38;5;248m#3      TypeInferrerImpl.inferExpression (package:front_end/src/fasta/type_inference/type_inferrer.dart:1583:27)[39;49m
[38;5;248m#4      InferenceVisitor.visitMethodInvocation (package:front_end/src/fasta/kernel/inference_visitor.dart:2410:18)[39;49m
[38;5;248m#5      MethodInvocation.accept1 (package:kernel/ast.dart:4002:9)[39;49m
[38;5;248m#6      TypeInferrerImpl.inferExpression (package:front_end/src/fasta/type_inference/type_inferrer.dart:1587:27)[39;49m
[38;5;248m#7      TypeInferrerImpl._inferInvocation (package:front_end/src/fasta/type_inference/type_inferrer.dart:1848:44)[39;49m

[38;5;248m#8      TypeInferrerImpl.inferInvocation (package:front_end/src/fasta/type_inference/type_inferrer.dart:1664:12)[39;49m
[38;5;248m#9      InferenceVisitor.visitConstructorInvocation (package:front_end/src/fasta/kernel/inference_visitor.dart:440:49)[39;49m

[38;5;248m#10     ConstructorInvocation.accept1 (package:kernel/ast.dart:4206:9)[39;49m
[38;5;248m#11     TypeInferrerImpl.inferExpression (package:front_end/src/fasta/type_inference/type_inferrer.dart:1587:27)[39;49m

[38;5;248m#12     TypeInferrerImpl._inferInvocation (package:front_end/src/fasta/type_inference/type_inferrer.dart:1887:42)[39;49m
[38;5;248m#13     TypeInferrerImpl.inferInvocation (package:front_end/src/fasta/type_inference/type_inferrer.dart:1664:12)[39;49m
[38;5;248m#14     InferenceVisitor.visitConstructorInvocation (package:front_end/src/fasta/kernel/inference_visitor.dart:440:49)[39;49m
[38;5;248m#15     ConstructorInvocation.accept1 (package:kernel/ast.dart:4206:9)[39;49m
[38;5;248m#16     TypeInferrerImpl.inferExpression (package:front_end/src/fasta/type_inference/type_inferrer.dart:1587:27)[39;49m
[38;5;248m#17     InferenceVisitor.inferElement (package:front_end/src/fasta/kernel/inference_visitor.dart:1578:51)[39;49m
[38;5;248m#18     InferenceVisitor.visitListLiteral (package:front_end/src/fasta/kernel/inference_visitor.dart:1672:44)[39;49m
[38;5;248m#19     ListLiteral.accept1 (package:kernel/ast.dart:5344:9)[39;49m

[38;5;248m#20     TypeInferrerImpl.inferExpression (package:front_end/src/fasta/type_inference/type_inferrer.dart:1587:27)[39;49m
[38;5;248m#21     TypeInferrerImpl._inferInvocation (package:front_end/src/fasta/type_inference/type_inferrer.dart:1887:42)[39;49m
[38;5;248m#22     TypeInferrerImpl.inferInvocation (package:front_end/src/fasta/type_inference/type_inferrer.dart:1664:12)[39;49m
[38;5;248m#23     InferenceVisitor.visitConstructorInvocation (package:front_end/src/fasta/kernel/inference_visitor.dart:440:49)[39;49m

[38;5;248m#24     ConstructorInvocation.accept1 (package:kernel/ast.dart:4206:9)[39;49m
[38;5;248m#25     TypeInferrerImpl.inferExpression (package:front_end/src/fasta/type_inference/type_inferrer.dart:1587:27)[39;49m

[38;5;248m#26     InferenceVisitor.inferElement (package:front_end/src/fasta/kernel/inference_visitor.dart:1578:51)[39;49m
[38;5;248m#27     InferenceVisitor.visitListLiteral (package:front_end/src/fasta/kernel/inference_visitor.dart:1672:44)[39;49m
[38;5;248m#28     ListLiteral.accept1 (package:kernel/ast.dart:5344:9)[39;49m
[38;5;248m#29     TypeInferrerImpl.inferExpression (package:front_end/src/fasta/type_inference/type_inferrer.dart:1587:27)[39;49m
[38;5;248m#30     TypeInferrerImpl._inferInvocation (package:front_end/src/fasta/type_inference/type_inferrer.dart:1887:42)[39;49m
[38;5;248m#31     TypeInferrerImpl.inferInvocation (package:front_end/src/fasta/type_inference/type_inferrer.dart:1664:12)[39;49m
[38;5;248m#32     InferenceVisitor.visitConstructorInvocation (package:front_end/src/fasta/kernel/inference_visitor.dart:440:49)[39;49m
[38;5;248m#33     ConstructorInvocation.accept1 (package:kernel/ast.dart:4206:9)[39;49m
[38;5;248m#34     TypeInferrerImpl.inferExpression (package:front_end/src/fasta/type_inference/type_inferrer.dart:1587:27)[39;49m
[38;5;248m#35     TypeInferrerImpl._inferInvocation (package:front_end/src/fasta/type_inference/type_inferrer.dart:1887:42)[39;49m

[38;5;248m#36     TypeInferrerImpl.inferInvocation (package:front_end/src/fasta/type_inference/type_inferrer.dart:1664:12)[39;49m
[38;5;248m#37     InferenceVisitor.visitConstructorInvocation (package:front_end/src/fasta/kernel/inference_visitor.dart:440:49)[39;49m

[38;5;248m#38     ConstructorInvocation.accept1 (package:kernel/ast.dart:4206:9)[39;49m
[38;5;248m#39     TypeInferrerImpl.inferExpression (package:front_end/src/fasta/type_inference/type_inferrer.dart:1587:27)[39;49m
[38;5;248m#40     TypeInferrerImpl._inferInvocation (package:front_end/src/fasta/type_inference/type_inferrer.dart:1887:42)[39;49m
[38;5;248m#41     TypeInferrerImpl.inferInvocation (package:front_end/src/fasta/type_inference/type_inferrer.dart:1664:12)[39;49m
[38;5;248m#42     InferenceVisitor.visitConstructorInvocation (package:front_end/src/fasta/kernel/inference_visitor.dart:440:49)[39;49m
[38;5;248m#43     ConstructorInvocation.accept1 (package:kernel/ast.dart:4206:9)[39;49m
[38;5;248m#44     TypeInferrerImpl.inferExpression (package:front_end/src/fasta/type_inference/type_inferrer.dart:1587:27)[39;49m
[38;5;248m#45     InferenceVisitor.visitReturnStatement (package:front_end/src/fasta/kernel/inference_visitor.dart:5061:61)[39;49m
[38;5;248m#46     ReturnStatement.accept (package:kernel/ast.dart:6541:43)[39;49m
[38;5;248m#47     TypeInferrerImpl.inferStatement (package:front_end/src/fasta/type_inference/type_inferrer.dart:3081:24)[39;49m
[38;5;248m#48     InferenceVisitor._visitStatements (package:front_end/src/fasta/kernel/inference_visitor.dart:285:20)[39;49m
[38;5;248m#49     InferenceVisitor.visitBlock (package:front_end/src/fasta/kernel/inference_visitor.dart:306:30)[39;49m
[38;5;248m#50     Block.accept (package:kernel/ast.dart:5873:43)[39;49m

[38;5;248m#51     TypeInferrerImpl.inferStatement (package:front_end/src/fasta/type_inference/type_inferrer.dart:3081:24)[39;49m
[38;5;248m#52     TypeInferrerImpl.inferFunctionBody (package:front_end/src/fasta/type_inference/type_inferrer.dart:1628:39)[39;49m

[38;5;248m#53     BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:989:28)[39;49m
[38;5;248m#54     DietListener.listenerFinishFunction (package:front_end/src/fasta/source/diet_listener.dart:955:14)[39;49m
[38;5;248m#55     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:993:7)[39;49m
[38;5;248m#56     DietListener._endClassMethod (package:front_end/src/fasta/source/diet_listener.dart:714:5)[39;49m
[38;5;248m#57     DietListener.endClassMethod (package:front_end/src/fasta/source/diet_listener.dart:665:5)[39;49m
[38;5;248m#58     Parser.parseMethod[39;49m
 package:_fe_analyzer_shared/…/parser/parser_impl.dart
[38;5;248m#59     Parser.parseClassOrMixinOrExtensionMemberImpl[39;49m
 package:_fe_analyzer_shared/…/parser/parser_impl.dart
[38;5;248m#60     Parser.parseClassOrMixinOrExtensionBody[39;49m
 package:_fe_analyzer_shared/…/parser/parser_impl.dart
[38;5;248m#61     Parser.parseClass[39;49m
 package:_fe_analyzer_shared/…/parser/parser_impl.dart
[38;5;248m#62     Parser.parseClassOrNamedMixinApplication[39;49m
 package:_fe_analyzer_shared/…/parser/parser_impl.dart
[38;5;248m#63     Parser.parseTopLevelKeywordDeclaration[39;49m
 package:_fe_analyzer_shared/…/parser/parser_impl.dart

[38;5;248m#64     Parser.parseTopLevelDeclarationImpl[39;49m
 package:_fe_analyzer_shared/…/parser/parser_impl.dart
[38;5;248m#65     Parser.parseUnit[39;49m
 package:_fe_analyzer_shared/…/parser/parser_impl.dart
[38;5;248m#66     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:427:14)[39;49m
[38;5;244m<asynchronous suspension>[39;49m
[38;5;248m#67     Loader.buildBodies (package:front_end/src/fasta/loader.dart:242:15)[39;49m
[38;5;248m#68     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:382:20)[39;49m
[38;5;248m#69     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)[39;49m
[38;5;248m#70     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:380:12)[39;49m

[38;5;248m#71     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:274:28)[39;49m
[38;5;244m<asynchronous suspension>[39;49m
[38;5;248m#72     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart)[39;49m
[38;5;248m#73     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)[39;49m
[38;5;244m#74     new Future.sync (dart:async/future.dart:223:31)[39;49m

[38;5;248m#75     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)[39;49m
[38;5;244m#76     _rootRun (dart:async/zone.dart:1190:13)[39;49m

[38;5;244m#77     _CustomZone.run (dart:async/zone.dart:1093:19)[39;49m
[38;5;244m#78     _runZoned (dart:async/zone.dart:1630:10)[39;49m

[38;5;244m#79     runZoned (dart:async/zone.dart:1550:10)[39;49m
[38;5;248m#80     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)[39;49m

[38;5;248m#81     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:206:20)[39;49m
[38;5;248m#82     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:69:46)[39;49m
[38;5;248m#83     FrontendCompiler.compile.<anonymous closure> (package:frontend_server/frontend_server.dart:524:59)[39;49m
[38;5;244m#84     new Future.<anonymous closure> (dart:async/future.dart:175:37)[39;49m
[38;5;244m#85     _rootRun (dart:async/zone.dart:1182:47)[39;49m
[38;5;244m#86     _CustomZone.run (dart:async/zone.dart:1093:19)[39;49m
[38;5;244m#87     _CustomZone.runGuarded (dart:async/zone.dart:997:7)[39;49m
[38;5;244m#88     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)[39;49m
[38;5;244m#89     _rootRun (dart:async/zone.dart:1190:13)[39;49m
[38;5;244m#90     _CustomZone.run (dart:async/zone.dart:1093:19)[39;49m
[38;5;244m#91     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)[39;49m
[38;5;244m#92     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)[39;49m
[38;5;244m#93     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)[39;49m
[38;5;244m#94     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)[39;49m
[38;5;244m#95     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)[39;49m

[38;5;248m#0      DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:998:7)[39;49m
[38;5;248m#1      DietListener._endClassMethod (package:front_end/src/fasta/source/diet_listener.dart:714:5)[39;49m
[38;5;248m#2      DietListener.endClassMethod (package:front_end/src/fasta/source/diet_listener.dart:665:5)[39;49m
[38;5;248m#3      Parser.parseMethod[39;49m
 package:_fe_analyzer_shared/…/parser/parser_impl.dart
[38;5;248m#4      Parser.parseClassOrMixinOrExtensionMemberImpl[39;49m
 package:_fe_analyzer_shared/…/parser/parser_impl.dart
[38;5;248m#5      Parser.parseClassOrMixinOrExtensionBody[39;49m
 package:_fe_analyzer_shared/…/parser/parser_impl.dart
[38;5;248m#6      Parser.parseClass[39;49m
 package:_fe_analyzer_shared/…/parser/parser_impl.dart
[38;5;248m#7      Parser.parseClassOrNamedMixinApplication[39;49m
 package:_fe_analyzer_shared/…/parser/parser_impl.dart
[38;5;248m#8      Parser.parseTopLevelKeywordDeclaration[39;49m
 package:_fe_analyzer_shared/…/parser/parser_impl.dart
[38;5;248m#9      Parser.parseTopLevelDeclarationImpl[39;49m
 package:_fe_analyzer_shared/…/parser/parser_impl.dart
[38;5;248m#10     Parser.parseUnit[39;49m
 package:_fe_analyzer_shared/…/parser/parser_impl.dart

[38;5;248m#11     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:427:14)[39;49m
[38;5;244m<asynchronous suspension>[39;49m
[38;5;248m#12     Loader.buildBodies (package:front_end/src/fasta/loader.dart:242:15)[39;49m
[38;5;248m#13     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:382:20)[39;49m
[38;5;248m#14     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)[39;49m
[38;5;248m#15     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:380:12)[39;49m
[38;5;248m#16     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:274:28)[39;49m
[38;5;244m<asynchronous suspension>[39;49m
[38;5;248m#17     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart)[39;49m

[38;5;248m#18     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)[39;49m
[38;5;244m#19     new Future.sync (dart:async/future.dart:223:31)[39;49m
[38;5;248m#20     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)[39;49m
[38;5;244m#21     _rootRun (dart:async/zone.dart:1190:13)[39;49m
[38;5;244m#22     _CustomZone.run (dart:async/zone.dart:1093:19)[39;49m
[38;5;244m#23     _runZoned (dart:async/zone.dart:1630:10)[39;49m
[38;5;244m#24     runZoned (dart:async/zone.dart:1550:10)[39;49m
[38;5;248m#25     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)[39;49m

[38;5;248m#26     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:206:20)[39;49m
[38;5;248m#27     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:69:46)[39;49m
[38;5;248m#28     FrontendCompiler.compile.<anonymous closure> (package:frontend_server/frontend_server.dart:524:59)[39;49m
[38;5;244m#29     new Future.<anonymous closure> (dart:async/future.dart:175:37)[39;49m
[38;5;244m#30     _rootRun (dart:async/zone.dart:1182:47)[39;49m
[38;5;244m#31     _CustomZone.run (dart:async/zone.dart:1093:19)[39;49m
[38;5;244m#32     _CustomZone.runGuarded (dart:async/zone.dart:997:7)[39;49m
[38;5;244m#33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)[39;49m

[38;5;244m#34     _rootRun (dart:async/zone.dart:1190:13)[39;49m
[38;5;244m#35     _CustomZone.run (dart:async/zone.dart:1093:19)[39;49m

[38;5;244m#36     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)[39;49m
[38;5;244m#37     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)[39;49m
[38;5;244m#38     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)[39;49m

[38;5;244m#39     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)[39;49m
[38;5;244m#40     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)[39;49m

the Dart compiler exited unexpectedly.
Exited (1)

刚刚学习flutter，做个适配多机型的项目，想用flutter_screenutil，跑example，结果报了这个问题，没整明白是什么原因导致的

**Comment by garrickvan** [comment]
版本问题，已经解决了

**Comment by caijingsong** [comment]
> 版本问题，已经解决了

最后是啥版本解决的啊，
现在我也碰到这个问题。

➜  example flutter doctor -v          
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.2.3 at /Users/caijingsong/flutter
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/caijingsong/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
