### ISSUE TITLE
_textScaleFactor 逻辑疑问

### ISSUE THREAD

**Issue by foxsofter** [OpenFlutter/flutter_screenutil#186]
[这里](https://github.com/OpenFlutter/flutter_screenutil/blob/11a2638c49c586a3918327f7b7185040de4a0d4d/lib/screenutil.dart#L118) 为什么是 ➗ 而不是 ✖️

**Comment by lizhuoyuan** [comment]
这个是之前修改单位的时候忘记改这里了， 已提交新版本~

**Comment by vasilich6107** [comment]
Could you use english please...
