### ISSUE TITLE
如果需要把工具类使用到margin padding上好像不能使用

### ISSUE THREAD

**Issue by Herryjoeson** [OpenFlutter/flutter_screenutil#19]
![image](https://user-images.githubusercontent.com/19682746/53496526-330a3080-3add-11e9-8ded-b07ec5f74e9a.png)

**Comment by Herryjoeson** [comment]
如何在margin上 padding也能使用工具类

**Comment by lizhuoyuan** [comment]
去掉 const修饰符
![image](https://user-images.githubusercontent.com/15923901/53537389-bf9c0980-3b44-11e9-9749-ab5478230c40.png)
