### ISSUE TITLE
使用ScreenUtil.init() 时报错,第一个参数该传什么

### ISSUE THREAD

**Issue by chenmoonmo** [OpenFlutter/flutter_screenutil#191]
![image](https://user-images.githubusercontent.com/36295999/103502533-7af1ff80-4e8c-11eb-9b16-9029c1b20b95.png)The argument type 'BuildContext' can't be assigned to the parameter type 'BoxConstraints'.

**Comment by lizhuoyuan** [comment]
不清楚你使用的版本
新版本已经不使用这个初始化的方式了，
请查看 https://github.com/OpenFlutter/flutter_screenutil/blob/master/README_CN.md
