### ISSUE TITLE
foldable phones width/height issue

### ISSUE THREAD

**Issue by AbdelrahmanElghoul** [OpenFlutter/flutter_screenutil#192]
when using foldable phone screenWidth get incorrect value 
so if  width 100 when i run and tried to use full width 150 at run time
 it will return 100 and when minimize it again it will return 150 not 100

**Comment by lizhuoyuan** [comment]
I guess it might be because flutter itself did not handle it well?
Please use flutter's own method of getting the width of the screen to try to see if the results are consistent.
Theoretically the two are the same.

Sorry i don't have a folding screen phone
