### ISSUE TITLE
插件有bug

### ISSUE THREAD

**Issue by gongshaozhu** [OpenFlutter/flutter_screenutil#193]
当路由连续多次跳转之后，会出现这只高度 例如：10. h    print(10.h);   // 高度无限高infinite

**Comment by lizhuoyuan** [comment]
仅按照描述的步骤来做
我并未复现
请问具体操作？

**Comment by zhanganzhe** [comment]
BottomNavigationBarItem 使用直接报错

**Comment by lizhuoyuan** [comment]
无回复，暂时关闭
