### ISSUE TITLE
Does not work for Tablets

### ISSUE THREAD

**Issue by ab-dev-github** [OpenFlutter/flutter_screenutil#194]
I am using ScreenUtil and it works most of the time for Phones, however, it does not work for Tablets & iPads. Is this a problem for all or I am not correctly using the package.

Can someone suggest the right way to use design draft? How to get the 360 and 690 for my phone as in example below & if I set this for my phone that I am using while developing the App, will this work for Tablet as well?

`//The size of the equipment in the design draft(360,690)
ScreenUtil.init(constraints, designSize: Size(360, 690));`

**Comment by lizhuoyuan** [comment]
Under normal circumstances it is possible,
designSize: the size of the device in the design draft, in dp.
And I updated readme

**Comment by ab-dev-github** [comment]
Thanks. If I run code on my dev phone, I get this

```
I/flutter (24600): Device width dp:411.42857142857144dp
I/flutter (24600): Device height dp:820.5714285714286dp
I/flutter (24600): Device pixel density:2.625
I/flutter (24600): Bottom safe zone distance dp:0.0dp
I/flutter (24600): Status bar height dp:33.904761904761905dp
I/flutter (24600): The ratio of actual width to UI design:0.380952380952381
I/flutter (24600): The ratio of actual height to UI design:0.38095238095238093
I/flutter (24600): System font scaling:1.0
I/flutter (24600): 0.5 times the screen width:205.71428571428572dp
I/flutter (24600): 0.5 times the screen height:410.2857142857143dp
```

So should I set 
`designSize: Size(411, 820)`

If I do and develop my App, i.e. set Font/Widget height/width/Padding and so on accordingly which will work perfectly for my dev phone - will this work on Tablet of different size without any problem?

**Comment by lizhuoyuan** [comment]
no no no no
When developing, there is a UI design draft，The phone size of the design draft is what we need to fill in.
If there is no design draft for the time being, please assume a mobile phone size, such as Size(320,480)

**Comment by ab-dev-github** [comment]
I am confused now :-( Sorry. 

With above information, what do you suggest I should set below?

Earlier I had set `Size(1080, 2154),` & it's kind of worked, but well not on Tablets

```
    return ScreenUtilInit(
      designSize: Size(1080, 2154),
      allowFontScaling: false,
```

**Comment by lizhuoyuan** [comment]
So, now , do you have a UI design?

**Comment by ab-dev-github** [comment]
What does that mean? Does that mean a device/dimensions that we'll use to design/develop an App the Development cycle?

**Comment by lizhuoyuan** [comment]
You don’t need to fill in the size of the actual device, just fill in the developed benchmark size.

But
 If you are based on the size of this phone throughout the process, you can fill in this way.

**Comment by ab-dev-github** [comment]
Okay. Just to make sure I understood (and probably help beginners like me) correctly - If I am going to use the below device through out the dev cycle, I can set Design Size as `designSize: Size(411, 820)` & continue the development, but if the design draft is not known - I can set something like Size(320,480) or (360,720) as you suggested earlier and continue the App development and make App responsive.  
```
I/flutter (24600): Device width dp:411.42857142857144dp
I/flutter (24600): Device height dp:820.5714285714286dp
```
Couple more question: If I continue with Size(320,480) when the design draft is not known, at any point in time, do I need to re-do the UI to match new Size OR
Because I have already developed the Responsive UI based on 320,480, it will work for other sizes as well.

Please correct me if I am wrong.

**Comment by lizhuoyuan** [comment]
The size of the design sketch is not important. The important thing is to try not to change it, otherwise there will be UI abnormalities, and if it is not changed, the initial value will be no problem.

**Comment by ab-dev-github** [comment]
Okay. Got it. When I had first set it, I had set it as `Size(1080, 2154)` since then there's no change. So why do you think in this case it doesn't work very well on Tablet / iPad?

**Comment by lizhuoyuan** [comment]
Which widget does not perform well, can you show the diagram and code?
Generally speaking, yes

**Comment by ab-dev-github** [comment]
Okay, I will try to share more data related to this. Thanks a lot for your help with this so far!

**Comment by lizhuoyuan** [comment]
Welcome to feedback more questions in time
