### ISSUE TITLE
设计稿高度适配问题

### ISSUE THREAD

**Issue by scolia** [OpenFlutter/flutter_screenutil#195]
1. 在适配的高度的时候, 需要手动减去顶部状态栏和底部小白条栏的高度吗? 例如: 我的设计稿是按iPhone x设计的, 那么我最后在设置高度的时候, 需要将 812(设备高度) - 44(状态栏高度) - 34(底部栏高度) 吗?

2. 在适配异形屏的时候, 如果我把组件都包到SafeArea里面, 那么此时的高度应该怎么设置?

**Comment by lizhuoyuan** [comment]
1初始化尺寸的时候就是整个屏幕的高度 ，不用在意异形的影响
2safearea就是整个屏幕的范围
