### ISSUE TITLE
Ensure to initialize ScreenUtil before accessing it

### ISSUE THREAD

**Issue by mehmetyilmaz001** [OpenFlutter/flutter_screenutil#196]
Hi all,

I am trying to implement flutter_screenutil like this in my project

`Widget build(BuildContext context) {
   
    return MultiBlocProvider(
      providers: [

      ],
      child: StyledToast(
  
        child: ScreenUtilInit(
          designSize: Size(375, 812),
          allowFontScaling: true,
          child: MaterialApp(
              title: 'Material App',`

Bu when  I restart the app in debug mode I got this error.

`Ensure to initialize ScreenUtil before accessing it.
Please execute the init method : ScreenUtil.init()
'package:flutter_screenutil/screenutil.dart':
Failed assertion: line 33 pos 7: '_instance != null'
` 

Bu when I Hot Reload the app the error is not showing.

I am using the version 4.0.2+3 
Flutter version: 1.22.5

I attached a video about the error.

Thanks.

https://user-images.githubusercontent.com/5219953/103944462-bd456600-5144-11eb-80c2-bbe265797724.mov

**Comment by lizhuoyuan** [comment]
Maybe you should rerun

**Comment by lakerszhy** [comment]
You can put `MaterialApp` in another widget.

**Comment by BelongsH** [comment]
```
return ScreenUtilInit(
      designSize: Size(375, 812),
      allowFontScaling: false,
      child: MaterialApp(
        title: '测试',
        debugShowCheckedModeBanner: false,
        theme: ThemeData(
          primarySwatch: Colors.blue,
          visualDensity: VisualDensity.adaptivePlatformDensity,
        ),
        home: SearchPage(),
      ),
    );
``` 

不知道什么原因，直接使用`ScreenUtilInit`，里面的build函数会比SearchPage里面包含sp的属性，执行的时机慢。就会出现上面的错误。

如果自己包装的话，就不会
```
  return LayoutBuilder(
      // ignore: missing_return
      builder: (_, BoxConstraints constraints) {
        if (constraints.maxWidth != 0) {
          ScreenUtil.init(
            constraints,
            designSize: Size(375, 812),
            allowFontScaling: false,
          );

          return MaterialApp(
            title: '测试',
            debugShowCheckedModeBanner: false,
            theme: ThemeData(
              primarySwatch: Colors.blue,
              visualDensity: VisualDensity.adaptivePlatformDensity,
            ),
            home: SearchPage(),
          );
        }
      },
    );
```
我很困惑。

**Comment by jasonlaw** [comment]
Same problem here.
The workaround by @BelongsH fixed the issue.

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building LayoutBuilder:
A build function returned null.

The offending widget is: LayoutBuilder
Build functions must never return null.

To return an empty space that causes the building widget to fill available room, return "Container()". To return an empty space that takes as little room as possible, return "Container(width: 0.0, height: 0.0)".

When the exception was thrown, this was the stack
#0      debugWidgetBuilderValue.<anonymous closure>
package:flutter/…/widgets/debug.dart:302
#1      debugWidgetBuilderValue
package:flutter/…/widgets/debug.dart:323
#2      _LayoutBuilderElement._layout.<anonymous closure>
package:flutter/…/widgets/layout_builder.dart:125
#3      BuildOwner.buildScope
package:flutter/…/widgets/framework.dart:2683
#4      _LayoutBuilderElement._layout
package:flutter/…/widgets/layout_builder.dart:120
...
══════════════════════════════════════════════════════════════════════════

**Comment by lizhuoyuan** [comment]
@jasonlaw   ok, I know, thank you

**Comment by AngusPei** [comment]
@lizhuoyuan 
flutter_screenutil: ^4.0.2+8
问题依然存在

**Comment by AngusPei** [comment]
这个应该是flutter对Build Widget更换了处理时机，建议去Flutter 提交一个issue

**Comment by a1005342094** [comment]
I've also met that after packing, some devices will be directly grayed out when they load slowly

**Comment by lizhuoyuan** [comment]
It seems I need to study this issue carefully

**Comment by lizhuoyuan** [comment]
> I've also met that after packing, some devices will be directly grayed out when they load slowly

please try 4.0.3

**Comment by IOCloudFly** [comment]
我也遇到的同样的问题，没解决

**Comment by idootop** [comment]
> ```
> return ScreenUtilInit(
>       designSize: Size(375, 812),
>       allowFontScaling: false,
>       child: MaterialApp(
>         title: '测试',
>         debugShowCheckedModeBanner: false,
>         theme: ThemeData(
>           primarySwatch: Colors.blue,
>           visualDensity: VisualDensity.adaptivePlatformDensity,
>         ),
>         home: SearchPage(),
>       ),
>     );
> ```
> 
> 不知道什么原因，直接使用`ScreenUtilInit`，里面的build函数会比SearchPage里面包含sp的属性，执行的时机慢。就会出现上面的错误。
> 
> 如果自己包装的话，就不会
> 
> ```
>   return LayoutBuilder(
>       // ignore: missing_return
>       builder: (_, BoxConstraints constraints) {
>         if (constraints.maxWidth != 0) {
>           ScreenUtil.init(
>             constraints,
>             designSize: Size(375, 812),
>             allowFontScaling: false,
>           );
> 
>           return MaterialApp(
>             title: '测试',
>             debugShowCheckedModeBanner: false,
>             theme: ThemeData(
>               primarySwatch: Colors.blue,
>               visualDensity: VisualDensity.adaptivePlatformDensity,
>             ),
>             home: SearchPage(),
>           );
>         }
>       },
>     );
> ```
> 
> 我很困惑。

原因很简单，ScreenUtilInit里的child是传过来的参数，相当于提前build好的child widget，把这个提前build好的widget放到LayoutBuilder里的效果可想而知

如果你自己在外面放一个LayoutBuilder，然后把child widget放到builder里当然就不会出现child widegt的尺寸没有初始化的问题

所以这个问题的解决方法也很简单，就是把传过来的child widget换成builder

![Snipaste_2021-02-05_11-16-48](https://user-images.githubusercontent.com/35302658/106986430-4a142b80-67a6-11eb-991e-d70d73b6119c.png)
