### ISSUE TITLE
每页都要import, flutteer_screenutil 

### ISSUE THREAD

**Issue by bitores** [OpenFlutter/flutter_screenutil#197]
![image](https://user-images.githubusercontent.com/17512181/104267491-a5ffd300-54cc-11eb-96e3-6378f5758c61.png)

**Comment by lizhuoyuan** [comment]
用到的地方肯定要引入啊，就像写UI每页都要引入material.dart一样

**Comment by bitores** [comment]
同上 4.0.x

**Comment by bitores** [comment]
恩，可能我对 dart extensoin 理解的不到位
