### ISSUE TITLE
Font scaling strictly by height or width

### ISSUE THREAD

**Issue by vasilich6107** [OpenFlutter/flutter_screenutil#201]
Hi. Thanks for your package.

Currently the font scales by the lowest of `min(scaleWidth, scaleHeight)`.
Could you add some getter or extension method that allows to choose the scaling by specific dimension.

Something like
22.wsp - sp by width
22.hsp - sp by height

**Comment by lizhuoyuan** [comment]
Maybe you can directly use the screen adaptation method, and then set the font scaling in the style
```
 MaterialApp(
        debugShowCheckedModeBanner: false,
        title: 'Flutter_ScreenUtil',
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        builder: (context, widget) {
          return MediaQuery(
            ///add this if you want
            data: MediaQuery.of(context).copyWith(textScaleFactor: 1.0),
            child: widget,
          );
        },
        home: HomePage(title: 'FlutterScreenUtil Demo'),
      ),
```

**Comment by lizhuoyuan** [comment]
I haven't waited for your reply, temporarily close the question and look forward to your reply
