### ISSUE TITLE
WidgetsBinding.instance.window.textScaleFactor issue

### ISSUE THREAD

**Issue by vasilich6107** [OpenFlutter/flutter_screenutil#202]
Due to the init flow of screen util `WidgetsBinding.instance.window.textScaleFactor` is saved in private variable during initialisation.
If I change the accessibility settings on the fly - the variable will not be reinitialized.

The solution is to always take a value from `WidgetsBinding.instance.window.textScaleFactor`

**UPDATE**

The main issue that I need to specify the `textTheme` in `MaterialApp` widget.
But in case of on fly accessibility change only the part beneath `MaterialApp` builder being re-rendered.

This causes the conflict - you cannot init screenutils before material app builder cause on flight accessibility will not work properly. In the same time initialization in builder will not give a possibility to use `ScreenUtil` for `textTheme` creation...

![720p](https://user-images.githubusercontent.com/6721286/105398209-bfbabc00-5c2a-11eb-9b2c-0fe8f23dab11.gif)

**Comment by lizhuoyuan** [comment]
thanks~
