### ISSUE TITLE
更新4.0版本之后不同机器字体不适配

### ISSUE THREAD

**Issue by superwei629** [OpenFlutter/flutter_screenutil#207]
如题
怎么解决呢,还是回退3版本
感觉作者解达

**Comment by superwei629** [comment]
文字大小在一个弹框内看着刚好，换成真机就显示快超屏了

谢谢作者解答

**Comment by lizhuoyuan** [comment]
啊这。。 抱歉才看到

**Comment by 2e2ee95304418f96** [comment]
我也是同样问题, 回退到3.x版本才生效, 你怎么解决的?



> 啊这。。 抱歉才看到

这个问题怎么解决呢?

**Comment by lizhuoyuan** [comment]
框是否也适配了呢？
按理说两个是同步变化的

**Comment by 2e2ee95304418f96** [comment]
我没有弹框,就是最简单的demo, 有个Text. 刚刚加你的qq群还没有通过

**Comment by lizhuoyuan** [comment]
具体什么问题？
文字确实会根据不同手机来变化的

**Comment by 2e2ee95304418f96** [comment]
研究了下源码, 是因为scaleText的取值改成了min(scaleWidth, scaleHeight), 为什么呢?

**Comment by lizhuoyuan** [comment]
就是一种策略，之前有网友提了issue，探讨之后决定使用两值中最小的来进行适配。
如果你想固定使用其中某一个可以使用x.w或者x.h来进行字体适配，在禁止APP字体缩放的情况下是没有问题的
