### ISSUE TITLE
Font scaling on iOS vastly different on simulator and app deployed via App Store

### ISSUE THREAD

**Issue by robertflesch** [OpenFlutter/flutter_screenutil#210]
I deployed my app into test flight today, and what I saw shocked me!
Here is the simulator shot
![iPhone11Simulator](https://user-images.githubusercontent.com/1186354/106962249-d4a84c80-670c-11eb-8c7d-d74adbd19be4.png)

and here is a screen capture from actual device after deploying to app store
![iPhone11Device](https://user-images.githubusercontent.com/1186354/106962283-e4c02c00-670c-11eb-8033-553b58cdd172.png)

I am using ScreenUtil 4.0.3
 Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19042.789], locale en-US)
Xcode 12.4
Android SDK 30.0.3

Using same init as example code.

Here is an example of how I am using ScreenUtil

```
Text( 'Sample Text',
                  style: TextStyle( fontSize: ScreenUtil().setSp(50.0),
                      fontWeight: FontWeight.bold,
                      color: Colors.black),
                  textAlign: TextAlign.center,
                )
```

Any clues?

(Edit) FYI Runs great on all Android phones.

**Comment by lizhuoyuan** [comment]
Can you look at the size in your initialization method?

It may be the wrong size

**Comment by robertflesch** [comment]
@override
  Widget build(BuildContext context) {
    final themeProvider = Provider.of<ThemeProvider>(context);
    return LayoutBuilder(
        builder: (_, BoxConstraints constraints) {
      //Set the fit size (fill in the screen size of the device in the design,in dp)
      ScreenUtil.init(
        context: _,
        constraints: constraints,
        designSize: Size( 1080, 1920 ),
        allowFontScaling: true,
      );
      
these settings work great everywhere else, is there something I am not understanding about design size?

**Comment by robertflesch** [comment]
So I tried my app with the suggested size, totally blows it all up.
Why is it different with ios on app store than it is everywhere else?

**Comment by robertflesch** [comment]
I rebuilt a page of my app using the suggested designSize: Size(360, 690),
Does not solve the problem.
Still looks great in the ios simulator, but as soon as I publish in app store, fonts go crazy.
Simulator image from iphone 11
![image](https://user-images.githubusercontent.com/1186354/107117274-38cf2b80-6847-11eb-92b5-639ef52ad73e.png)

and image from app deployed to app store.
![IMG_5361](https://user-images.githubusercontent.com/1186354/107117279-42f12a00-6847-11eb-8ff4-27c5bc78b138.PNG)

Am I doing something wrong?
Or is something broken in lib? I just dont understand why the deployed version is so different than simulator. I am using ScreenUtil through out the page to set padding and position and font size. 
For example 
```
return Column(
      children: <Widget>[
        Padding(
          padding: EdgeInsets.only(
            top: ScreenUtil().setHeight(20.0),
            left: ScreenUtil().setWidth(20.0),
            right: ScreenUtil().setWidth(20.0),
          ),
          child: RichText(
            text: TextSpan(
              text: topic.title,
              style: TextStyle(
                  fontFamily: 'NuniSans',
                  fontSize: ScreenUtil().setSp(17.0),
                  color: Constants.black,
                  fontWeight: FontWeight.bold,
                  height: 1.2),
            ),
            overflow: TextOverflow.ellipsis,
            maxLines: 2,
            softWrap: true,
            textAlign: TextAlign.center,
          ),
        ),
     ]
  );
```

**Comment by lizhuoyuan** [comment]
Is there an ios installation package?
I want to install and see the effect。
In addition, have you tested it with a real machine and is there any problem with the display effect?

**Comment by robertflesch** [comment]
Thanks for the response. 
I am not allowed to share the app by my boss, but the screen shots I have posted are from real machines (deployed to test flight).
It's the "real machines" where the effect shows up. The font scaling effect does not show up in the simulator at all.
App looks perfect on ios simulator, but totally wrong factors the on test flight machines.
I have started digging into your code, one thing I notice is the internal textScaleFactor on ios test flight machines is 1.647... and on the ios simulator and android simulator and android real machine it is 1.0. That factor explains the much larger fonts on ios test flight machines.

**Comment by robertflesch** [comment]
So I have resolved my issue with the following fix, I edited the ScreenUtil source code and removed the textScaleFactor from the setSP, this combined with ONLY using RichText controls rather than Text control solves my font scaling issues.

**Comment by lizhuoyuan** [comment]
In fact, I have considered removing textScaleFactor, because textScaleFactor can be set uniformly in MaterailApp, but is there any decision? I don’t know if this is a good practice
