### ISSUE TITLE
stack positioned widget

### ISSUE THREAD

**Issue by ganeshchenniah** [OpenFlutter/flutter_screenutil#212]
Hi ,

I m having stack widget as shown below , can i make use of screen_util package and render same across different screen ?
Currently i m having design phone width 392, height 872 . 
But rendering is proper in design phone only , when i render in other phone with resolution width 411 height 683 , it is messing up , positioned widgets are not in place .

![Screenshot_1612528640](https://user-images.githubusercontent.com/13198936/107035430-2cfb4f00-67de-11eb-8c5f-3ae2ead27585.png)
![Screenshot_2021-02-05-18-14-05-215_com simform example](https://user-images.githubusercontent.com/13198936/107035437-2ec51280-67de-11eb-924f-6e53d9476c6e.jpg)

**Comment by lizhuoyuan** [comment]
You need to initialize based on the size of the design draft, not the size of the test phone.
In addition, the unit of size is dp, not px

**Comment by ganeshchenniah** [comment]
I m wrapping mainHomePage widget , i m giving screen sizes in dp only . I didnt understand "based on the size of the design draft" . Can you provide me some examples ?
ScreenUtilInit(
            designSize: Size(392, 872),
            allowFontScaling: false,
            builder: () => MaterialApp() //HomePage

**Comment by ganeshchenniah** [comment]
My test phone is POCO , 2400x1080 .and 392x872 in dp . What could be the design size for this ?

**Comment by lizhuoyuan** [comment]
I probably understand, did you not use the design draft as a reference, but directly make the UI and fine-tune the display effect yourself?
It is best to have a benchmark, otherwise the effect may have unknown display problems

**Comment by lizhuoyuan** [comment]
Temporarily close the question, if you still have a question, please reopen it
