### ISSUE TITLE
Different ouput on different devices

### ISSUE THREAD

**Issue by mobilegeekkk** [OpenFlutter/flutter_screenutil#215]
I used logical pixel value 50 dp directly without using screen util, the output comes 100px, 150px, 200px on 2x, 3x, 4x devices (Android & iOS) which is perfect I think as per native development approach while using ScreenUtil when we use adaptive height of 50dp the output differs with the LP approach. If flutter is already managing the screen adaptiveness then how screen util is beneficial for us. Can someone guide me regarding this ?

**Comment by lizhuoyuan** [comment]
for example:
Your current phone width is 400dp
So you write down 400dp so that the width is exactly the width of the screen,
Then you have another phone with a width of 500dp,
400dp here is not equal to the width of the screen
