### ISSUE TITLE
0.2.sw     0.5.sh  not work

### ISSUE THREAD

**Issue by hsnbsst** [OpenFlutter/flutter_screenutil#219]
This way usage might cause it doesn't work

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.7 19H114 darwin-x64, locale tr-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.3)
[✓] VS Code (version 1.53.0)
[✓] Connected device (3 available)

• No issues found!

**Comment by lizhuoyuan** [comment]
screenutil version?

**Comment by hsnbsst** [comment]
flutter_screenutil: ^4.0.3+1

**Comment by lizhuoyuan** [comment]
![image](https://user-images.githubusercontent.com/15923901/108964743-d71c1780-76b6-11eb-884e-aa15cf7578a2.png)
this is example code.
 What do you mean by "not work"？
