### ISSUE TITLE
你好，在redux 应用中如此使用报下面的异常

### ISSUE THREAD

**Issue by hszheng** [OpenFlutter/flutter_screenutil#22]
![image](https://user-images.githubusercontent.com/9276161/53950083-6284f280-4106-11e9-953d-6b66f80c7868.png)

![image](https://user-images.githubusercontent.com/9276161/53950050-4aad6e80-4106-11e9-9be3-08050d97fddf.png)

**Comment by lizhuoyuan** [comment]
在materialApp 里面的第一个加载的widget中初始化
