### ISSUE TITLE
How to responsive oriantaion layout

### ISSUE THREAD

**Issue by ashishoffice** [OpenFlutter/flutter_screenutil#220]
Can you added responsive oriantaion layout

**Comment by lizhuoyuan** [comment]
Sorry, I did not understand what you mean.
Can you elaborate

**Comment by Faiyyaz** [comment]
Previously we use to use this plugin inside an ```OrientationBuilder``` widget, so that we can change the design size on orientation change but now i think it will not be possible since you are wrapping the whole material app inside the ```ScreenUtilInit``` init

**Comment by lizhuoyuan** [comment]
> Previously we use to use this plugin inside an `OrientationBuilder` widget, so that we can change the design size on orientation change but now i think it will not be possible since you are wrapping the whole material app inside the `ScreenUtilInit` init

In fact, OrientationBuilder is used internally

**Comment by Faiyyaz** [comment]
Oh okay then can you expose the orientation so that we can know current orientation of the device? Also do you switch the designSize too according to the orientation or not?

**Comment by ashishoffice** [comment]
Can you send the example how to orientation

**Comment by Faiyyaz** [comment]
> Can you send the example how to orientation

Sorry i will send an updated sample tomorrow. I am using older version of the lib so i will update it to current version and send you the sample code.

**Comment by lizhuoyuan** [comment]
I think your problem should be resolved, if anyone has a problem, you can reopen it

**Comment by Faiyyaz** [comment]
Yes it has been thank you for your contribution

**Comment by RicardoLimaDev** [comment]
Hello @lizhuoyuan , i'm using version 5.0.0+2 and this is not working anymore; How can i change the designSize based on orientation?

**Comment by Faiyyaz** [comment]
Hi @RicardoLimaDev you can orientationbuilder widget. The design size will just interchange you can't have two different designsize

**Comment by lizhuoyuan** [comment]
> Hello @lizhuoyuan , i'm using version 5.0.0+2 and this is not working anymore; How can i change the designSize based on orientation?

You only need to set the vertical
