### ISSUE TITLE
Error: Getter not found: 'potrait'

### ISSUE THREAD

**Issue by rgushel** [OpenFlutter/flutter_screenutil#221]
Flutter 1.25.0-8.3.pre
Dart 2.12.0 (build 2.12.0-133.7.beta)
build 5.0.0-nullsafety.6

```
../../../.pub-cache/hosted/pub.dartlang.org/flutter_screenutil-5.0.0-nullsafety.6/lib/screenutil.dart:48:35: Error: Getter not found: 'potrait'.
    if(orientation == Orientation.potrait){
```

**Comment by maares** [comment]
In the mean time, you can replace the misspell word, until its fixed: 

`if (orientation == Orientation.portrait) {` 

#216
