### ISSUE TITLE
Re-initialize ScreenUtil when handling multiple layouts

### ISSUE THREAD

**Issue by thebuggycoder** [OpenFlutter/flutter_screenutil#224]
Currently, my application has two different UI design drafts for mobiles and tablets. The mobile design draft has the size **375x812** and the tablet draft has a size of **768x1024**.

I'm using `LayoutBuilder` widget to display different UI to the user according to the screen size. My question is that how can I initialize or rather re-initialize `ScreenUtilInit` separately for mobile and tablet layouts?

For example, consider the below code -
```dart
@override
Widget build(BuildContext context) {
  return ScreenUtilInit(
    designSize: Size(375, 812), // Draft size according to mobile device
    allowFontScaling: true,
    builder: () {
      return MaterialApp(
        home: LayoutBuilder(
          builder: (context, constraints) {
            if (constraints.maxWidth > 600) {
              //UI for tablet devices
            } else {
              //UI for mobile devices
            }
          },
        ),
      );
    },
  );
}
```
In this case, is there an option to re-initialize `ScreenUtil` with different dimensions when the application is running on tablet devices?

**Comment by lizhuoyuan** [comment]
device_info can determine whether the device is a tablet or a mobile phone.
And it’s better to use dp as the unit of the design draft, because the unit of initialization is now dp more appropriate
