### ISSUE TITLE
平板适配问题

### ISSUE THREAD

**Issue by momtboy** [OpenFlutter/flutter_screenutil#225]
想问大佬，如果设计稿是按照平板的尺寸设计的，并且是强制**横屏**的设计稿，宽度和高度应该怎么填写呢？

**Comment by lizhuoyuan** [comment]
我还真没试过。。
感觉这个有点特殊。
一般来讲，你可以直接输入横屏后的尺寸作为初始尺寸， 然后看一下效果

**Comment by HZRZCW** [comment]
> 想问大佬，如果设计稿是按照平板的尺寸设计的，并且是强制**横屏**的设计稿，宽度和高度应该怎么填写呢？

平板就不要适配了!

**Comment by momtboy** [comment]
@HZRZCW 手机上也要使用的啊，只是主要使用场景是平板

**Comment by lizhuoyuan** [comment]
使用上还有什么问题吗? 因为没有恢复暂时关闭，有问题可以重新打开并描述问题
