### ISSUE TITLE
Init error

### ISSUE THREAD

**Issue by caijiami** [OpenFlutter/flutter_screenutil#227]
Error: Too few positional arguments: 2 required, 1 given.
    ScreenUtil.init(
                   ^

flutter_screenutil: ^4.0.2
<img width="1233" alt="截屏2021-03-11 上午11 07 58" src="https://user-images.githubusercontent.com/45455521/110729655-0c4d6b80-825a-11eb-9954-03465120bef7.png">

**Comment by lizhuoyuan** [comment]
Switch to v4 branch View readme.md
