### ISSUE TITLE
ScreenUtil.screenWidth    打包release版本在真机上 获取的值是0

### ISSUE THREAD

**Issue by qyfeng009** [OpenFlutter/flutter_screenutil#23]
手机类型：MX3

**Comment by lizhuoyuan** [comment]
看一下具体代码?

**Comment by qyfeng009** [comment]
![main.dart](https://user-images.githubusercontent.com/17894845/54102335-ebe83d80-4402-11e9-8f9f-75d1c17d7a5e.png)
![home.dart](https://user-images.githubusercontent.com/17894845/54102343-f571a580-4402-11e9-8609-cc4d997507d8.png)
![login.dart](https://user-images.githubusercontent.com/17894845/54102345-fc001d00-4402-11e9-9c74-684b559c6fbf.png)

我是在 home 页面中完成注册的，在login中使用ScreenUtil.screenWidth 获取设备屏款，在开发模式和debug模式是可以正常获取屏宽的，只是在打包release版本后在手机上运行获取的值是0

**Comment by qyfeng009** [comment]
感觉像是 init 方法没有执行

**Comment by lizhuoyuan** [comment]
不要在initstate里面使用
因为这个时候 context还无法使用
获取屏幕数据依赖context

**Comment by qyfeng009** [comment]
![D494DB58-E194-4A2A-9E60-D87CDD3A464E](https://user-images.githubusercontent.com/17894845/54102805-d4aa4f80-4404-11e9-99cc-9abe78e22a43.png)
刚才我试一下 在build 中使用 ScreenUtil.screenWidth ，可以获取的值还是 0.0，这个问题只在release版本中出现

**Comment by lizhuoyuan** [comment]
我一会试一下

**Comment by qyfeng009** [comment]
我在 login 中也注册一遍，测试发现可以获取正常的值。产生我这个问题的原因应该和我的main.dart中的页面管理代码有关，不好意思应该是我的问题，谢谢了

**Comment by lizhuoyuan** [comment]
找到原因就好

**Comment by luckysmg** [comment]
能说一下这个页面管理具体是什么问题么，我也遇到这个问题
