### ISSUE TITLE
5.0.0-nullsafety

### ISSUE THREAD

**Issue by justkost** [OpenFlutter/flutter_screenutil#230]
I use the short format 30.sp, 20.w and so on, after upgrading to version 5.0.0-nullsafety.10, i get error:
_The argument type 'dynamic' can't be assigned to the parameter type 'double'_

sdk: ">=2.12.0 <3.0.0"
Flutter 2.0.2

![image](https://user-images.githubusercontent.com/18269060/111328704-0f54bb80-86a1-11eb-86c8-7cb0fdace11a.png)

**Comment by ken-ng-esotec** [comment]
Ditto

**Comment by ken-ng-esotec** [comment]
As a temporary fix, I created the below

// screen_util_extension.dart and imported this wherever I needed to use h, w or sp

```
import 'package:flutter_screenutil/screen_util.dart';

extension ScreenUtilExtension on int {
  double get h {
    return ScreenUtil().setHeight(this);
  }

  double get w {
    return ScreenUtil().setWidth(this);
  }

  double get sp {
    return ScreenUtil().setSp(this);
  }
}
```

**Comment by AscentionOne** [comment]
I have the same issue when using the 5.0.0-nullsafety version!

**Comment by lizhuoyuan** [comment]
I will check it on Flutter 2.0.2 today.
If there is a problem, I will submit a new version

**Comment by lizhuoyuan** [comment]
Can anyone run an example to reproduce this problem? I have upgraded to 2.0.2, but I still haven't encountered the same problem

**Comment by AscentionOne** [comment]
I am also on Flutter 2.0.2 and using flutter_screenutil 5.0.0-nullsafety.10 version. 
This is my error message:
![image](https://user-images.githubusercontent.com/44708790/111408820-cdfbf480-8710-11eb-9ec3-93485885bc27.png)

**Comment by lizhuoyuan** [comment]
@AscentionOne 
![image](https://user-images.githubusercontent.com/15923901/111409029-23d09c80-8711-11eb-8ec7-be911582d30f.png)
😌

**Comment by AscentionOne** [comment]
I get it to work when I change the parameter to specified as double.

![image](https://user-images.githubusercontent.com/44708790/111409148-5b3f4900-8711-11eb-840e-85577a8b18bf.png)

interesting...

**Comment by lizhuoyuan** [comment]
Is it only the compiler that reports an error or does it run with the same problem?
Could it be a problem with the compiler/plugin version?

**Comment by AscentionOne** [comment]
I think @justkost 's error message comes from linting. I did get the same error message when using lint.

**Comment by AscentionOne** [comment]
However, when I close the lint it did show the error I just post. I didn't add `const`. 

This is my flutter doctor -v short version:

[√] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.19041.867], locale zh-TW)
    • Flutter version 2.0.2 at D:\flutterdevelopment\flutter
    • Framework revision 8962f6dc68 (5 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2) 
    • Android SDK at D:\androidsdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = D:\androidsdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

**Comment by lizhuoyuan** [comment]
It’s exactly the same as my information, but I haven’t reproduced this problem in vscode or android studio. I have a headache.

**Comment by AscentionOne** [comment]
I think the error message comes from dart check. Not sure if it is because in the 5.0.0-nullsafety.11. I saw the change from `double` to `num`. So dart cannot be sure, because it could be `int` or `double` and getter return a double specifically. I think that is the reason why I explicitly use double work and int doesn't work.

**Comment by AscentionOne** [comment]
Sorry I might be wrong ..... However, I check the package `size_extension.dart` in 5.0.0-nullsafety.10 version its still extending on `double`. Is this correct? 

![image](https://user-images.githubusercontent.com/44708790/111410594-ff29f400-8713-11eb-8ad1-cfd0b8176b67.png)

**Comment by lizhuoyuan** [comment]
no , you should update

**Comment by AscentionOne** [comment]
But the Pub.dev page is still on version 10.
https://pub.dev/packages/flutter_screenutil/versions/5.0.0-nullsafety.10/changelog

**Comment by lizhuoyuan** [comment]
I remember that I submitted version 11 two days ago. It may be that my memory has been biased. Sorry.
Or there is a problem with the network.
In short, I am sorry.
Now , you can use 11.

**Comment by AscentionOne** [comment]
I see the changes now! It's okay we all forget something sometimes. More important is the problem is solved😊! I updated the package to version 11 and it works like a charm! Thank you! 

p.s. there is a small typo in the changelog 'nnullsafety'. 😁
