### ISSUE TITLE
padding 10.w is not working. 

### ISSUE THREAD

**Issue by NTMS2017** [OpenFlutter/flutter_screenutil#231]
I follow the examples and examples is working. But when I implement in my project the  padding: EdgeInsets.all(10.w),  in w is not working. 

the h, w, r as well as sp is not working.

I am using 2.0.2 flutter sdk stable width flutter_screenutil: ^4.0.3+3.

Any idea?

```
child: new Padding(
          padding: EdgeInsets.all(10.w),
```

```
 appBar: PreferredSize(
            preferredSize: Size(double.infinity, 6.0.h),
```

**Comment by lizhuoyuan** [comment]
请使用null-safety.11

**Comment by NTMS2017** [comment]
Sorry didnt work. I use flutter clean and test it.

MyApp section is:

```
return MultiProvider(
  providers: [
    ChangeNotifierProvider(create: (_) => packageInfoProvider),
    ChangeNotifierProvider(create: (_) => appLanguage),
    ChangeNotifierProvider(create: (_) => UserInfoProvider()),
  ],
  child: LayoutBuilder(builder: (context, constraints) {
    return OrientationBuilder(
      builder: (context, orientation) {
        return Consumer<AppLanguage>(builder: (context, model, child) {
          return ScreenUtilInit(
              designSize: Size(360, 690),
              allowFontScaling: true,
              builder: () => MaterialApp(
```

**Comment by lizhuoyuan** [comment]
Did you import flutter_screenutil?

**Comment by NTMS2017** [comment]
Yes, null safety 11 version. And in AS terminal I wrote flutter clean twice ad well as I use invalidate and cash restart. Have no idea? I thought my main.dart has a problem. But ScreenUtil().screenwidth is working.

**Comment by lizhuoyuan** [comment]
Maybe you imported the wrong file?
Use import'package:flutter_screenutil/flutter_screenutil.dart';

**Comment by NTMS2017** [comment]
I will check gain this afternoon (GMT3.0). Thanks

**Comment by NTMS2017** [comment]
Thanks this " **import'package:flutter_screenutil/flutter_screenutil.dart';** " worked.

In my project I have a container and set:

 `width: ScreenUtil().screenWidth,`

ScreenUtil() had Curley red line under it. When I try to see what should I need to do still tells me to import old screen util dart file. In flutter sdk .pub-cache I only have new version of screen util plugin. So I need to import above line one by one to make it to work. 

Thanks for help

**Comment by lizhuoyuan** [comment]
I will try to see if there is a way to optimize the behavior of this guide package

**Comment by NTMS2017** [comment]
Before closing this issue I need to ask one more thing.

If I had an old style height as shown below. How can I use plugin to make similar.

**Before:**
 `preferredSize: Size(double.infinity, 66.0),`

**After:**
` preferredSize: Size(double.infinity, 6.0.h),`

Does both same or should have to still make like  **preferredSize: Size(double.infinity, 66.0.h),**?

**Comment by lizhuoyuan** [comment]
If your 66.0 comes from the size of the design draft, you can write 66.h/66.w.
Otherwise, there may be a problem of inappropriate size

**Comment by NTMS2017** [comment]
Thank you very much.
