### ISSUE TITLE
你好 flutter_screenutil 4.0.3 版本中的 ScreenUtil.init()中给了orientation会提示参数未定义(用了实例代码也是一样) 编译器是vscode

### ISSUE THREAD

**Issue by wzy113028** [OpenFlutter/flutter_screenutil#232]
你好 flutter_screenutil 4.0.3 版本中的 ScreenUtil.init()中给了orientation会提示参数未定义(用了实例代码也是一样) 编译器是vscode

**Comment by siberiawolf** [comment]
<img width="821" alt="QQ20210321-111222@2x" src="https://user-images.githubusercontent.com/3274949/111892419-58f12d80-8a36-11eb-8379-273bd08be171.png">

我也保这个错误了～

**Comment by siberiawolf** [comment]
示例代码有问题，初始化参数写的不对吧。另外注意`Orientation.portrait`这个参数，得在`BoxConstraints`这个参数后面

修改成如下方式即可：

```dart
//设置尺寸（填写设计中设备的屏幕尺寸）如果设计基于360dp * 690dp的屏幕
    ScreenUtil.init(
      BoxConstraints(
        maxWidth: MediaQuery.of(context).size.width,
        maxHeight: MediaQuery.of(context).size.height,
      ),
      Orientation.portrait,
      designSize: Size(360, 690), 
      allowFontScaling: false,
    );
```

**Comment by lizhuoyuan** [comment]
不好意思，是版本问题
null-safety是这样初始化的，我修改一下
