### ISSUE TITLE
混合开发项目，首次报错_instance != null

### ISSUE THREAD

**Issue by chenzufeng** [OpenFlutter/flutter_screenutil#234]
环境：
混合开发项目
插件：^4.0.4
flutter sdk: 1.22.6

mian里面的初始化代码：
ScreenUtilInit(
      designSize: Size(750,1334),
      allowFontScaling: false,
      builder: () => MultiProvider(
        providers: [
          ChangeNotifierProvider(create: (_) => themeModel)
        ],
        child: CommonRefreshConfig(
            child: App()
        ),
      ),
    )

项目首次报错会_instance != null，原因是constraints.maxWidth == 0导致没有初始化ScreenUtil。
可能是因为原生项目启动时，预加载了Flutter模块，触发mian里面的ScreenUtilInit初始化，此时Flutter页面还未打开，就导致constraints.maxWidth == 0了。

请问有什么办法解决吗？

**Comment by chenzufeng** [comment]
感谢这么快的回复。
原生会跳多个Flutter的页面，这样的话，每个页面都需要手动调一次init方法对吧？
我希望能有一个统一的init方法，这样可以避免有些页面忘记init而报错。
你有什么建议吗？

**Comment by lizhuoyuan** [comment]
之前多个engine的时候，如果是从原生跳到flutter页面是会这样
我不太确定现在单engine的情况了。
如果是 原生页面->flutter页面A->flutter页面B->flutter页面C 这种的话 ， 只在A初始化就可以了。
只取决于当前flutter页面的前一个页面
暂时没有太好的方法，因为近期都没有搞类似频繁跳转的混合开发

**Comment by chenzufeng** [comment]
测试了下，单engine的情况下，你说的case，只要A初始化就可以了。
只是我的项目不确定用户是先进A还是先进B，暂时我还是A和B都初始化。
我先关闭这个问题，继续关注~
