### ISSUE TITLE
not support null safety

### ISSUE THREAD

**Issue by hadeerr95** [OpenFlutter/flutter_screenutil#236]
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:
 - package:flutter_screenutil

**Comment by lizhuoyuan** [comment]
Is the empty safe version used?

**Comment by hadeerr95** [comment]
This is last version used

**Comment by lizhuoyuan** [comment]
Can you provide detailed information?

**Comment by hadeerr95** [comment]
done
