### ISSUE TITLE
版本4.0.4 在web端获取屏幕的宽得到的是屏幕的高

### ISSUE THREAD

**Issue by mengsiyitiaojie** [OpenFlutter/flutter_screenutil#238]
版本4.0.4 在web端获取屏幕的宽得到的是屏幕的高   获取屏幕的高得到的是屏幕的宽

**Comment by mengsiyitiaojie** [comment]
希望能解决一下

**Comment by lizhuoyuan** [comment]
是同一套代码只在web端是相反的吗

**Comment by mengsiyitiaojie** [comment]
![image](https://user-images.githubusercontent.com/55568326/112809684-d6f3ab00-90ac-11eb-9a44-b55afe63d97e.png)

**Comment by mengsiyitiaojie** [comment]
对的 导致web端和手机端不统一

**Comment by lizhuoyuan** [comment]
了解了，确实代码有个地方不对，我看一下是不是这个问题

**Comment by mengsiyitiaojie** [comment]
这样写在web端是正常了 但是在手机端就不对了

**Comment by lizhuoyuan** [comment]
方便打印一下屏幕方向吗？

**Comment by lizhuoyuan** [comment]
依赖一下github的v4分支试一下。

**Comment by mengsiyitiaojie** [comment]
咋依赖呢

**Comment by lizhuoyuan** [comment]
flutter_screenutil:
    git:
      url: https://github.com/OpenFlutter/flutter_screenutil
      ref: v4

**Comment by mengsiyitiaojie** [comment]
![image](https://user-images.githubusercontent.com/55568326/112812179-613d0e80-90af-11eb-9981-65a48e24a698.png)

**Comment by mengsiyitiaojie** [comment]
这样吗

**Comment by mengsiyitiaojie** [comment]
![image](https://user-images.githubusercontent.com/55568326/112812293-8893db80-90af-11eb-83d6-cf3a754db5c7.png)

**Comment by mengsiyitiaojie** [comment]
要报错

**Comment by lizhuoyuan** [comment]
缩进
```
git:
    url: https://github.com/OpenFlutter/flutter_screenutil
    ref: v4
```

**Comment by mengsiyitiaojie** [comment]
可以了 v4版本正常

**Comment by mengsiyitiaojie** [comment]
![image](https://user-images.githubusercontent.com/55568326/112812995-520a9080-90b0-11eb-9b65-95b2124b9117.png)

**Comment by lizhuoyuan** [comment]
那稍后就换成 4.0.4+1 版本就好了

**Comment by mengsiyitiaojie** [comment]
![image](https://user-images.githubusercontent.com/55568326/112813027-5c2c8f00-90b0-11eb-949f-e83311840c7a.png)

**Comment by lizhuoyuan** [comment]
是的

**Comment by mengsiyitiaojie** [comment]
![image](https://user-images.githubusercontent.com/55568326/112814273-b548f280-90b1-11eb-9b3e-958c82655d08.png)

**Comment by mengsiyitiaojie** [comment]
要报错

**Comment by lizhuoyuan** [comment]
我这边显示已经有了 
![image](https://user-images.githubusercontent.com/15923901/112814621-0fe24e80-90b2-11eb-9982-911f6fd6a900.png)

可能要稍后再试吧

**Comment by mengsiyitiaojie** [comment]
可以了
