### ISSUE TITLE
AndroidX migration

### ISSUE THREAD

**Issue by siddharthpatankar** [OpenFlutter/flutter_screenutil#24]
Any plans to migrate the plugin to use the AndroidX support library? It would really help since lot of plugins are migrating the AndroidX.

**Comment by lizhuoyuan** [comment]
This library does not need to be migrated to androidx and can be used normally. If necessary, I will do it, thank you.

**Comment by siddharthpatankar** [comment]
Great! I'll close the issue. Thanks for a great library!
