### ISSUE TITLE
字体大小缩放问题

### ISSUE THREAD

**Issue by windrunner414** [OpenFlutter/flutter_screenutil#240]
setSp里面对textScaleFactor的处理是如果允许缩放则`(fontSize * scaleText) * _textScaleFactor`，应该为若不允许缩放则`(fontSize * scaleText) / _textScaleFactor`
flutter本身会根据MediaQuery里的textScaleFactor进行一次缩放，并不需要再次*textScaleFactor
现在如果allowFontScaling为true则会缩放两次，为false则根据系统缩放

**Comment by windrunner414** [comment]
看起来_textScaleFactor也没有自动更新，启动app时系统设置为默认大小（1.0），再切换到超大（1.3），是正常的缩放倍数（1.3），如果启动时是超大，就放大了两次（1.3*1.3），再切换回默认，放大了一次（1.3）

**Comment by lizhuoyuan** [comment]
这个我准备去掉缩放相关的东西， 因为可以在MaterialApp里设置缩放系数，这个你可以在文档最后面里找到。

**Comment by lizhuoyuan** [comment]
已经提交了新的版本，如果还有问题欢迎回复
