### ISSUE TITLE
改变屏幕大小时不会重建组件

### ISSUE THREAD

**Issue by windrunner414** [OpenFlutter/flutter_screenutil#241]
flutter 2.1.0
当屏幕大小改变（比如分屏模式下调整窗口大小，或者是浏览器改变窗口大小），LayoutBuilder重新调用了builder，screenutil重新init了，但是页面中别的组件并不会重新build，导致并没能按照新的屏幕大小进行变化。此时如果其他操作触发了组件重建，便会按照新的大小进行适配，造成屏幕中部分组件按旧大小适配，部分组件按新大小适配的情况

**Comment by lyf571321556** [comment]
同样问题，在ios safari浏览器中，输入地址访问项目首页后，点击浏览器地址栏，接着点击取消，会发现所有问题都变小了，只有刷新页面才会恢复正常。

**Comment by AscentionOne** [comment]
Hi, I also have the same issue. I am using it in web applications. When I resize the screen the font (ex: 15.sp) and the widget size (ex: 30.w) is not changed accordingly. I have to hot reload or refresh the page so the widget will rebuild correctly. I am initializing the application using the below method.

``` dart 
ScreenUtilInit(
      builder: () => MaterialApp(),
    );
```

**Comment by lizhuoyuan** [comment]
@AscentionOne Can you provide a minimal demo

**Comment by AscentionOne** [comment]
My problem is that I am creating a web app with a layout builder for responsiveness and in different layouts, I will show different widgets. However, when the layout change based on the web windows size (width). The font size (ex: 15.sp) and width (10.w) is not changing accordingly. I will have to manually refresh the page to rebuild the widget then it will work.

I initial the flutterutil like below which is the first method you suggest.

``` dart
void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    //Set the fit size (Find your UI design, look at the dimensions of the device screen and fill it in,unit in dp)
    return ScreenUtilInit(
      designSize: Size(360, 690),
      builder: () => MaterialApp( ),
    );
  }
}
```

I also read through this issue
https://github.com/OpenFlutter/flutter_screenutil/issues/252

Does this mean that we will have run the below method in every widget we use flutterutil? (the second method)

``` dart
ScreenUtil.init(
        BoxConstraints(
            maxWidth: MediaQuery.of(context).size.width,
            maxHeight: MediaQuery.of(context).size.height),
        designSize: Size(360, 690),
        orientation: Orientation.portrait);
```

or just do like this?

``` dart
Widget build(BuildContext context) {
    return LayoutBuilder(
      ScreenUtil.init(
        BoxConstraints(
            maxWidth: MediaQuery.of(context).size.width,
            maxHeight: MediaQuery.of(context).size.height),
        designSize: Size(360, 690),
        orientation: Orientation.portrait);
      builder: (context, constraints) {
        if (constraints.maxWidth >= 1024) {
          return desktop;
        }
        else if (constraints.maxWidth >= 768) {
          return tablet;
        }
        else {
          return mobile;
        }
      },
    );
  }
```

**Comment by lizhuoyuan** [comment]
I ran the example code and modified the size of the browser. The UI has changed.
![2021-07-14 10 33 29](https://user-images.githubusercontent.com/15923901/125551691-bd41437f-6d32-41db-9352-c8f53e18694e.gif)

**Comment by AscentionOne** [comment]
@lizhuoyuan  Wow, can I check the example code that you run? I am curious where did you initialize the screenutil? Maybe I did it wrong... 😋 Thank you!

**Comment by lizhuoyuan** [comment]
https://github.com/OpenFlutter/flutter_screenutil/blob/master/example/lib/main.dart.

**Comment by lizhuoyuan** [comment]
> @lizhuoyuan Wow, can I check the example code that you run? I am curious where did you initialize the screenutil? Maybe I did it wrong... My font is not resizing... 😋 Thank you!

https://github.com/OpenFlutter/flutter_screenutil/blob/master/example/lib/main.dart

**Comment by AscentionOne** [comment]
@lizhuoyuan  Thank you, I check and it did work. I have a question is, since I am creating an application that is both works in web applications and mobile. What is a good method to create a responsive layout? Since as in the web application changing the screen size (dragging the edge of the browser screen) width or height does not change the padding of the widget. However, if I use the screenutil and set the padding let's say 

``` dart
Padding(
                padding: EdgeInsets.symmetric(
                  vertical: 20.w,
                  horizontal: 40.w,
                ),
```
The widget padding will change according to the screen size. However, if I don't use 20.w and use 20. The scale will not be right. Since the design is based on 1920*1080. I have to set ```designSize: Size(1920, 1080)``` like this.

However, when in mobile. This will work fine because we don't change the screen size as the web does. 

Thank you! 😁

**Comment by lizhuoyuan** [comment]
The best way is to try not to write a fixed value, and try to use a ratio instead of a fixed value, so as to maximize the display effect of the style on different devices. 
However, it is impractical to not use it at all.

So I wrote this plugin to help the program display properly on as many devices as possible.

**Comment by xiaobingcaicai** [comment]
> flutter 2.1.0 当屏幕大小改变（比如分屏模式下调整窗口大小，或者是浏览器改变窗口大小），LayoutBuilder重新调用了builder，screenutil重新init了，但是页面中别的组件并不会重新build，导致并没能按照新的屏幕大小进行变化。此时如果其他操作触发了组件重建，便会按照新的大小进行适配，造成屏幕中部分组件按旧大小适配，部分组件按新大小适配的情况

我在桌面应用上遇到了同样的问题和现象，请问你的问题解决了么？

**Comment by windrunner414** [comment]
> > flutter 2.1.0 当屏幕大小改变（比如分屏模式下调整窗口大小，或者是浏览器改变窗口大小），LayoutBuilder重新调用了builder，screenutil重新init了，但是页面中别的组件并不会重新build，导致并没能按照新的屏幕大小进行变化。此时如果其他操作触发了组件重建，便会按照新的大小进行适配，造成屏幕中部分组件按旧大小适配，部分组件按新大小适配的情况
> 
> 我在桌面应用上遇到了同样的问题和现象，请问你的问题解决了么？

我已经用别的方法做屏幕适配了，这个问题是因为build的时候没有依赖MediaQuery，所以并没有让所有使用到了的组件都rebuild。如果必须解决的话，在计算宽高的时候把当前的context传过去，然后MediaQuery.of(context)。或者换成全局缩放的方式来做适配

**Comment by lizhuoyuan** [comment]
更新5.0.3然后尝试一下

**Comment by xiaobingcaicai** [comment]
> 更新5.0.3然后尝试一下

试了下 并没有起作用，这是我的使用代码

`class LurkerApp extends StatelessWidget {
  LurkerApp({Key? key}) : super(key: key);

  final easyLoad = EasyLoading.init();
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    // okToast
    return OKToast(child: _buildApp());
  }

  // 创建主app widget
  Widget _buildApp() {
    return GetMaterialApp(
              initialRoute: RouteConfig.main,
              getPages: RouteConfig.getPages,
              title: 'xxxxx',
              theme: createTheme(),
              home: const LurkerHome(),
              builder: (context, child) {
                child = easyLoad(context, child);
                // 可继续构建其他插件
                return child;
              },
            );
  }
}

class LurkerHome extends StatefulWidget {
  const LurkerHome({Key? key}) : super(key: key);

  @override
  _LurkerHomeState createState() => _LurkerHomeState();
}

class _LurkerHomeState extends State<LurkerHome> {
  @override
  Widget build(BuildContext context) {
    ScreenUtil.init(
      BoxConstraints(
          maxWidth: MediaQuery.of(context).size.width,
          maxHeight: MediaQuery.of(context).size.height),
      designSize: const Size(1920, 1080),
      // 传入context会更灵敏的根据屏幕变化而改变
      context: context,
    );
    return Scaffold(
      body: Center(
        child: Container(
           // 其他页面
            child: const HomeMainPage()),
      ),
    );
  }
}`
