### ISSUE TITLE
【android】在新页面自动获取焦点，键盘弹出后，字体大小.sp后显示错误大小；

### ISSUE THREAD

**Issue by lyf571321556** [OpenFlutter/flutter_screenutil#242]
stop to reproduce:
![image](https://user-images.githubusercontent.com/2295872/114007885-4bd89900-9894-11eb-9520-457082e0228c.png)

点击搜索历史，搜索显示结果后：
![image](https://user-images.githubusercontent.com/2295872/114008096-7d516480-9894-11eb-8804-ea24d10edd5c.png)

期望结果应该是：
![image](https://user-images.githubusercontent.com/2295872/114008226-9bb76000-9894-11eb-9eff-2754f16cda68.png)

 flutter_screenutil: ^4.0.4+1

**Comment by lizhuoyuan** [comment]
是自动获取焦点才会有这个问题吗？

**Comment by lyf571321556** [comment]
并且关闭带键盘的搜索页面返回上一个页面，也会造成上一个页面字体大小从不正常变为正常切换；

**Comment by lyf571321556** [comment]
> 是自动获取焦点才会有这个问题吗？

是的，关闭自动获取焦点，不会出现这个现象，怀疑是键盘弹出过程，flutter_screenutil 重新init了，并且获取到的屏幕大小是键盘上方区域部分

**Comment by lizhuoyuan** [comment]
你是在哪里init的？
当前页面的build里？
你尝试讲.sp替换为.w试一下？

**Comment by lyf571321556** [comment]
> 你是在哪里init的？
> 当前页面的build里？
> 你尝试将.sp替换为.w试一下？
在app入口
ScreenUtilInit(
              builder: () {
                return MaterialApp();
});
ok，先试试w看看

**Comment by lyf571321556** [comment]
> 你是在哪里init的？
> 当前页面的build里？
> 你尝试将.sp替换为.w试一下？

请教个问题，在app入口初始化完成之后，在app内还会不会存在再次执行下列代码的可能？
![image](https://user-images.githubusercontent.com/2295872/114009886-25b3f880-9896-11eb-8328-1204b913c4e7.png)

**Comment by lyf571321556** [comment]
> 你是在哪里init的？
> 当前页面的build里？
> 你尝试将.sp替换为.w试一下？

用.w，看起来没什么问题，这样的话说明键盘弹出后screenutil获取到的高度是不包含键盘部分的，导致依赖高度比例计算有问题

**Comment by lyf571321556** [comment]
> > 你是在哪里init的？
> > 当前页面的build里？
> > 你尝试将.sp替换为.w试一下？
> 
> 用.w，看起来没什么问题，这样的话说明键盘弹出后screenutil获取到的高度是不包含键盘部分的，导致依赖高度比例计算有问题

![image](https://user-images.githubusercontent.com/2295872/114012066-76c4ec00-9898-11eb-9992-e876abb56e2a.png)
的确是我说的这个问题

**Comment by lyf571321556** [comment]
用w字体没问题，但是.h设置的间距或者widget大小 在上边说的情况也会存在一个从小变大的情况，而且间距和大小这些都用.w替换.h还是不太理想

**Comment by lizhuoyuan** [comment]
会的

**Comment by lizhuoyuan** [comment]
我也试过页面自动获取焦点，但是没有复现，
有没有可以复现的最小代码块发一下？
我针对性修改一下

**Comment by lyf571321556** [comment]
> 我也试过页面自动获取焦点，但是没有复现，
> 有没有可以复现的最小代码块发一下？
> 我针对性修改一下

Page A 一个列表 列表使用.sp设置字体大小，Page B 顶部一个textfield（autofocus:true），底部一个listview,然后从A跳转到B之后，键盘弹出，然后在输入框输入文字后，根据输入文字触发搜索，然后将搜索结果给到listview（其中的item中的字体也是用.sp设置大小）渲染，此时渲染出来的字体就不是正常的，重点是一定要进入B的时候自动弹出键盘，并且此时listview中还没任何元素，得由用户输入后生成待显示结果后设置给listview才会重现这个问题。

**Comment by lyf571321556** [comment]
如果调整代码后还不能复现，请回复下我，我把关键代码从项目中整理处理上传

**Comment by lizhuoyuan** [comment]
第一个页面是SingleChildScrollView，基于example中的代码加了以下跳转代码：
```dart
 floatingActionButton: FloatingActionButton(
        onPressed: () {
          Navigator.of(context)
              .push(MaterialPageRoute(builder: (BuildContext context) => SecondPage()));
        },
      ),
```
其他没做改动
第二个页面代码：
```dart
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

class SecondPage extends StatefulWidget {
  @override
  _SecondPageState createState() => _SecondPageState();
}

class _SecondPageState extends State<SecondPage> {
  List<String> list = [];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(
          '20sp',
          style: TextStyle(fontSize: 20.sp),
        ),
      ),
      body: Column(
        children: [
          TextField(
            autofocus: true,
            style: TextStyle(fontSize: 20.sp),
            onChanged: (text) {
              list.add(text);
              setState(() {

              });
            },
          ),
          ListView.builder(
            shrinkWrap: true,
            itemBuilder: _itemBuilder,
            itemCount: list?.length ?? 0,
          ),
        ],
      ),
    );
  }

  Widget _itemBuilder(BuildContext context, int index) {
    return Text(
      '${list[index]}',
      style: TextStyle(fontSize: 20.sp),
    );
  }
}

```
gif:

![2021-04-12 11 59 48](https://user-images.githubusercontent.com/15923901/114339025-e2ec6c00-9b86-11eb-8189-102304334f1a.gif)



暂时没有复现.

**Comment by lyf571321556** [comment]
已经找到screenutil.init在键盘弹出时被重新调用的问题了，是因为android的Mainactivity主题里边某个属性导致的，感谢回复。
