### ISSUE TITLE
5.0版本不设置字体缩放的方式  是怎么用新的方式缩放的呢 还可以继续使用14.sp这样的吗 .sp在5.0版本也是缩放的吗

### ISSUE THREAD

**Issue by mengsiyitiaojie** [OpenFlutter/flutter_screenutil#243]
5.0版本不设置字体缩放的方式  是怎么用新的方式缩放的呢 还可以继续使用14.sp这样的吗 .sp在5.0版本也是缩放的吗  就是用这样的方式的时候
![image](https://user-images.githubusercontent.com/55568326/114680595-ef67f480-9d3f-11eb-8306-f1c577fbc31e.png)

**Comment by lizhuoyuan** [comment]
直接使用14.sp这样的
如果不想跟随系统缩放可以设置
```dart
 MediaQuery.of(context).copyWith(textScaleFactor: 1.0)
```
具体可以看文档结尾部分
