### ISSUE TITLE
How to use allow allowFontScalingSelf in new versio null safety?

### ISSUE THREAD

**Issue by yusriltakeuchi** [OpenFlutter/flutter_screenutil#246]
I' confusing because my font is really big!
How to use allowFontScalingSelf: true in the new version of null safety?

**Comment by lizhuoyuan** [comment]
The new version does not have this parameter, if you want to set it to false, you need to set it in the theme.
 ```
MediaQuery.of(context).copyWith(textScaleFactor: 1.0),
```
please read read.me:
https://github.com/OpenFlutter/flutter_screenutil#setting-font-does-not-change-with-system-font-size

If there is something difficult to understand, please tell me and I will try my best to modify

**Comment by yusriltakeuchi** [comment]
> The new version does not have this parameter, if you want to set it to false, you need to set it in the theme.
> 
> ```
> MediaQuery.of(context).copyWith(textScaleFactor: 1.0),
> ```
> 
> please read read.me:
> https://github.com/OpenFlutter/flutter_screenutil#setting-font-does-not-change-with-system-font-size
> 
> If there is something difficult to understand, please tell me and I will try my best to modify

I tested on ipad, and when i use ScreenUtil.defaultSize.width, i get the size for the small iphone not for ipad, so my UI is not good when i try in ipad.

I use this code to initial screen util, it's work in lower version than null safety
can you give me solution why?

```dart
void setupScreenUtil(BuildContext context) {
  double width = MediaQuery.of(context).size.width;
  double height = MediaQuery.of(context).size.height;
  double defaultScreenUtilWidth = 1080;
  double defaultScreenUtilHeight = 1920;
  double iPadPro12InchWidth = 2048;
  double iPadPro12InchHeight = 2732;

  /// ipad 11-inch width: 834, height: 1194
  /// ipad 9-inch width: 768, height: 1024
  if (width >= 768) {
    width = iPadPro12InchWidth;
  } else {
    width = defaultScreenUtilWidth;
  }

  if (height >= 1024) {
    height = iPadPro12InchHeight;
  } else {
    height = defaultScreenUtilHeight;
  }
  ScreenUtil.init(
    BoxConstraints(
      maxWidth: width,
      maxHeight: height
    ),
    designSize: Size(width, height),
    orientation: Orientation.portrait
  );
}
```

This is the look when run on ipad, shouldn't be like this, it looks really small
![Simulator Screen Shot - iPad Pro (12 9-inch) (4th generation) - 2021-04-25 at 12 46 12](https://user-images.githubusercontent.com/10339660/115982330-79c41a00-a5c4-11eb-8f35-16e0c1521607.png)


This is the look when run on iphone
![Simulator Screen Shot - iPhone 11 Pro Max - 2021-04-25 at 12 32 32](https://user-images.githubusercontent.com/10339660/115982347-93fdf800-a5c4-11eb-968e-fb54188d17bb.png)

**Comment by lizhuoyuan** [comment]
designSize: Size(width, height), 
The width and height here are the height and width of the device in the design draft

**Comment by yusriltakeuchi** [comment]
> designSize: Size(width, height),
> The width and height here are the height and width of the device in the design draft. （Will not change with the equipment）
> 
> And the size of the size should use DP instead of PX (my suggestion, of course, if you can keep it, there should be no problem)

So in the designSize we must insert like this?
designSize: Size(360, 690)

**Comment by yusriltakeuchi** [comment]
When i use default value 
 designSize: Size(360, 690)

the result is really bad
![Screenshot_1619337685](https://user-images.githubusercontent.com/10339660/115985699-38893580-a5d7-11eb-9401-0d39bece6e61.png)

I try to set font using this
double setFontSize(double size) => size.sp;

and get width and height device using like this:
double get deviceWidth => ScreenUtil.defaultSize.width;
double get deviceHeight => ScreenUtil.defaultSize.height;

**Comment by adnankhan74444** [comment]
how i can use this allowFontScalingSelf in new version ?

**Comment by lizhuoyuan** [comment]
> how i can use this allowFontScalingSelf in new version ?

#243

The new version removes this parameter, and the font will be scaled according to the system by default.
If you don’t want this behavior, you can see the end of the document

**Comment by lizhuoyuan** [comment]
> When i use default value
> 
> ```dart
>  designSize: Size(360, 690)
> ```
> 
> the result is really bad
> ![Screenshot_1619337685](https://user-images.githubusercontent.com/10339660/115985699-38893580-a5d7-11eb-9401-0d39bece6e61.png)
> 
> I try to set font using this
> 
> ```dart
> double setFontSize(double size) => size.sp;
> ```
> 
> and get width and height device using like this:
> 
> ```dart
> double get deviceWidth => ScreenUtil.defaultSize.width;
> double get deviceHeight => ScreenUtil.defaultSize.height;
> ```

Your units are inconsistent. If the initial unit is dp, then the unit in the code should also be dp.
By the way, do you have a design draft?

**Comment by lizhuoyuan** [comment]
> > The new version does not have this parameter, if you want to set it to false, you need to set it in the theme.
> > ```
> > MediaQuery.of(context).copyWith(textScaleFactor: 1.0),
> > ```
> > 
> > 
> > please read read.me:
> > https://github.com/OpenFlutter/flutter_screenutil#setting-font-does-not-change-with-system-font-size
> > If there is something difficult to understand, please tell me and I will try my best to modify
> 
> I tested on ipad, and when i use ScreenUtil.defaultSize.width, i get the size for the small iphone not for ipad, so my UI is not good when i try in ipad.
> 
> I use this code to initial screen util, it's work in lower version than null safety
> can you give me solution why?
> 
> ```dart
> void setupScreenUtil(BuildContext context) {
>   double width = MediaQuery.of(context).size.width;
>   double height = MediaQuery.of(context).size.height;
>   double defaultScreenUtilWidth = 1080;
>   double defaultScreenUtilHeight = 1920;
>   double iPadPro12InchWidth = 2048;
>   double iPadPro12InchHeight = 2732;
> 
>   /// ipad 11-inch width: 834, height: 1194
>   /// ipad 9-inch width: 768, height: 1024
>   if (width >= 768) {
>     width = iPadPro12InchWidth;
>   } else {
>     width = defaultScreenUtilWidth;
>   }
> 
>   if (height >= 1024) {
>     height = iPadPro12InchHeight;
>   } else {
>     height = defaultScreenUtilHeight;
>   }
>   ScreenUtil.init(
>     BoxConstraints(
>       maxWidth: width,
>       maxHeight: height
>     ),
>     designSize: Size(width, height),
>     orientation: Orientation.portrait
>   );
> }
> ```
> 
> This is the look when run on ipad, shouldn't be like this, it looks really small
> ![Simulator Screen Shot - iPad Pro (12 9-inch) (4th generation) - 2021-04-25 at 12 46 12](https://user-images.githubusercontent.com/10339660/115982330-79c41a00-a5c4-11eb-8f35-16e0c1521607.png)
> 
> This is the look when run on iphone
> ![Simulator Screen Shot - iPhone 11 Pro Max - 2021-04-25 at 12 32 32](https://user-images.githubusercontent.com/10339660/115982347-93fdf800-a5c4-11eb-968e-fb54188d17bb.png)

defaultSize is designSize .
It has nothing to do with the device you are currently using

**Comment by yusriltakeuchi** [comment]
@lizhuoyuan but if i use default design size like this

designSize: Size(360, 690),
The result text is really big,

**Comment by lizhuoyuan** [comment]
Can you upload a screenshot of the design draft with the size

**Comment by lizhuoyuan** [comment]
The main problem now is that you don't know what to fill in designSize.
Generally speaking, there will be a UI designer drawing a design draft, and the developer will develop the program according to the design draft. Here is the fill-in, the screen size in the design draft (the unit is recommended dp, but the unit of size should be used with other places Unite).
If you do not have a design draft and you are directly developing, the first mobile phone can be used as the size of your design draft, and fill in its size to ensure that it displays normally on the device.

```dart
 double width = MediaQuery.of(context).size.width;
  double height = MediaQuery.of(context).size.height;
  double defaultScreenUtilWidth = 1080;
  double defaultScreenUtilHeight = 1920;
  double iPadPro12InchWidth = 2048;
  double iPadPro12InchHeight = 2732;
```

In addition, in the following, the first two units are DP, and the two units below are PX, which can cause the UI to abnormally.

**Comment by yusriltakeuchi** [comment]
So i must convert the variable defaultScreenUtilWidth into DP value because the value 1080 are PX?

**Comment by yusriltakeuchi** [comment]
Becauase i don't have design draft size

**Comment by lizhuoyuan** [comment]
> So i must convert the variable defaultScreenUtilWidth into DP value because the value 1080 are PX?

It is recommended to use dp uniformly, but in fact, as long as your unit is uniform, either dp or px can be used.

And if you don’t have a design draft, please enter the size of your phone(After all, you show it perfectly on your phone）

**Comment by yusriltakeuchi** [comment]
> > So i must convert the variable defaultScreenUtilWidth into DP value because the value 1080 are PX?
> 
> It is recommended to use dp uniformly, but in fact, as long as your unit is uniform, either dp or px can be used.
> 
> And if you don’t have a design draft, please enter the size of your phone(After all, you show it perfectly on your phone）.
> 
> Or you can upload your code with github, I will help you fix it.
> You don’t seem to have much code at the moment

When i use my phone as size design draft, how if i want to test on iPad? is that just put the same value like my phone? or must the  value of the iPad?

**Comment by lizhuoyuan** [comment]
Yes, the code does not need to be changed at all, as long as the display is normal on the phone, you can run it directly on the ipad.

**Comment by yusriltakeuchi** [comment]
@lizhuoyuan i think this is not best practice, because when i migrate my old project to null safety, the design is really bad.
I can't use the same font size with the value before i migrating with this library.

for example
when i use font size 30 in old project, when i use this library with null safety, the design will be broken.

Why you remove allow font scalling in the settings?

**Comment by lizhuoyuan** [comment]
Because the official code provides font scaling related code, so I removed it here.
There is a complete guide in read.me to let you know how to set font scaling related settings
