### ISSUE TITLE
how i give resposive padding by using this package ?

### ISSUE THREAD

**Issue by adnankhan74444** [OpenFlutter/flutter_screenutil#247]

**Comment by adnankhan74444** [comment]
for example:
Padding(
            padding: const EdgeInsetsDirectional.only(top: ? ,start:?,end:?),
          )

**Comment by lizhuoyuan** [comment]
Remove const

for example:
Padding(
padding: EdgeInsetsDirectional.only(top: 10.w ,start:5.w,end:6.w),
)
