### ISSUE TITLE
[5.0.0] README: allowFontScaling parameter doesn't exist anymore

### ISSUE THREAD

**Issue by llucax** [OpenFlutter/flutter_screenutil#249]
In the 5.0.0 release (the current latest stable release and the one shown in https://pub.dev/packages/flutter_screenutil at the time of writing) have an error in the first example:

![image](https://user-images.githubusercontent.com/1031485/116908340-0f098300-ac43-11eb-9a55-e1ee878ebf4b.png)

`allowFontScaling: false` gives an error because the parameter doesn't exist anymore. It seems to be fixed in the master README, but it is quite confusing for people visiting https://pub.dev/packages/flutter_screenutil, so it might be worth a point release to fix it.

**Comment by lizhuoyuan** [comment]
thanks， I will fix it
