### ISSUE TITLE
用ScreenUtil去设置ListView列表中的文字大小，滑动列表卡死的情况

### ISSUE THREAD

**Issue by zhyhub** [OpenFlutter/flutter_screenutil#25]
外面嵌套HomeSliverAppBar，里面一个listview列表数据。用ScreenUtil去设置ListView列表中的文字大小，滑动列表App会卡死。

**Comment by lizhuoyuan** [comment]
上代码?

**Comment by zhyhub** [comment]
![1553168201701](https://user-images.githubusercontent.com/19427945/54750037-638f4700-4c11-11e9-8b12-a705edc4ecb9.jpg)
![1553168269119](https://user-images.githubusercontent.com/19427945/54750096-89b4e700-4c11-11e9-92a0-fba0f6ce3103.jpg)

**Comment by zhyhub** [comment]
@lizhuoyuan 我把ScreenUtil.getInstance().setSp() 直接改成数值 ，滑动就没有问题

**Comment by lizhuoyuan** [comment]
emmmm
你把sp试着换成setWidth呢?
