### ISSUE TITLE
Font Size in not working as per screen resolution. 

### ISSUE THREAD

**Issue by panchalAlpit** [OpenFlutter/flutter_screenutil#251]
I have checked the font size on multiple devices and not getting satisfactory [results](https://prnt.sc/12igcli). I have checked the iPhone 7, iPhone 11, and Samsung M40. iPhone 11 and Samsung m40 results are good but in iPhone 7 font size is not working as per screen resolution.
![Screenshot 2021-05-05 at 12 11 13 PM](https://user-images.githubusercontent.com/48007084/117105152-1348b400-ad9b-11eb-8101-707a46cd84f6.png)

Thanks in Advance

**Comment by lizhuoyuan** [comment]
Is font scaling set in the system settings?

**Comment by panchalAlpit** [comment]
> Is font scaling set in the system settings?

No

**Comment by panchalAlpit** [comment]
> Can you show the code and version

Yeah sure,

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return ScreenUtilInit(
      allowFontScaling: true,
      builder: () =>
          GetMaterialApp(
          //  localizationsDelegates: context.localizationDelegates,
          //  supportedLocales: context.supportedLocales,
            routes: {
              LLRoutes.LLPageList: (BuildContext context) => LLPageListScreen(),
              LLRoutes.PageSocialVerify: (BuildContext context) => LLPageSocialVerify(),
            },
            locale: Locale(LLPrefrence.llshareprefs.getString(LLPrefrence.language_code)!=null?LLPrefrence.llshareprefs.getString(LLPrefrence.language_code):'en', LLPrefrence.llshareprefs.getString(LLPrefrence.country_code)!=null?LLPrefrence.llshareprefs.getString(LLPrefrence.country_code):'US'),
            //locale: Locale('en', 'US'),
            //locale: Get.locale,
            translations: LLLanguages(),
            navigatorKey:Get.key,
            debugShowCheckedModeBanner:false,
            theme:LLTheme.light,
            darkTheme: LLTheme.dark,
            themeMode: ThemeService().theme,
            home:LLSplashScreen(),
          ),
    );
  }
}



  static double size14=ScreenUtil().setSp(14,allowFontScalingSelf: true);
   flutter_screenutil: ^4.0.3+2

**Comment by lizhuoyuan** [comment]
please use new version .
