### ISSUE TITLE
【safari】 浏览器窗口变化后，字体没有恢复正常大小

### ISSUE THREAD

**Issue by lyf571321556** [OpenFlutter/flutter_screenutil#252]
flutter_screenutil: ^4.0.4+1

step reproduce:
在ios safari浏览器中，输入地址访问项目首页后，点击浏览器地址栏，接着点击取消，会发现所有问题都变小了，只有刷新页面才会恢复正常。

类似的场景还有android手机的虚拟导航栏上的菜单键引发的app窗口化后字体缩小问题。

result:
![screen_util](https://user-images.githubusercontent.com/2295872/117786134-ca4f9e80-b277-11eb-9f5b-7e733e03fd88.gif)

**Comment by LvJson** [comment]
我在华为nove 7se上旋转屏幕时，也是和你这个情况差不多，横屏后部分正常部分不正常，再次竖屏后有些控件依然很大，只有执行setState才能恢复正常

**Comment by lizhuoyuan** [comment]
#241

**Comment by lizhuoyuan** [comment]
可以先尝试使用第二种初始化方式看看会不会有问题
