### ISSUE TITLE
使用了该插件会根据屏幕宽度改变实际大小，但我想加一个上限值要怎么处理

### ISSUE THREAD

**Issue by Sweet-KK** [OpenFlutter/flutter_screenutil#254]
类似于前端css这种，为了不让适配根据屏幕宽度无限增大，给一个最大宽度，根字体大小也是，屏幕超过540适配就不再增加大小了
![image](https://user-images.githubusercontent.com/29600932/119327735-e579cf80-bcb5-11eb-9446-1408634394d9.png)

**Comment by Sweet-KK** [comment]
还会有最小值的需求，例如，字体适配在某小屏下过小，需要设置该适配的最小值

**Comment by lizhuoyuan** [comment]
先给你一个临时解决办法：
新建一个方法：比较适配后的字体/宽度，和你想要的最大值/最小值，然后根据你的需求进行返回。
比如：
```
getSmall(screenText){
   
return  [screenText, 30].reduce(max);
}
```
当然你也看看有没有更优雅的比较方法

**Comment by hysea** [comment]
重新计算scaleText： 
double get scaleText => max(min(scaleWidth, scaleHeight), 1);
