### ISSUE TITLE
在某些场景下会出现null异常，请问该怎么处理？

### ISSUE THREAD

**Issue by LuodiJackShen** [OpenFlutter/flutter_screenutil#258]
根据日志分析，是从后台切换到前台时报的错，请问有遇到过吗？

### 代码
```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ScreenUtilInit(
      designSize: Size(375.0, 812.0),
      allowFontScaling: false,
      builder: () {
        return HomePage();
      }
    );
  }
}
```
### 报错日志
```
【NoSuchMethodError: The method 'setSp' was called on null.
Receiver: null
Tried calling: setSp()】 
 #0      SizeExtension.sp (package:flutter_screenutil/size_extension.dart:14)
```
### 其他信息
设备	 vivo - vivo X20	
系统版本	8.1.0	
ROM版本	OPM1.171019.011 release-key	
屏幕	 2034*1080

设备运行时间	
前台：12020ms；
后台：5295ms；
休眠：0ms；

**Comment by lizhuoyuan** [comment]
运行一下example看有报错吗？
这我还针没遇到过

**Comment by LuodiJackShen** [comment]
正常运行不会报错，这是线上监控到的崩溃，分析日志貌似是内存不够被回收了

**Comment by LuodiJackShen** [comment]
请教下，这里嵌套`LayoutBuilder`和`OrientationBuilder`是出于什么目的呢？


<img width="1062" alt="截屏2021-06-08 15 26 05" src="https://user-images.githubusercontent.com/25525335/121141858-00c80b80-c86e-11eb-99c8-966206533799.png">

**Comment by lizhuoyuan** [comment]
layoutbuilder我最初的目的是用于屏幕的尺寸，因为flutter默认获取屏幕尺寸的时机较晚，不够及时。
OrientationBuilder 应该是之前有人提出需求希望有个屏幕方向的东西

**Comment by LuodiJackShen** [comment]
我再分析下吧，目前不太确定是否一定和flutter_screenutil有关系，先关了吧。
