### ISSUE TITLE
How to give design draft size dynamically for different screens , like for android mobile , android tablet and same for IOS

### ISSUE THREAD

**Issue by majidflutter** [OpenFlutter/flutter_screenutil#259]

**Comment by majidflutter** [comment]
```
       ScreenUtilInit(
              designSize: Size(Get.size.width, Get.size.height), //-padding.top-padding.bottom-kToolbarHeight
              allowFontScaling: true,
)
```

This is how I am adding screen draft sizes but fonts are not working as per expectation

**Comment by lizhuoyuan** [comment]
Fill in the device size in the draft here, not the actual size

**Comment by majidflutter** [comment]
> Fill in the device size in the draft here, not the actual size

How can we do that could you please help me out ?

**Comment by lizhuoyuan** [comment]
Find your UI design draft
View device size
such as:
![image](https://user-images.githubusercontent.com/15923901/123915882-88a7be00-d9b3-11eb-85f5-c491834fe532.png)
375*667 ， so
designSize: Size(375, 667)

**Comment by majidflutter** [comment]
> Find your UI design draft
> View device size
> such as:
> ![image](https://user-images.githubusercontent.com/15923901/123915882-88a7be00-d9b3-11eb-85f5-c491834fe532.png)
> 375*667 ， so
> designSize: Size(375, 667)

**Comment by majidflutter** [comment]
> > Find your UI design draft
> > View device size
> > such as:
> > ![image](https://user-images.githubusercontent.com/15923901/123915882-88a7be00-d9b3-11eb-85f5-c491834fe532.png)
> > 375*667 ， so
> > designSize: Size(375, 667)
Please do not mind I am new to this stuff I still have problem with it please let me know 
what is design draft actually? how to open and find device size? I am new to this stuff please guide step by step, What is actually design draft and how to open it and how to find screen size and then finally give it to designSize()

**Comment by majidflutter** [comment]
> > > Find your UI design draft
> > > View device size
> > > such as:
> > > ![image](https://user-images.githubusercontent.com/15923901/123915882-88a7be00-d9b3-11eb-85f5-c491834fe532.png)
> > > 375*667 ， so
> > > designSize: Size(375, 667)
> > > Please do not mind I am new to this stuff I still have problem with it please let me know
> > > what is design draft actually? how to open and find device size? I am new to this stuff please guide step by step, What is actually design draft and how to open it and how to find screen size and then finally give it to designSize()

How did you find this size mentioned above, what is that which is helping you to find screen  size dynamically when app is running on different screen sizes

**Comment by lizhuoyuan** [comment]
It is a program design draft made by a UI designer.
If you don't have one, please use your usual device size in dp

**Comment by abdimussa87** [comment]
Where can we get our device size in dp, since most of them are in px?

**Comment by lizhuoyuan** [comment]
this is UI design draft
