### ISSUE TITLE
使用ScreenUtilInit运行报错：Ensure to initialize ScreenUtil before accessing it.

### ISSUE THREAD

**Issue by allhuo** [OpenFlutter/flutter_screenutil#260]
版本：4.0.4+1以及其他4.0.X其他版本
错误：======== Exception caught by widgets library =======================================================
The following assertion was thrown building LayoutBuilder:

Ensure to initialize ScreenUtil before accessing it.
Please execute the init method : ScreenUtil.init()
'package:flutter_screenutil/screen_util.dart':
Failed assertion: line 34 pos 7: '_instance != null'

The relevant error-causing widget was: 
  OrientationBuilder file:///D:/tool/flutter-env/flutter_1.22.6/.pub-cache/hosted/pub.flutter-io.cn/flutter_screenutil-4.0.4+1/lib/screenutil_init.dart:25:14
When the exception was thrown, this was the stack: 
#2      new ScreenUtil (package:flutter_screenutil/screen_util.dart:34:7)
#3      Base.dp (package:qniqni/common/base.dart:14:36)
#4      _StartPageState.build.<anonymous closure> (package:qniqni/page/init/start.dart:81:26)
#5      ScreenUtilInit.build.<anonymous closure>.<anonymous closure> (package:flutter_screenutil/screenutil_init.dart:35:25)
#6      OrientationBuilder._buildWithConstraints (package:flutter/src/widgets/orientation_builder.dart:52:19)
代码：
  @override
  Widget build(BuildContext context) {
    return ScreenUtilInit(
      designSize: Base.size,
      builder: () {
        return Scaffold(
          body: SizedBox(
            width: MediaQuery.of(context).size.width, //获取屏幕宽度
            child: Stack(
              alignment: Alignment.center,
              children: <Widget>[
                SizedBox(
                  width: dp(375),
                  child: Image.asset("assets/start.jpg"),
                ),
                Positioned(
                  right: dp(40),
                  top: dp(40),
                  child: CountDown(),
                ),
              ],
            ),
          ),
        );
      },
    );
  }

**Comment by lizhuoyuan** [comment]
需要 WidgetsApp, CupertinoApp, 或者 MaterialApp

**Comment by allhuo** [comment]
也就是说在main.dart文件中MyApp类的build方法中使用ScreenUtilInit，该设置就会对全局作用，不需要再到其他页面使用ScreenUtilInit对吗？？？？

**Comment by lizhuoyuan** [comment]
是的

> 也就是说在main.dart文件中MyApp类的build方法中使用ScreenUtilInit，该设置就会对MaterialApp声明的路由都起作用，不需要再到其他页面使用ScreenUtilInit对吗？？？？

**Comment by allhuo** [comment]
谢谢解答
