### ISSUE TITLE
用了GetX状态管理框架后

### ISSUE THREAD

**Issue by git-maven** [OpenFlutter/flutter_screenutil#261]
用了第一种初始化方式包裹GetMaterialApp会导致Getx的dialog丢失主题

**Comment by git-maven** [comment]
发现不止Getx会丢失,其他dialog控件都会丢失主题

**Comment by lizhuoyuan** [comment]
如果不是必要的话，可以使用第二种。
其实第二种不是需要每个页面都调用的，只要在第一个路由页面或者home（也就是第一个进入的flutter页面）中调用一次就好

**Comment by xiaobingcaicai** [comment]
> 用了第一种初始化方式包裹GetMaterialApp会导致Getx的dialog丢失主题

包裹GetMaterialApp后有没有出现窗口resize后 字体不会缩放的问题？

**Comment by xiaobingcaicai** [comment]
> 如果不是必要的话，可以使用第二种。 其实第二种不是需要每个页面都调用的，只要在第一个路由页面或者home（也就是第一个进入的flutter页面）中调用一次就好

两种方式都尝试过，在使用包裹GetMaterialApp后，桌面应用进行窗口大小调整的时候，字体不会随着缩放，只有在hotreload后才会适应窗口尺寸缩放，这个怎么解决？

**Comment by KochabStar** [comment]
> > 如果不是必要的话，可以使用第二种。其实第二种不是需要每个页面都调用的，只要在第一个路由页面或者home（也就是第一个进入的flutter页面）中调用一次就好
> 
> 两种方式都尝试过，在使用包裹GetMaterialApp后，桌面应用进行窗口大小调整的时候，字体不会随着缩放，只有在hotreload后才会适应窗口尺寸缩放，这个怎么解决？
请问解决了吗
