### ISSUE TITLE
What to use for objects that have only one size?

### ISSUE THREAD

**Issue by eli1stark** [OpenFlutter/flutter_screenutil#262]
When I have something simple like Container I use `x.w` and `x.h`, for Font I use `x.sp`, for Radius `x.r`.
But when I have something like (with single size field):
```
const Icon(
  Icons.ac_unit,
  size: 150.0,
),
```
What to use in this case? `x.r`?

**Comment by lizhuoyuan** [comment]
It is recommended to use ‘r’

**Comment by eli1stark** [comment]
Thank you
