### ISSUE TITLE
ScreenUtil崩溃

### ISSUE THREAD

**Issue by fangkyi03** [OpenFlutter/flutter_screenutil#263]
#0      ScreenUtil._instance (package:flutter_screenutil/screen_util.dart)
package:flutter_screenutil/screen_util.dart:1
#1      new ScreenUtil
package:flutter_screenutil/screen_util.dart:28
#2      _DEMOState.renderTest
package:taobao/main.dart:150
#3      _DEMOState.build
package:taobao/main.dart:156

[✓] Flutter (Channel master, 2.4.0-1.0.pre.79, on macOS 12.0 21A5268h darwin-arm, locale zh-Hans-CN)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.2)
[✓] VS Code (version 1.58.0-insider)
[✓] Connected device (2 available)

```
class Main extends HookWidget {
  const Main({Key? key, required this.child}) : super(key: key);
  final Widget child;
  Widget renderView() {
    return MaterialApp(
        home: Scaffold(
            body: SafeArea(
      child: child,
    )));
  }

  @override
  Widget build(BuildContext context) {
    return ScreenUtilInit(
        designSize: const Size(360, 690), builder: () => renderView());
  }
}
```
我因为不想每个页面都去写一个ScreenUtilInit 所以将其封装成了组件 但是这样封装玩在使用的时候我发现 如果直接按照下面的方式使用的话 就会出现最开始的那个崩溃 但是如果直接把Main里面的代码 原封不动的搬过来的话 执行是正常的 我现在的问题就在于 如果我想依旧这种封装组件的方式来实现的话 如何可以不崩溃能正常使用
```
class _DEMOState extends State<DEMO> {
  Widget renderTest() {
    return Container(
        color: Colors.blue,
        width: ScreenUtil().setWidth(100),
        height: ScreenUtil().setWidth(199));
  }

  @override
  Widget build(BuildContext context) {
    return Main(child: renderTest());
  }
}

```

**Comment by lizhuoyuan** [comment]
可以ScreenUtilInit包裹MaterialApp
或者在home里调用init方法 ， 这个方法不需要每个页面都调用的
