### ISSUE TITLE
横屏竖屏切换

### ISSUE THREAD

**Issue by shaonianahua** [OpenFlutter/flutter_screenutil#265]
我在做一个app在pad上运行的
然后app本身是竖屏使用 个别页面需要切换到横屏
SystemChrome.setEnabledSystemUIOverlays([]);
    SystemChrome.setPreferredOrientations([
      DeviceOrientation.landscapeLeft,
      DeviceOrientation.landscapeRight,
    ]); 
我会在init的时候用代码将它变成横屏 然后我之前在入口文件加了ScreenUtilInit  designSize: Size(1200, 1920),
之后我在变成横屏的页面也加了ScreenUtilInit 不过 designSize设置为了 Size(1920, 1200)
因为不设置的话貌似有兼容问题 但是设置了之后貌似跳转到页面时会有卡顿
插件使用的是最新版的 请问这种场景一般需要怎么做

**Comment by jxtx123456** [comment]
横竖屏切换的时候底层的宽高要互换，自己修改一下底层逻辑吧

**Comment by lizhuoyuan** [comment]
目前example中的效果是这样的，没有其他额外操作。因为用的模拟器 ，所以反应有点慢， 不太确定你是想要什么样的效果？
![2021-07-14 11 06 50](https://user-images.githubusercontent.com/15923901/125554726-8d2c1b55-f058-4e8a-84ae-519cb671a7ae.gif)
你也可以运行一下example来看一下

**Comment by jxtx123456** [comment]
> 目前example中的效果是这样的，没有其他额外操作。因为用的模拟器 ，所以反应有点慢， 不太确定你是想要什么样的效果？
> ![2021-07-14 11 06 50](https://user-images.githubusercontent.com/15923901/125554726-8d2c1b55-f058-4e8a-84ae-519cb671a7ae.gif)
> 你也可以运行一下example来看一下

你仔细看一下，横竖屏切换的时候宽高不一样，字体大小也不一样

**Comment by lizhuoyuan** [comment]
> > 目前example中的效果是这样的，没有其他额外操作。因为用的模拟器 ，所以反应有点慢， 不太确定你是想要什么样的效果？
> > ![2021-07-14 11 06 50](https://user-images.githubusercontent.com/15923901/125554726-8d2c1b55-f058-4e8a-84ae-519cb671a7ae.gif)
> > 你也可以运行一下example来看一下
> 
> 你仔细看一下，横竖屏切换的时候宽高不一样，字体大小也不一样

是的，这是目前代码正常的效果。
所以你的期望是横竖屏之后，组件尺寸不变对吧？

**Comment by shaonianahua** [comment]
好的 因为我这边的需求是不能随意横竖屏切换的 然后特定某个页面是横屏 其他都是竖屏的情况 我这边的问题已经找到其他的解决方案 感谢回复

**Comment by lizhuoyuan** [comment]
> 好的 因为我这边的需求是不能随意横竖屏切换的 然后特定某个页面是横屏 其他都是竖屏的情况 我这边的问题已经找到其他的解决方案 感谢回复

如果不是改源码的话，可以先分享一下，方便同样有问题的同学。
我这边可以考虑一下是否通过参数配置来控制一下这个效果。

**Comment by jxtx123456** [comment]
> > > 目前example中的效果是这样的，没有其他额外操作。因为用的模拟器 ，所以反应有点慢， 不太确定你是想要什么样的效果？
> > > ![2021-07-14 11 06 50](https://user-images.githubusercontent.com/15923901/125554726-8d2c1b55-f058-4e8a-84ae-519cb671a7ae.gif)
> > > 你也可以运行一下example来看一下
> > 
> > 
> > 你仔细看一下，横竖屏切换的时候宽高不一样，字体大小也不一样
> 
> 是的，这是目前代码正常的效果。
> 所以你的期望是横竖屏之后，组件尺寸不变对吧？

嗯
