### ISSUE TITLE
The Ratio of width and height is incorrect

### ISSUE THREAD

**Issue by omidraha** [OpenFlutter/flutter_screenutil#266]
The size of design is 375w and 768h.

And I have a rectangle with 90w and 102h.

Now In a Phone size with 360w and 592.

This rectangle will be: 86w and 78h.

Because of:  
```
(360*90/375) = 86
(592*102/768) = 78

```
So the [90w, h102] size changed to [86w, 78h]

The problem here is,  we have a rectangle with bigger height in the Design, 
But we have a rectangle with bigger width  in the Phone.

**Comment by lizhuoyuan** [comment]
No matter how the equipment is changed, you should use [90.w, 102.h].
Will get the result you expected
