### ISSUE TITLE
Operand of null-aware operation '?.'

### ISSUE THREAD

**Issue by hainiu9999** [OpenFlutter/flutter_screenutil#271]
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_screenutil-5.0.0+2/lib/screen_util.dart:42:33: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/binding.dart').
    var window = WidgetsBinding.instance?.window ?? ui.window;

**Comment by lizhuoyuan** [comment]
what is your flutter version?
