### ISSUE TITLE
How to set EdgeInsets left, top, right, bottom with screenutil

### ISSUE THREAD

**Issue by ardeveloper492** [OpenFlutter/flutter_screenutil#272]
Which is correct?

EdgeInsets.fromLTRB(
                      10.w, //left
                      **_20.w, //top_**
                      30.w, //right
                      **_40.w, //bottom_**
                    ),

OR

EdgeInsets.fromLTRB(
                      10.w, //left
                      **_20.h, //top_**
                      30.w, //right
                      **_40.h, //bottom_**
                    ),

Thanks.

**Comment by lizhuoyuan** [comment]
It doesn't really matter whether it is correct or not.
It mainly depends on your needs, but if you don’t know which one you want, I suggest the first one

**Comment by ardeveloper492** [comment]
Thank you
