### ISSUE TITLE
用了初始化之后会黑屏

### ISSUE THREAD

**Issue by siyehua** [OpenFlutter/flutter_screenutil#274]
```
  return ScreenUtilInit(
      designSize: Size(375, 812),
      builder: () => InitApp(),
    );
```

用这段代码之后，屏幕会先黑一下，接着才正常

**Comment by siyehua** [comment]
版本 5.0.0+2

**Comment by lizhuoyuan** [comment]
看一下InitApp中的代码，我觉得这个应该是其他问题

**Comment by siyehua** [comment]
> 看一下InitApp中的代码，我觉得这个应该是其他问题

昨天仔细找了一个，问题是这样的：
ScreenUtilInit 它一开始如果拿到的宽度 == 0，就先返回一个默认的 Container，

```
@override
Widget build(BuildContext context) {
  return LayoutBuilder(builder: (_, BoxConstraints constraints) {
    return OrientationBuilder(
      builder: (_, Orientation orientation) {
        if (constraints.maxWidth != 0) {
          ScreenUtil.init(
            constraints,
            orientation: orientation,
            designSize: designSize,
          );
          return builder();
        }
        return Container();
      },
    );
  });
}
```
我在 runApp 之后就直接初始化 ScreenUtilInit的，发现第一次总是拿不到宽高，所以但是返回默认的，
接着界面刷新之后， constraints 拿到的屏幕宽高才会初始化 builder(),
这样  Container 和 builder() 切换就会有一个黑屏，在第一次打开 flutter 页面的时候特别明显。
顺便说一下，我的工程是混合开发，我尝试把

ScreenUtil.init(
            constraints,
            orientation: orientation,
            designSize: designSize,
          );

这段代码直接提取出来初始化，是不会有黑屏情况的

**Comment by zhixinpeng** [comment]
同版本 发现同样问题

**Comment by lizhuoyuan** [comment]
请先使用第二种初始化方式
