### ISSUE TITLE
会有一丝丝的间距

### ISSUE THREAD

**Issue by houziruinb87** [OpenFlutter/flutter_screenutil#277]
目前使用这个库进行计算后的UI，在视图上，不同的widget之间有时会有那么肉眼可见的，一丝丝的间距。不知道是因为什么，是不是计算出的精度太高了导致的bug呢

**Comment by lizhuoyuan** [comment]
不会,但是flutter在某种情况下会出现两个container之间会有一个缝隙的问题,
我记得是通过decoration来设置可以取消.

但如果是每个地方都有一点间距,可能是布局的其他问题, 可以仔细看一下
