### ISSUE TITLE
How to calculate only safeArea

### ISSUE THREAD

**Issue by tananga** [OpenFlutter/flutter_screenutil#283]
Hello. I understand that ScreenUtil calculate device width and height and resize the widgets but how can I calculate only SafeArea? I dont want to calculate useless part of my device.

**Comment by tananga** [comment]
Hey, any updates? I really need to know how to scale widget base not on device size but on SafeArea size.

**Comment by lizhuoyuan** [comment]
Flutter has its own api：
    MediaQuery.of(context).padding.top/bottom

**Comment by tananga** [comment]
@lizhuoyuan Thank you It sounds easy.

**Comment by tananga** [comment]
@lizhuoyuan  My mockups are 207 pt width and 447 pt height but Mockups dont include top bar where battery is and they also dont include bottom bar with back and menu button.  My device which is android phone have both top bar with battery info, time and wifi status and bottom bar with 3 buttons inside. Could you advise me something?

**Comment by lizhuoyuan** [comment]
First get the size of your so-called safeare area.
Then fill it in when initializing

**Comment by tananga** [comment]
@lizhuoyuan But when Im using ScreenUtilInit() widget the only property which I can put inside is "designSize"  ({Size designSize = ScreenUtil.defaultSize}) and my desig size is constant "207x447". Where can I put my safearea size?

**Comment by eli1stark** [comment]
@tananga you can just wrap `ScreenUtilInit ` with `SafeArea` and your design size will be within a safe area
