### ISSUE TITLE
使用插件软件在横竖屏切换的时候会导致ui错乱

### ISSUE THREAD

**Issue by a250059653** [OpenFlutter/flutter_screenutil#286]
使用插件软件在横竖屏切换的时候会导致ui错乱

**Comment by a250059653** [comment]
> 会根据横屏重新计算尺寸

但是切换回竖屏后仍然还是根据横屏计算，并没有重新计算

**Comment by a250059653** [comment]
> ok，我后续查看一下 为什么回来的时候尺寸没有改变

修复了到时候麻烦通知一下，感谢

**Comment by a250059653** [comment]
> 能否提供一个简单的demo？ 我这里没有复现，每次切换屏幕方向都会走一次build

demo地址：https://muoutv.lanzoui.com/ie4Ybvj2lxg

**Comment by lizhuoyuan** [comment]
https://user-images.githubusercontent.com/15923901/138021995-0aa877c3-05e6-435b-bf22-d954403a05d1.mp4

这是我转动手机切换横竖屏的效果。

如果是点击视频里的放大，效果稍微差点 会看到有个变化的过程，应该需要手动处理一下

**Comment by a250059653** [comment]
>  1634699408174269.mp4 
> 这是我转动手机切换横竖屏的效果。
> 
> 如果是点击视频里的放大，效果稍微差点 会看到有个变化的过程，应该需要手动处理一下

#

- [ ] 

> [](url)

>  1634699408174269.mp4 
> 这是我转动手机切换横竖屏的效果。
> 
> 如果是点击视频里的放大，效果稍微差点 会看到有个变化的过程，应该需要手动处理一下

这是我这边demo运行的视频，视频地址:http://demo.muoutv.com/demo.mp4

**Comment by lizhuoyuan** [comment]
估计是手动切换横竖屏的时候 ， 没有及时捕捉到屏幕变化，那就只能手动触发一下了

**Comment by a250059653** [comment]
> 估计是手动切换横竖屏的时候 ， 没有及时捕捉到屏幕变化，那就只能手动触发一下了

这边能修复么？

**Comment by Gloud-Zhao** [comment]
> 使用插件软件在横竖屏切换的时候会导致ui错乱

参考ScreenUtilInit中的代码

return LayoutBuilder(builder: (_, BoxConstraints constraints) {
      return OrientationBuilder(
        builder: (_, Orientation orientation) {
          if (constraints.maxWidth != 0) {
            ScreenUtil.init(
              constraints,
              orientation: orientation,
              designSize: (orientation==Orientation.portrait)?竖屏尺寸:横屏尺寸,
            );
            return 返回你实际widget
          }
          return Container();
        },
      );
    })

**Comment by werfei** [comment]
如何强制尺寸使用竖屏尺寸，就是应用打开初始化后，不管横竖屏不再切换了

**Comment by lizhuoyuan** [comment]
@werfei 

  SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown
  ]);

**Comment by werfei** [comment]
> @werfei
> 
> SystemChrome.setPreferredOrientations([ DeviceOrientation.portraitUp, DeviceOrientation.portraitDown ]);

我意思是应用初始化后就初始化完咱的插件了，不管横竖屏不再重新计算了

**Comment by lizhuoyuan** [comment]
> > @werfei
> > SystemChrome.setPreferredOrientations([ DeviceOrientation.portraitUp, DeviceOrientation.portraitDown ]);
> 
> 我意思是应用初始化后就初始化完咱的插件了，不管横竖屏不再重新计算了

加个条件判断，如果当前不是竖屏，就不执行init的代码

**Comment by werfei** [comment]
> > > @werfei
> > > SystemChrome.setPreferredOrientations([ DeviceOrientation.portraitUp, DeviceOrientation.portraitDown ]);
> > 
> > 
> > 我意思是应用初始化后就初始化完咱的插件了，不管横竖屏不再重新计算了
> 
> 加个条件判断，如果当前不是竖屏，就不执行init的代码

我是直接在main app里面用的ScreenUtilInit这个组件，这个能不能加个参数呢，可以控制是否适应横竖屏切换

**Comment by lizhuoyuan** [comment]
那需要在插件的代码里判断了

**Comment by a250059653** [comment]
> 那需要在插件的代码里判断了

看样子不止我一个人遇到这个问题，我建议大佬还是更新一下插件呗

**Comment by zhihongzhang123** [comment]
遇到同样的问题。之前横竖屏切换，字体可以自适应，现在切换横屏，字体大小，图片大小都错误

**Comment by libretyZW** [comment]
var orientation = MediaQuery.of(context).orientation;
    screenWidth = orientation == Orientation.landscape
        ? MediaQuery.of(context).size.width
        : MediaQuery.of(context).size.height;
    screenHeight = orientation == Orientation.landscape
        ? MediaQuery.of(context).size.height
        : MediaQuery.of(context).size.width;
    debugPrint(
        "orientation: $orientation, screenWidth: $screenWidth, screenHeight: $screenHeight");
    ScreenUtil.init(
        BoxConstraints(maxWidth: screenWidth, maxHeight: screenHeight),
        designSize: const Size(defaultWidth, defaultHeight),
        orientation: Orientation.landscape);

**Comment by Thor1016** [comment]
请问这个issue还会解决吗？也遇到了这个问题，横屏切回竖屏之后，没有rebuild

**Comment by a250059653** [comment]
> 请问这个issue还会解决吗？也遇到了这个问题，横屏切回竖屏之后，没有rebuild

不会了

**Comment by Thor1016** [comment]
> 
我找到了我得页面为什么不会 重新rebuild了，因为我用的是tabView 和tab bar，目前我的项目只有用这个在横竖屏切换的时候，才会有问题，所以我换了一种布局就好了

**Comment by viccP** [comment]
> > 请问这个issue还会解决吗？也遇到了这个问题，横屏切回竖屏之后，没有rebuild
> 
> 不会了

额，这个不是开源了么。谁修好了提一下RP呗。别都指望着作者改啊

**Comment by lizhuoyuan** [comment]
有些问题我这里没法复现， 所以不是很好解决，
然后刚发布了新版本，可以试一下。
有些问题也未必是插件的问题，就希望大家多看看 。
