### ISSUE TITLE
app运行时仍能受系统字体影响

### ISSUE THREAD

**Issue by li1110** [OpenFlutter/flutter_screenutil#29]
设置了字体不随系统改变，但是app在运行时进入后台后，调整系统字体大小，app的字体还是会随着系统字体大小改变，把app进程杀掉重新进入之后字体又恢复了。这个有什么方法解决吗？

**Comment by lizhuoyuan** [comment]
目前是在APP启动时 , 获取系统字体的缩放比例
后续可能不会及时刷新
以后可能考虑做到实时

**Comment by li1110** [comment]
期待中。。。

**Comment by luoxuuguang** [comment]
> 目前是在APP启动时 , 获取系统字体的缩放比例
> 后续可能不会及时刷新
> 以后可能考虑做到实时

兄弟，实时的解决了吗-。-
