### ISSUE TITLE
关于.h在不同机型适配出现的问题

### ISSUE THREAD

**Issue by 515445681** [OpenFlutter/flutter_screenutil#290]
效果图是：iphone x
宽度是375
高度是812

测试机是iphone 8p 
宽度是iphonex的1.104倍，那我代码里写10像素的时候，就是10*1.104 = 11
结果高度是iphonex的0.9倍，那代码里写10像素的时候，就变成了10*0.9 = 9

如果是一个在效果图里是宽110，高62的，代码使用的是 110.w和62.h，在iphone8P里，就变成了宽122，高56

表现为：

![image](https://user-images.githubusercontent.com/11323678/140884431-dea969d4-04f8-4404-b9a9-b2d27deb1c72.png)

发现iphone8p和iphonex已经不是等比例的缩放了

难道代码里要全部都用 110.w和62.w吗，全基于宽度的缩放，那.h的使用场景是什么呢。

**Comment by lizhuoyuan** [comment]
一般来讲， 全部使用.w是常规做法。
.h 适用于想要在高度上跟设计稿保持一致比例的情况。

**Comment by moujunqiang** [comment]
> 一般来讲， 全部使用.w是常规做法。
> .h 适用于想要在高度上跟设计稿保持一致比例的情况。

您好，请问这个是不是可以理解为 如果想和设计稿一样一屏幕显示所有内容高度就用.h进行适配，如果屏幕可以滑动 就可以用.w来进行适配

**Comment by lizhuoyuan** [comment]
@moujunqiang 是的  一般仅用做此
