### ISSUE TITLE
OPPO 折叠屏适配

### ISSUE THREAD

**Issue by RicoLiu** [OpenFlutter/flutter_screenutil#292]
flutter_screenutil: 3.2.0
目前在 OPPO 折叠屏手机上，UI显示会有被截断的情况。

**Comment by lizhuoyuan** [comment]
具体说说

**Comment by RicoLiu** [comment]
UI适配的地方都是使用 .w （包括高度），具体显示问题可以看下截图。

![image](https://user-images.githubusercontent.com/12722992/142375063-f54ac7b9-db4d-4dbc-a6ff-b13dd10b6329.png)

**Comment by lizhuoyuan** [comment]
那个是appbar吗？ appbar是有默认高度的 
可能会导致子组件显示不全

**Comment by RicoLiu** [comment]
> 那个是appbar吗？ appbar是有默认高度的 可能会导致子组件显示不全

对的，是 appbar。
那我是需要修改下 appbar 的默认高度来进行适配吗？

**Comment by lizhuoyuan** [comment]
> > 那个是appbar吗？ appbar是有默认高度的 可能会导致子组件显示不全
> 
> 对的，是 appbar。 那我是需要修改下 appbar 的默认高度来进行适配吗？

或者自己写一个组件放在那里，不要用appbar。
这个是父组件大小固定导致子组件显示不全的。

下面那个不确定，建议看一下布局。 应该也不是插件的问题
