### ISSUE TITLE
字号问题与设计稿上的有差别

### ISSUE THREAD

**Issue by zhangbodreams** [OpenFlutter/flutter_screenutil#293]
设计图是 375x812 设置字号是  16sp  运行手机上(360x640) 但是实际字体是13.793103448275861，发现跟设计图大小不一样，看源码发现double get scaleText => min(scaleWidth, scaleHeight); 这里实际的大小是乘以的高度比例 不是乘的宽，导致的字体不对，请问这样情况怎么解决？

**Comment by lizhuoyuan** [comment]
用16.w来替换16.sp
