### ISSUE TITLE
".h", ".w" and ".r" don't trigger a rebuilt when orientation changes

### ISSUE THREAD

**Issue by jcblancomartinez** [OpenFlutter/flutter_screenutil#294]
Hi,

I'm initializing ScreenUtilInit as follows:
```

class App extends StatelessWidget {
...

  @override
  Widget build(BuildContext context) {
    return ScreenUtilInit(
        designSize: const Size(375, 814),
        builder: () {
          final ThemeData materialTheme = ThemeData(
            fontFamily: 'Red Hat Display',
            ...
          );

          return GetMaterialApp(
              title: 'XXX',
              theme: materialTheme,
              themeMode: ThemeMode.light,
              supportedLocales: _supportedLocales,
              locale: Get.locale,
              localizationsDelegates: const [
                ...GlobalMaterialLocalizations.delegates,
                RefreshLocalizations.delegate
              ],
              getPages: Get.find(),
              debugShowCheckedModeBanner: false,
              onInit: () {
                FirebaseMessagingConfigurer firebaseMessagingConfigurer =
                    Get.find();
                firebaseMessagingConfigurer.configure();
                FirebaseBasedLinkAuthority firebaseBasedLinkAuthority =
                    Get.find();
                firebaseBasedLinkAuthority.init();
              });
        });
  }
}
```

In one of the pages, I have the following widget:

`SizedBox(height: 40.h,child: Text('Test'))`

When orientation changes, no rebuild gets triggered and therefore the height doesn't change between landscape and portrait.

However, when I declare:

`Container(color: Colors.cyanAccent, height: 40.h,child: Text('Test', style: Theme.of(context).textTheme.bodyText2,))`

 the rebuild gets triggered and the height changes.

I would expect ".h", ".w" and ".r" to always trigger a rebuild wherever they are used without having to invoke Theme.of(context).

Am I missing anything?

Thanks.

**Comment by lizhuoyuan** [comment]
The sample code I run will change the size when the screen is rotated. Maybe you restrict this change somewhere?
