### ISSUE TITLE
Help Wanted - How to use Screen_Utils Package for Responsive Padding and Marking

### ISSUE THREAD

**Issue by pavanjoshi914** [OpenFlutter/flutter_screenutil#299]
I came through the StackOverflow question and now I am willing to find a solution for this using the screen_utils package.

for padding and circular radius and mainAxisSpacing and crossAxisSpacing , positioned(top, left) what shall i use ```w or h or sp or sw or sh```

https://stackoverflow.com/questions/61698987/how-to-add-padding-or-margin-according-to-different-screen-sizes

Thanks in advance

**Comment by lizhuoyuan** [comment]
text: sp
width/height: w (You can use w when you don’t know whether to use w or h)
sw： screen width
sh:    screen height
