### ISSUE TITLE
屏幕旋转

### ISSUE THREAD

**Issue by AboutJarry** [OpenFlutter/flutter_screenutil#30]
屏幕状态变化，屏幕旋转后屏幕的宽高数值不会跟随反转，导致的UI异常

**Comment by zhangxq** [comment]
我看作者的源码，应该是需要重新调用init才行，没有测试过哈，理论上是这样

**Comment by lizhuoyuan** [comment]
理论上是的 , 因为屏幕尺寸变化而ScreenUtil的尺寸还是之前赋予的

**Comment by lizhuoyuan** [comment]
Duplicate of #34
