### ISSUE TITLE
关于splitScreenMode，默认为true，导致高度计算出错

### ISSUE THREAD

**Issue by AhhhhDong** [OpenFlutter/flutter_screenutil#301]
作者你好，最近无意中更新了您的库，代码中各种控件高度出现了错误。经过查看发现，代码中将高度直接设置为700。而我的设备高度只有480。。。希望您能将splitScreenMode默认设置为false，或者使用其他方式解决这个问题。。。（以免很多人打开项目一跑起来高度各种溢出。。）
`static void init(
    BoxConstraints constraints, {
    Orientation orientation = Orientation.portrait,
    Size designSize = defaultSize,
    bool splitScreenMode = true,
  }) {
    _instance = ScreenUtil._()
      ..uiSize = designSize
      .._orientation = orientation
      .._screenWidth = constraints.maxWidth
      .._screenHeight = splitScreenMode
          ? max(constraints.maxHeight, 700)
          : constraints.maxHeight;

    var window = WidgetsBinding.instance?.window ?? ui.window;
    _instance._pixelRatio = window.devicePixelRatio;
    _instance._statusBarHeight = window.padding.top;
    _instance._bottomBarHeight = window.padding.bottom;
    _instance._textScaleFactor = window.textScaleFactor;
  }`

**Comment by lizhuoyuan** [comment]
很好的提议 谢谢~
