### ISSUE TITLE
1.sh与MediaQuery.of(context).size.height的值不一样

### ISSUE THREAD

**Issue by xssxxssx** [OpenFlutter/flutter_screenutil#302]

**Comment by lizhuoyuan** [comment]
能看一下两个值都是什么吗

**Comment by B0ringM4n** [comment]
the same thing happened to me, it is difficult to detect. when you print the value of MediaQuery and 1.sh in the same widget this if it is refreshed but if you do it in different widgets this is not updated as media query.

I think it has to do with how the get of the num extension is handled. when the get is created it returns a value and if the widget is constant this value does not change unless there is another variable that changes within the widget such as the mediaquery

<img width="209" alt="Screen Shot 2022-01-19 at 14 48 39" src="https://user-images.githubusercontent.com/72772180/150203637-6e3f6dfc-621f-4200-90d9-2d025862dcc9.png">

**Comment by lizhuoyuan** [comment]
> 

what about 5.1.0？
