### ISSUE TITLE
[bug] Height properties not changing 2 - flutter web

### ISSUE THREAD

**Issue by Macacoazul01** [OpenFlutter/flutter_screenutil#303]
Using #300 as a reference, the `.h` and `.sh` properties still aren't changing on the latest version (5.0.1+2), that should have fixed this bug.
But everything is ok when i set `flutter_screenutil: 5.0.0` on pubspec.yaml.

flutter version 2.8.0 stable

**Comment by Macacoazul01** [comment]
As said in #295 something was broken in this transition.

**Comment by lizhuoyuan** [comment]
Thank you, I will find time to upgrade the flutter version and troubleshoot this issue,

**Comment by Saidjamol** [comment]
Set splitScreenMode: false

**Comment by Macacoazul01** [comment]
why it's not the default, @lizhuoyuan ?

> Set splitScreenMode: false
