### ISSUE TITLE
桌名应用窗口缩放后字体不缩放

### ISSUE THREAD

**Issue by xiaobingcaicai** [OpenFlutter/flutter_screenutil#304]
桌面端应用，窗口缩放后字体不会随着缩放，需要重新hot reload。
使用了getx的GetMaterialApp包裹的app，screen util的两种初始化方法都尝试了，问题没有解决。

`class LurkerApp extends StatelessWidget {
  LurkerApp({Key? key}) : super(key: key);

  final easyLoad = EasyLoading.init();
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    // okToast包裹初始化
    //return OKToast(child: _buildApp());
    return _buildApp();
  }

  // 创建主app widget
  Widget _buildApp() {
    return GetMaterialApp(
      initialRoute: RouteConfig.main,
      getPages: RouteConfig.getPages,
      title: 'xxxxxxxxx',
      theme: createTheme(),
      // home: const MyHomePage(title: 'Flutter Demo Home Page'),
      home: const LurkerHome(),
      builder: (context, child) {
        child = easyLoad(context, child);
        // 可继续构建其他插件等
        return child;
      },
    );
  }
}

class LurkerHome extends StatefulWidget {
  const LurkerHome({Key? key}) : super(key: key);

  @override
  _LurkerHomeState createState() => _LurkerHomeState();
}

class _LurkerHomeState extends State<LurkerHome> {
  @override
  Widget build(BuildContext context) {
    ScreenUtil.init(
        BoxConstraints(
            maxWidth: MediaQuery.of(context).size.width,
            maxHeight: MediaQuery.of(context).size.height),
        designSize: Size(1920, 1080));
    return Scaffold(
      body: Center(
        child: Container(
            child: const HomeMainPage()),
      ),
    );
  }
}`

**Comment by lizhuoyuan** [comment]
尚未尝试桌面端， 有空会适配一下

**Comment by xiaobingcaicai** [comment]
> 

添加了尺寸变化的监听，监听到尺寸变化后执行ScreenUtil.init，但是界面上并没有变化。 
如果使用setstate的话 需要更新哪些数据？
