### ISSUE TITLE
'setWidth'  and 'setHeight' params should be double type.

### ISSUE THREAD

**Issue by hanhui6145** [OpenFlutter/flutter_screenutil#31]

**Comment by lizhuoyuan** [comment]
Maybe you are right, but now only supports integers.

**Comment by icarus31** [comment]
Hi,

You said it is fixed, but your source code is still:

```
num setWidth(num width) => width * scaleWidth;
num setHeight(num height) => height * scaleHeight;
```

Where can we get the version with double?

**Comment by lizhuoyuan** [comment]
> Hi,
> 
> You said it is fixed, but your source code is still:
> 
> ```
> num setWidth(num width) => width * scaleWidth;
> num setHeight(num height) => height * scaleHeight;
> ```
> 
> Where can we get the version with double?

you can use double ,have a  try

**Comment by alvindrakes** [comment]
"SetWidth" 和 "SetHeight" return 的 data type 还不是 double。

例子： SizedBox(height:  5.h)   

还是行不通啊.

**Comment by lizhuoyuan** [comment]
> "SetWidth" 和 "SetHeight" return 的 data type 还不是 double。
> 
> 例子： SizedBox(height: 5.h)
> 
> 还是行不通啊.

我回头测试一下，看是否把num类型替换为double
