### ISSUE TITLE
v5.0.3，ScreenUtil().statusBarHeight=0

### ISSUE THREAD

**Issue by 1203556555** [OpenFlutter/flutter_screenutil#310]
用第一种方式初始化:
return ScreenUtilInit(
  designSize: const Size(360, 690),
  builder: () => MaterialApp(
    title: 'Flutter_ScreenUtil',
    home: const MyHomePage(title: 'FlutterScreenUtil Demo'),
  ),
);

然后调用ScreenUtil().statusBarHeight结果是0。

**Comment by gujintao1900** [comment]
@lizhuoyuan  
another problem ScreenUtil().pixelRatio=1.0 width first init way.

**Comment by wapchief** [comment]
+1

**Comment by 1227228155** [comment]
+1

**Comment by lan2000** [comment]
这个版本我这边获取ScreenUtil().pixelRatio 等于1，你们有这个问题吗

**Comment by lan2000** [comment]
flutter_screenutil-5.0.0+2 的时候，ScreenUtil().pixelRatio 等于3.0

**Comment by lizhuoyuan** [comment]
什么时候调用的呢

**Comment by zhanghuan88** [comment]
![image](https://user-images.githubusercontent.com/64683397/149073690-d6b88014-1dd8-4344-99fe-a41f3e22986c.png)
这样调用

**Comment by wangyujie1207** [comment]
+1 同样问题

**Comment by lizhuoyuan** [comment]
依赖一下github的版本
稍后我再多检查检查发布新版
