### ISSUE TITLE
Orientation change doesn't update screenutil properties in constant widgets

### ISSUE THREAD

**Issue by AhmedLSayed9** [OpenFlutter/flutter_screenutil#312]
Hi,
When using `const` widgets "in any place in the app" and using screenutil properties ".h , .w etc.." in that widgets, It won't update its value on orientation change. While using normal `MediaQuery` is updating normally. Here's the sample code:

```
void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return ScreenUtilInit(
        designSize: const Size(414, 895),
        minTextAdapt: true,
        builder: () {
          return const MaterialApp(
            home: HomePage(),
          );
        });
  }
}

class HomePage extends StatelessWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    print(MediaQuery.of(context).size.width);
    print(ScreenUtil().screenWidth);
    return Scaffold(
      body: Center(
        child: Container(
          height: 40.h,
          width: 400.w,
          color: Colors.red,
        ),
      ),
    );
  }
}
```

By using `const MaterialApp` and try changing orientation, Print statement of `MediaQuery` will change while `ScreenUtil` won't change "will only change with hot reload".
If you use `MaterialApp` without `const` both will work fine. but of course you'll need to avoid using `const` with any widget that use `ScreenUtil` in the app which is hard and inefficient to do.

I found a way to force updating the UI when orientation change using `Get` but I think a fix of the issue so `ScreenUtil` work efficiently as `MediaQuery` would be better. Here's the force updating that temporarily fix the issue:

```
void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> with WidgetsBindingObserver {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance?.addObserver(this);
  }

  @override
  void dispose() {
    WidgetsBinding.instance?.removeObserver(this);
    super.dispose();
  }

  @override
  void didChangeMetrics() {
    final _currentOrientation = ScreenUtil().screenWidth;
    WidgetsBinding.instance?.addPostFrameCallback((timeStamp) {
      if (_currentOrientation != ScreenUtil().screenWidth) {
        Get.forceAppUpdate();
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return ScreenUtilInit(
        designSize: const Size(414, 895),
        minTextAdapt: true,
        builder: () {
          return const MaterialApp(
            home: HomePage(),
          );
        });
  }
}
```

**Comment by lizhuoyuan** [comment]
thanks , I will try

**Comment by AhmedLSayed9** [comment]
Thanks @lizhuoyuan for your great efforts!

The issue has been fixed for `screenWidth, screenHeight..` but for `.w, .h, .r, and .sp` is still the same.
If you tried to add const to `home: const HomePage(),` you'll get the print statement change but the container width doesn't change.
That's because the `scaleWidth, scaleHeight` getters are using the '_screenWidth, _screenHeight' from ScreenUtil class members. They should use their getters instead which check if `context` is true then get values from MediaQuery.
