### ISSUE TITLE
为什么小版本号更新引入了破坏性更改？

### ISSUE THREAD

**Issue by ConanXie** [OpenFlutter/flutter_screenutil#315]
![1fd06711f42480c16a3bd214805dfa1f](https://user-images.githubusercontent.com/10040846/149478712-7b8d814d-9a69-456c-94d1-e674c23e1a97.jpg)

**Comment by lizhuoyuan** [comment]
这个是我疏忽了，请参考readme更新一下

**Comment by jahnli** [comment]
@lizhuoyuan  ios运行报错， 这个应该如何解决

**Comment by lizhuoyuan** [comment]
> @lizhuoyuan ios运行报错， 这个应该如何解决

同样的错吗？

**Comment by jahnli** [comment]
![0c91b1384029119b9e935156bd0eee8](https://user-images.githubusercontent.com/20943608/149507255-8f2f6ffe-6e77-4146-bdc7-d733f32cddfb.png)
是的， 只有IOS有问题

**Comment by jahnli** [comment]
@lizhuoyuan  
![image](https://user-images.githubusercontent.com/20943608/149507650-72516324-24b8-496a-816f-b5024e3816f1.png)
这是我的myApp，我应该如何适配新版本？ 以保证正确运行

**Comment by lizhuoyuan** [comment]
bottoastInit()中调用一下setContext方法 
可以参考一下example

**Comment by jahnli** [comment]
我用的是BotToast 这个插件，bottoastInit()中好像不行， 我应该如何改写 ？

**Comment by lizhuoyuan** [comment]
> 我用的是BotToast 这个插件，bottoastInit()中好像不行， 我应该如何改写 ？

builder: (context, widget) {
              //add this line
              ScreenUtil.setContext(context);
return bottoastInit()

我不确定里面是什么代码，可以试一下这样

**Comment by supermebing** [comment]
一样的代码  不行

**Comment by lizhuoyuan** [comment]
> 一样的代码 不行

设置一下context， 有提供新方法
