### ISSUE TITLE
scaleWidth and scaleHeight need to be updated with the new setContext parameter

### ISSUE THREAD

**Issue by AhmedLSayed9** [OpenFlutter/flutter_screenutil#321]
Hello,
First of all, Thanks so much for making screenUtil adapt MediaQuery context with the `setContext` parameter.

The issue has been fixed for `screenWidth, screenHeight..` but `scaleWidth, scaleHeight` getters are still using the '_screenWidth, _screenHeight' from ScreenUtil class members. They should use their getters instead which check if context is true then get values from MediaQuery so changes be more sensitive with screen orientation change. I've explained that at #312 too.

Thanks.

**Comment by lizhuoyuan** [comment]
I think the latest changes should be what you want

**Comment by AhmedLSayed9** [comment]
Exactly, well done!
