### ISSUE TITLE
使用getx，第一个界面init一次后，跳转到第二个界面，适配失效。

### ISSUE THREAD

**Issue by junge89221** [OpenFlutter/flutter_screenutil#323]
如题：使用getx，第一个界面init一次后，跳转到第二个界面，适配失效。

**Comment by junge89221** [comment]
runApp(
    GetMaterialApp(
      title: "Application",
      initialRoute: AppPages.INITIAL,
      getPages: AppPages.routes,
    ),
  );


===================


![image](https://user-images.githubusercontent.com/12729702/150269301-c88dde32-6cfc-4cc3-8a9d-e1e09f332e5f.png)
![image](https://user-images.githubusercontent.com/12729702/150269376-9d50c1aa-8103-486e-828a-8749ea78ac34.png)
![image](https://user-images.githubusercontent.com/12729702/150269390-fa373716-2ccd-4afa-a573-87c162952be6.png)

**Comment by junge89221** [comment]
第一个界面可以适配，第二个界面适配失败

**Comment by BlazingCC** [comment]
第二个界面,
build里执行下
ScreenUtil.setContext(context);
试试
