### ISSUE TITLE
container size not same on iOS and android

### ISSUE THREAD

**Issue by avinashk369** [OpenFlutter/flutter_screenutil#325]
container size is different in iOS.
see container with text "Online personal training pack" in iOS and android screenshot.

`SliverAppBar(
            expandedHeight: MediaQuery.of(context).size.height * .58.h,
            floating: false,
            pinned: true,
            flexibleSpace: FlexibleSpaceBar(
              collapseMode: CollapseMode.pin,
              title: Text(
                myTitle,
                style: kLabelStyle.copyWith(
                  fontSize: 16,
                ),
              ),
              background: TrainerCheckoutHeader(
                trainerModel: trainerModel,
                bookingDate: widget.data['booking_date'],
                triningSlot: widget.data['slot'],
              ),
            ),
          ),
`
![Simulator Screen Shot - iPhone 13 - 2022-01-22 at 10 39 52](https://user-images.githubusercontent.com/5073425/150625618-c95304ac-df8d-4f9e-a603-0de9f0f1a8dd.png)
![WhatsApp Image 2022-01-22 at 10 40 29 AM](https://user-images.githubusercontent.com/5073425/150625621-ce5364d8-95ab-4a42-961c-4b33e2426519.jpeg)

**Comment by lizhuoyuan** [comment]
You mean the font size is different? It does vary a bit on different phones

**Comment by paul-lilac** [comment]
Not the font size, check the spacing under Online button, same spacing but different on android and ios

**Comment by Akshaykakkodi** [comment]
same issue, ios have extra space on bottom
