### ISSUE TITLE
Example in README doesn't work in master branch

### ISSUE THREAD

**Issue by brunoalod** [OpenFlutter/flutter_screenutil#326]
Copy & pasting the example in readme actually doesn't work.

No MediaQuery ancestor could be found starting from the context that was passed to MediaQuery.of().

**Comment by AhmedLSayed9** [comment]
I had this issue too.
In first way, You have to add `ScreenUtil.setContext(context);` line and the `context` should be of MaterialApp Builder not MyApp class builder.

**Comment by lizhuoyuan** [comment]
//add this line
           ```   ScreenUtil.setContext(context);```
