### ISSUE TITLE
SafeArea widget is Ignored while using this package

### ISSUE THREAD

**Issue by ItsYasser** [OpenFlutter/flutter_screenutil#328]
SafeArea widget is totally Ignored when i try to use this package
![Screenshot_1643224159](https://user-images.githubusercontent.com/87891892/151232177-0793b998-ccec-4b05-9959-8e5ae7db7e86.png)

**Comment by lizhuoyuan** [comment]
SafeArea add this:
```
SafeArea(
top: false,
```
