### ISSUE TITLE
No MediaQuery widget ancestor found.

### ISSUE THREAD

**Issue by CyJaySong** [OpenFlutter/flutter_screenutil#329]
编码时热更后，会出现该错误：No MediaQuery widget ancestor found.

**Comment by kungege** [comment]
你的flutter_screenutil版本是多少？
最新版需要加上
![image](https://user-images.githubusercontent.com/16132584/151309788-10df0513-5271-4602-9477-47763e84175a.png)

**Comment by CyJaySong** [comment]
加上了的，使用master 也这样

**Comment by sanjaymajoka** [comment]
Facing same issue. I am using below code.

```
  @override
  Widget build(BuildContext context) {
    return ScreenUtilInit(
      designSize: const Size(360, 690),
      minTextAdapt: true,
      builder: () {
        return GetMaterialApp(
          builder: (context, widget) {
            ScreenUtil.setContext(context);
            return MediaQuery(
                data: MediaQuery.of(context).copyWith(textScaleFactor: 1.0),
                child: widget!);
          },
          debugShowCheckedModeBanner: false,
          theme: settingService.getThemeData(context),
          home: SplashPage(),
        );
      },
    );
  }
```

**Comment by CyJaySong** [comment]
But I didn't use `Getx`

**Comment by linxkaa** [comment]
i solve this by add `MediaQuery` above the `ScreenUtilInit`

```
 return MediaQuery(
      data: const MediaQueryData(
        size: Size(1000, 500),
      ),
      child: ScreenUtilInit(
        minTextAdapt: true,
        designSize: const Size(500, 300),
        builder: () {
          return MaterialApp.router(
            // restorationScopeId: 'app',
            builder: (context, widget) {
              //add this line
              ScreenUtil.setContext(context);
              return MediaQuery(
                //Setting font does not change with system font size
                data: MediaQuery.of(context).copyWith(
                  textScaleFactor: 1.5,
                ),
                child: widget!,
              );
            },
            localizationsDelegates: const [
              // AppLocalizations.delegate,
              GlobalMaterialLocalizations.delegate,
              GlobalWidgetsLocalizations.delegate,
              GlobalCupertinoLocalizations.delegate,
            ],
            supportedLocales: const [
              Locale('id', ''),
            ],
            // onGenerateTitle: (BuildContext context) => AppLocalizations.of(context)!.appTitle,
            theme: AppTheme.theme,
            darkTheme: AppTheme.theme,
            routerDelegate: AutoRouterDelegate(router),
            routeInformationParser: router.defaultRouteParser(),
          );
        },
      ),
    );
```

dont know if this was the best approach tho, but for now it solve for me

**Comment by gfb-47** [comment]
I'm having the same issue, I'm using Getx and @sanjaymajoka's solution worked

**Comment by sanjaymajoka** [comment]
@gfb-47 But same thing didn't worked for me.
 
So I used Second Way which is recommended in flutter_screenutil

**Comment by IdemenB** [comment]
This has started In my app today, too after updating to 5.1.1. Yet, even after reverting back to 5.1.0, running flutter clean and trying wrapping all Widgets available in main.dart one by one did not solve it and now I'm stuck. A very interesting issue...

**Comment by IdemenB** [comment]
> This has started In my app today, too after updating to 5.1.1. Yet, even after reverting back to 5.1.0, running flutter clean and trying wrapping all Widgets available in main.dart one by one with MediaQuery() did not solve it and now I'm stuck. A very interesting issue...

After spending 3 hours on this, I just noticed that the ^ mark forces the app to use 5.1.1, which satisfies the condition. Those of you who get "No MediaQuery widget ancestor found" error, make sure that the version is entered as '5.1.0' into pub spec.yaml.

**Comment by Thalinda** [comment]
@IdemenB  as you said i have change version back to from 5..1.1+2 to 5.1.1 but once it's updated the errors is coming back now @linxkaa solution worked but i don't think it's adapting any thing according to the screen size but remaining in version 5.1.1 fixed the issue but still it's not a proper solution i guess

**Comment by gfb-47** [comment]
If puspec.lock don't downgrade the version you can remove it and re-generate it with a `flutter pub get`

**Comment by IdemenB** [comment]
If you write   flutter_screenutil: ^5.1.1.  you don't downgrade, because 5.1.1. satisfies the conditions brought by ^. Make sure that In the pubspec.yaml you have: flutter_screenutil: '5.1.0'

**Comment by yangbo001** [comment]
Facing same issue. the version i downgrade to 5.1.0.

**Comment by techouse** [comment]
I used @sanjaymajoka solution of manually setting `ScreenUtil.setContext(context);` before I return my `MaterialApp` in the builder off `app.dart` and it fixed the issue.

I'm just not sure how such a breaking change made its way into a patch version. 😅

**Comment by techouse** [comment]
I used @linxkaa's solution and it works. <3

I'm just not sure how such a breaking change made itself into a patch release. :/

**Comment by techouse** [comment]
> i solve this by add `MediaQuery` above the `ScreenUtilInit`
> 
> ```
>  return MediaQuery(
>       data: const MediaQueryData(
>         size: Size(1000, 500),
>       ),
>       child: ScreenUtilInit(
>         minTextAdapt: true,
>         designSize: const Size(500, 300),
>         builder: () {
>           return MaterialApp.router(
>             // restorationScopeId: 'app',
>             builder: (context, widget) {
>               //add this line
>               ScreenUtil.setContext(context);
>               return MediaQuery(
>                 //Setting font does not change with system font size
>                 data: MediaQuery.of(context).copyWith(
>                   textScaleFactor: 1.5,
>                 ),
>                 child: widget!,
>               );
>             },
>             localizationsDelegates: const [
>               // AppLocalizations.delegate,
>               GlobalMaterialLocalizations.delegate,
>               GlobalWidgetsLocalizations.delegate,
>               GlobalCupertinoLocalizations.delegate,
>             ],
>             supportedLocales: const [
>               Locale('id', ''),
>             ],
>             // onGenerateTitle: (BuildContext context) => AppLocalizations.of(context)!.appTitle,
>             theme: AppTheme.theme,
>             darkTheme: AppTheme.theme,
>             routerDelegate: AutoRouterDelegate(router),
>             routeInformationParser: router.defaultRouteParser(),
>           );
>         },
>       ),
>     );
> ```
> 
> dont know if this was the best approach tho, but for now it solve for me

This indeed fixes the compilation issue but messes up font sizes and spacing.

**Comment by miladrashidizade** [comment]
All you have to do is call ScreenUtil.setContext (context); inside the builder widget MaterialApp

**Comment by techouse** [comment]
> All you have to do is call ScreenUtil.setContext (context); inside the builder widget MaterialApp

I had that already with v5.1.0 and it worked completely fine but with v5.1.1 it complained with this runtime error.

```dart
@override
Widget build(BuildContext context) {
  return MultiProvider(
    providers: <SingleChildWidget>[
      // list of providers
    ],
    child: ScreenUtilInit(
      designSize: designSize,
      minTextAdapt: true,
      builder: () => Selector<SettingsProvider, bool>(
        selector: (context, SettingsProvider settings) => settings.darkMode,
        builder: (context, bool darkMode, _) => MaterialApp.router(
          builder: (context, Widget? widget) {
            ScreenUtil.setContext(context);

            return MediaQuery(
              data: MediaQuery.of(context).copyWith(textScaleFactor: 1.0),
              child: widget!,
            );
          },
          routeInformationParser: _router.routeInformationParser,
          routerDelegate: _router.routerDelegate,
          theme: Style.lightTheme,
          darkTheme: Style.darkTheme,
          themeMode: darkMode ? ThemeMode.dark : ThemeMode.light,
        ),
      ),
    ),
  );
}
```

**Comment by miladrashidizade** [comment]
> > All you have to do is call ScreenUtil.setContext (context); inside the builder widget MaterialApp
> 
> I had that already with v5.1.0 and it worked completely fine but with v5.1.1 it complained with this runtime error.
> 
> ```dart
> @override
> Widget build(BuildContext context) {
>   return MultiProvider(
>     providers: <SingleChildWidget>[
>       // list of providers
>     ],
>     child: ScreenUtilInit(
>       designSize: designSize,
>       minTextAdapt: true,
>       builder: () => Selector<SettingsProvider, bool>(
>         selector: (context, SettingsProvider settings) => settings.darkMode,
>         builder: (context, bool darkMode, _) => MaterialApp.router(
>           builder: (context, Widget? widget) {
>             ScreenUtil.setContext(context);
> 
>             return MediaQuery(
>               data: MediaQuery.of(context).copyWith(textScaleFactor: 1.0),
>               child: widget!,
>             );
>           },
>           routeInformationParser: _router.routeInformationParser,
>           routerDelegate: _router.routerDelegate,
>           theme: Style.lightTheme,
>           darkTheme: Style.darkTheme,
>           themeMode: darkMode ? ThemeMode.dark : ThemeMode.light,
>         ),
>       ),
>     ),
>   );
> }
> ```

 return MaterialApp(
          useInheritedMediaQuery: true,
          title: "Stream Heroes",
          builder: (context, widget) {
            ScreenUtil.setContext(context);
            return MediaQuery(
              data: MediaQuery.of(context).copyWith(textScaleFactor: 1.0),
              child: widget!);
          },)

Please check above code.

**Comment by techouse** [comment]
> return MaterialApp( useInheritedMediaQuery: true, title: "Stream Heroes", builder: (context, widget) { ScreenUtil.setContext(context); return MediaQuery( data: MediaQuery.of(context).copyWith(textScaleFactor: 1.0), child: widget!); },)
> 
> Please check above code.

Doesn't work. And if I wrap my `ScreenUtilInit` inside something like
```dart
@override
Widget build(BuildContext context) {
  return MultiProvider(
    providers: _providers,
    child: MediaQuery( // wrapping ScreenUtilInit in MediaQuery messes up the font sizes and spacing
      data: const MediaQueryData(size: designSize),
      child: ScreenUtilInit(
        designSize: designSize,
        minTextAdapt: true,
        builder: () => Selector<SettingsProvider, bool>(
          selector: (context, SettingsProvider settings) => settings.darkMode,
          builder: (context, bool darkMode, _) => MaterialApp.router(
            useInheritedMediaQuery: true, // here I tried adding your suggestion
            builder: (context, Widget? widget) {
              ScreenUtil.setContext(context);

              return MediaQuery(
                data: MediaQuery.of(context).copyWith(textScaleFactor: 1.0),
                child: widget!,
              );
            },
            routeInformationParser: _router.routeInformationParser,
            routerDelegate: _router.routerDelegate,
            theme: Style.lightTheme,
            darkTheme: Style.darkTheme,
            themeMode: darkMode ? ThemeMode.dark : ThemeMode.light,
          ),
        ),
      ),
    ),
  );
}
```

It messes up the fonts and spacing

**Comment by mohammedhasna2015** [comment]
its work Good for me on 5.1.1 , you should just to remove const from your class ui and use setContext on builder MaterialApp

**Comment by mohammedhasna2015** [comment]
about the font , i'm created custom widget, use it on whole project and handle the width if above 1100 not using sp , if not using it => just it

**Comment by techouse** [comment]
So basically you have to tell `ScreenUtil`'s parent `MediaQuery` how big your screen resolution is. I was previously using the design resolution above, that's why the sizes got skewed. Using it like this works:
```dart
@override
Widget build(BuildContext context) {
  return MultiProvider(
    providers: _providers,
    child: MediaQuery(
      data: MediaQueryData.fromWindow(WidgetsBinding.instance!.window), // like this it works and produces correct font sizes
      child: ScreenUtilInit(
        designSize: designSize,
        minTextAdapt: true,
        builder: () => Selector<SettingsProvider, bool>(
          selector: (context, SettingsProvider settings) => settings.darkMode,
          builder: (context, bool darkMode, _) => MaterialApp.router(
            useInheritedMediaQuery: true,
            builder: (context, Widget? widget) {
              ScreenUtil.setContext(context);

              return MediaQuery(
                data: MediaQuery.of(context).copyWith(textScaleFactor: 1.0),
                child: widget!,
              );
            },
            routeInformationParser: _router.routeInformationParser,
            routerDelegate: _router.routerDelegate,
            theme: Style.lightTheme,
            darkTheme: Style.darkTheme,
            themeMode: darkMode ? ThemeMode.dark : ThemeMode.light,
          ),
        ),
      ),
    ),
  );
}
```

**Comment by bawantha** [comment]
Can someone tell me why this change did in 5.1.1 what wrong with 5.1.0 ? Can we just ignore 5.1.1 ?

**Comment by techouse** [comment]
> Can someone tell me why this change did in 5.1.1 what wrong with 5.1.0 ? Can we just ignore 5.1.1 ?

If you check the [changelog](https://github.com/OpenFlutter/flutter_screenutil/blob/master/CHANGELOG.md) you'll see numerous breaking changes in minor and even patch versions from 5.0.0 to now. I suggest you check carefully every time this package updates and if it's crucial to your app, pin it and only update manually.

**Comment by andrehaupt** [comment]
> > Can someone tell me why this change did in 5.1.1 what wrong with 5.1.0 ? Can we just ignore 5.1.1 ?
> 
> If you check the [changelog](https://github.com/OpenFlutter/flutter_screenutil/blob/master/CHANGELOG.md) you'll see numerous breaking changes in minor and even patch versions from 5.0.0 to now. I suggest you check carefully every time this package updates and if it's crucial to your app, pin it and only update manually.

Breaking changes in minor and patch versions... Nice.

**Comment by bawantha** [comment]
Yeah, this thing change our UI view it was not good

**Comment by axiaofang666** [comment]
同样的问题

**Comment by gfb-47** [comment]
It changed our UI too, we just messed with this field: **textScaleFactor** to correct.

**Comment by lizhuoyuan** [comment]
Hello everyone, first of all, I'm sorry, some changes I had thought were not destructive, sometimes did not take into account the complexity, in short, it was an oversight on my part. I will try to avoid repeating the problem in the future and will fix some of the known problems, sorry again!

**Comment by techouse** [comment]
Looks like this is now fixed. I just removed the `MediaQuery` wrapping `ScreenUtilInit` and it works as expected.

**Comment by CyJaySong** [comment]
> Looks like this is now fixed. I just removed the `MediaQuery` wrapping `ScreenUtilInit` and it works as expected.

Yes
