### ISSUE TITLE
setWIdth 和 setHeight 没有考虑设备的分辨率

### ISSUE THREAD

**Issue by cixiu** [OpenFlutter/flutter_screenutil#33]
一张图片，通过setWidth和setHeight设置好宽高，在不同的分辨率下，这张图片的显示区域不一致。

**Comment by lizhuoyuan** [comment]
大小的话会按照屏幕分辨率进行不同程度的放大/缩小

**Comment by cixiu** [comment]
我遇到的是，有2个手机，分辨率分辨是1080x1920, 另一个是1080x2280。pixelRatio都等于3，这就导致通过setWidth 和 setHeight设置宽度后，宽是一致，但是不同手机计算出来的高度不一致，所以图片的显示区域也就不一致了。所以有没有实现微信小程序的 rpx 实现方式呢。

**Comment by lizhuoyuan** [comment]
你可以都使用setWidth来设置宽和高

**Comment by cixiu** [comment]
是的，确实可以都使用 setWidth 来设置宽高，不过 setWidth 和 setHeight 这2个命名会造成歧义。setWidth 和 setHeight 本身都是返回一个 double，一个是根据 MediaQuery.of(context).size.width 返回一个double，一个是根据 MediaQuery.of(context).size.height 返回一个 double。所以使用setWidth和setHeight的命名并不是字面的设置宽和设置高的意思。

**Comment by lizhuoyuan** [comment]
是有点歧义 , 但我文档里有说......
