### ISSUE TITLE
集成到 Native 项目中时，请不要使用方式一

### ISSUE THREAD

**Issue by NianyiYang** [OpenFlutter/flutter_screenutil#345]
使用方式一集成到 Android 原生项目时，会出现使用该库的组件全都出不来的情况一片空白...排查了一晚上，从 flutterboost 查到 资源文件集成方式，最后才发现是 flutter_screenutil 的锅

**建议在文档中加重清晰注明一下**，免得后来的小白也踩坑...

Edit 在页面中加入 `ScreenUtils.getContext(context) ` 也可以

**Comment by lizhuoyuan** [comment]
确实可以。
因为flutter和原生之间跳转走的逻辑不同

**Comment by AlanJN** [comment]
我也遇到了这个，我把ScreenUtilInit 放在了MaterialApp 里面。Add-to-App 模式下 ，方式一可能获取不到Context
