### ISSUE TITLE
每个字体设置的地方都调用fontSize: SCUtil.ScreenUtil().setSp(9.0.sp),

### ISSUE THREAD

**Issue by Sabirjan** [OpenFlutter/flutter_screenutil#351]
需要每个字体设置的地方 都要调用fontSize: SCUtil.ScreenUtil().setSp(9.0.sp),  
还是 直接设置 9.0.sp就行。两个的有区别吗

**Comment by BrunoJurkovic** [comment]
There is no difference between the two. The second option is shorter.

**Comment by lizhuoyuan** [comment]
fontSize:9.sp 即可
