### ISSUE TITLE
Not working with ListView.separated()

### ISSUE THREAD

**Issue by ketancts** [OpenFlutter/flutter_screenutil#355]
**Causes issue Exception caught by widgets library when we scroll frequently** 

```
class ScreenDrawerTrading extends StatelessWidget {
  const ScreenDrawerTrading({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    ScreenUtil.setContext(context);

    return ListView.separated(
      itemCount: 10,
      separatorBuilder: (_ctx, _index) {
        return SizedBox(height: 20.h); //Causes issue here Error is **Exception caught by widgets library**
      },
      itemBuilder: (_ctx, _index) {
        return WidgetDrawerTrading(
          key: UniqueKey(), // This line will update UI after removing item
        );
      },
    );
  }
}
```

**Comment by Mounir-Bouaiche** [comment]
Please provide the complete error log.

**Comment by ketancts** [comment]
════════ Exception caught by widgets library ═══════════════════════════════════
Null check operator used on a null value

**Comment by ketancts** [comment]
@BrunoJurkovic As you can see ScreenUtil.setContext(context); is already mentioned in the snippet I provided.

The issue is caused when we frequently scroll.

**Comment by sharad-paghadal** [comment]
@ketancts I'm also facing the same error, Please do let me know if you somehow able to fix this.

**Comment by lizhuoyuan** [comment]
do u have "navigatorKey" ?
try to use navigatorKey.currentContext

**Comment by Mounir-Bouaiche** [comment]
Hi @ketancts @sharad-paghadal , I have recently publish the new version of the library. Go check it out and if it works fine for you please close this issue, or else drop error log here. Thank you.

**Comment by ketancts** [comment]
@sharad-paghadal Can you please check this and let me know I can't check this issue as I have removed this library from my project. If the newly updated library solved the problem then let me know so that I can close this issue.

@Mounir-Bouaiche Thank you for the resolution
