### ISSUE TITLE
启动APP后，调整系统字体大小，使用setSp设置fontSize的文字大小会跟随变化

### ISSUE THREAD

**Issue by danieldai** [OpenFlutter/flutter_screenutil#36]
我在screenutil里采用了默认的不跟随系统字体大小；但是启动APP后，调整系统字体大小，使用setSp设置fontSize的文字大小会跟随变化。然后把APP退出再启动后，字体大小恢复正常。

我猜测使用setSp计算的字体大小在系统字体大小调整后并没有重新计算。

**Comment by lizhuoyuan** [comment]
你猜对了 QAQ

**Comment by lizhuoyuan** [comment]
Duplicate of #29
