### ISSUE TITLE
Another exception was thrown: Null check operator used on a null value

### ISSUE THREAD

**Issue by desire0420** [OpenFlutter/flutter_screenutil#363]
ScreenUtil.init(
        BoxConstraints(
            maxWidth: MediaQuery.of(context).size.width,
            maxHeight: MediaQuery.of(context).size.height),
        designSize: Size(360, 690),
        context: context,
        minTextAdapt: true,
        orientation: Orientation.portrait);

使用这种方式在第一个页面的build方法初始化后，在其他页面使用的时候会报错
Another exception was thrown: Null check operator used on a null value

**Comment by kid-with-a-gun** [comment]
+1

**Comment by leavky** [comment]
+1

**Comment by lizhuoyuan** [comment]
今晚会发布新版哈
公司网络问题没法发布
