### ISSUE TITLE
Error: Superclass has no constructor named 'SizedBox.square'.  super.square(key: key, child: child, dimension: dimension);

### ISSUE THREAD

**Issue by ABmamunHoneybee** [OpenFlutter/flutter_screenutil#369]
flutter_screenutil-5.4.0/lib/src/r_sizedbox.dart:35:9: Error: Superclass has no constructor named 'SizedBox.square'.
        super.square(key: key, child: child, dimension: dimension);

**Comment by Mounir-Bouaiche** [comment]
Please provide the output of
```
flutter doctor -v
```

**Comment by techistoner** [comment]
fvm flutter doctor -v
[✓] Flutter (Channel stable, 2.0.3, on macOS 12.3.1 21E258 darwin-arm, locale zh-Hans-CN)
    • Flutter version 2.0.3 at /Users/tech/fvm/versions/2.0.3
    • Framework revision 4d7946a68d (1 year, 1 month ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tech/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.3.1, Build version 13E500a
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (1 available)

**Comment by Mounir-Bouaiche** [comment]
Update to latest version of flutter by running
```flutter upgrade```
