### ISSUE TITLE
Why use MediaQuery when I set deviceSize?

### ISSUE THREAD

**Issue by zhcode-fun** [OpenFlutter/flutter_screenutil#372]
![image](https://user-images.githubusercontent.com/31911177/164178306-04bd65e7-2c9d-4e33-b40f-19492d51d89d.png)

Why use MediaQuery when I set deviceSize?
Is deviceSize useful?

英语不好，再用中文说一遍
按理说，我传了deviceSize那应该就用我传的尺寸计算才对，而且我觉得如果传了deviceSize的情况下context也可以不用传了，
但现在无论传不传deviceSize，插件都会自己用MediaQuery 获取的尺寸，deviceSize好像没什么用

**Comment by Mounir-Bouaiche** [comment]
Good point.

**Comment by lizhuoyuan** [comment]
应该是历史遗留问题
