### ISSUE TITLE
font size changing when keyboard shows up

### ISSUE THREAD

**Issue by monkeyboss** [OpenFlutter/flutter_screenutil#373]
font size changes when keyboard shows up, and resizes back when it closes,
tried to set "resizeToAvoidBottomInset: false" but it didnt work
flutter_screenutil version: 5.3.1

**Comment by lizhuoyuan** [comment]
Is the height of the phone too low?
Can you print your phone size and UI Design size?

**Comment by monkeyboss** [comment]
手机分辨率：2340×1080
UI设计：375*667dp
*初始化：*
ScreenUtil.init(
        BoxConstraints(
            maxWidth: MediaQuery.of(context).size.width,
            maxHeight: MediaQuery.of(context).size.height,
        ),
        designSize: dqDefaultSize,
        context: context,
        minTextAdapt: true,
        orientation: Orientation.portrait,
    );


键盘弹出时，页面字体会缩小，收起键盘恢复正常

LiZhuoyuan ***@***.***> 于2022年4月24日周日 18:29写道：

**Comment by monkeyboss** [comment]
Size dqDefaultSize = Size(375.0, 667.0);

Xu Liang ***@***.***> 于2022年4月26日周二 11:02写道：

**Comment by lizhuoyuan** [comment]
我大概知道了出现问题的原因，因为要适配平板， 我要想一个比较合适的方式来解决

**Comment by lizhuoyuan** [comment]
然后有一个参数,在inist时候 使用 minTextAdapt 传入true 将不会改变大小

**Comment by Mounir-Bouaiche** [comment]
@monkeyboss , Please try with master branch and tell us if it works with you so we can ship a stable version in pub.dev.
```yaml
dependencies:

  flutter_screenutil:
    git:
      url: https://github.com/OpenFlutter/flutter_screenutil
      branch: master
```

**Comment by Mounir-Bouaiche** [comment]
Hi @monkeyboss , I have recently publish the new version of the library. Go check it out and if it works fine for you please close this issue, or else drop error log here. Thank you.
