### ISSUE TITLE
5.4.0+1版本有问题

### ISSUE THREAD

**Issue by fuyunmanbu** [OpenFlutter/flutter_screenutil#376]
该版本在键盘弹出时会导致ScreenUtilInit的builder方法重复调用

**Comment by Mounir-Bouaiche** [comment]
Hello friend, do you have any better idea?

**Comment by fuyunmanbu** [comment]
I changed it to use ScreenUtil.init instead of ScreenUtilInit

**Comment by Mounir-Bouaiche** [comment]
@fuyunmanbu it's recommanded to use ScreenUtil.init() unless you want to use the library to build MaterialApp's themedata. However, in the next few weeks, there will be an upgrade, especially in performance. So stay tuned and you're welcome to give any idea or PR. You can contact me via email if you want: <bouaiche.9@gmail.com>.

**Comment by Mounir-Bouaiche** [comment]
@fuyunmanbu I've updated the library and the error is fixed. Go check it out.
