### ISSUE TITLE
v5.51: open soft keyboard covers content

### ISSUE THREAD

**Issue by techouse** [OpenFlutter/flutter_screenutil#385]
Hi,

I've noticed that upgrading to `v5.5.1` somehow prevents the content from being pushed upwards. Reverting back to `v5.4.0+1` fixes it.

Example:

```dart
@override
Widget build(BuildContext context) {
  return Scaffold(
    body: Padding(
      padding: EdgeInsets.symmetric(
        horizontal: 24.w,
      ),
      child: Column(
        children: [
          Expanded(
            child: AnimatedList(
              reverse: true,
              itemBuilder: (context, index, animation) => ChatMessageBubble(
                animation: animation,
                message: _chatMessages.reversed.elementAt(index),
              ),
            ),
          ),
          SizedBox(height: 48.h),
          CupertinoTextField(
            autofocus: true,
            // ... other conf
          )
        ],
      ),
    ),
  );
```

**Working v5.4.0+1**
![v5 4 0+1](https://user-images.githubusercontent.com/1174328/166661698-0a7e97ed-efc6-452e-9bf6-db37265c612f.png)

**Broken v5.5.1**
![v5 5 1](https://user-images.githubusercontent.com/1174328/166661768-df5492ca-9fa8-42dd-b7f8-a76c0e58b1ca.png)

**Comment by Mounir-Bouaiche** [comment]
@techouse You are using ScreenUtilInit() or ScreenUtil.init()

**Comment by techouse** [comment]
@Mounir-Bouaiche I'm using `ScreenUtilInit`

**Comment by Mounir-Bouaiche** [comment]
> @Mounir-Bouaiche I'm using `ScreenUtilInit`

Did you set ``` useInheritedMediaQuery: true ```?

**Comment by Mounir-Bouaiche** [comment]
> > > @Mounir-Bouaiche I'm using `ScreenUtilInit`
> > 
> > Did you set `useInheritedMediaQuery: true`?
> 
> Yes.

Remove it then or set it to false.

**Comment by techouse** [comment]
> > > > @Mounir-Bouaiche I'm using `ScreenUtilInit`
> > > 
> > > 
> > > Did you set `useInheritedMediaQuery: true`?
> > 
> > 
> > Yes.
> 
> Remove it then or set it to false.

Yep, that fixed it. Thanx!
