### ISSUE TITLE
使用 5.5.2版本 后出现的问题

### ISSUE THREAD

**Issue by LiWenHui96** [OpenFlutter/flutter_screenutil#388]
使用 `chewie: ^1.3.2` 进行横竖屏转换后，无法正常播放视频

目前解决方案为 `rebuildFactor: (MediaQueryData old, MediaQueryData data) => old.size == data.size,`

但由此带来的问题是，非视频播放的横竖屏转换不能正常的调整尺寸。

希望作者大大可以关注下这个问题

**Comment by Mounir-Bouaiche** [comment]
Ah yes, how I forgot about it.
Try removing rebuildFactor, and use key in MaterialApp.
ex:
```dart
MaterialApp(
  key: const GlobalObjectKey('my-app'),
)
```

**Comment by Mounir-Bouaiche** [comment]
@LiWenHui96 if it doesn't work for you, please share with us some code of how you initialize ScreenUtil and how you use chewie, else close this issue.

**Comment by LiWenHui96** [comment]
@Mounir-Bouaiche 我想我知道应该怎么去正确的处理这个事情了，感谢。我因为错误的使用了 `key`，导致 `chewie` 重新生成了。
