### ISSUE TITLE
MediaQuery.of(context) viewInsets is not working

### ISSUE THREAD

**Issue by mertcandev** [OpenFlutter/flutter_screenutil#389]
Hi all,

Noticed this error while working on a modal bottom sheet. Trying to use viewInsets.bottom in order to move the bottom sheet upwards while keyboard appears. I was not able to manage it properly. Bottom sheet was always overlapped by the keyboard even though I tried every solution. 

For the last try, I moved the codes to a new project which is not involved with screenUtil package and seems it works smoothly this way. 

Without screenUtil;

![image](https://user-images.githubusercontent.com/75225566/167578627-4393bcf2-2e3d-48c4-9b12-632786418087.png)
![Screenshot_1652168097](https://user-images.githubusercontent.com/75225566/167579741-2b43ee3d-04d1-40da-81af-09a7e20b3690.png)

With ScreenUtil

![image](https://user-images.githubusercontent.com/75225566/167579926-dbb1cd72-fcd1-455d-b126-27e364bb7667.png)

Am I doing something wrong or missing something?

**Comment by Mounir-Bouaiche** [comment]
Did you use ```useInheritedMediaQuery: true``` in MaterialApp?

**Comment by mertcandev** [comment]
Yes, been using it since the beginning. 

![image](https://user-images.githubusercontent.com/75225566/167665436-b3405e15-ef9e-4f34-9004-2b917482bd90.png)

**Comment by Mounir-Bouaiche** [comment]
This is similar to issue #385

**Comment by mertcandev** [comment]
Oh god. Thank you so much. Fixed it.
