### ISSUE TITLE
ScreenUtil 打release包的问题

### ISSUE THREAD

**Issue by zhyhub** [OpenFlutter/flutter_screenutil#39]
release包的界面和debug的界面不一样，有部分组件不能显示或者显示不完全。后来我使用MediaQuery去设置高宽，release和debug呈现的界面就一样了。

**Comment by zhyhub** [comment]
希望大佬查看下原因，完善下。PS：ScreenUtil还是很好用的

**Comment by uljjmhn520** [comment]
我也遇到类似的问题

运行官方这段代码
```bash
    print('Device width:${ScreenUtil.screenWidth}'); //Device width
    print('Device height:${ScreenUtil.screenHeight}'); //Device height
    print(
        'Device pixel density:${ScreenUtil.pixelRatio}'); //Device pixel density
    print(
        'Bottom safe zone distance:${ScreenUtil.bottomBarHeight}'); //Bottom safe zone distance，suitable for buttons with full screen
    print(
        'Status bar height:${ScreenUtil.statusBarHeight}px'); //Status bar height , Notch will be higher Unit px
    print(
        'Ratio of actual width dp to design draft px:${ScreenUtil.getInstance().scaleWidth}'); 
    print(
        'Ratio of actual height dp to design draft px:${ScreenUtil.getInstance().scaleHeight}'); 
    print(
        'The ratio of font and width to the size of the design:${ScreenUtil.getInstance().scaleWidth * ScreenUtil.pixelRatio}');
    print(
        'The ratio of  height width to the size of the design:${ScreenUtil.getInstance().scaleHeight * ScreenUtil.pixelRatio}');
```

如果 flutter run ，结果：
```text
I/flutter (13647): Device width:1080.0                                  
I/flutter (13647): Device height:1919.9999999999998                     
I/flutter (13647): Device pixel density:2.75                            
I/flutter (13647): Bottom safe zone distance:0.0                        
I/flutter (13647): Status bar height:66.0px                             
I/flutter (13647): Ratio of actual width dp to design draft px:0.5236363636363637
I/flutter (13647): Ratio of actual height dp to design draft px:0.5233746762982144
I/flutter (13647): The ratio of font and width to the size of the design:1.4400000000000002
I/flutter (13647): The ratio of  height width to the size of the design:1.4392803598200896
```

但是 flutter fun --profile / --release 结果：

```text
I/flutter (12960): Device width:0.0
I/flutter (12960): Device height:0.0
I/flutter (12960): Device pixel density:1.0
I/flutter (12960): Bottom safe zone distance:0.0
I/flutter (12960): Status bar height:0.0px
I/flutter (12960): Ratio of actual width dp to design draft px:0.0
I/flutter (12960): Ratio of actual height dp to design draft px:0.0
I/flutter (12960): The ratio of font and width to the size of the design:0.0
I/flutter (12960): The ratio of  height width to the size of the design:0.0

```

**Comment by lizhuoyuan** [comment]
已知 
稍后看一下原因

**Comment by lizhuoyuan** [comment]
我试了一下打开了我的flutter_screenutil项目 
然后运行了一下:
![image](https://user-images.githubusercontent.com/15923901/57753673-537e7a00-771f-11e9-95b9-6baee9ea0bff.png)

后面我再看看

**Comment by weir008** [comment]
存在同样的问题. 
调试模式一切正常, 打包之后, 发现有个页面文字不显示(用 SU设置了字体大小), 把字体大小改为直接设置就正常了.

**Comment by weir008** [comment]
比较奇怪的是, 我几乎每个页面都用到了SU, 但只有一个页面出问题..

**Comment by hzysunrain** [comment]
页面第一次启动的时候，获取不到屏幕尺寸，需要用监听页面的方式类初始化

**Comment by hzysunrain** [comment]
为了测试获取屏幕尺寸为0的问题，就进行下面的测试:

我的启动页面，在启动的时候获取不到屏幕的尺寸，跳转到第二个页面才可以获取到屏幕尺寸。（有些机型不会出现这个问题）

原因是打开启动页面时，ScreenUtil 初始化时，获取的屏幕尺寸都是0；在第二个页面，ScreenUtil再次调用初始化函数，这时就可以获取到屏幕的尺寸。

官方的解析是，需要监听页面的屏幕尺寸变化，

class MetricsReactor extends StatefulWidget {
  const MetricsReactor({ Key key }) : super(key: key);

  @override
  _MetricsReactorState createState() => _MetricsReactorState();
}

class _MetricsReactorState extends State<MetricsReactor> with WidgetsBindingObserver {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  Size _lastSize;

  @override
  void didChangeMetrics() {
    setState(() { 
      _lastSize = WidgetsBinding.instance.window.physicalSize; 
      // 在这里可以进行ScreenUtil的初始化

    });
  }

  @override
  Widget build(BuildContext context) {
    return Text('Current size: $_lastSize');
  }
}

**Comment by lizhuoyuan** [comment]
@hzysunrain  我试过在didChangeMetrics中初始化ScreenUtil , 但是它的触发时间晚于build (在我尝试的几次)
哪怕我在Myapp中的didChangeMetrics都要在home的build方法之后才调用
