### ISSUE TITLE
flutter dialog widget is dismissed when resizing the App window

### ISSUE THREAD

**Issue by AbdalahTaha** [OpenFlutter/flutter_screenutil#390]
using Screenutil 5.5.2 for creating Desktop App on Windows 10

when resizng the App window, Flutter Dialog is dismissed Autamatically.

note: this issue appears only on version 5.5.2 , Downgrading to 5.5.1 solves the issue.

**Comment by Mounir-Bouaiche** [comment]
Ah yes, how I forgot about it.
Try removing rebuildFactor, and use key in MaterialApp.
ex:
```dart
MaterialApp(
  key: GlobalObjectKey(this),
)
```
