### ISSUE TITLE
横竖屏触发重新绘制bug

### ISSUE THREAD

**Issue by bakboem** [OpenFlutter/flutter_screenutil#396]
一直用得好好的，这次更新到3.0发现问题不小，
之前没有改成 build(child)的时候， 直接用build(context)衔接上下文, 从context取什么都很方便。
现在感觉把context 给拦截了..很担心被触发重新绘制。所以我觉得你应该把context还给使用者。

**Comment by Mounir-Bouaiche** [comment]
You are using context for what exactly?
