### ISSUE TITLE
5.5.3+1的版本，使用第一种方法获取不到状态栏的高度

### ISSUE THREAD

**Issue by zhoujia456888** [OpenFlutter/flutter_screenutil#398]
5.5.3+1的版本，使用第一种方法获取不到状态栏的高度。
测试第二种方法，刚开始进入也是获取不到状态栏的高度，旋转一次之后就能获取到
测试手机是红米NotePro8

![image](https://user-images.githubusercontent.com/7905253/168944464-eb6745b1-f106-48ab-83e1-9ec62d979207.png)

**Comment by Shahmirzali-Huseynov** [comment]
@zhoujia456888  explain in english

**Comment by zhoujia456888** [comment]
The 5.5.3+1 version does not get the height of the status bar using the first method.

To test the second method, the height of the status bar can not be obtained at the beginning of the entry, but can be obtained after one rotation

The test phone was redmi Note8Pro

**Comment by jinjilynn** [comment]
> @zhoujia456888 explain in english

牛逼,咋的,中文配不上你了还?????

**Comment by jinjilynn** [comment]
他在init方法里并没有保存你传进去context

**Comment by shichunlei** [comment]
the first method      ScreenUtil().statusBarHeight   is 0dp
