### ISSUE TITLE
Adapt Flutter 3.0

### ISSUE THREAD

**Issue by lyellss** [OpenFlutter/flutter_screenutil#401]
when run on Flutter 3.0

log show this warning

` - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../Program/Flutter/packages/flutter/lib/src/widgets/binding.dart').
      data: MediaQueryData.fromWindow(WidgetsBinding.instance!.window),
`

**Comment by shareef-dweikat** [comment]
Same in my side

**Comment by Mounir-Bouaiche** [comment]
@shareef-dweikat @lyellss , Hello please use latest version, that was a breaking change from flutter itself.
