### ISSUE TITLE
Text in Ahem font is not scaled properly (results is failed widget tests)

### ISSUE THREAD

**Issue by mkranus** [OpenFlutter/flutter_screenutil#403]
During widget tests Flutter by default uses Ahem font for all texts. Since this font is not scaled properly, the tests fail due to overflow errors. Overriding the font to a normal font like OpenSans fixes this issue, but it is too heavy to load custom font before every test.

**Comment by Mounir-Bouaiche** [comment]
You should use FittedBox, Flexible, Expanded or other widgets recommanded by flutter team.
