### ISSUE TITLE
Keyboard not push up content/ resize screen

### ISSUE THREAD

**Issue by kzjn10** [OpenFlutter/flutter_screenutil#406]

**Comment by kzjn10** [comment]
After adding this lib when I focus on edit text, it shows the keyboard but does not push up content.

`flutter_screenutil: ^5.5.3+2
`

`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.3 21E230 darwin-arm, locale en-VN)
[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
`

**Comment by EnesKaraosman** [comment]
Yes, I confirm this issue as well, it's not happening in v5.0.0 so I downgraded.

**Comment by lizhuoyuan** [comment]
I ran the example and found that the textfield would like to be jacked up.

**Comment by Mounir-Bouaiche** [comment]
Please make sure you set useInheritedMediaQuery to false, in MaterialApp
