### ISSUE TITLE
不明白为什么要设置初始高度？还有`st.setHeight()`

### ISSUE THREAD

**Issue by sunwgit** [OpenFlutter/flutter_screenutil#41]
设计稿一般都是按照宽度来的，所以高度在这里起什么作用？求大佬解惑

**Comment by lizhuoyuan** [comment]
设置初始宽度, 是为了知道设计稿的尺寸 然后来适配尺寸.
一般情况下只有setWidth就可以了
setHeight 是为了在高度上满足等比例才需要用到的.

具体请看文档
