### ISSUE TITLE
Scaling issue in iPad Pro

### ISSUE THREAD

**Issue by ASHIR14** [OpenFlutter/flutter_screenutil#410]
I'm using this plugin in my app and everything is working fine in Android phone and tablet and in iphones. But there is a scaling/resizing issue in iPad (image attached). Any help is appreciated.
![WhatsApp Image 2022-06-23 at 5 50 10 PM](https://user-images.githubusercontent.com/58700119/175302836-33d2c485-1b56-4042-9459-1d9b0f487c49.jpeg)

**Comment by lizhuoyuan** [comment]
Please provide more information and where is the exception

**Comment by ASHIR14** [comment]
There is no exception or error. It just appears like this

**Comment by Mounir-Bouaiche** [comment]
> There is no exception or error. It just appears like this

Hello, please provide us some code, if you can, we'll appreciate it.

**Comment by ASHIR14** [comment]
`@override
  Widget build(BuildContext context) {
    return ScreenUtilInit(
      designSize: const Size(384, 812),
      minTextAdapt: true,
      splitScreenMode: true,
      builder: (BuildContext context, child) {
        return GetMaterialApp(
          title: 'title',
          theme: ThemeData(
            primarySwatch: Colors.blue,
          ),
          home: child,
        );
      },
      child: const HomeScreen(),
    );
  }`

**Comment by lizhuoyuan** [comment]
i am not sure , plz instead false of true for 'splitScreenMode'

**Comment by Lzyct** [comment]
> ![image](https://user-images.githubusercontent.com/58700119/179930056-061d707d-7820-4b7b-ad54-ddca54ab1a65.png)


You should define the size if the Device is a tablet or phone like this

![image](https://user-images.githubusercontent.com/1531684/188107344-96c88826-d42f-4fbd-8979-c6472a377258.png)
