### ISSUE TITLE
Value of setHeight is weird

### ISSUE THREAD

**Issue by excess4** [OpenFlutter/flutter_screenutil#412]
設計圖長寬是 414, 896
所以ScreenUtilInit 我填入designSize: Size(414, 896)

使用的手機寬高為 375, 667
setWidth(414) 會拿到375的數值 這部分是符合預期的
但setHeight(896) 卻會拿到 700 而非667

想詢問setHeight 的數值是否有誤？感謝

版本為 [5.5.3+2] 其他版本也有相同的狀況

**Comment by lizhuoyuan** [comment]
这可能需要你打印一下获取到的屏幕高度 确认一下

**Comment by excess4** [comment]
<img width="325" alt="截圖 2022-06-29 下午2 41 22" src="https://user-images.githubusercontent.com/63989952/176369432-76418144-1a55-4f19-8332-3fa4977d7474.png">

<img width="126" alt="截圖 2022-06-29 下午2 42 29" src="https://user-images.githubusercontent.com/63989952/176369473-4d410118-a6a7-440e-b8a4-5756dd43eb52.png">

**Comment by Mounir-Bouaiche** [comment]
> 
> <img width="325" alt="截圖 2022-06-29 下午2 41 22" src="https://user-images.githubusercontent.com/63989952/176369432-76418144-1a55-4f19-8332-3fa4977d7474.png">
> 
> <img width="126" alt="截圖 2022-06-29 下午2 42 29" src="https://user-images.githubusercontent.com/63989952/176369473-4d410118-a6a7-440e-b8a4-5756dd43eb52.png">
> 
> 

Hello, please share with us version you are using, and some code of how you initialized ScreenUtil, we'll appreciate it.

**Comment by excess4** [comment]
Hello Bouaiche:

The version that I'm using is [5.5.3+2]

I initialized ScreenUtil like this:

Widget build(BuildContext context) {
    return ScreenUtilInit(
      designSize: const Size(414, 896),
      minTextAdapt: true,
      splitScreenMode: true,
      builder: (BuildContext context, child) => GetMaterialApp(
   ...

**Comment by maxruby74** [comment]
Hi,
just set splitScreenMode to false.
As you can see in the following lines of code, with splitScreenMode the screen height is ignored when less than 700:
```
  ///  /// The ratio of actual height to UI design
  double get scaleHeight =>
      (_splitScreenMode ? max(screenHeight, 700) : screenHeight) /
      _uiSize.height; 
```
(from screen_util.dart, lines 169 to 172) 
[https://github.com/OpenFlutter/flutter_screenutil/blob/0818c1fd26a17c9690c24b6ca4a8686d963974ba/lib/src/screen_util.dart#L169](url)

**Comment by excess4** [comment]
Hi maxruby74:

Thanks for help, you save me a day.
