### ISSUE TITLE
横竖屏切换BUG

### ISSUE THREAD

**Issue by yixiu1043** [OpenFlutter/flutter_screenutil#414]
flutter_screenutil: ^5.2.0

操作步骤：
1. 先置为横屏
2. 横屏状态下跳转到下一个页面
3. 在第二个页面切为竖屏

期待的结果：
布局尺寸不会有问题

实际结果：
布局尺寸被放大了

```
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return ScreenUtilInit(
      designSize: const Size(375, 812),
      builder: () {
        ScreenUtil.setContext(context);
        return MaterialApp(
          title: 'Flutter Demo',
          theme: ThemeData(
            primarySwatch: Colors.blue,
          ),
          home: const MyHomePage(title: 'Flutter Demo Home Page'),
        );
      },
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Container(height: 20.w, color: Colors.red),
            const Text(
              'You have pushed the button this many times:',
            ),
            Container(height: 20.w, color: Colors.blue),
            Text(
              '0',
              style: Theme.of(context).textTheme.headline4,
            ),
            Container(height: 20.w, color: Colors.yellow),
            Icon(Icons.abc_outlined, size: 50.w),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          Navigator.push<void>(
            context,
            MaterialPageRoute<void>(
              builder: (BuildContext context) => const NextPage(),
            ),
          );
        },
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

class NextPage extends StatelessWidget {
  const NextPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('NextPage'),
      ),
      body: Column(
        children: [
          Container(height: 20.w, color: Colors.red),
          const Text('NextPage'),
          Container(height: 20.w, color: Colors.blue),
          Text(
            '0',
            style: Theme.of(context).textTheme.headline4,
          ),
          Container(height: 20.w, color: Colors.yellow),
          Icon(Icons.abc_outlined, size: 50.w),
        ],
      ),
    );
  }
}

```

**Comment by Mounir-Bouaiche** [comment]
Please use latest version.

**Comment by yjt1216** [comment]
version 5.3.0就可以了

**Comment by GreenPepperForPotato** [comment]
> flutter_screenutil: ^5.2.0
> 
> 操作步骤：
> 
> 1. 先置为横屏
> 2. 横屏状态下跳转到下一个页面
> 3. 在第二个页面切为竖屏
> 
> 期待的结果： 布局尺寸不会有问题
> 
> 实际结果： 布局尺寸被放大了
> 
> ```
> import 'package:flutter/material.dart';
> import 'package:flutter_screenutil/flutter_screenutil.dart';
> 
> void main() {
>   runApp(const MyApp());
> }
> 
> class MyApp extends StatelessWidget {
>   const MyApp({Key? key}) : super(key: key);
> 
>   // This widget is the root of your application.
>   @override
>   Widget build(BuildContext context) {
>     return ScreenUtilInit(
>       designSize: const Size(375, 812),
>       builder: () {
>         ScreenUtil.setContext(context);
>         return MaterialApp(
>           title: 'Flutter Demo',
>           theme: ThemeData(
>             primarySwatch: Colors.blue,
>           ),
>           home: const MyHomePage(title: 'Flutter Demo Home Page'),
>         );
>       },
>     );
>   }
> }
> 
> class MyHomePage extends StatefulWidget {
>   const MyHomePage({Key? key, required this.title}) : super(key: key);
>   final String title;
> 
>   @override
>   State<MyHomePage> createState() => _MyHomePageState();
> }
> 
> class _MyHomePageState extends State<MyHomePage> {
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: Text(widget.title),
>       ),
>       body: Center(
>         child: Column(
>           mainAxisAlignment: MainAxisAlignment.center,
>           children: <Widget>[
>             Container(height: 20.w, color: Colors.red),
>             const Text(
>               'You have pushed the button this many times:',
>             ),
>             Container(height: 20.w, color: Colors.blue),
>             Text(
>               '0',
>               style: Theme.of(context).textTheme.headline4,
>             ),
>             Container(height: 20.w, color: Colors.yellow),
>             Icon(Icons.abc_outlined, size: 50.w),
>           ],
>         ),
>       ),
>       floatingActionButton: FloatingActionButton(
>         onPressed: () {
>           Navigator.push<void>(
>             context,
>             MaterialPageRoute<void>(
>               builder: (BuildContext context) => const NextPage(),
>             ),
>           );
>         },
>         tooltip: 'Increment',
>         child: const Icon(Icons.add),
>       ),
>     );
>   }
> }
> 
> class NextPage extends StatelessWidget {
>   const NextPage({Key? key}) : super(key: key);
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: const Text('NextPage'),
>       ),
>       body: Column(
>         children: [
>           Container(height: 20.w, color: Colors.red),
>           const Text('NextPage'),
>           Container(height: 20.w, color: Colors.blue),
>           Text(
>             '0',
>             style: Theme.of(context).textTheme.headline4,
>           ),
>           Container(height: 20.w, color: Colors.yellow),
>           Icon(Icons.abc_outlined, size: 50.w),
>         ],
>       ),
>     );
>   }
> }
> ```



> version 5.3.0就可以了

一样的问题，升级上去也没用，example就可以看。调试看貌似是scaleWidth和scaleHeight计算有问题

**Comment by GreenPepperForPotato** [comment]
> flutter_screenutil: ^5.2.0
> 
> 操作步骤：
> 
> 1. 先置为横屏
> 2. 横屏状态下跳转到下一个页面
> 3. 在第二个页面切为竖屏
> 
> 期待的结果： 布局尺寸不会有问题
> 
> 实际结果： 布局尺寸被放大了
> 
> ```
> import 'package:flutter/material.dart';
> import 'package:flutter_screenutil/flutter_screenutil.dart';
> 
> void main() {
>   runApp(const MyApp());
> }
> 
> class MyApp extends StatelessWidget {
>   const MyApp({Key? key}) : super(key: key);
> 
>   // This widget is the root of your application.
>   @override
>   Widget build(BuildContext context) {
>     return ScreenUtilInit(
>       designSize: const Size(375, 812),
>       builder: () {
>         ScreenUtil.setContext(context);
>         return MaterialApp(
>           title: 'Flutter Demo',
>           theme: ThemeData(
>             primarySwatch: Colors.blue,
>           ),
>           home: const MyHomePage(title: 'Flutter Demo Home Page'),
>         );
>       },
>     );
>   }
> }
> 
> class MyHomePage extends StatefulWidget {
>   const MyHomePage({Key? key, required this.title}) : super(key: key);
>   final String title;
> 
>   @override
>   State<MyHomePage> createState() => _MyHomePageState();
> }
> 
> class _MyHomePageState extends State<MyHomePage> {
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: Text(widget.title),
>       ),
>       body: Center(
>         child: Column(
>           mainAxisAlignment: MainAxisAlignment.center,
>           children: <Widget>[
>             Container(height: 20.w, color: Colors.red),
>             const Text(
>               'You have pushed the button this many times:',
>             ),
>             Container(height: 20.w, color: Colors.blue),
>             Text(
>               '0',
>               style: Theme.of(context).textTheme.headline4,
>             ),
>             Container(height: 20.w, color: Colors.yellow),
>             Icon(Icons.abc_outlined, size: 50.w),
>           ],
>         ),
>       ),
>       floatingActionButton: FloatingActionButton(
>         onPressed: () {
>           Navigator.push<void>(
>             context,
>             MaterialPageRoute<void>(
>               builder: (BuildContext context) => const NextPage(),
>             ),
>           );
>         },
>         tooltip: 'Increment',
>         child: const Icon(Icons.add),
>       ),
>     );
>   }
> }
> 
> class NextPage extends StatelessWidget {
>   const NextPage({Key? key}) : super(key: key);
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: const Text('NextPage'),
>       ),
>       body: Column(
>         children: [
>           Container(height: 20.w, color: Colors.red),
>           const Text('NextPage'),
>           Container(height: 20.w, color: Colors.blue),
>           Text(
>             '0',
>             style: Theme.of(context).textTheme.headline4,
>           ),
>           Container(height: 20.w, color: Colors.yellow),
>           Icon(Icons.abc_outlined, size: 50.w),
>         ],
>       ),
>     );
>   }
> }
> ```

高版本也没有解决，这边改了下库里面代码处理好了，亲测有效
<img width="1223" alt="image" src="https://user-images.githubusercontent.com/13328957/186054520-8242373c-505b-4e78-809b-dc7fda92dd71.png">

**Comment by Mounir-Bouaiche** [comment]
@GreenPepperForPotato What version you are using ?

**Comment by wwtssu** [comment]
其实这个不是BUG，假设软件是为横屏设计的，designSize的宽高大小和竖屏本来就是反过来的。
同理，要解决横竖屏切换的问题，你只需要把ScreenUtilInit所谓的Widget Stateful化，在切换横屏的时将designSize的Size(375, 812)，改为Size(812, 375)，即可解决。

**Comment by GreenPepperForPotato** [comment]
> @GreenPepperForPotato What version you are using ?
I'm waiting for the flutter_screenutil team to update the fixed version. Before that, I used the fork library and fixed the problem myself in the library

**Comment by lizhuoyuan** [comment]
目前的最新版本, 我跑了一下, 看起来正常的 , 
先试一下新版, 如果还有问题 可以弄一个动图来看看吗? 
@yueyang8389  @GreenPepperForPotato

**Comment by longsirhero** [comment]
这个横竖屏切换问题还没弄好吗？
