### ISSUE TITLE
bug: 用了screenUtil之后，image.asset的属性 centerSlice不起作用了，去掉ScreenUtil恢复正常

### ISSUE THREAD

**Issue by lichengkun1** [OpenFlutter/flutter_screenutil#418]
bug: 用了screenUtil之后，image.asset的属性 centerSlice不起作用了，去掉ScreenUtil恢复正常

**Comment by Mounir-Bouaiche** [comment]
@lichengkun1 Please provide reproduction code, and attach your image.
