### ISSUE TITLE
高度适配问题

### ISSUE THREAD

**Issue by allencelee** [OpenFlutter/flutter_screenutil#42]
用ScreenUtil 设置高度  在iPhone6 上没问题  iPhone8P上高度不够  iphoneX上又超出了，按 iPhone6的尺寸初始化的  750*1334。请问这个问题怎么解决

**Comment by lizhuoyuan** [comment]
如果不强求高度满足一屏的话 ， 
建议都使用SetWidth来进行适配，
由于不知道你页面具体什么样子， 也考虑使用滚动组件做外层组件，

**Comment by lztbwlkj** [comment]
我也碰到了相同的问题
