### ISSUE TITLE
升级至最新版本后，字体变大，组件尺寸变大，暂时没有找到解决办法，求助！

### ISSUE THREAD

**Issue by FangPro** [OpenFlutter/flutter_screenutil#421]

**Comment by WxqKb** [comment]
+1，在windows上，第一次读取theme里面的字体，大小使用sp，读取不到。
重载运行后，正常。
![image](https://user-images.githubusercontent.com/48406291/184122303-cebbd2bd-648b-4810-bbd2-ed77d0667940.png)
![image](https://user-images.githubusercontent.com/48406291/184122363-526a6257-9785-4e2f-8f4a-0d8b1921345d.png)

**Comment by Mounir-Bouaiche** [comment]
Hi @FangPro We'll take a look very soon, but can you provide us some code ?

**Comment by FangPro** [comment]
抱歉，我解决了。之前的版本，我依据设计图是以px为准，现在只需要按照dp就能正常显示尺寸，非常感谢你的回应。
