### ISSUE TITLE
bug on 5.5.1 to 5.5.2 transition

### ISSUE THREAD

**Issue by Macacoazul01** [OpenFlutter/flutter_screenutil#423]
maybe this new `rebuildFactor property` added some problems on web.

Everytime I change my navigator's size, `ScreenUtilInit` widget rebuilds everything bellow it on the widget tree.

The problem is that it changes the firebase_auth stream, making every widget to rebuild:
https://github.com/firebase/flutterfire/issues/9451

**Comment by Mounir-Bouaiche** [comment]
@Macacoazul01 Please use latest version.

**Comment by Macacoazul01** [comment]
using `RebuildFactors.all` didn't solve the problem.
Setting false as return value helped:
```
return ScreenUtilInit(
      rebuildFactor: (o,n) => false,
```

Is there any setting that i can use to change `.w`, `.h`... dynamically with the navigator like what rebuildFactor does but without this "setState" behavior that rebuildFactor has?

**Comment by Macacoazul01** [comment]
> @Macacoazul01 Please use latest version.

it's present on 5.5.3+ and .4 too

**Comment by Lorenzobettega** [comment]
@Mounir-Bouaiche any update on this issue? I am having the same problem.

**Comment by Lorenzobettega** [comment]
@Mounir-Bouaiche any update on this issue? I am having the same problem.
