### ISSUE TITLE
set height not work as expected 

### ISSUE THREAD

**Issue by heshesh2010** [OpenFlutter/flutter_screenutil#424]
Hi , my screen size from adobe xd is 
 
designSize: Size(375, 812), 

when i set Container height to height: 250.w it works ok , but when i set it to 250.h i got stackoverflow error 
A RenderFlex overflowed by 10 pixels on the bottom.

**Comment by lizhuoyuan** [comment]
Generally speaking 250.h>250.w, if the size is not enough, there will be overflow
