### ISSUE TITLE
Different between 24.r vs 24.h or 24.w in portrait 

### ISSUE THREAD

**Issue by AbdalazizAbdallah** [OpenFlutter/flutter_screenutil#425]
Hi everyone ^_^

I have a misunderstanding about 24.r and different for others, and where I can use .r in my design?

BTW I use .r in all sizes in my design such as my draft (375,667) and declare Card width 330.r , height 178.r

so can you explain this, and I write true according to your package to get responsive design 

Thank in advance

**Comment by E-MRE** [comment]
@AbdalazizAbdallah 
Radius: .r
Height: .h
Width: .w
FontSize: .sp

This video will help to you. --> [Video](https://www.youtube.com/watch?v=LWteDQes4Kk)

**Comment by lizhuoyuan** [comment]
ScreenUtil().setWidth(540)  (dart sdk>=2.6 : 540.w) //Adapted to screen width
    ScreenUtil().setHeight(200) (dart sdk>=2.6 : 200.h) //Adapted to screen height , under normal circumstances, the height still uses x.w
    ScreenUtil().radius(200)    (dart sdk>=2.6 : 200.r)    //Adapt according to the smaller of width or height
    ScreenUtil().setSp(24)      (dart sdk>=2.6 : 24.sp) //Adapter font
