### ISSUE TITLE
Fixed display size not working for tablet and mobile screens

### ISSUE THREAD

**Issue by awaisjamil-vd** [OpenFlutter/flutter_screenutil#431]
return ScreenUtilInit(
                      designSize: const Size(768, 1024),
                      minTextAdapt: true,
                      splitScreenMode: true,
                      builder: (ctx, child) {});

**Comment by awaisjamil-vd** [comment]
I want app to work on both mobile and tablet screens
please guide

**Comment by lizhuoyuan** [comment]
try splitScreenMode = false
And confirm your design draft size

**Comment by panchalAlpit** [comment]
> I want app to work on both mobile and tablet screens please guide

How can you fix this issue?
