### ISSUE TITLE
 Error: Superclass has no constructor named 'SizedBox.square'.

### ISSUE THREAD

**Issue by lazy-xia** [OpenFlutter/flutter_screenutil#438]
../../../work/dev/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_screenutil-5.6.0/lib/src/r_sizedbox.dart:35:9: Error: Superclass has no constructor named 'SizedBox.square'.
        super.square(key: key, child: child, dimension: dimension);
        ^^^^^
        
环境如下
Flutter 2.2.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d79295af24 (1 year, 5 months ago) • 2021-06-11 08:56:01 -0700
Engine • revision 91c9fc8fe0
Tools • Dart 2.13.3

**Comment by lizhuoyuan** [comment]
你这应该是低版本flutter没有这个属性?
我这直接写 没有问题 
```
RSizedBox.square(dimension: 20),
```
