### ISSUE TITLE
Error: The getter 'setVerticalSpacing' isn't defined for the type 'int'. 

### ISSUE THREAD

**Issue by TheCIash** [OpenFlutter/flutter_screenutil#439]
Hello,
I am having the following error:

The getter 'setVerticalSpacing' isn't defined for the type 'int'.
Try importing the library that defines 'setVerticalSpacing', correcting the name to the name of an existing getter, or defining a getter or field named 'setVerticalSpacing'.

![image](https://user-images.githubusercontent.com/15365699/200559522-42f6608c-2117-4929-b0ab-beaa97d1b4a2.png)

**Comment by lizhuoyuan** [comment]
<img width="466" alt="image" src="https://user-images.githubusercontent.com/15923901/201257410-134e8b26-fcae-4a58-aae8-57713259ec6d.png">
