### ISSUE TITLE
有没有一个可以设置单一像素的方法，比如我想给Padding设个值

### ISSUE THREAD

**Issue by mx4g** [OpenFlutter/flutter_screenutil#44]
padding: EdgeInsetsDirectional.only(bottom: 10),

有没有一个可以设置单一像素的方法，类似setSp

**Comment by lizhuoyuan** [comment]
没太理解你的需求  
可能你是想问有的时候
![image](https://user-images.githubusercontent.com/15923901/60407962-6d045400-9bef-11e9-8438-1af3c4e16320.png)

EdgeInsets 里面不能使用 ScreenUtil ? 
这是因为有的地方需要参数是常量, 而ScreenUtil的计算的结果会根据手机不同而不同, 是一个变量, 所以无法使用 .

**Comment by mx4g** [comment]
不好意思没有表达清楚，EdgeInsets.all(10)，我不想上下左右都写。
像这种，这个10，我就不知道用setHeight还是setWidth

**Comment by lizhuoyuan** [comment]
用setWidth .
一般情况下都是根据宽度来适配的 , 只要能保证宽度不溢出就好了. 高度上一般都是随缘 , 超出了就用滚动组件嵌套. 一般很少出现刚好溢出.

而setHeight 就为了保证某些UI刚好想要满足一屏展示并且不想滚动的情况下来用的.

如果对UI的还原度不是极高, 也就是不用100%还原的情况下, 我认为全都可以使用setWidth.

**Comment by Jinxishihenian** [comment]
谢谢你建议，这很对我很有帮助，我将Padding替换为Container,可以使用
