### ISSUE TITLE
不知本package是否可达到这样的效果？

### ISSUE THREAD

**Issue by dbsxdbsx** [OpenFlutter/flutter_screenutil#442]
我希望写一个电视app，但同时也可以在windows上运行。  debug都是在windows上执行的。然后windows上，我也希望当确定好某一个layout后，当用鼠标等比例放大缩小它的同时也不影响layout（即只影响layout中的widgets的大小，但彼此的布局不变---即使把windows的“缩放与布局”从100%改为其他也不影响）。

**Comment by lizhuoyuan** [comment]
看你的描述 应该是可以

**Comment by dbsxdbsx** [comment]
> 看你的描述 应该是可以

ok，感谢回复。我先关了此issue。有问题再开。
