### ISSUE TITLE
Landscape size is not correct?

### ISSUE THREAD

**Issue by rajesh2701** [OpenFlutter/flutter_screenutil#444]
I ran a sample device width and height checking for **Portrait** and **Landscape** mode in build(BuildContext context) {} on Oneplus 6T device and here is the output. 

**PORTRAIT**
Device Height: 784.0
Device Width: 384.0

**LANDSCAPE**
Device Height: 384.0
Device Width: 755.5555555555555

Onscreen navigation buttons were turned on. How to calculate it?

**Comment by lizhuoyuan** [comment]
Will consider the height of the status bar
