### ISSUE TITLE
FlutterWindow? window,

### ISSUE THREAD

**Issue by hailuongsl97** [OpenFlutter/flutter_screenutil#449]
I have a problem related to flutter_screenutil
AppData/Local/Pub/Cache/hosted/pub.dev/flutter_screenutil-5.6.0/lib/src/screen_util.dart:58:5: Error: Type 'FlutterWindow' not found.
    FlutterWindow? window,
    ^^^^^^^^^^^^^
![image](https://user-images.githubusercontent.com/57215412/211459465-3b802b2d-8c59-452c-ad24-679b755cb786.png)
pls support for me!

**Comment by stralz** [comment]
Got an exact same error, please help.

**Comment by stralz** [comment]
I've found a fix, in my Dockerfile i replaced `flutter channel master` to `flutter channel stable`.

**Comment by hailuongsl97** [comment]
> I've found a fix, in my Dockerfile i replaced `flutter channel master` to `flutter channel stable`.
Oh it worked!
Thank you for your help

**Comment by lesslielee** [comment]
> I've found a fix, in my Dockerfile i replaced `flutter channel master` to `flutter channel stable`.
Thanks! @stralz 

I hit the same issue of 'FlutterWindow? window,' when I was in master channel 
[✓] Flutter (Channel master, 3.9.0-18.0.pre.2, on Microsoft Windows [版本 10.0.19044.2728], locale zh-CN)
And **FIXED** by switching back to stable channel
[✓] Flutter (Channel stable, 3.7.10, on Microsoft Windows [版本 10.0.19044.2728], locale zh-CN)

BTW,
though it reports issues from flutter doctor when using stable channel but flutter actually can build and run properly on Windows 10 zh-CN edition.  So I choose to simply ignore the flutter doctor reporting issue below.

"[✓] Flutter (Channel stable, 3.7.10, on Microsoft Windows [版本 10.0.19044.2728], locale zh-CN)
[✗] Windows Version (Unable to confirm if installed Windows version is 10 or greater)"
