### ISSUE TITLE
Maybe there is a misspelling in readme file.

### ISSUE THREAD

**Issue by lizihanglove** [OpenFlutter/flutter_screenutil#45]
//If you **_wang_** to set the font size is scaled according to the system's "font size" assist option
ScreenUtil.instance = ScreenUtil(width: 750, height: 1334, allowFontScaling: true)..init(context);

THANKS for all of you guys for convenience you brought to us!  here is a small problem: 
the comment of the code, the " **if you wang to**"   maybe is " if you want to ". I'm appreciated if someone can correct the misspelling.

**Comment by lizhuoyuan** [comment]
haha thank you .
