### ISSUE TITLE
Minimum text size on small devices

### ISSUE THREAD

**Issue by wamynobe** [OpenFlutter/flutter_screenutil#452]
Should we add `double get smx => max(toDouble(), sp);` to size extension and use it to get minimum size same as design size on some small devices(smaller than design size)? It's fine to write it in our own project extension but integrating it into the package is more awesome ^_^. Skip this if it doesn't make sense. Thanks.

**Comment by lizhuoyuan** [comment]
You are right, since there is "min", there should be "max".
