### ISSUE TITLE
flutter_boost混合开发模式 有问题

### ISSUE THREAD

**Issue by tang5011235** [OpenFlutter/flutter_screenutil#453]
是否考虑 通过原生获取屏幕的参数  不依赖 context

**Comment by lizhuoyuan** [comment]
混合开发其实完全可以这么做

**Comment by tang5011235** [comment]
因为 在fluter boost 启动的时候 会出现一个问题  ， 看了下flutter_boost的人员说  flutter 在启动的时候 会出现 第一次 通过context 获取屏幕的宽高  为0的问题 第二次会正常  但是 如果我使用 一些 static 静态配置 参数 会出现 问题

**Comment by lizhuoyuan** [comment]
确实会这样, 一开始context是无法取到屏幕数据的,这个flutter官方有提过.
最简单的是在build方法中init一下 你可以试一下看看效果

**Comment by tang5011235** [comment]
有效果 ，但是因为走多次 导致了context 的丢失 ，特别是一个界面是是listView  会出现 context 丢失问题

**Comment by tang5011235** [comment]
其实 想改造 这个插件  但是  有个疑问   window.devicePixelRatio  这个参数  不知道如何计算  android 上的density和这个有点不符合，请问有没有适配的思路

**Comment by lizhuoyuan** [comment]
> 其实 想改造 这个插件 但是 有个疑问 window.devicePixelRatio 这个参数 不知道如何计算 android 上的density和这个有点不符合，请问有没有适配的思路

这个参数可以直接代码获取到,原生和flutter都支持

**Comment by tang5011235** [comment]
做了一个插件 是基于 你的逻辑做的    可以适用于  android平台 和 iOS平台    https://pub.flutter-io.cn/packages/screen_adapter
