### ISSUE TITLE
使用该插件报错error G4127D1E8: The getter 'useInheritedMediaQuery' isn't defined for the class 'ScreenUtilInit Function()'

### ISSUE THREAD

**Issue by Sakura-1205** [OpenFlutter/flutter_screenutil#454]
/D:/%E5%AE%89%E8%A3%85/Flutter/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_screenutil-5.6.1/lib/src/screenutil_init.dart(72,16): error G4127D1E8: The getter 'useInheritedMediaQuery' isn't defined for the class 'ScreenUtilInit Function()'. [E:\Commissioning_app\fsu_tool\build\windows\flutter\flutter_assemble.vcxproj]

**Comment by lizhuoyuan** [comment]
放一下初始化代码

**Comment by Sakura-1205** [comment]
void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return ScreenUtilInit(
      designSize: const Size(1440, 3120),
      minTextAdapt: true,
      splitScreenMode: true,
      builder: ((context, child) {
        return MaterialApp(
          title: 'xxxx',
          theme: ThemeData(
              platform: Platform.isAndroid || Platform.isIOS ? TargetPlatform.iOS : null,
              scaffoldBackgroundColor: Colors.white),
          // initialRoute: '/',
          // routes: RouteConfiguration.routes,
          onGenerateRoute: RouteConfiguration.onGenerateRoute,
          debugShowCheckedModeBanner: false,
        );
      }),
    );
  }
}

**Comment by Sakura-1205** [comment]
![image](https://user-images.githubusercontent.com/74439194/217450288-bce829ce-5149-4eef-a8a8-843069e8dbe6.png)

**Comment by Sakura-1205** [comment]
Flutter SDK : 3.3.10
Dart Sdk : 2.18.6
flutter_screenutil: ^5.6.0

**Comment by Sakura-1205** [comment]
FAILURE: Build failed with an exception.

* Where:
Script 'D:\��װ\Flutter\Flutter\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1159

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'D:\��װ\Flutter\Flutter\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)


可能是这个错误导致的？我导入其它插件也报错误，这个有什么解决方法么

**Comment by lizhuoyuan** [comment]
没看到有用的日志啊
