### ISSUE TITLE
Meaning of setSp and .sp

### ISSUE THREAD

**Issue by AthreshK** [OpenFlutter/flutter_screenutil#456]
Hi ,
I was reading through the documentation and I felt it confusing to understand the difference between setSp() and .sp

I am new to using this package and I wanted to know what am I "setting" when I use the setSp(10) 

Is it just a getter for the adapted font size ?

Do I need to call it everytime when want the size if I have already used the initializer and set the canvas size and given MaterialApp in builder?

Is it different than 10.sp ?

Please help me understand

Thank you

**Comment by lizhuoyuan** [comment]
10.sp = setSp(10)
