### ISSUE TITLE
Version managment

### ISSUE THREAD

**Issue by mirland** [OpenFlutter/flutter_screenutil#457]
Hi, thanks for the plugin! 

Right now the library is not creating GitHub versions when a new version is released. So it's a bit hard to check what changed.

How can I compare the code between different versions?
Thanks!

**Comment by mirland** [comment]
Oh, I think you are using git tags, but some versions are missing (like the last one)

**Comment by lizhuoyuan** [comment]
Thank you for your reminder, it is really omissions, I will post it in each version but add tag
