### ISSUE TITLE
如何取消适配

### ISSUE THREAD

**Issue by joker-fu** [OpenFlutter/flutter_screenutil#459]
如题，在某些设备上不需要使用适配。没有找到相应的方法

**Comment by joker-fu** [comment]
我目前使用 MediaQuery.of(context).size 获取的尺寸作为设计图尺寸传入

**Comment by lizhuoyuan** [comment]
直接正常写你的ui数值就行了
比如适配的地方你会写 12.w, 不需要就直接写12

**Comment by xuxu5112** [comment]
包一下，需要适配的直接调用，不需要适配的，使用到的属性都 * 1。
