### ISSUE TITLE
Weird sizes returned when using setWidth / setHeight

### ISSUE THREAD

**Issue by hexdump2002** [OpenFlutter/flutter_screenutil#46]
Hi,

I am a first time user of your library, and there's something I should be doing wrong but I can't find out. I'm testing your lib with a simple app running in a pixel 2 virtual device (1920x1080). And this is how I init the lib as per the documentation:

ScreenUtil.instance = ScreenUtil(width:1080, height:1920, allowFontScaling: true)..init(context);

When I try to use setWidth for a value of 200 in this device it returns a value of 76.19 which is wrong. Looking at the source code I see how you do:

  setWidth(double width) => width * scaleWidth;

and scaleWidth is:

 get scaleWidth => _screenWidth / instance.width;

This is where things get weird. _screenWidth following mediaquery documentation is measured in Logical pixels but in the ScreenUtil constructor we must provide physical pixels. So the reason I get 76 instead of 200 (or a value close to it because I'm running on a device with the designed resolution) is because the scaleWith is calculated with 683.42/1080 , and it should be 1080/1080 = 1.

I know it must be me doing something I shouldn't because I don't see any bug opened about this problem. But there's no much to it. Could you help here?

Cheers.

**Comment by lizhuoyuan** [comment]
The unit of input is px, and the unit obtained is dp 。 
maybe it is right?
