### ISSUE TITLE
ensureScreenSize non-recursive version ?

### ISSUE THREAD

**Issue by dodatw** [OpenFlutter/flutter_screenutil#460]
I have same issue https://github.com/OpenFlutter/flutter_screenutil/issues/402
It seem have concern about recursive issue for stackoverflow.

Is it possiable provide ensureScreenSize non-recursive version ?

**Comment by lizhuoyuan** [comment]
Please try this first
<img width="545" alt="image" src="https://user-images.githubusercontent.com/15923901/224240467-02c18f04-6432-4cc1-971f-c7b1a620605a.png">
