### ISSUE TITLE
[flutter-web] In the newest flutter, it will cause flutter to show nothing

### ISSUE THREAD

**Issue by yingshaoxo** [OpenFlutter/flutter_screenutil#462]
Flutter 3.7.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 12cb4eb7a0 (3 days ago) • 2023-03-01 10:29:26 -0800
Engine • revision ada363ee93
Tools • Dart 2.19.3 • DevTools 2.20.1

___

`await ScreenUtil.ensureScreenSize();` will block the main process on web client.

**Comment by lizhuoyuan** [comment]
I'm not sure if this is the cause of the plugin,

**Comment by yingshaoxo** [comment]
Did you tried to create a web client project, and run the code to see if it
really blocks it?

```dart
import 'package:get/get.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();

  () async {
    await ScreenUtil.ensureScreenSize();

    runApp(GetMaterialApp(
      initialRoute: RoutesMap.login,
      getPages: [
        GetPage(
            name: RoutesMap.location_management,
            page: () => const LocationManagementHomePage()),
        GetPage(name: RoutesMap.login, page: () => const LoginPage()),
      ],
      theme: ThemeData(
        primarySwatch: Colors.blue,
        ),
      ),
    ));
  }();
}
```

**Comment by n0n1** [comment]
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/2964597/233331896-5f5fdda5-85fe-46ad-85cf-99c69ed1f2e3.png">

**Comment by n0n1** [comment]
<img width="922" alt="image" src="https://user-images.githubusercontent.com/2964597/233333197-0a68c25b-2462-450d-ae96-c883a1975565.png">

**Comment by n0n1** [comment]
https://docs.flutter.dev/release/breaking-changes/window-singleton

**Comment by dudodv** [comment]
any update?

**Comment by kashiflab** [comment]
did anyone find a solution? I'm stuck. I am using GoRoute, and need to check the size for web & mobile before passing routes in Material.route

**Comment by lizhuoyuan** [comment]
Can you provide a minimal example?

**Comment by sittingbool** [comment]
This is still an issue. The main function just stops here on web
