### ISSUE TITLE
Safearea pixels

### ISSUE THREAD

**Issue by ertugrulcakici** [OpenFlutter/flutter_screenutil#467]
On ios devices, we are not able to do fullscreen apps. Sometimes, I may need to use a safe area widget but library calculation does not care about safe area pixels. My expectation is when I wrap the page with the safe area, it should consider the rest of the page as full device pixel and it should resize everything depending on that.

**Comment by dudodv** [comment]
Any update?

**Comment by ertugrulcakici** [comment]
> Any update?

I wrote my own extension which i get safearea pixels and calculate itself
