### ISSUE TITLE
resizetoavoidbottominset true not working 

### ISSUE THREAD

**Issue by brahimkh** [OpenFlutter/flutter_screenutil#472]
My code:
![image](https://user-images.githubusercontent.com/87469140/234551212-fcd0b7ac-84af-458c-b814-e969f0c10646.png)

My an issue 
![Video_2023-04-26_174229](https://user-images.githubusercontent.com/87469140/234552390-2ebadea7-ce8b-47ab-a87d-459c07877fa6.gif)

**Comment by quangpc** [comment]
hi @brahimkh I have same issue. could you pls share how to fix it. Thank you!

**Comment by brahimkh** [comment]
Wrap ScreenUtilInit to top 
![Screenshot 2024-05-17 at 10 48 06 AM](https://github.com/OpenFlutter/flutter_screenutil/assets/87469140/fa134c81-06fa-4c1a-828c-9881ada1b19a)
