### ISSUE TITLE
Pushed pages recreates from a scratch instead of just resize

### ISSUE THREAD

**Issue by nadrolinux** [OpenFlutter/flutter_screenutil#473]
Hi,
When you push some page/widget on the navigation stack with:
`Navigator.of(context).push`
and manually resize a main window on the desktop you can see that a page/widget on the top of the stack is continiously recreated from a scratch (constructor is called instead of just build method like with LayoutBuilder). Both stateful and stateless widgets are affected. This is a serious bug, especially on the desktop, makes this really good lib totally useless on the desktop platforms, because all fields like a handles to a logic components are broken after a window resize. I attached quick example.
[main.txt](https://github.com/OpenFlutter/flutter_screenutil/files/11332671/main.txt)

BTW. At first glance it looks like this issue is related to a combination of flutter_screenutil + MaterialPageRoute, but I'm not 100% sure (I'm really new with Flutter). If yes, is it possible to solve this issue from a library level?
Best regards,

**Comment by lizhuoyuan** [comment]
I will test the effect on the desktop platform
