### ISSUE TITLE
unabe to build apk or run app, due to this please help

### ISSUE THREAD

**Issue by fisforfaheem** [OpenFlutter/flutter_screenutil#475]
![Uploading Screenshot 2023-05-12 at 1.27.26 PM.png…]()

**Comment by fisforfaheem** [comment]
<img width="1022" alt="Screenshot 2023-05-12 at 1 27 26 PM" src="https://github.com/OpenFlutter/flutter_screenutil/assets/35878088/2fa4dde1-004c-4d6d-b1f6-e1db2373d4c3">

**Comment by lowapple** [comment]
You can work around this with a temporary fix.
Just put in the version you're currently using, and build.
```yaml
dependency_overrides:
  flutter_screenutil: 5.6.0
```

**Comment by lizhuoyuan** [comment]
use 5.7
5.8 only support flutter 3.10

**Comment by fisforfaheem** [comment]
Thanks 🙏👍 working
