### ISSUE TITLE
The getter 'implicitView' isn't defined for the class 'PlatformDispatcher'.

### ISSUE THREAD

**Issue by Noor-Mahammad** [OpenFlutter/flutter_screenutil#478]
Launching lib/configs/main_qa.dart on iPhone SE (3rd generation) in debug mode...
Running Xcode build...
Xcode build done.                                           42.2s
Failed to build iOS app
Error (Xcode): ../../.pub-cache/hosted/pub.dev/flutter_screenutil-5.8.0/lib/src/screen_util.dart:62:59: Error: The getter 'implicitView' isn't defined for the class 'PlatformDispatcher'.

Could not build the application for the simulator.
Error launching application on iPhone SE (3rd generation).

**Comment by lizhuoyuan** [comment]
5.8.0 need flutter 3.10.0 
use 5.7.0 plz
