### ISSUE TITLE
 MediaQuery.of() called with a context that does not contain a MediaQuery.

### ISSUE THREAD

**Issue by chavesgu** [OpenFlutter/flutter_screenutil#48]
```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    ScreenUtil.instance = ScreenUtil(width: 750, height: 1334)..init(context);
    return MaterialApp();
  }
}
```

I don't think that it's necessary to use context,
you can get screen width like this,
```dart
import 'package:flutter/material.dart';
import 'dart:ui';

final num vh = MediaQueryData.fromWindow(window).size.height;
```

**Comment by lizhuoyuan** [comment]
Dart:ui can't get screen data in release mode in time .
But if you have a good way to welcome sharing

**Comment by chavesgu** [comment]
> Dart:ui can't get screen data in release mode in time .
> But if you have a good way to welcome sharing

I've tried, Dart:ui can get screen data in release mode，
Do you think it is async？

**Comment by chavesgu** [comment]
Here's my environment   
 • Flutter version 1.5.4-hotfix.2
• Framework revision 7a4c33425d (9 weeks ago), 2019-04-29 11:05:24 -0700
• Engine revision 52c7a1e849
• Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

**Comment by lizhuoyuan** [comment]
Maybe I should try again at 1.5.4, thank you for your suggestion.

**Comment by lizhuoyuan** [comment]
![image](https://user-images.githubusercontent.com/15923901/60642029-fe2e3180-9e60-11e9-9bb9-ecbd12c9a291.png)

I don't know why my test was good before.

But , I tested it a few times and found that it didn't work.

**Comment by chavesgu** [comment]
what's wrong?

**Comment by chavesgu** [comment]
![0E08BA9942731966DC5B6221F8A3E2B1](https://user-images.githubusercontent.com/20633606/60692547-1063aa80-9f09-11e9-8da1-94db6756d48e.jpg)

**Comment by lizhuoyuan** [comment]
Sometimes it works, but sometimes it doesn't work.Do you think there is a problem with the code above?

**Comment by chavesgu** [comment]
I think when your home page draw, window's width shouldn't be zero

**Comment by lizhuoyuan** [comment]
It seems that it is asynchronous, so I am not going to use this method for the time being.

**Comment by chavesgu** [comment]
But this method doesn't work at the root app class, it work at app's home class

**Comment by lizhuoyuan** [comment]
My phone is rooted and it works fine, I don't know what your problem is.

**Comment by chavesgu** [comment]
no other problem and you can try print width in root main method

**Comment by lizhuoyuan** [comment]
I guess what you mean is to get the screen data in MyApp? This is not possible, because it is initialized in the home, so the data can only be obtained after the initialization method in the home. If I am wrong, mostShow the code you want to implement

**Comment by chavesgu** [comment]
all right, use context config your plugin, It doesn't affect my use

**Comment by fluttercorner1** [comment]
Look at this article maybe helpfull for you
[Flutter Error: MediaQuery.of() called with a context that does not contain a MediaQuery](https://fluttercorner.com/flutter-error-mediaquery-of-called-with-a-context-that-does-not-contain-a-med/)
