### ISSUE TITLE
error (null)

### ISSUE THREAD

**Issue by mazab99** [OpenFlutter/flutter_screenutil#482]
this is line 40 

SizedBox(height: 70.h)

When the exception was thrown, this was the stack: 
#0      Element.widget (package:flutter/src/widgets/framework.dart:3361:31)
#1      debugCheckHasMediaQuery.<anonymous closure> (package:flutter/src/widgets/debug.dart:296:17)
#2      debugCheckHasMediaQuery (package:flutter/src/widgets/debug.dart:311:4)
#3      MediaQuery._of (package:flutter/src/widgets/media_query.dart:1017:12)
#4      MediaQuery.of (package:flutter/src/widgets/media_query.dart:1013:12)
#5      ScreenUtil.screenHeight (package:flutter_screenutil/src/screen_util.dart:157:37)
#6      ScreenUtil.scaleHeight (package:flutter_screenutil/src/screen_util.dart:175:52)
#7      ScreenUtil.setHeight (package:flutter_screenutil/src/screen_util.dart:196:44)
#8      SizeExtension.h (package:flutter_screenutil/src/size_extension.dart:12:32)
#9      HomeScreen.build.<anonymous closure>

 (/src//home_screen.dart:40:41)

**Comment by lizhuoyuan** [comment]
Can you provide reproducible code
