### ISSUE TITLE
useInheritedMediaQuery default value is error of  false

### ISSUE THREAD

**Issue by CheckThird** [OpenFlutter/flutter_screenutil#486]
case version 5.8.3,the useInheritedMediaQuery  default is fasle
![image](https://github.com/OpenFlutter/flutter_screenutil/assets/31229845/53f1b8aa-110e-44f0-977a-08a36585a098)
![image](https://github.com/OpenFlutter/flutter_screenutil/assets/31229845/02f992b3-b204-4f3a-95cc-9543be18d2e5)

**Comment by naivetoby** [comment]
> Foolish, I wasted two days adjusting this, and this attribute is not displayed in Chinese documents, only in English documents

change useInheritedMediaQuery default value to false after 5.8.3

https://github.com/OpenFlutter/flutter_screenutil/pull/485
