### ISSUE TITLE
Web 初始化的时候 await ScreenUtil.ensureScreenSize(); 会一直递归

### ISSUE THREAD

**Issue by YOrange834** [OpenFlutter/flutter_screenutil#488]
void main() async {
  // Add this line
  await ScreenUtil.ensureScreenSize();
  runApp(MyApp());
}

如果是Web的话他会一直递归
static Future<void> ensureScreenSize([
    FlutterView? window,
    Duration duration = const Duration(milliseconds: 10),
  ]) async {
    final binding = WidgetsFlutterBinding.ensureInitialized();
    window ??= binding.window;

    if (window.physicalGeometry.isEmpty) {
      return Future.delayed(duration, () async {
        binding.deferFirstFrame();
        await ensureScreenSize(window, duration);
        return binding.allowFirstFrame();
      });
    }
  }

**Comment by YOrange834** [comment]
还是有影响，首次安装app的时候可以获取到尺寸，但是二次打开的时候获取不到尺寸

**Comment by YOrange834** [comment]
Web是正常的，安卓端会出现这个问题， iOS还没有测试

**Comment by lizhuoyuan** [comment]
不应当啊 , 我示例运行了好多次 没发现这个问题
