### ISSUE TITLE
简化的建议

### ISSUE THREAD

**Issue by yn-tadpole** [OpenFlutter/flutter_screenutil#49]
有两个问题：
1.需要用一个BuildContext去做初始化，这样无法在initState等方法中调用，而有时初始化动画参数必然需要在initState中使用。
2.调用语法太长，不太优雅。

建议：
代码如下
class ScreenUtils {
  static double get screenWidth => window.physicalSize.width / window.devicePixelRatio;
  static double get screenHeight => window.physicalSize.height / window.devicePixelRatio;

  ///单位换算，750总是等于屏幕宽度
  static double upx(double num) {
    return num/750.0*screenWidth;
  }
}

double upx(double num) {
  return ScreenUtils .upx(num);
}

任何需要调用的地方只需
upx(xxx)
upx(750) 总是会等于屏幕宽度

**Comment by lizhuoyuan** [comment]
关于window这个东西 
在release没模式下
拿到窗口数据的时间是未知的.
利用context去获取的话是肯定有数据的
我的测试结果是这样
 下图为示例.

如果有什么方法可以不需要context一样能拿到数据的话, 求指点 
![image](https://user-images.githubusercontent.com/15923901/61263379-36b40080-a7bb-11e9-8c76-661691305056.png)
![image](https://user-images.githubusercontent.com/15923901/61263385-39165a80-a7bb-11e9-968c-5756abe90fab.png)

**Comment by OHeroJ** [comment]
在混合情况下，都需要初始化这个单例是否太过麻烦

**Comment by lizhuoyuan** [comment]
@OHeroJ  毫无疑问是的.
所以我想自己写一个继承state的组件 , 然后把初始化封装进去会不会稍微好一点

**Comment by lizhuoyuan** [comment]
@yn-tadpole  

反正现在利用context是肯定能正确拿到屏幕数据的,虽然它也是用的window的数据.
所以就只能这样了 
还没有找到更好的方式

**Comment by yn-tadpole** [comment]
不是利用context拿到正确的数据，是因为不是在程序一启动就获取相应的值，或者build方法执行时间靠后，碰巧而已。
下面才是有效的临时处理方式，让程序等一下，200ms后再执行。
```
void main () {
    Future.delayed(Duration(milliseconds: 200)).then((val) {
        runApp(MyApp());
      }, onError: (error) {});
    }
}
```

**Comment by lizhuoyuan** [comment]
为什么是200ms不是100ms？
谁都不知道具体多久能拿到屏幕数据
万一我10ms就拿到了还要多等190ms？
不要意识流吧

反正 利用context去拿数据是没问题的
你喜欢用你的方式也ok

**Comment by doudouaixiaoyu** [comment]
不建议用windows 这种方式获取屏幕大小，发布为release时，启动太快，导致为0
