### ISSUE TITLE
flutter SDK 3.0.5 ,flutter_screenutil: ^5.5.2,

### ISSUE THREAD

**Issue by litingios** [OpenFlutter/flutter_screenutil#490]
import 'package:flutter_screenutil/flutter_screenutil.dart';

<img width="1171" alt="image" src="https://github.com/OpenFlutter/flutter_screenutil/assets/44352741/6b401636-018c-49d0-b583-7e9eb78e3e73">

**Comment by lizhuoyuan** [comment]
use flutter_screenutil: 5.5.2
remove ^
