### ISSUE TITLE
Keyboard is closed immediately when trying to write inside dialog

### ISSUE THREAD

**Issue by Khawlah-Mohammed** [OpenFlutter/flutter_screenutil#494]
I have some TextFormField inside dialog .. while trying to write on them the keyboard is shown and closed immediately.

**Comment by Khawlah-Mohammed** [comment]
Sorry, it is an issue with something els.

**Comment by 842787863** [comment]
> 对不起，这是某些东西的问题。
Can you tell me what went wrong? I had the same problem, you know? thank you

**Comment by 842787863** [comment]
> Sorry, it is an issue with something els.

Can you tell me what went wrong? I had the same problem, you know? thank you

**Comment by Heilum** [comment]
It's a bug, the following code can reproduce the bug:
`import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return ScreenUtilInit(
        designSize: const Size(375, 812),
        minTextAdapt: true,
        splitScreenMode: true,
        useInheritedMediaQuery: true,
        builder: (context, child) => MaterialApp(
              title: 'Flutter Demo',
              theme: ThemeData(
                // This is the theme of your application.
                //
                // TRY THIS: Try running your application with "flutter run". You'll see
                // the application has a blue toolbar. Then, without quitting the app,
                // try changing the seedColor in the colorScheme below to Colors.green
                // and then invoke "hot reload" (save your changes or press the "hot
                // reload" button in a Flutter-supported IDE, or press "r" if you used
                // the command line to start the app).
                //
                // Notice that the counter didn't reset back to zero; the application
                // state is not lost during the reload. To reset the state, use hot
                // restart instead.
                //
                // This works for code too, not just values: Most code changes can be
                // tested with just a hot reload.
                colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
                useMaterial3: true,
              ),
              home: const MyHomePage(title: 'Flutter Demo Home Page'),
            ));
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // TRY THIS: Try changing the color here to a specific color (to
        // Colors.amber, perhaps?) and trigger a hot reload to see the AppBar
        // change color while the other colors stay the same.
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          //
          // TRY THIS: Invoke "debug painting" (choose the "Toggle Debug Paint"
          // action in the IDE, or press "p" in the console), to see the
          // wireframe for each widget.
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          showAddLinkDialog(context);
        },
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }

  Future<void> showAddLinkDialog(BuildContext context) async {
    await showDialog(
        context: context,
        builder: (context) {
          final _formKey = GlobalKey<FormState>();
          final _linkController = TextEditingController();
          final _titleController = TextEditingController();

          _linkController.addListener(() {
            setState(() {});
          });

          _titleController.addListener(() {
            setState(() {});
          });

          return StatefulBuilder(builder: (context, setState) {
            return AlertDialog(
              title: Text("Add a link / attachment"),
              content: Form(
                key: _formKey,
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    TextFormField(
                      validator: (value) {
                        if (value == null || value.isEmpty) {
                          return "Please enter the title";
                        }
                        return null;
                      },
                      controller: _titleController,
                      decoration: const InputDecoration(labelText: 'title'),
                    ),
                    SizedBox(height: 8),
                    Row(
                      children: [
                        Expanded(
                          child: TextFormField(
                            validator: (value) {
                              if (value == null || value.isEmpty) {
                                return "Please enter the link";
                              }
                              return null;
                            },
                            controller: _linkController,
                            decoration:
                                const InputDecoration(labelText: 'link'),
                          ),
                        ),
                        IconButton(
                            onPressed: () {
                              setState(() {});
                            },
                            icon: Icon(Icons.add_circle_outline))
                      ],
                    ),
                  ],
                ),
              ),
              actions: [
                TextButton(
                  onPressed: () {
                    Navigator.pop(context);
                  },
                  child: const Text("Cancel"),
                ),
                TextButton(
                    onPressed: (_linkController.text.isNotEmpty &&
                            _titleController.text.isNotEmpty)
                        ? () {
                            Navigator.pop(context);
                          }
                        : null,
                    child: const Text("Add")),
              ],
            );
          });
        });
  }
}
`

**Comment by Heilum** [comment]
@842787863 ,just define your FormKey/TextEditingController outside, not inside the closure!

**Comment by Khawlah-Mohammed** [comment]
Thanks, I have done that and it solved the problem.

**Comment by 842787863** [comment]
@Heilum Thanks! I solved this problem after replacing MediaQuery with LayoutBuilder, TextEditing is not refreshing other widgets

**Comment by janek515** [comment]
> @842787863 ,just define your FormKey/TextEditingController outside, not inside the closure!

Hi! Could you give me a small example of what you're trying to explain? I'm trying to tackle the same problem and don't know what to do. Also, I'm using TextEditingController through flutter_hooks.

Thanks in advance!

**Comment by 842787863** [comment]
@janek515 Hi, flutter_screenutil uses MediaQuery to get the screen size, using MediaQuery will refresh the widget when the screen size changes, this problem causes the keyboard to refresh the widget when it pops up, I use LayoutBuilder to get the screen size instead to solve this problem, also I haven't used flutter_hooks, I can't give you advice sorry

**Comment by janek515** [comment]
@842787863 Hi, thanks for your answer, I was able to figure it out, the solution in my case was here https://github.com/OpenFlutter/flutter_screenutil/issues/484#issuecomment-1590254340
