### ISSUE TITLE
Keyboard opening triggers the rebuild of whole MaterialApp starting from Flutter 3.10.0

### ISSUE THREAD

**Issue by vovaklh** [OpenFlutter/flutter_screenutil#496]
So, when I open keyboard on my page, the whole MaterialApp is rebuilded

**Comment by hhuseyinpay** [comment]
if anyone faces this issue, this is related to [flutter](https://github.com/flutter/flutter/issues/105184)

**Comment by Hvt261** [comment]
@vovaklh  How did you close this bug ? Please help me.

**Comment by AnasAthimannil** [comment]
- **Find a solution for it**
**- Solution 1**
- Remove MediaQuery.of(context).size and use LayoutBuilder contstraint to get height and width
 **Solution 2** 
- Use any of state management library, if you are using Getx library use Get.Height, Get.Width to get screen size
