### ISSUE TITLE
when using getx show this error - "Null check operator used on a null value" in latest version of flutter_screenutil: ^5.8.4 but perfectly work in version :^5.7.0 

### ISSUE THREAD

**Issue by pragneshpalsanabitcoding** [OpenFlutter/flutter_screenutil#499]
======== Exception caught by widgets library =======================================================
The following _TypeError was thrown building Obx(has builder, dirty, state: _ObxState#74ed7):
Null check operator used on a null value

The relevant error-causing widget was: 
  Obx Obx:file:///Users/mac/StudioProjects/lib/app/ui/home_screen/bottom_bar.dart:37:18
When the exception was thrown, this was the stack: 
#0      Element.widget (package:flutter/src/widgets/framework.dart:3361:31)
#1      debugCheckHasMediaQuery.<anonymous closure> (package:flutter/src/widgets/debug.dart:296:17)
#2      debugCheckHasMediaQuery (package:flutter/src/widgets/debug.dart:311:4)
#3      MediaQuery._of (package:flutter/src/widgets/media_query.dart:1017:12)
#4      MediaQuery.of (package:flutter/src/widgets/media_query.dart:1013:12)
#5      ScreenUtil.screenWidth (package:flutter_screenutil/src/screen_util.dart:148:37)
#6      ScreenUtil.scaleWidth (package:flutter_screenutil/src/screen_util.dart:167:28)
#7      ScreenUtil.setWidth (package:flutter_screenutil/src/screen_util.dart:182:41)
#8      SizeExtension.w (package:flutter_screenutil/src/size_extension.dart:9:32)
#9      _BottomBarScreenState.build.<anonymous closure>.<anonymous closure> (package:app/ui/home_screen/bottom_bar.dart:58:48)
#10     Obx.build (package:get/get_state_manager/src/rx_flutter/rx_obx_widget.dart:70:28)
#11     RxInterface.notifyChildren (package:get/get_rx/src/rx_types/rx_core/rx_interface.dart:26:27)
#12     _ObxState.build (package:get/get_state_manager/src/rx_flutter/rx_obx_widget.dart:54:19)
#13     StatefulElement.build (package:flutter/src/widgets/framework.dart:5198:27)
#14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5086:15)
#15     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#17     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2780:19)
#18     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:903:21)
#19     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358:5)
#20     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284:15)
#21     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1214:9)
#22     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1072:5)
#23     _invoke (dart:ui/hooks.dart:142:13)
#24     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359:5)
#25     _drawFrame (dart:ui/hooks.dart:112:31)
====================================================================================================

**Comment by xweng1016** [comment]
same issue here, using GetX and Getbuilder to update state

**Comment by lizhuoyuan** [comment]
It seems that the context at this time is null
