### ISSUE TITLE
对于各种类型的尺寸不是那么完美.

### ISSUE THREAD

**Issue by pheromone** [OpenFlutter/flutter_screenutil#50]
比如:设置i6为标椎,设置位置,长度,有时候在不同机型上显示位置不太一样.
![image](https://user-images.githubusercontent.com/14305431/61943454-00059380-afce-11e9-98c9-b8636ede7a70.png)
                        width: ScreenUtil().setWidth(680.0),

**Comment by lizhuoyuan** [comment]
如果你的设计稿是750宽度的, 你设置了680 , 那么在宽度为750(比如i6)的屏幕上就680的宽度
在1500宽度的屏幕上会变成1360 .
在不同的屏幕会进行放大/缩小,
以保证整体的比例更加协调.
你的问题我希望看到更多的代码以及想要的效果(或者直接上设计稿)

**Comment by pheromone** [comment]
比如说:
我的设计尺寸是750 * 1334
![image](https://user-images.githubusercontent.com/14305431/61987953-be1c3200-b04d-11e9-9d34-1f54a7e71707.png)
UI设计图效果:
![image](https://user-images.githubusercontent.com/14305431/61987976-1ce1ab80-b04e-11e9-85ef-a53806237692.png)
下方的联想widget明显iOS和Android位置不太一样.
![image](https://user-images.githubusercontent.com/14305431/61987999-7518ad80-b04e-11e9-9191-f9e292a85eb2.png)

**Comment by lizhuoyuan** [comment]
不使用绝对布局 ， 或者top和left不适用Screnutil看一下效果？
