### ISSUE TITLE
After adjusting the display size in Android settings, the App UI does not change.

### ISSUE THREAD

**Issue by rex26** [OpenFlutter/flutter_screenutil#500]
We have customers who want to enlarge the UI of the app. 
They try to adjust it via Display Size in Android settings. 
But after the adjustment, the App using flutter_screenutil will not change.

Can you tell me why?
I don't know if there is any setting that can make the customer's setting take effect.

**Comment by lizhuoyuan** [comment]
Do you want to enlarge the font? Is it set in the code that the font does not follow the system change?

**Comment by Mounir-Bouaiche** [comment]
We accept only issues with minimal reproducable code. Many problems are not related to this library.
