### ISSUE TITLE
Field '_instance@968075166' has not been

### ISSUE THREAD

**Issue by lynnscode** [OpenFlutter/flutter_screenutil#501]
The following LateError was thrown:
    LateInitializationError: Field '_instance@968075166' has not been
    initialized.
    
    When the exception was thrown, this was the stack:
    #0      ScreenUtil._instance (package:flutter_screenutil/screen_util.dart)
    #1      new ScreenUtil (package:flutter_screenutil/screen_util.dart:26:12)
    #2      SizeExtension.h (package:flutter_screenutil/size_extension.dart:8:19)
    #3      _DLLoginPageState.buildLogoInfo

flutter_screenutil 5.1.0

**Comment by Mounir-Bouaiche** [comment]
@lynnscode It may have been fixed in next releases, please consider upgrade to latest.
