### ISSUE TITLE
[Bug] Re-build layout error when keyboard appear 

### ISSUE THREAD

**Issue by VinhNguyenTruong** [OpenFlutter/flutter_screenutil#504]
Hi team.
i find bug when re-layout chat feature 

https://github.com/OpenFlutter/flutter_screenutil/assets/118323545/a644bac5-17e1-4ad0-8707-5a64c57764ad

**Comment by abdullah432** [comment]
Same Issue

**Comment by Mounir-Bouaiche** [comment]
@VinhNguyenTruong, @abdullah432 You need to provide code to reproduce the bug. We aren't able to reproduce this issue. Will be closed after 2 days if no code is there.

**Comment by jack24254029** [comment]
try this.
https://github.com/OpenFlutter/flutter_screenutil/issues/495#issuecomment-1598513177
