### ISSUE TITLE
scaleByHeight make screen rebuild when there is a horizontal scroll listview

### ISSUE THREAD

**Issue by ChauCM** [OpenFlutter/flutter_screenutil#505]
When there is a listview like this, inside a vertical listview, and scaleByHeight = true.

Scroll up and down is very junk and slow

<img width="774" alt="image" src="https://github.com/OpenFlutter/flutter_screenutil/assets/86839861/5dff114f-05f3-4703-9152-8f0dbf2ec6b2">

**Comment by Mounir-Bouaiche** [comment]
I believe scaleByHeight doesn't have any effect in recent release.
