### ISSUE TITLE
Keyboard is not open on textfield (I am using this package with GoRouter)

### ISSUE THREAD

**Issue by anilflutter** [OpenFlutter/flutter_screenutil#506]
this package sued with GoRouter then I am getting issue while type on textfield. Keyboard doesn't open .

this issue is occurred if  TextEditingController without static or global key without static as below given:

 // this code give the error
 final GlobalKey<FormState> _formKey = GlobalKey<FormState>();
 final TextEditingController mobileController = TextEditingController();

// solved error after add static, but this is not the good solution
  static final GlobalKey<FormState> _formKey = GlobalKey<FormState>();
  static final TextEditingController mobileController = TextEditingController();

**Comment by Mounir-Bouaiche** [comment]
@anilflutter make sure you are not building routes inside ScreenUtilInit scope

**Comment by anilflutter** [comment]
But ScreenUtil is the parent widget above the MaterialApp. And GoRouter used with Materialapp as MaterialApp.GoRouter().

ScreenUtilInit(
          designSize: const Size(430, 932),
          builder: (BuildContext context, Widget? child) {
            return MaterialApp.router(
              debugShowCheckedModeBanner: false,
              theme: AppTheme.appThemeData(context),
              builder: EasyLoading.init(),
              routeInformationProvider: Routes.onRouter.routeInformationProvider,
              routeInformationParser: Routes.onRouter.routeInformationParser,
              routerDelegate: Routes.onRouter.routerDelegate,
            );
          },
        )

**Comment by anilflutter** [comment]
The issue is resolved after moving theme out of screen until scope
ScreenUtilInit(
        designSize: const Size(430, 932),
        builder: (BuildContext context, Widget? child) {
          return child!;
        },
        child: const MaterialRoute(),
      ),

**Comment by abdullah432** [comment]
> child

After applying your solution, I'm now getting this error 
```
Another exception was thrown: LateInitializationError: Field '_minTextAdapt@3085084504' has not been
initialized.
```

**Comment by anilgsharma900** [comment]
Using this solution, I am not getting any error and not even warning

ScreenUtilInit(
designSize: const Size(430, 932),
builder: (BuildContext context, Widget? child) {
return child!;
},
child: const MaterialRoute(),
),

**Comment by anilgsharma900** [comment]
> 

Can you share the code where are you getting error?

**Comment by aditya-bajpai-gh** [comment]
is anyone resolved this error?
