### ISSUE TITLE
适配问题

### ISSUE THREAD

**Issue by lztbwlkj** [OpenFlutter/flutter_screenutil#51]
优化前
<img width="355" alt="WechatIMG4368" src="https://user-images.githubusercontent.com/20568661/61952713-2b48ac80-afe7-11e9-89e3-62737f9c6e29.png">
优化后<img width="355" alt="WechatIMG4370" src="https://user-images.githubusercontent.com/20568661/61952693-1a983680-afe7-11e9-9e76-20465050793c.png">

**Comment by lizhuoyuan** [comment]
你想要的效果是啥呢？

**Comment by lztbwlkj** [comment]
我想要第二种效果，这是我的使用代码，麻烦看一下是哪里不对

[screenutil.txt](https://github.com/OpenFlutter/flutter_screenutil/files/3438376/screenutil.txt)
