### ISSUE TITLE
Coflicts with routemaster package

### ISSUE THREAD

**Issue by erimeilis** [OpenFlutter/flutter_screenutil#511]
Any time i resize window, route fall back to home. I guess, it just rebuild the whole page on resize, not particular widgets.

**Comment by Mounir-Bouaiche** [comment]
@erimeilis You must provide code. Also, see previous solved issues about using routing packages, like Getx or GoRouter.
Note: Never call a function inside ScreenUtilInit block/context, and never use builder, unless it depends on the library (ex: theme).
