### ISSUE TITLE
Widget tree rebuild when keyboard show

### ISSUE THREAD

**Issue by Hvt261** [OpenFlutter/flutter_screenutil#512]
I used screenUtil from old version to current version (5.9.0)
When keyboard show, widget tree was rebuild.
When I remove SreenUtil lib, it worked normally.

Flutter 3.10.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 796c8ef792 (2 months ago) • 2023-06-13 15:51:02 -0700
Engine • revision 45f6e00911
Tools • Dart 3.0.5 • DevTools 2.23.1

**Comment by Mounir-Bouaiche** [comment]
@Hvt261 Not the widget tree, but the widgets you declared see README.md file. We're listening to MediaQuery changes, so rebuilds on screen changes depends on core MediaQuery functionnality. Some improvements are planned by the end of Sep, but it will be a minor version.

**Comment by Hvt261** [comment]
@Mounir-Bouaiche I removed all sources which have MediaQuery but error still happen
I wrap ScreenUtilInit out of MaterialApp.

**Comment by Mounir-Bouaiche** [comment]
> @Mounir-Bouaiche I removed all sources which have MediaQuery but error still happen I wrap ScreenUtilInit out of MaterialApp.

The libarary uses MediaQuery, not you. You can't change this behaivior, it's a core functionnality. If you have better options that MediaQuery we can suggest that.

**Comment by AsadMoulviDev** [comment]
Hello, my app crashes every time i open the keyboard, I removed ScreenUtilInit and it solved the problem. I think the way I used ScreenUtilInit is wrong please help.

`class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ScreenUtilInit(
      useInheritedMediaQuery: true ,
      designSize: const Size(390, 844), // Set your design size here
      builder: (_ , child) {
        return MultiProvider(
          providers: [
            ChangeNotifierProvider(create: (context) => UserModel()),
            ChangeNotifierProvider(create: (context) => EmailProvider()),
            ChangeNotifierProvider(create: (context) => QuestionProvider()),
            ChangeNotifierProvider(create: (context) => QuizSessionsProvider()),
            ChangeNotifierProvider(create: (context) => AnalyticsProvider()),
            ChangeNotifierProvider(create: (context) => DailyQuestionStreakProvider()),
            ChangeNotifierProvider(create: (context) => GameProvider()),
            ChangeNotifierProvider(create: (context) => IconSelectionProvider())
          ],
          child: MaterialApp.router(
            theme: ThemeData(
              scaffoldBackgroundColor: const Color(0xFF333863),
              textTheme: GoogleFonts.nunitoTextTheme(Theme.of(context).textTheme),
              bottomNavigationBarTheme: BottomNavigationBarThemeData(
                backgroundColor: AppColors.bg_color,
                selectedItemColor: Colors.white,
                unselectedItemColor: Colors.grey,
              ),
            ),
            debugShowCheckedModeBanner: true,
            routerConfig: AppRouter.createRouter(),
          ),
        );
      },
    );
  }
}`

**Comment by fuadreza** [comment]
Yeah this also happen to me

**Comment by WeicongLi124** [comment]
There is also a problem with mine. When using 5.9.0, the keyboard will pop up and push the entire page up

**Comment by WeicongLi124** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by fisforfaheem** [comment]
I am having same issues on forms when keybaord opens all text gone

**Comment by xalikoutis** [comment]
try solution from this comment
https://github.com/OpenFlutter/flutter_screenutil/issues/495#issuecomment-1598513177

**Comment by WeicongLi124** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by abdullah432** [comment]
I'm getting same issue

**Comment by fisforfaheem** [comment]
Will this be Fixed? Or shall use something else

**Comment by aman246149** [comment]
> try solution from this comment [#495 (comment)](https://github.com/OpenFlutter/flutter_screenutil/issues/495#issuecomment-1598513177)

Thanks it work for me

**Comment by WeicongLi124** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by WeicongLi124** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by WeicongLi124** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by fisforfaheem** [comment]
Reply

**Comment by WeicongLi124** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by WeicongLi124** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by WeicongLi124** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
