### ISSUE TITLE
.sp and .r not working problem?

### ISSUE THREAD

**Issue by muhammetsalci** [OpenFlutter/flutter_screenutil#518]
Hello, in flutter version 3.12.2, the parts where I use .sp and .r in screenutil do not appear when I get the release apk.

**Comment by a-ibrkh** [comment]
Hi, I have the same issue, flutter version 3.13.6, flutter_screenutil version 5.9.0, decoration and texts are not visible in release mode

**Comment by a-ibrkh** [comment]
downgrading  flutter_screenutil to 5.8.4 did not help

**Comment by AliSabbar** [comment]
Hi, I have the same problem. Is there any solution?

**Comment by DexEze** [comment]
None of my .sp seem to be working correctly in 5.9.0

The scaling seems to be way too big. Rolling back to 5.8.4 fixed the issue for me.
