### ISSUE TITLE
The method '/' was called on null.

### ISSUE THREAD

**Issue by alylhb** [OpenFlutter/flutter_screenutil#52]
![image](https://user-images.githubusercontent.com/38207968/62351690-d9e57380-b538-11e9-89c6-0526352583da.png)
![image](https://user-images.githubusercontent.com/38207968/62351696-e2d64500-b538-11e9-8145-8345cab19472.png)

**Comment by lizhuoyuan** [comment]
有初始化吗?

**Comment by alylhb** [comment]
额, 没有, 怎么初始化




------------------ 原始邮件 ------------------
发件人: "LiZhuoyuan"<notifications@github.com>;
发送时间: 2019年8月2日(星期五) 下午4:26
收件人: "OpenFlutter/flutter_screenutil"<flutter_screenutil@noreply.github.com>;
抄送: "WEBL"<1310845803@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [OpenFlutter/flutter_screenutil] The method '/' was called onnull. (#52)




有初始化吗?

**Comment by lizhuoyuan** [comment]
看readme .  有中文版
还可以看看example
