### ISSUE TITLE
Version 5.9.0 has exaggerated proportions in landscape mode

### ISSUE THREAD

**Issue by SkyOfFeather** [OpenFlutter/flutter_screenutil#528]
My application has a landscape and portrait screen switching function. After version 5.9.0, when the page is in landscape mode, the proportion is significantly different from the previous version, which becomes very exaggerated. On versions<=5.8.4, it is normal

![IMG_0758](https://github.com/OpenFlutter/flutter_screenutil/assets/14194251/d807a6da-d680-4caf-8c04-a8c9c5289885)
![IMG_0759](https://github.com/OpenFlutter/flutter_screenutil/assets/14194251/5c6c5e99-1b7d-465c-ba42-08415d644fb5)

**Comment by DexEze** [comment]
I seem to be having the same issue. Anything using .sp is far too big after upgrading to 5.9.0 from 5.8.4

Downgrading to 5.8.4 fixed this for me.

**Comment by SkyOfFeather** [comment]
Yes, by the way, it should be caused by the use of. sp

**Comment by jobinjva** [comment]
this worked for me. (v5.9.0)
```
    ScreenUtilInit(
      fontSizeResolver: (fontSize, instance) => FontSizeResolvers.radius(fontSize, instance),
      ........
```

**Comment by RakaAlrian** [comment]
> this worked for me. (v5.9.0)
> 
> ```
>     ScreenUtilInit(
>       fontSizeResolver: (fontSize, instance) => FontSizeResolvers.radius(fontSize, instance),
>       ........
> ```

this should be included in the documentation
