### ISSUE TITLE
设置字体的时候Setsp是像素吗？

### ISSUE THREAD

**Issue by programmerElephant** [OpenFlutter/flutter_screenutil#53]
fontSize: ScreenUtil(allowFontScaling: true).setSp(50)，等价于fontSize: 25,

**Comment by programmerElephant** [comment]
在设置的时候我都需要从设计图的值乘以2哇？

**Comment by lizhuoyuan** [comment]
是像素. 单位px的那种

**Comment by programmerElephant** [comment]
我用设计图上面字体为14px，填进去setSp(14)过后根本看不见，初始化为iphone6的750X1335,测试为iphonex真机

**Comment by lizhuoyuan** [comment]
可能你这个需要像素*2?

**Comment by programmerElephant** [comment]
就是*2过后正常

**Comment by lizhuoyuan** [comment]
调整一下设计稿的设置.
可能设计的时候不太一样.

**Comment by programmerElephant** [comment]
我发现,字体没有根据不同机型来变大或者缩小,
###
    ScreenUtil.instance = ScreenUtil(width: 750, height: 1334, allowFontScaling: true)..init(context);
### 
ScreenUtil().setSp(20),
###
iphone6和iphoneX的字体并无变化

**Comment by lizhuoyuan** [comment]
你试试打印一下ScreenUtil().setSp(20), 
看看不同手机会不会有变化

**Comment by programmerElephant** [comment]
iphone6-iphoneX的机型都没有变,其他有变化

**Comment by programmerElephant** [comment]
只有iphone6和iphonex没有变化，都是20，其余的plus和5s有改变

**Comment by lizhuoyuan** [comment]
可能它觉得这俩手机上应该表现一致 ..
