### ISSUE TITLE
UI not updated when Foldable screen state changed

### ISSUE THREAD

**Issue by Huanxin1997** [OpenFlutter/flutter_screenutil#530]
I raised the issue with the flutter team, but it seems to be caused by the use of ScreenUtil in the Flustar pub, I would like to ask if flutter_screenutil supports handling of this situation?
[Flutter Issue Link](https://github.com/flutter/flutter/issues/137399)

**Comment by wdcs-vivekmakvana** [comment]
Is there any update on this?
