### ISSUE TITLE
Flutter UI Issue Urgent issue on Production

### ISSUE THREAD

**Issue by ankitmiyan30** [OpenFlutter/flutter_screenutil#533]
Hello Team
Out of a sudden, this package has started giving me UI issues on WEB, could you please let me know what needs to be done?
 Tried on both 3.13.5 and 3.13.9 but no luck.
**OLD UI**
<img width="1351" alt="Screenshot 2023-11-13 at 12 23 30 PM" src="https://github.com/OpenFlutter/flutter_screenutil/assets/30353044/aefb4d46-507d-4941-8211-02489851781e">

**New UI**
Without any update on anything 
<img width="1428" alt="Screenshot 2023-11-10 at 7 26 59 PM" src="https://github.com/OpenFlutter/flutter_screenutil/assets/30353044/6889fb15-ecd7-432f-85dd-6bcfb89ad155">

**Comment by juanxcueva** [comment]
Same issue

**Comment by potikorn** [comment]
I have same issue on flutter version 3.16.0 too. seem like some of property not apply when upgrade. I tried to downgrade to 3.13.9. It's work fine. maybe breaking change version cause the issue. (I testing on android)

**Comment by dmytrohurskyi** [comment]
I too have similar issue on Android and iOS. After the update to Flutter 3.16.0, the UI dimensions became a bit off (parts that use screen_util)

**Comment by ankitmiyan30** [comment]
Got the solution please use version flutter_screenutil 5.7.0 if you are using this in flutter web until they fix the issue in the latest flutter_screenutil.

Use it like
 **flutter_screenutil 5.7.0**
Do not use it like
 **flutter_screenutil ^5.7.0**

**Comment by dmytrohurskyi** [comment]
Hi! Downgrading this lib doesn't solve this issue on mobile at all. All measurements are off.

**Comment by juanxcueva** [comment]
Also returning flutter_screenutil to 5.7.0 returns the error #477 (Keyboard error)

**Comment by Den-creator** [comment]
I have the same issue on Android. 
Latest flutter 3.19.3 + latest package flutter_screenutil: 5.9.0 have the issue. 
It is weird, as problem happens only when run the app in **release** mode.
