### ISSUE TITLE
Flutter_screenutil for fluent_ui 

### ISSUE THREAD

**Issue by longfit** [OpenFlutter/flutter_screenutil#538]
I have made use flutter_screenutil at fluent_ui  development

I follow your method 1 and designSize (360,690) , ipad , table size seems ok
but  android phone , iPhone seems strange font size 

android and iPhone vertical navigation Pane item is so smaller than expected.  and tablet and iPad is under control font size

I don't know where I misuse flutter_screenutil or fluent_ui are no need to adopt font size ???

<img width="377" alt="android" src="https://github.com/OpenFlutter/flutter_screenutil/assets/4157794/b27c3f72-b07d-4951-813b-f2d832b9b9cf">

![ipad ](https://github.com/OpenFlutter/flutter_screenutil/assets/4157794/cabd017f-8f28-45c1-8450-a6524778da6f)

**Comment by longfit** [comment]
<img width="377" alt="android" src="https://github.com/OpenFlutter/flutter_screenutil/assets/4157794/ba2e185f-0861-43fc-8a4e-bb2b11ec0dc2">
![ipad ](https://github.com/OpenFlutter/flutter_screenutil/assets/4157794/0ce5b6de-f734-42b8-b9b9-391ee969fe21)

**Comment by lizhuoyuan** [comment]
To be honest, in supporting both pad and mobile, the effect is not as expected. You may need to do some extra work yourself.
