### ISSUE TITLE
貌似在苹果模拟器上，scale 的比例有问题

### ISSUE THREAD

**Issue by zhouzhuhao** [OpenFlutter/flutter_screenutil#54]
![WeChatff19bd5917955e8e4531c86b5be0b6d6](https://user-images.githubusercontent.com/11433842/62671104-18ab7b80-b9c8-11e9-9c75-1914106a7128.png)

**Comment by zhouzhuhao** [comment]
咋变成 0.5了 1334 / 1334 😂

**Comment by lizhuoyuan** [comment]
你得给我看代码啊

**Comment by zhouzhuhao** [comment]
![WechatIMG3](https://user-images.githubusercontent.com/11433842/62671397-5230b680-b9c9-11e9-879f-deb5937fe760.png)

**Comment by lizhuoyuan** [comment]
![image](https://user-images.githubusercontent.com/15923901/62671466-99b74280-b9c9-11e9-9a52-0805f0553baa.png)
