### ISSUE TITLE
Lib doesn't work starting from Flutter 3.16 on mobile: all screen util values became invalid

### ISSUE THREAD

**Issue by dmytrohurskyi** [OpenFlutter/flutter_screenutil#541]
#533 was closed, but for mobile platforms the issue hasn't been resolved. Users suffer from UI being shifted, because suddenly the values that library gives after flutter update are different from what they should be. 
Please look at this issue!

**Comment by juanxcueva** [comment]
I have same issue on flutter version 3.16.0 too

**Comment by lizhuoyuan** [comment]
I am running on flutter 3.16.5 and no problem is found. Try using 3.16.5 and tell me the result. Thank you

**Comment by dmytrohurskyi** [comment]
@lizhuoyuan the issue persists on 3.16.5. Values calculated by the library seem have changed after the 3.16 update and still not resolved. For example, what previously was 50.w now looks like 35.w

**Comment by FullstackWEB-developer** [comment]
I think this is due to new features in flutter 3.16
https://docs.flutter.dev/release/breaking-changes/android-14-nonlinear-text-scaling-migration
