### ISSUE TITLE
How to automatically adjust the font size with changes in screen size

### ISSUE THREAD

**Issue by zhiyaoTu** [OpenFlutter/flutter_screenutil#543]
Hello, I am a Flutter beginner and not very familiar with the functionality of libraries. 
For example, on iPhone 15, the font size is set to 15, while on iPhone SE, it will automatically adjust to 13."

**Comment by lizhuoyuan** [comment]
直接写15.sp   这样 会根据屏幕大小变化

**Comment by zhiyaoTu** [comment]
好的，谢谢
