### ISSUE TITLE
How do I use this correctly to fit for iPad with a iPhone design?

### ISSUE THREAD

**Issue by magic3584** [OpenFlutter/flutter_screenutil#544]
My iPhone design is 390*844, before using this package, the cell container height is 50 and font size is 17, it looks  well on iPad.

But after changed ti 50.h and 17.sp, it looks a little large.

What can I do to fit the iPad?

**Comment by juanxcueva** [comment]
Hey @magic3584 you can try https://github.com/OpenFlutter/flutter_screenutil/issues/528#issuecomment-1806839404 thats solve my problem.

**Comment by lizhuoyuan** [comment]
You should first clarify the effect you want, and then consider how to use it
