### ISSUE TITLE
LateInitializationError: Field '_minTextAdapt@941084504' has not been initialized. 

### ISSUE THREAD

**Issue by mohamed-seiam** [OpenFlutter/flutter_screenutil#545]
i have this error suddenly when i run new application

**Comment by Dhruvrajsinh7Span** [comment]
I am having same issue did you find any solution

**Comment by abdifitahabdulkadir** [comment]
I have same issue now this time while I am using this package for mobile dev responsive ui and I wondered why so far no one solved. waiting to be solve but dont know how long wiill that take

**Comment by Omar-Khaium** [comment]
Same issue

**Comment by DAMHONGDUC** [comment]
you guys have to wrap your MaterialApp with ScreenUtilInit

**Comment by Aditya7738** [comment]
I got solution. Here is my code,
 @override
  Widget build(BuildContext context) {
    return ScreenUtilInit(
      designSize: Size(MediaQuery.of(context).size.width,
          MediaQuery.of(context).size.height),
      minTextAdapt: true,
      splitScreenMode: true,
      child:  MaterialApp(
          title: Constants.app_name,
          builder: (context, child) {
            ScreenUtil.init(context);
            return Theme(
                child: Home(),
                data: ThemeData(
                  textTheme: TextTheme(
                      headline1: TextStyle(
                              fontWeight: FontWeight.bold,
                              fontSize: 15.sp,
                          )),
                ));
          },
          debugShowCheckedModeBanner: false,
        ),
    );
  }

**Comment by muhamedsaber** [comment]
i got the same error

**Comment by muhamedsaber** [comment]
The MaterialApp should be returned From the ScreenUtilInit builder not as a child --
 ScreenUtilInit(
            designSize: const Size(360, 690),
            minTextAdapt: true,
            splitScreenMode: true,
            builder: (_, child) {
              return MaterialApp(
                debugShowCheckedModeBanner: false,
                theme: isDarkMode ? darkThemeManager : lightThemeManager,
                onGenerateRoute: onGenerateRoute,
              );
            });

**Comment by michaelfeb** [comment]
have same issue

**Comment by Mounir-Bouaiche** [comment]
You must use ScreenUtilInit widget on top of your widget. If they are on the same level, use builder.

Example when use child:
```dart
WidgetA(
  child: ScreenUtilInit(
    child: WidgetB(),
  ),
)

class WidgetB extends State..Widget {
  @override
  build(context) {
    return Text('', fontSize: 18.sp),
  }
}
```

Example when use builder:
```dart
WidgetA(
  child: ScreenUtilInit(
    builder: (_, __) => {
      return Text('', fontSize: 18.sp);
    },
  ),
)
```

Example when use both:
```dart
WidgetA(
  child: ScreenUtilInit(
    builder: (_, __) => {
      return Text('', fontSize: 18.sp);
    },
  ),
)
```

**Comment by Mounir-Bouaiche** [comment]
You must use ScreenUtilInit widget on top of your widget. If they are on the same level, use builder.

Example when use child:
```dart
WidgetA(
  child: ScreenUtilInit(
    child: WidgetB(),
  ),
)

class WidgetB extends State..Widget {
  @override
  build(context) {
    return Text('', fontSize: 18.sp),
  }
}
```

Example when use builder:
```dart
WidgetA(
  child: ScreenUtilInit(
    builder: (_, __) => {
      return Text('', fontSize: 18.sp);
    },
  ),
)
```

Example when use both:
```dart
WidgetA(
  child: ScreenUtilInit(
    builder: (_, child) => {
      return Container(
        width: .2.sw,
        child: child,
      );
    },
    // Use child so WidgetB not get built every time .2.sw change
    child: WidgetB(),
  ),
)
```
