### ISSUE TITLE
Display problems on tablets and mobile devices

### ISSUE THREAD

**Issue by vfxbro** [OpenFlutter/flutter_screenutil#546]
Hi!
I'm using Flutter version: 3.13.9
and the latest version of flutter_screenutil: ^5.9.0

My layout resolution for flutter_screenutil is set as follows:

ScreenUtilInit(
        designSize: const Size(390, 844),
        minTextAdapt: true,
        splitScreenMode: false,

On phones the display is correct, but on tablets such as Galaxy Tab A8, Galaxy Tab S3, S4 it is not correct for some reason.

Below I have attached 2 screenshots from and you can all see for yourself that there are problems on tablets.

I don't quite understand why this happens, please help me to understand what the problem is?

<img width="1322" alt="trouve_screen" src="https://github.com/OpenFlutter/flutter_screenutil/assets/4408699/dd359bc4-91ca-4ccd-b81e-337a46f7b19b">

thx!

**Comment by juanxcueva** [comment]
I have the same problem, you can try jobinjva solution in #528
