### ISSUE TITLE
The getter 'physicalGeometry' isn't defined for the type 'FlutterView'.

### ISSUE THREAD

**Issue by ankitmiyantechspian** [OpenFlutter/flutter_screenutil#548]
After upgrading flutter package stopped working.

The getter 'physicalGeometry' isn't defined for the type 'FlutterView'.

<img width="971" alt="Screenshot 2024-02-19 at 4 49 11 PM" src="https://github.com/OpenFlutter/flutter_screenutil/assets/137860496/cd89c440-94d1-4694-a120-489bfcb9290a">

**Comment by ski96277** [comment]
**### This version solved my issue** `flutter_screenutil: ^5.9.0 `
