### ISSUE TITLE
i update to flutter 3.19.5 the package dosen't work any more

### ISSUE THREAD

**Issue by AliSabbar** [OpenFlutter/flutter_screenutil#559]
![Screenshot 2024-04-06 041812](https://github.com/OpenFlutter/flutter_screenutil/assets/80877002/18a71dfd-83a3-4ff2-803d-ebc58ba52e2a)

i'm using the 5.8.4 when i update to 5.9.0 it work but the text problem still not fixed yet in realse mode

**Comment by mozomig** [comment]
You can try my solution for fix 5.9.0 version https://github.com/OpenFlutter/flutter_screenutil/issues/558#issuecomment-2047043378

**Comment by AliSabbar** [comment]
> You can try my solution for fix 5.9.0 version [#558 (comment)](https://github.com/OpenFlutter/flutter_screenutil/issues/558#issuecomment-2047043378)

thank you but i uninstall the package and i'll use media query

**Comment by Mounir-Bouaiche** [comment]
@AliSabbar Please provide a minimal reproduction code to help us debug and find a solution, thanks

**Comment by AliSabbar** [comment]
> @AliSabbar Please provide a minimal reproduction code to help us debug and find a solution, thanks

i remove the package from a long time but the problem was when run the app not work and throw error as it show in image above 

package --version 5.9.0

**Comment by Mounir-Bouaiche** [comment]
Package version 5.8.4 will only support flutter <= 3.13. Please use recent versions

**Comment by Mounir-Bouaiche** [comment]
@AliSabbar Can you use latest version (5.9.2) and let us if your issue is fixed, thanks
