### ISSUE TITLE
在release模式下设置的东西全部是0

### ISSUE THREAD

**Issue by luckysmg** [OpenFlutter/flutter_screenutil#56]
如题😂

**Comment by luckysmg** [comment]
对了，在appbar上会失效

**Comment by luckysmg** [comment]
好吧貌似要在每个页面都要初始化才正常。。。

**Comment by lizhuoyuan** [comment]
不需要每个页面 , 在home页面初始化一次就可以了 
详情看readme

**Comment by lds8988** [comment]
@luckysmg @lizhuoyuan 我也出现了这个问题，debug 包是正常的，release 包会出现这个问题，好奇怪。

**Comment by lizhuoyuan** [comment]
对照一下文档和示例 , 看看有没有遗漏 ,
没有的话 发一下相关代码给你看看

**Comment by lds8988** [comment]
代码有点长，就是 home 页面有三个 Tab，在 home 的 build 方法里初始化。然后那三个 tab 里的尺寸都返回 0。项目用了 provider，不知道有没有影响。但是在那三个 tab 里分别初始化就可以解决这个问题。

**Comment by lizhuoyuan** [comment]
我总觉得你初始化的位置不对

**Comment by zfha** [comment]
> @luckysmg @lizhuoyuan 我也出现了这个问题，debug 包是正常的，release 包会出现这个问题，好奇怪。

怎么处理，我的也是

**Comment by luckysmg** [comment]
@zfha 
如果home里面是底部tab导航栏布局，最好在每个tab页面的跟布局也加上init方法，我是这样解决的

**Comment by luckysmg** [comment]
@lds8988

**Comment by zfha** [comment]
> @zfha
> 如果home里面是底部tab导航栏布局，最好在每个tab页面的跟布局也加上init方法，我是这样解决的

我是每个页面加上的，在debug模式下运行时可以的，退出debug，断掉数据线，杀掉进程，重启下就会发现失效

**Comment by luckysmg** [comment]
我是home里面加了，然后每个Tab页面加了，后面的页面都没加

**Comment by lizhuoyuan** [comment]
![image](https://user-images.githubusercontent.com/15923901/63254629-a465b780-c2a6-11e9-8df9-d4f1555ba17d.png)

 你们有问题的应该都是这么写的吧 . 
bottomNavigationBar 不在home内. 
其实bottomNavigationBar也未必需要用到flutter_screenutil , 按比例给高宽度就可以了.

然后home那一些代码建议封装出去 .

**Comment by lds8988** [comment]
@luckysmg 我现在也是这么处理的，就是觉得奇怪怎么会有这个问题

**Comment by weichongchong** [comment]
单独跑flutter项目没问题，运行android项目第一次启动布局拿到的数据都是0，必现的问题。 问题解决了吗就关闭了？ 2.3.1的版本

**Comment by lizhuoyuan** [comment]
@weichongchong  v2不行就用v3, 还不行就仔细看看readme  
再不行上代码
