### ISSUE TITLE
5.9.0 oppo colorOS 14.0 Android14列表item有时会空白

### ISSUE THREAD

**Issue by Bter** [OpenFlutter/flutter_screenutil#561]
![有问题的时候]
<img src="https://github.com/OpenFlutter/flutter_screenutil/assets/20014318/498cbc16-b478-4459-8925-e71e81cb31b8" width="300px">
![正常的时候]
<img src="https://github.com/OpenFlutter/flutter_screenutil/assets/20014318/43ceae7f-ec67-4466-a436-2ad37c45977a" width="300px">

**Comment by Bter** [comment]
问题同 #529

**Comment by Bter** [comment]
解决方案 https://github.com/OpenFlutter/flutter_screenutil/issues/558#issuecomment-2047043378

**Comment by lizhuoyuan** [comment]
试试 
final designSize = const Size(412, 892);

ScreenUtilInit(
          designSize: designSize,
          fontSizeResolver: (fontSize, instance) {
            final display = View.of(context).display;
            final screenSize = display.size / display.devicePixelRatio;
            final scaleWidth = screenSize.width / designSize.width;

            return fontSize * scaleWidth;
          },
          builder: (context, _) {
              return MaterialApp.....
})
