### ISSUE TITLE
横竖屏切换布局错乱

### ISSUE THREAD

**Issue by applebest** [OpenFlutter/flutter_screenutil#566]
https://github.com/OpenFlutter/flutter_screenutil/issues/414#issuecomment-1223441452

使用这种方式，改动源码可以解决横竖屏切换的问题 ，横竖屏切换后要重置设计比例

**Comment by applebest** [comment]
改动过后，首次渲染白屏

**Comment by applebest** [comment]
<img width="1267" alt="image" src="https://github.com/OpenFlutter/flutter_screenutil/assets/16376401/0e67cd94-ddae-41d9-b212-be1d3f3e8862">

**Comment by applebest** [comment]
> @applebest Great idea, package used by many users including web and desktop that they are needing resize by width rather than orientation. You can use fontSizeResolver though (`FontSizeResolver.[your_factor-radius in this case]` or any other function), maybe conditionnaly based on device type

 Is it possible to add a parameter to the initialization method to control via a variable whether or not the design ratio needs to be refreshed based on orientation?

**Comment by applebest** [comment]
There is no screen rotation on the web and desktop, so there is no problem using width adaptation. On mobile phones and tablets, the screen rotation will be chaotic. Can the frame adapt? grateful

**Comment by Mounir-Bouaiche** [comment]
> > @applebest Great idea, package used by many users including web and desktop that they are needing resize by width rather than orientation. You can use fontSizeResolver though (`FontSizeResolver.[your_factor-radius in this case]` or any other function), maybe conditionnaly based on device type
> 
> Is it possible to add a parameter to the initialization method to control via a variable whether or not the design ratio needs to be refreshed based on orientation?

See [Docs](https://github.com/OpenFlutter/flutter_screenutil?tab=readme-ov-file#properties), fontSizeResolver parameter, in your case you can pass `FontSizeResolvers.radius` instead of default (`FontSizeResolvers.width`)

**Comment by applebest** [comment]
> > > @applebest Great idea, package used by many users including web and desktop that they are needing resize by width rather than orientation. You can use fontSizeResolver though (`FontSizeResolver.[your_factor-radius in this case]` or any other function), maybe conditionnaly based on device type
> > 
> > 
> > Is it possible to add a parameter to the initialization method to control via a variable whether or not the design ratio needs to be refreshed based on orientation?
> 
> See [Docs](https://github.com/OpenFlutter/flutter_screenutil?tab=readme-ov-file#properties), fontSizeResolver parameter, in your case you can pass `FontSizeResolvers.radius` instead of default (`FontSizeResolvers.width`)

`FontSizeResolvers.radius` only solves the font adaptation problem, the width and height of the widget are adapted using `.w` `.h`, when the screen is rotated . `.w` `.h` still uses the vertical scaling, I need to change the scaling according to the horizontal/vertical switch, because the width and height change when the screen is rotated.

**Comment by Mounir-Bouaiche** [comment]
@applebest This is expected, you should use your own code then with Flutter's `LayoutBuilder` widget, this package will not re-invent what is already built-in in flutter

**Comment by Mounir-Bouaiche** [comment]
> > > > @applebest Great idea, package used by many users including web and desktop that they are needing resize by width rather than orientation. You can use fontSizeResolver though (`FontSizeResolver.[your_factor-radius in this case]` or any other function), maybe conditionnaly based on device type
> > > 
> > > 
> > > Is it possible to add a parameter to the initialization method to control via a variable whether or not the design ratio needs to be refreshed based on orientation?
> > 
> > 
> > See [Docs](https://github.com/OpenFlutter/flutter_screenutil?tab=readme-ov-file#properties), fontSizeResolver parameter, in your case you can pass `FontSizeResolvers.radius` instead of default (`FontSizeResolvers.width`)
> 
> `FontSizeResolvers.radius` only solves the font adaptation problem, the width and height of the widget are adapted using `.w` `.h`, when the screen is rotated . `.w` `.h` still uses the vertical scaling, I need to change the scaling according to the horizontal/vertical switch, because the width and height change when the screen is rotated.

This is not a default for all users, either mobile users they want to calculate box width based on actual width of viewport whether landscape or portrait, so this custom feature will not be coded in this library. You should take a look at `LayoutBuilder` for this behaviour.

**Comment by Mounir-Bouaiche** [comment]
@applebest You can also use `.r` instead of `.w` and `.h` if you want the minimum value of width/height viewport, in any case

**Comment by applebest** [comment]
> @applebest您也可以使用`.r`而不是`.w`，`.h`如果您想要宽度/高度视口的最小值，无论如何


Some public widgets use a lot of `.w` and `.h` when laying out. In landscape mode, I still want the public widgets to have good layout performance when rotating, so use `.r` This means that a lot of layout code needs to be modified based on rotation.

**Comment by Mounir-Bouaiche** [comment]
> <img alt="image" width="1267" src="https://private-user-images.githubusercontent.com/16376401/333184583-0e67cd94-ddae-41d9-b212-be1d3f3e8862.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0ODIzNTQsIm5iZiI6MTcxNjQ4MjA1NCwicGF0aCI6Ii8xNjM3NjQwMS8zMzMxODQ1ODMtMGU2N2NkOTQtZGRhZS00MWQ5LWIyMTItYmUxZDNmM2U4ODYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDE2MzQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5MjNlZGEyNDJlNThjM2RlOTY4MTM2OGRkMDAyOTZjZWQ4MjNlMmZiMGJlMGZjNWRhNGY5NTZhMjg4OWIxYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wxRaWoeHGA1seOrD_aJKHlJCyG3NOmuRALY1e8pS2p8">

You can use this code, wrap `ScreenUtilInit` with `LayoutBuilder` and pass `designSize` according to orientation

**Comment by applebest** [comment]
> > <img alt="image" width="1267" src="https://private-user-images.githubusercontent.com/16376401/333184583-0e67cd94-ddae-41d9-b212-be1d3f3e8862.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0ODIzNTQsIm5iZiI6MTcxNjQ4MjA1NCwicGF0aCI6Ii8xNjM3NjQwMS8zMzMxODQ1ODMtMGU2N2NkOTQtZGRhZS00MWQ5LWIyMTItYmUxZDNmM2U4ODYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDE2MzQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5MjNlZGEyNDJlNThjM2RlOTY4MTM2OGRkMDAyOTZjZWQ4MjNlMmZiMGJlMGZjNWRhNGY5NTZhMjg4OWIxYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wxRaWoeHGA1seOrD_aJKHlJCyG3NOmuRALY1e8pS2p8">
> 
> You can use this code, wrap `ScreenUtilInit` with `LayoutBuilder` and pass `designSize` according to orientation

Please send another picture, it was not uploaded, thank you

**Comment by Mounir-Bouaiche** [comment]
> <img width="1267" alt="image" src="https://github.com/OpenFlutter/flutter_screenutil/assets/16376401/0e67cd94-ddae-41d9-b212-be1d3f3e8862">
> 

It's yours
