### ISSUE TITLE
Text Visibility Issue in Release Mode

### ISSUE THREAD

**Issue by tamremariam** [OpenFlutter/flutter_screenutil#579]
I'm experiencing an issue with the `flutter_screenutil` package in my Flutter application. When running the app in debug mode, everything works as expected. However, upon building and installing the app in release mode, the text becomes invisible when the app is reopened after being closed. The issue appears to be related to the `flutter_screenutil` package, as removing this package resolves the problem.

Steps to Reproduce:

1. Integrate the `flutter_screenutil` package into a Flutter project.
2. Build the app in debug mode and verify that text is visible and displayed correctly.
3. Build and install the app in release mode.
4. Open the app, close it, and then reopen it.
5. Observe that text is not visible upon reopening.

Expected Behavior:

Text should be visible and properly rendered in release mode, even after reopening the app.

Actual Behavior:

Text is not visible when the app is reopened in release mode.

Environment:

- Flutter version: 3.23.0-0.1.pre (beta channel)
- Dart version: 3.5.0
- DevTools version: 2.36.0
- `flutter_screenutil` package version: [Latest version]
- Operating System: Windows 11
- Device: Both emulator and physical devices

Additional Notes:

- The issue does not occur when `flutter_screenutil` is removed from the project.
- The problem persists even after cleaning the build cache and reinstalling the app.
Attachments:

Thank you for your assistance!

**Comment by KXwonderful** [comment]
I have also encountered a similar problem.How did you solve it later?

**Comment by KXwonderful** [comment]
I have also encountered a similar problem.How did you solve it later?@tamremariam

**Comment by tamremariam** [comment]
> [KXwonderful](/KXwonderful)
i hope this solves your problem @KXwonderful
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await ScreenUtil.ensureScreenSize(); //add this line this fix fi for me in your main.dar
  runApp(const MyApp());
}
