### ISSUE TITLE
how to set it once in MaterialApp's home?

### ISSUE THREAD

**Issue by NTMS2017** [OpenFlutter/flutter_screenutil#58]
In your plugin info you were talking about 'set the page in the MaterialApp's home once' but in your example I couldn't find how to set in once in MaterialApp's home. 

Is it possible to show me how to do it? I need to set it once in MaterialApp's home(ie the entry file, just set it once).

` Be sure to set the page in the MaterialApp's home(ie the entry file, just set it once) to ensure that the fit size is set before each use:`

**Comment by lizhuoyuan** [comment]
for example :
https://github.com/lizhuoyuan/flutter_study

this project used flutter_screenutil.
You can refer to this to achieve

**Comment by NTMS2017** [comment]
Thanks I will try
