### ISSUE TITLE
Error : LateError (LateInitializationError: Field '_data@68084504' has not been initialized.)

### ISSUE THREAD

**Issue by ahmetbinomer** [OpenFlutter/flutter_screenutil#584]
How can i solve it ?

<img width="1727" alt="Screenshot at Sep 14 12-28-23" src="https://github.com/user-attachments/assets/4a5842d5-9e6d-47fa-8285-50a0488ecac8">

<img width="1727" alt="Screenshot at Sep 14 12-28-36" src="https://github.com/user-attachments/assets/0f89a53a-4e82-43c1-9e62-d5cde5b074f5">

**Comment by rersheed** [comment]
I have the same issue. have you found the solution?

**Comment by Mounir-Bouaiche** [comment]
Convert appTheme.theme to function, or move `AppTheme appTheme = AppTheme()` to ScreenUtilInit's builder function
