### ISSUE TITLE
升级之后参数只接受double

### ISSUE THREAD

**Issue by jintangWang** [OpenFlutter/flutter_screenutil#59]
升级了之后 `setWidth` 这些只支持 `double`，不再支持 `int`。升级的时候能否考虑下向下兼容呢？

**Comment by jintangWang** [comment]
#31

**Comment by lizhuoyuan** [comment]
不可能啊
你直接写int有问题?
我示例里都是int的啊
![image](https://user-images.githubusercontent.com/15923901/63241185-4f657980-c285-11e9-90c1-7f9006ba3974.png)

**Comment by jintangWang** [comment]
我看到0.5.3 的源码里是这样
```
  setWidth(double width) => width * scaleWidth;
``` 
然后 `dart analysis` 就会报 `error: The argument type 'int' can't be assigned to the parameter type 'double'. `

版本切到 `0.5.1` 就可以了

**Comment by lizhuoyuan** [comment]
Dart2.1里面新增特性，当double的值为int值时，int自动转成double.

另外, 我每次都会跑示例代码的 ,示例代码也都是传的int类型 , 没有发现问题. 
不太清楚为什么你会只切换插件版本就能搞定问题,

**Comment by jintangWang** [comment]
- - 因为 `0.5.1` 里参数声明是 `int` ，
```
setWidth(int width) => width * scaleWidth;
```
![image](https://user-images.githubusercontent.com/12557847/63410785-ad7d9280-c426-11e9-8342-db4518ed311c.png)
我的 `dart` 已经这么高了，但会提示那个问题，我用的 `jetbrain` 里的 `dart` 插件
![image](https://user-images.githubusercontent.com/12557847/63410856-d4d45f80-c426-11e9-80ba-53754d02ea55.png)

**Comment by lizhuoyuan** [comment]
我又看了一眼, 最新版是double , 应该可以了  .
尴尬

**Comment by jintangWang** [comment]
最新版本来就是 `double` 呀，然后我的就报错了嘛

**Comment by lizhuoyuan** [comment]
但是可以直接填写int啊 ... 不会报错啊

**Comment by jintangWang** [comment]
你的插件是什么版本啊？

**Comment by lizhuoyuan** [comment]
我现在下载github的示例泡一下(0.5.3)

**Comment by jintangWang** [comment]
![image](https://user-images.githubusercontent.com/12557847/63413532-78743e80-c42c-11e9-9b8c-97db44fdf81c.png)
![image](https://user-images.githubusercontent.com/12557847/63413539-7dd18900-c42c-11e9-9124-3bb9a2f8c830.png)
为啥变量的话会报错？

**Comment by jintangWang** [comment]
`width` 和 `height` 我都声明的是 `int` ，好奇怪啊

**Comment by lizhuoyuan** [comment]
我理解是它做类型检查的时候检查到类型不匹配 , 因为你规定了它就是int . 
直接输入数字的话, 它自己判断类型 , 然后会自动转成double

**Comment by jintangWang** [comment]
看来参数的话不会自动转 - - ！

**Comment by jintangWang** [comment]
@lizhuoyuan 要不要把接受的参数改成 `num` 类型，因为我觉得变量如果是 `int` 类型，传入  `setWidth()` 也应该是合理的 ：
``` dart
setWidth(num width) => width * scaleWidth;
```

**Comment by lizhuoyuan** [comment]
我测试一下 , 如果没有其他问题就改一下

**Comment by akulubala** [comment]
setHeight, setWidth 返回类型这里也需要设置为double，
`  
setHeight(num height) => height * scaleHeight;
`

改为
`
double setHeight(num height) => height * scaleHeight;
`
否则也会报类型不匹配：
The argument type 'dynamic' can't be assigned to the parameter type 'double'.dart(argument_type_not_assignable)


flutter dart 版本：
`
Flutter 1.9.1+hotfix.6 • channel stable • git@github.com:flutter/flutter.git
Framework • revision 68587a0916 (9 weeks ago) • 2019-09-13 19:46:58 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0
`

**Comment by lizhuoyuan** [comment]
> setHeight, setWidth 返回类型这里也需要设置为double，
> ` setHeight(num height) => height * scaleHeight;`
> 
> 改为
> `double setHeight(num height) => height * scaleHeight;`
> 否则也会报类型不匹配：
> The argument type 'dynamic' can't be assigned to the parameter type 'double'.dart(argument_type_not_assignable)
> 
> flutter dart 版本：
> `Flutter 1.9.1+hotfix.6 • channel stable • git@github.com:flutter/flutter.git Framework • revision 68587a0916 (9 weeks ago) • 2019-09-13 19:46:58 -0700 Engine • revision b863200c37 Tools • Dart 2.5.0`

感觉你这个不是这个问题啊

**Comment by akulubala** [comment]
@lizhuoyuan 方法没有给返回类型，返回类型默认为dynamic, 而那边可以接收的类型是double的

`
ListView(
            shrinkWrap: true,
            padding: EdgeInsets.only(
                left: ScreenUtil().setWidth(48),
                right: ScreenUtil().setWidth(48))
`
<img width="633" alt="屏幕快照 2019-11-19 上午11 11 22" src="https://user-images.githubusercontent.com/1884768/69113250-74a09880-0abd-11ea-95df-f36918eaa207.png">

**Comment by lizhuoyuan** [comment]
@akulubala 
确实需要加个返回类型 , 这里应该因为是const的所以才不支持自动推导类型 ,  然后我给所有的方法都加了返回类型 .  0.6.1
