### ISSUE TITLE
theme字体大小设置

### ISSUE THREAD

**Issue by RhaegarLannister** [OpenFlutter/flutter_screenutil#61]
在app入口
return MaterialApp(...
/*------*/
theme:createTheme()
)
如果我想在createTheme()的时候就使用ScreenUtil，比如指定某些textStyle的字体大小，我该怎么办

**Comment by lizhuoyuan** [comment]
一般这个时候还没有拿到屏幕数据 , 
我觉得你可以等到设置好之后调用一个方法来设置

**Comment by Prn-Ice** [comment]
I used google translate to translate your reply and I think you said 
> I think you can wait until it is set up and call a method to set it up.

Please, could you explain some more because I have a theme defined with textStyles in MaterialApp and a lot of screens in my route that use those styles? 
How can I tell when it is set up and what sort of method am I creating.

**Comment by lizhuoyuan** [comment]
@Prn-Ice 
There is no way to get the screen data in the first time, because the method of obtaining the screen data is asynchronous.
So , I think you should call it after making sure to get the screen data.
Use screenutil to get the screen data. When the data is not 0, set the textstyle.
