### ISSUE TITLE
用法问题

### ISSUE THREAD

**Issue by doudouaixiaoyu** [OpenFlutter/flutter_screenutil#62]
你在文档里写了您也可以使用ScreenUtil()代替ScreenUtil.getInstance()，例如：ScreenUtil().setHeight(200) 这样一句话，但是在【[0.5.1] - 修正错误的使用方法】更新日志中，你说明了不建议用ScreenUtil()代替ScreenUtil.getInstance()。想问一下，用ScreenUtil()代替会出现什么不可预料的事情吗？因为ScreenUtil.getInstance() 代码太长了，一个页面需要太多的适配。如果可能的话，我还是喜欢用ScreenUtil()。

**Comment by doudouaixiaoyu** [comment]
还有一个问题就是，我必须在登录页初始化，然后登录页登录到主页，主页的设置高和宽以及字体才可以用，要是不用登录页，在MaterialApp的HOME 指定主页，那主页只要是被设置的元素，会全部消失，主页是有底部导航的。类似：  @override
  void initState() {
    super.initState();
    _widgetOptions..add(HomeIndex())..add(UserIndex());
  }

  @override
  Widget build(BuildContext context) {
    ScreenUtil.instance = ScreenUtil.getInstance()..init(context);
    return Scaffold(
      body: IndexedStack(
        index: _currentIndex,
        children: _widgetOptions,
      ),
      floatingActionButton: FloatingActionButton(
        backgroundColor: Theme.of(context).primaryColor,
        onPressed: () {},
        child: Text('勤'),
        mini: true,
        elevation: 0.0,
      ),
      floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
这种的。

**Comment by doudouaixiaoyu** [comment]
> 还有一个问题就是，我必须在登录页初始化，然后登录页登录到主页，主页的设置高和宽以及字体才可以用，要是不用登录页，在MaterialApp的HOME 指定主页，那主页只要是被设置的元素，会全部消失，主页是有底部导航的。类似： @override
> void initState() {
> super.initState();
> _widgetOptions..add(HomeIndex())..add(UserIndex());
> }
> 
> @override
> Widget build(BuildContext context) {
> ScreenUtil.instance = ScreenUtil.getInstance()..init(context);
> return Scaffold(
> body: IndexedStack(
> index: _currentIndex,
> children: _widgetOptions,
> ),
> floatingActionButton: FloatingActionButton(
> backgroundColor: Theme.of(context).primaryColor,
> onPressed: () {},
> child: Text('勤'),
> mini: true,
> elevation: 0.0,
> ),
> floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
> 这种的。

主页的底部导航栏被设置后不会消失，但是body里的页面，像HomeIndex()里的，只要是被设置过的，就会消失，这里设置过的意思是SetWidth或setheight或setsp.

**Comment by doudouaixiaoyu** [comment]
问题应该还是发布成release时，启动太快，因为我从主页跳转到登录页的时候，在跳转回主页，HomeIndex()里面的内容就正常了

**Comment by lizhuoyuan** [comment]
1.是因为 release 的时候用的是AOT  ,  debug的时候是JIT(存疑)
2. 是获取到屏幕数据需要时间 ,
所以在刚开始进入的页面 建议就不用ScreenUtil来做适配, 
而是用比例以及部分不影响适配的东西直接写死数值 .

**Comment by lizhuoyuan** [comment]
关于你说的用法的问题, 
我记得好像 之前是用工厂模式构造方法来写的,  后来改掉了 , 这部分我再研究一下怎么搞会更好

**Comment by doudouaixiaoyu** [comment]
> 1.是因为 release 的时候用的是AOT , debug的时候是JIT(存疑)
> 2. 是获取到屏幕数据需要时间 ,
> 所以在刚开始进入的页面 建议就不用ScreenUtil来做适配,
> 而是用比例以及部分不影响适配的东西直接写死数值 .

好的，谢谢。那我在初始界面手动获取屏幕宽高，进行比例转化，应该也是可以的

**Comment by lizhuoyuan** [comment]
> > 1.是因为 release 的时候用的是AOT , debug的时候是JIT(存疑)
> > 2. 是获取到屏幕数据需要时间 ,
> > 所以在刚开始进入的页面 建议就不用ScreenUtil来做适配,
> > 而是用比例以及部分不影响适配的东西直接写死数值 .
> 
> 好的，谢谢。那我在初始界面手动获取屏幕宽高，进行比例转化，应该也是可以的

其实 , 因为是异步, 且官方也提供了一个状态改变的生命周期类的一个东西 WidgetsBinding.instance.addObserver,
是可以监控屏幕变化的 , 但也是异步监听的方式 , 感觉不够好, 反正多条路多个方向. 给你参考.
当然 有好的方案也希望分享给大家哈~

**Comment by doudouaixiaoyu** [comment]
> > > 1.是因为 release 的时候用的是AOT , debug的时候是JIT(存疑)
> > > 2. 是获取到屏幕数据需要时间 ,
> > > 所以在刚开始进入的页面 建议就不用ScreenUtil来做适配,
> > > 而是用比例以及部分不影响适配的东西直接写死数值 .
> > 
> > 
> > 好的，谢谢。那我在初始界面手动获取屏幕宽高，进行比例转化，应该也是可以的
> 
> 其实 , 因为是异步, 且官方也提供了一个状态改变的生命周期类的一个东西 WidgetsBinding.instance.addObserver,
> 是可以监控屏幕变化的 , 但也是异步监听的方式 , 感觉不够好, 反正多条路多个方向. 给你参考.
> 当然 有好的方案也希望分享给大家哈~
> 
> 再者, 关于你之前说的那个HomeIndex的问题, 你不是像我说的那种 进入到home ,然后进入其他页面 的, 看描述的结论.
> 
> 如果是在B页面初始化
> 打开APP, 进入A , 会发现适配无效, 再 进入B, B的适配是有效的, 回到A , 会发现A也有效了 , 其实是在进入B之后适配才有效导致的A也好了.

对，不过我是在A页面初始化的，A页面适配无效，进入B页面，B页面有效，再返回A页面，A页面有效，可能是我A页面写的有问题，或者是获取屏幕时间的问题。因为，如果把初始化写在登录页，且进来的第一个页面仍然是登录页，适配在登录页就有效

**Comment by lizhuoyuan** [comment]
如果登录页面是 home:登录页 , 是可以的 
我觉得完全可以放一个欢迎页, 然后进入主页,
因为Scaffold也是有bottomNavigationBar这个东西的,
算是提供一种方案吧 .
当然主要原因就是获取屏幕数据不及时.
加油
