### ISSUE TITLE
关于初始化位置

### ISSUE THREAD

**Issue by xpader** [OpenFlutter/flutter_screenutil#63]
目前的初始化是通过 MediaQuery 进行查询从而得到屏幕宽度，这就导致了很多限制，MediaQuery 要求至少要在页面级的 Scaffold 层 build 才能获取屏幕宽高，但有的 App 可能不是纯 Flutter 页面，而是与原生混合的，这时可能有多个入口页面，这就需要每个入口页面都要放一个 init 的过程。

我想做到的是在 MaterialApp 层面只做一次初始化，这样不论入口是什么，都会从这个层面进行设置，而所有其它页面都不需要再关心这个，但在这个层面就不能用 MediaQuery 了，需要使用 dart:ui 里的 window.physicalSize 等参数进行计算，希望撸主有空能对这一块进行优化下。

**Comment by lizhuoyuan** [comment]
window.physicalSize 看起来没有使用context参数 
实际上跟media里的获取是一样的
都是用的同一个东西.

所以只是单纯换成这个是没有改变的,这个我曾经试过.

当然我也希望在app层面只做一次初始化, 暂未想到好的方式 . 
会努力的

**Comment by xpader** [comment]
我这里尝试在 MeterialApp 层面通过 window 是可以获取到屏幕宽高的，而不需要进行 MediaQuery，使用 MediaQuery 时必须到页面级中，不然取不到。唯一的区别是 window 取到的宽高是实际象素级的宽高，所以可能计算方式得不一样。

**Comment by lizhuoyuan** [comment]
如果你是debug可以
但release不行

**Comment by xpader** [comment]
好吧，希望能有更好的方法，我如果有更好的方法也会告诉你。

**Comment by xpader** [comment]
因为我们的App现在是网页、半混合、原生、Flutter 这么一大堆东西混在一起，而 Flutter 有多个入口，这些入口可能是平级的，所以现在需要多个入口进行屏幕尺寸计算的初始化。

我这里初始化已经封装的很简单了，提供了三个方法 Helper.initScreen(), Helper.size(width), Helper.sp(fontSize)，但多人协同开发时，仍有人会忘记在 build() 中调用 initScreen() 从而导致非常容易出问题。

我现在做了个比较简单的补救措施：
在顶层的 MaterialApp 这个 Widget 层面，加了一个 `final navigatorKey = GlobalKey<NavigatorState>();` 属性，然后在 initState() 中增加了
···
    new Timer(Duration(microseconds: 0), () {
      Helper.initScreen(navigatorKey.currentState.overlay.context);
    });
···

然后在 MaterialApp 中指定 navigatorKey
···
Widget build(BuildContext context) {
    return MaterialApp(
      navigatorKey: navigatorKey,
···

因为 initState() 时 context 可能还没生成，所以必须用 Timer() 降低执行优先级，虽然这种做法仍然是异步初始化（并不十分靠谱），但可以做到一定程度上预防忘记在入口中 initScreen() 的问题。

希望还有更好的办法。

**Comment by zhujinsheng** [comment]
也是一种不错的技巧额

**Comment by xpader** [comment]
这篇文章里是否有用？
https://www.jianshu.com/p/f04dbec57343
它使用的是：MediaQueryData.fromWindow(window);

**Comment by lizhuoyuan** [comment]
@xpader  只是形式不同, 拿的都是同一个东西

**Comment by VoterLin** [comment]
之前有人在官方issue里提过，官方更推荐使用MediaQuery, window获取数据不依赖Widget的生命周期，这就会产生一些问题，例如使用debug版本因为程序运行缓慢而拿到宽高数据，而release版本应用速度提升后就无法获取。我现在是在iniState中使用SchedulerBinding.instance.addPostFrameCallback()的回调进行初始化，希望对您有帮助。
