### ISSUE TITLE
 I get this error when I introduce such a file

### ISSUE THREAD

**Issue by Jinxishihenian** [OpenFlutter/flutter_screenutil#64]
The following assertion was thrown building SptErpApp(dirty):
I/flutter ( 5460): MediaQuery.of() called with a context that does not contain a MediaQuery.
I/flutter ( 5460): No MediaQuery ancestor could be found starting from the context that was passed to MediaQuery.of().
I/flutter ( 5460): This can happen because you do not have a WidgetsApp or MaterialApp widget (those widgets introduce
I/flutter ( 5460): a MediaQuery), or it can happen if the context you use comes from a widget above those widgets.
I/flutter ( 5460): The context used was:
I/flutter ( 5460):   SptErpApp(dirty)

**Comment by lizhuoyuan** [comment]
要他它放在MaterialApp内部使用
