### ISSUE TITLE
v0.4.0 设置字体问题

### ISSUE THREAD

**Issue by luanshi210** [OpenFlutter/flutter_ScreenUtil#7]
大神 你的0.4.0版本 设置字体  和老版本不一样了吗？不是用px了？  原来的字体全部变大了。

**Comment by lizhuoyuan** [comment]
是px啊 方法只是增加了是否随系统的文字缩放而进行缩放 你看是不是系统缩放里的问题

**Comment by lizhuoyuan** [comment]
ScreenUtil().setSp(28)         //传入字体大小，根据系统的“字体大小”辅助选项来进行缩放
      ScreenUtil().setSp(28，false)  //传入字体大小，不会根据系统的“字体大小”辅助选项来进行缩放

**Comment by iGenMO** [comment]
有问题，750的标准，pixelRatio=2没问题，一旦大于2，字体变得很大

**Comment by lizhuoyuan** [comment]
谢谢反馈,我会多测试一下 
尽快发新版本改正问题

**Comment by iGenMO** [comment]
`setSp(int fontSize, [allowFontScaling = true]) => allowFontScaling
      ? setWidth(fontSize) * _pixelRatio * _textScaleFactor
      : setWidth(fontSize) * _pixelRatio;`

这里应该不需要*_pixelRatio，直接用setWidth()即可。

**Comment by lizhuoyuan** [comment]
已将字体适配恢复到0.3.0的版本
后续将会对字体适配进行改进.

**Comment by lizhuoyuan** [comment]
前一个版本是这么写的
不记得为嘛在这个版本我加了这个
我已经发布了0.4.1版本(最新版本) 改回了0.3.0的适配方法 
后续我会继续针对字体方面看一看怎么适配比较好 
谢谢~
