### ISSUE TITLE
ScreenUtil.getInstance().setHeight(200) 报错了。

### ISSUE THREAD

**Issue by blockmood** [OpenFlutter/flutter_screenutil#70]
具体错：

flutter: The following NoSuchMethodError was thrown building TopNavigator(dirty):
flutter: The method '/' was called on null.
flutter: Receiver: null
flutter: Tried calling: /(1920.0)

**Comment by blockmood** [comment]
解决了，未初始化。

**Comment by ahmedkassem** [comment]
problem still exist

**Comment by lizhuoyuan** [comment]
@ahmedkassem Do you initialize screenutil?

**Comment by ahmedkassem** [comment]
@lizhuoyuan at each file I use it,
    ScreenUtil.instance =
        ScreenUtil(width: 1080, height: 1920, allowFontScaling: true)
          ..init(context);

**Comment by lizhuoyuan** [comment]
I think you used it before initialize

**Comment by ahmedkassem** [comment]
@lizhuoyuan I will check every file now, thanks for the help

**Comment by lizhuoyuan** [comment]
This is a project：　https://github.com/lizhuoyuan/flutter_study
it used flutter_screenutil , you can refer to this to initialize and use
