### ISSUE TITLE
The method '/' was called on null

### ISSUE THREAD

**Issue by MoSala7** [OpenFlutter/flutter_screenutil#71]
my code :

              FlatButton(
              onPressed: () { },
              color: Colors.blue,
              child: Text(
                  'My font size is 24px on the design draft and will change with the system.',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: ScreenUtil(allowFontScaling: true).setSp(24),
                  )),
            )

and the result !!!!

`I/flutter (29201): The method '/' was called on null.
I/flutter (29201): Receiver: null
I/flutter (29201): Tried calling: /(1080.0)`

**Comment by lizhuoyuan** [comment]
看起来问题不是出在这里啊.. 
看看哪里使用了屏幕宽度

**Comment by lizhuoyuan** [comment]
Did not reply for a while, so close first
