### ISSUE TITLE
iOS版英文数字字体适配，显示很粗

### ISSUE THREAD

**Issue by YanCorey** [OpenFlutter/flutter_screenutil#73]
在iOS 6sp xmax上  字体显示的很大，想问下要怎么解决？
![QQ20191024-0](https://user-images.githubusercontent.com/51994705/67446604-b87dba80-f643-11e9-96d8-1e9dcffda26d.png)

**Comment by lizhuoyuan** [comment]
这个粗应该是字体的问题吧? 
你试试不用这个适配看字体是不是还是粗体的?

**Comment by YanCorey** [comment]
嗯  上面的language是没有适配的效果，底下的English是适配后的效果，显得更粗点。
我想问下这是flutter的原因吗？为啥英文这么靠拢？
我还想问下，这种情况我应该这么适配啊？

**Comment by lizhuoyuan** [comment]
你换个字体试试  我觉得你的字体可能有问题

**Comment by YanCorey** [comment]
使用的是默认字体，然后我把手机设置里的粗体字体关了，显示就正常了。
我想问下这种开启粗体的情况下，我们这边应该这么适配啊？

**Comment by YanCorey** [comment]
好像是flutter的问题，这是链接 https://github.com/flutter/flutter/issues/41101
