### ISSUE TITLE
请问，使用插件之后会重复调用怎么回事呢？

### ISSUE THREAD

**Issue by cn-Meepo** [OpenFlutter/flutter_screenutil#75]
我从A页面跳转B页面，在跳转的时候会重新发起A页面的刚才的请求，在B页面返回A页面的时候也会重新发起请求。

**Comment by lizhuoyuan** [comment]
没遇到过这种情况 
建议看一下是什么原因导致的

**Comment by cn-Meepo** [comment]
void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final router = Router();
    Routers.configureRoutes(router);
    Application.router = router;
    return MultiProvider(
        providers: providers,
        child: Container(
          child: MaterialApp(
            debugShowCheckedModeBanner: false,
            theme: ThemeData(primaryColor: Color(0xff354DBE)),
            home: MainPage(),
          ),
        ));
  }
}

class MainPage extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    ScreenUtil.instance = ScreenUtil(width: 1920, height: 1200)..init(context);
    return Container(
        child: Scaffold(
            appBar: AppBar(title: Text('Demo'), centerTitle: true),
            body: MeetingRoomListPage ()));
  }
}


class MeetingRoomListPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      child: MeetingRoomList(),
    );
  }
}

class MeetingRoomList extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    _getMeetingRooms(context);
    return Container(
      child: RaisedButton(
        onPressed: (){
          Application.router.navigateTo(
              context, "/detail?id=123");
        },
        child: Text('123'),
      ),
    );
  }

  _getMeetingRooms(context) async {
    await get("open/meetingRoom/listAll").then((val) {
      if (val != null) {
        Provider.of<MeetingRoomProvider>(context,listen: false).setMeetingRooms(val);
      }
      print('val');
      print(val);
    });
  }
}


像这样的，我在onPressed跳转的时候会再次调用_getMeetingRooms，返回的时候又会调用_getMeetingRooms，请问这是为什么？

**Comment by lizhuoyuan** [comment]
显然是调用了build方法导致了调用_getMeetingRooms .
会不会是哪里有代码导致这边UI修改调用了build

**Comment by cn-Meepo** [comment]
奇怪的是把这个注释掉之后就不会调用
![image](https://user-images.githubusercontent.com/28797329/69120640-0a93ed80-0ad5-11ea-9020-12079a3be6a4.png)

**Comment by lizhuoyuan** [comment]
> 奇怪的是把这个注释掉之后就不会调用
> ![image](https://user-images.githubusercontent.com/28797329/69120640-0a93ed80-0ad5-11ea-9020-12079a3be6a4.png)

我本地尝试了一下 , 在build里加了个print , 会多次调用的啊

**Comment by cn-Meepo** [comment]
兄弟，我明白了，在给值的时候给个final就可以了

**Comment by lizhuoyuan** [comment]
> 兄弟，我明白了，在给值的时候给个final就可以了

哪个的final ...

**Comment by cn-Meepo** [comment]
我最开始在初始化 ScreenUtil.instance = ScreenUtil(width: 1920, height: 1200)..init(context); 的时候  return Container(
      color: Color(0xff313178),
      child: IndexPage(),
    );
IndexPage()这个页面是一个StatelessWidget，摧毁或返回应该都会影响页面吧，既然我这个页面其实应该是不变的，所以我先  final Widget tabBodies = IndexPage();  然后返回 return Container(
      color: Color(0xff313178),
      child: tabBodies,
    );

**Comment by cn-Meepo** [comment]
谢谢解惑！
