### ISSUE TITLE
Android的虚拟按键影响高度的计算

### ISSUE THREAD

**Issue by danieldai** [OpenFlutter/flutter_screenutil#77]
在系统同尺寸的屏幕上，比如 华为荣耀畅玩 6X 和 iPhone 6 Plus 都是1920 x 1080的物理屏幕，把一个widget的高度设置为screenUtil.setWidth(100) ，这个widget在这两个手机上显示的高度不同，我猜测是荣耀畅玩 6X虚机按键的影响

我测试发现

华为荣耀畅玩6X上 screenUtil.setWidth(1920) 计算出来的高度 698，通过mediaQuery查询出来的高度是654，在苹果 6 plus上，screenUtil.setWidth(1920) 计算出高度 736，media查询出来高度也是736。

**Comment by lizhuoyuan** [comment]
如果你想获取屏幕的高度 应该使用 ScreenUtil.getScreenHeight的方法 , setWidth是根据宽度来适配一个数值
