### ISSUE TITLE
Font disappears in android & iOS release builds

### ISSUE THREAD

**Issue by niranjan-b-prajapati** [OpenFlutter/flutter_screenutil#78]
We have integrated ScreenUtil in the app, it works properly in debug mode when the application is directly run on devices. 

But when we create a release build of iOS or Android version of the app the fonts disappear at most places inside widgets like material button, input text field, appbar, etc.  It is pretty weird, can anyone please help us resolve this issue.  Or help us understand if we are doing anything wrong?

Please check the screenshot attached.

![Screenshot_20191127-150856](https://user-images.githubusercontent.com/22167542/69711992-09dc0680-1128-11ea-9e78-d67d1154490c.png)
![Screenshot_2019-11-27-14-53-14-974_com tatacapital csfd](https://user-images.githubusercontent.com/22167542/69711993-09dc0680-1128-11ea-85c8-db29fcdd79d4.jpg)

**Comment by lizhuoyuan** [comment]
I think you used the font before initialization, or the way of initialization is wrong.
Please show the code of where you initialize and where you use

**Comment by niranjan-b-prajapati** [comment]
@lizhuoyuan The screenshots provided above are of same code implementation but one screenshot in which the fonts are visible are of the app directly run on device in debug mode, and the screenshot in which the fonts are not visible is of a release build. The code implementation is the same If it is showing in debug mode then it should show in release mode also?

**Comment by niranjan-b-prajapati** [comment]
@lizhuoyuan I just figured out that [this](https://github.com/flutter/flutter/issues/25827) is happening in my case.

**Comment by lizhuoyuan** [comment]
If you usage is correct ,the same code should show the same effect . 
and maybe this project will help you. https://github.com/lizhuoyuan/flutter_study
This is my own project  , I used flutter_screenutil in this project .

**Comment by lizhuoyuan** [comment]
#80

**Comment by lizhuoyuan** [comment]
#80
