### ISSUE TITLE
好像有点问题,可以讨论一下

### ISSUE THREAD

**Issue by JakeyYe** [OpenFlutter/flutter_ScreenUtil#8]
`///这里应该直接返回而不是再乘以设备像素比例_statusBarHeightPx * _pixelRatio，可以查看MediaQuery.padding变量的代码注释，Padding中设置间距数值单位是px，而不是dp`
`static double get statusBarHeightPx => _statusBarHeightPx;`
`///问题同上`
`static double get bottomBarHeightPx => _bottomBarHeightPx;`

**Comment by lizhuoyuan** [comment]
```
SizedBox(
              height: MediaQuery.of(context).padding.top,
            ),
```
如果这 `MediaQuery.of(context).padding.top` 的单位是dp 的话 ,那么应该这个sizedbox的高度和状态栏高度相同.
如果是px , 应该比状态栏高很多. 
但我这样写,它的高度与状态栏相同.
![image](https://user-images.githubusercontent.com/15923901/48683364-b4e9e400-ebe7-11e8-8ad3-4d784c5b9c71.png)

**Comment by JakeyYe** [comment]
感谢纠正错误，`MeidaQuery.of(context).padding.top`返回数值的单位确实是dp，我前面单从`MediaQueryData.padding`的注释上认为单位是sp，其实在赋值时进行了sp到dp的转换。还有个问题就是,`“Flutter中默认组件尺寸单位都是dp”`这句话我也认为是对的，但是没有在那看到说明这个，请问，你有在那里看到这个的说明吗？感谢！

**Comment by lizhuoyuan** [comment]
这个的明确说明好像确实没有
只是我确实发现多数情况直接写尺寸的话 , 实际出来的效果是dp单位的.
但字体我不是十分确定
