### ISSUE TITLE
release版本打包 界面会变形

### ISSUE THREAD

**Issue by hufu4635** [OpenFlutter/flutter_screenutil#80]
请作者知悉 debug版本 运行没问题 release版本打包后界面使用的地方会变形

**Comment by lizhuoyuan** [comment]
请检查使用方式

**Comment by hufu4635** [comment]
ScreenUtil.instance = ScreenUtil(width: 375, height: 667)
    ..init(.context);   只在app 闪屏界面初始化一次。  debug版本包运行没问题 只有以release版本运行的时候才会出现

**Comment by lizhuoyuan** [comment]
![image](https://user-images.githubusercontent.com/15923901/69865294-caeeb200-12db-11ea-8dfd-bf8de206f10b.png)
在这个 地方初始化

**Comment by hufu4635** [comment]
谢谢作者   

` onGenerateRoute: (RouteSettings settings) {
      return MaterialPageRoute<Object>(builder: (BuildContext context) {
        ScreenUtil.instance = ScreenUtil(width: 375, height: 667)
          ..init(context);
        return routes.buildPage(settings.name, settings.arguments);
      });
    },`

添加到这里后 可以正常显示了
