### ISSUE TITLE
关于全面屏的问题，再次打扰一下。

### ISSUE THREAD

**Issue by bladeofgod** [OpenFlutter/flutter_screenutil#84]
你好，如果在全面屏下，对于正方形，需要在设置高的时候将 setHeight改成，setWidth，这样对16比9的屏幕会不会有影响，我需不需要写个判断，全面屏的时候用setWidth，正常比率的用setHeight ? 
谢谢解答

**Comment by lizhuoyuan** [comment]
如果都需要显示正方形 
 那么不管什么屏幕下都应该使用setWidth

**Comment by bladeofgod** [comment]
> 如果都需要显示正方形
> 那么不管什么屏幕下都应该使用setWidth

谢谢，看来是个浩大的工程，哈哈
