### ISSUE TITLE
考虑到性能应该优先使用单例或做个防止创建新实例的处理吧？

### ISSUE THREAD

**Issue by GanZhiXiong** [OpenFlutter/flutter_screenutil#87]
readme里面是这样写的，如下
> 也可以使用 ScreenUtil() 替代 ScreenUtil.getInstance(), 例如：ScreenUtil().setHeight(200)

如果使用ScreenUtil()的话每次都会创建一个实例，是不是会影响性能呢？
我觉得应该做一个防止创建新实例的代码处理。

**Comment by lizhuoyuan** [comment]
我记得之前是有做过不会创建新实例的.
刚看代码好像没有了.
一会看看用工厂搞一个 .
多谢提醒
