### ISSUE TITLE
字体适配问题

### ISSUE THREAD

**Issue by joeyczz** [OpenFlutter/flutter_screenutil#89]
` 
  /// 实际的dp与UI设计px的比例
  /// The ratio of the actual dp to the design draft px
  double get scaleWidth => _screenWidth / uiWidthPx;

  double get scaleHeight => _screenHeight / uiHeightPx;

  double get scaleText => scaleWidth > scaleHeight ? scaleWidth : scaleHeight;
`

97行这段感觉有点奇怪，假设设计图是iPhone 6（375*667），UI尺寸是 750*1334
iPhone 6（375*667）上 scaleWidth和scaleHeight都是0.5 
iPhone X（375*812）上 scaleWidth是0.5 scaleHeight是812/1334=0.6

iPhone X上最终字体是按高度计算缩放的

当然也可以把调整传入高度

`
  ScreenUtil.init(
    context,
    width: 750,
    height: 2000, // 放大高度让 scaleHeight始终偏小
    allowFontScaling: false,
  );
`

version 1.0.1

**Comment by lizhuoyuan** [comment]
我一开始想的是支持pad上的字体缩放, 看起来有点草率了
我再考虑一下怎么弄更好

**Comment by xunzzz** [comment]
![image](https://user-images.githubusercontent.com/13808022/72501504-f15bb300-3871-11ea-876f-8403a1133a4a.png)
匹配不到1.0.2版本
