### ISSUE TITLE
setheight 方法的参数 的单位是dp？

### ISSUE THREAD

**Issue by Marcello168** [OpenFlutter/flutter_ScreenUtil#9]
setheight 方法的参数 的单位是dp？

**Comment by lizhuoyuan** [comment]
参数是px
返回结果是dp

**Comment by Marcello168** [comment]
那在iOS 上怎么适配呢 ，我还以为是直接返回的px 因为设计稿一般都是iphon 6  然后假如在设计稿的真实高度是100   然后我需要在iphone XR 上面 按照比例放大  这个没有提供方法吗？

**Comment by Marcello168** [comment]
> 参数是px
> 返回结果是dp

那在iOS 上怎么适配呢 ，我还以为是直接返回的px 因为设计稿一般都是iphon 6 然后假如在设计稿的真实高度是100 然后我需要在iphone XR 上面 按照比例放大 这个没有提供方法吗？

**Comment by lizhuoyuan** [comment]
因为flutter的单位是dp的
你直接填入设计稿上的px就可以了

**Comment by lizhuoyuan** [comment]
都是输入px , 返回dp  dp是flutter的默认单位

**Comment by Marcello168** [comment]
> 你设备宽度是828px . 此图160px 大概是设备宽度 是1/ 5 看上去好像没什么问题

好像也是 ，不过感觉还是怪怪的

**Comment by lizhuoyuan** [comment]
后续有问题可以联系,
issue先关闭 了

**Comment by Marcello168** [comment]
原来是我搞错了， 我设计稿的单位是pt

**Comment by lizhuoyuan** [comment]
以我开发经验来看 , 都是可以直接改成其他单位的

**Comment by Marcello168** [comment]
> 以我开发经验来看 , 都是可以直接改成其他单位的

啥意思 能提示下吗，刚毕业不久

**Comment by lizhuoyuan** [comment]
就是你的设计稿可以改成px为单位
找不到并且不介意的话 可以把设计稿发出来, 我帮你看看

**Comment by Marcello168** [comment]
> 就是你的设计稿可以改成px为单位
> 找不到并且不介意的话 可以把设计稿发出来, 我帮你看看

找到了 真的是可以切换。可以切换成dp px 和pt  ，我用的是蓝湖 谢谢了
