### ISSUE TITLE
1.0.2版本下载匹配不到

### ISSUE THREAD

**Issue by xunzzz** [OpenFlutter/flutter_screenutil#90]
![image](https://user-images.githubusercontent.com/13808022/72501817-d0e02880-3872-11ea-9fa0-788cec21a49d.png)
packages get后，提示上述错误

**Comment by lizhuoyuan** [comment]
你这个难到我了..
我一会试一下

**Comment by lizhuoyuan** [comment]
![image](https://user-images.githubusercontent.com/15923901/72520360-414b7180-3894-11ea-8289-7354369feb29.png)
没问题啊  你再看看是不是哪里字打错了

**Comment by lizhuoyuan** [comment]
我只是没有单独拉出1.0.2的分支 .
我这里是可以的啊 没理由啊

**Comment by xunzzz** [comment]
把三方库的国内镜像关了以后就可以了，国内镜像的可能还没有同步过去，已解决，多谢！

**Comment by zhangjunhou** [comment]
@xunzzz 请问你是怎么关闭的

**Comment by lizhuoyuan** [comment]
> @xunzzz 请问你是怎么关闭的

环境变量, 看一下是设置的教程就知道怎么关了
