### ISSUE TITLE
在平板上有bug

### ISSUE THREAD

**Issue by yexiaodong** [OpenFlutter/flutter_screenutil#91]
**初始化**
 ScreenUtil.init(context, width: 750, height: 1334);
**使用**
 Image.asset('assets/images/detail.jpg',width: ScreenUtil().setWidth(750),height: ScreenUtil().setHeight(370)),
**图片大小**
750px*370px
**通过api获取设备信息**

1. screenWidth：1536.0
2. screenWidthDp：768
3. pixelRatio：2.0

**问题**
图片宽度没有100%

**Comment by lizhuoyuan** [comment]
有图片和更多的代码吗?

**Comment by yexiaodong** [comment]
`
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

class PluginFlutterScreenutilPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    ScreenUtil.init(context, width: 750, height: 1334);

    return Scaffold(
      appBar: AppBar(
        title: Text('插件-屏幕适配'),
      ),
      body: Column(
        children: <Widget>[
          Text('简单例子'),
          Image.asset('assets/images/detail.jpg',width: ScreenUtil().setWidth(750),height: ScreenUtil().setHeight(370)),

          Text('设备宽度:${ScreenUtil.screenWidth}px'),
          Text('设备宽度:${ScreenUtil.screenWidthDp}dp'),
          Text('设备的像素密度:${ScreenUtil.pixelRatio}'),
          Text('底部安全区距离:${ScreenUtil.bottomBarHeight}dp'),
          Text('状态栏高度:${ScreenUtil.statusBarHeight}dp'),
          Text('实际宽度的dp与设计稿px的比例:${ScreenUtil().scaleWidth}'),
        ],
      ),
    );
  }
}

`
![detail](https://user-images.githubusercontent.com/13914749/72981909-d4e2ec00-3e18-11ea-806a-bbee64e1d60e.jpg)

**Comment by yexiaodong** [comment]
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

class PluginFlutterScreenutilPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    ScreenUtil.init(context, width: 750, height: 1334);

    return Scaffold(
      appBar: AppBar(
        title: Text('插件-屏幕适配'),
      ),
      body: Column(
        children: <Widget>[
          Text('简单例子'),
          Image.asset('assets/images/detail.jpg',width: ScreenUtil().setWidth(750),height: ScreenUtil().setHeight(370)),

          Text('设备宽度:${ScreenUtil.screenWidth}px'),
          Text('设备宽度:${ScreenUtil.screenWidthDp}dp'),
          Text('设备的像素密度:${ScreenUtil.pixelRatio}'),
          Text('底部安全区距离:${ScreenUtil.bottomBarHeight}dp'),
          Text('状态栏高度:${ScreenUtil.statusBarHeight}dp'),
          Text('实际宽度的dp与设计稿px的比例:${ScreenUtil().scaleWidth}'),
        ],
      ),
    );
  }
}

![detail](https://user-images.githubusercontent.com/13914749/72982387-e8db1d80-3e19-11ea-8c44-12bd5ccfa491.jpg)

**Comment by lizhuoyuan** [comment]
设置图片fit的参数

**Comment by yexiaodong** [comment]
谢谢
