### ISSUE TITLE
我的设计图是375的，按照上面的尺寸匹配字体比设计图中大

### ISSUE THREAD

**Issue by xiechunyan** [OpenFlutter/flutter_screenutil#93]
我的设计图是375的，初始化使用 ScreenUtil.init(context, width: 375, height: 667);设置fontSize为ScreenUtil().setWidth(22)，显得比设计图中大很多，这个怎么解决呢？

**Comment by lizhuoyuan** [comment]
这个是要输入px的，你看一下单位

**Comment by xiechunyan** [comment]
单位是px的

**Comment by lizhuoyuan** [comment]
不确定到底是哪里问题，除非贴代码。
但如果真是375px宽度下的22px的话 ， 这个字体还是很大的， 一行大概能放40个数字左右吧

**Comment by xiechunyan** [comment]
文字是按照宽度算的大小？我是按照设计图上的高度来的emm...

**Comment by lizhuoyuan** [comment]
我只是给你折算一下让你参考是哪里出了问题

**Comment by xiechunyan** [comment]
按照宽度算的话看起来差不多，文字的高度是比宽度要大一点的，我用的苹果模拟器测试的，应该没有系统缩放

**Comment by xiechunyan** [comment]
谢谢你哈，没问题了，文字确实不应该取高度，用CSS插件取出来的没问题
