### ISSUE TITLE
What about landscape width and height?

### ISSUE THREAD

**Issue by sj602** [OpenFlutter/flutter_screenutil#94]
How can it be changed to width and height when it's landscape view (not portrait)?

is it reversed? (width becomes height and vice versa)

**Comment by lizhuoyuan** [comment]
Are you talking about rotating the screen?

**Comment by sj602** [comment]
yup

**Comment by lizhuoyuan** [comment]
Yes, if you rotate the screen, it will re-lay out according to the new size
