### ISSUE TITLE
蓝湖上面的字体与设置的字体不一样，跟设计稿上的有差别

### ISSUE THREAD

**Issue by JamesBondPc** [OpenFlutter/flutter_screenutil#96]

**Comment by lizhuoyuan** [comment]
字体我不管的啊。。 是你自己要设置字体

**Comment by JamesBondPc** [comment]
是按照UI图上设置的，跟不适用这个工具有差别，感觉偏大了，不知道是这个工具问题，还是字体问题

**Comment by lizhuoyuan** [comment]
看看是不是字体大小或者手机缩放或者适配啥的原因吧

**Comment by JamesBondPc** [comment]
不是，设计稿上是19sp, 56px ，ScreenUtil().setSp(56) 算出来的却是21.33333 sp跟设计稿上不一样
&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "LiZhuoyuan"<notifications@github.com&gt;; 
发送时间: 2020年2月28日(星期五) 晚上6:18
收件人: "OpenFlutter/flutter_screenutil"<flutter_screenutil@noreply.github.com&gt;; 
抄送: "James Bond"<710774798@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [OpenFlutter/flutter_screenutil] 蓝湖上面的字体与设置的字体不一样，跟设计稿上的有差别 (#96)




看看是不是字体大小或者手机缩放或者适配啥的原因吧

**Comment by lizhuoyuan** [comment]
![image](https://user-images.githubusercontent.com/15923901/75541905-aaa8cd80-5a59-11ea-871e-0b94209924d7.png)
把这个填进去

**Comment by JamesBondPc** [comment]
是填的这个，算出来的18.666666666666664，跟设计稿上19，相差0.4,不知道会不会有影响






------------------ 原始邮件 ------------------
发件人: "LiZhuoyuan"<notifications@github.com&gt;; 
发送时间: 2020年2月28日(星期五) 晚上6:39
收件人: "OpenFlutter/flutter_screenutil"<flutter_screenutil@noreply.github.com&gt;; 
抄送: "James Bond"<710774798@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [OpenFlutter/flutter_screenutil] 蓝湖上面的字体与设置的字体不一样，跟设计稿上的有差别 (#96)





 把这个填进去

**Comment by JamesBondPc** [comment]
print(ScreenUtil().setSp(56));
 print(ScreenUtil.screenWidth);
 print(ScreenUtil.screenHeight); 设置了56px，算出来的sp是21.3333333336与设计稿上面的18.67不一样，请问这是什么原因呢！很奇怪






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "LiZhuoyuan"<notifications@github.com&gt;; 
发送时间: 2020年2月28日(星期五) 晚上6:39
收件人: "OpenFlutter/flutter_screenutil"<flutter_screenutil@noreply.github.com&gt;; 
抄送: "James Bond"<710774798@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [OpenFlutter/flutter_screenutil] 蓝湖上面的字体与设置的字体不一样，跟设计稿上的有差别 (#96)





 把这个填进去

**Comment by JamesBondPc** [comment]
> ![image](https://user-images.githubusercontent.com/15923901/75541905-aaa8cd80-5a59-11ea-871e-0b94209924d7.png)
> 把这个填进去

**Comment by JamesBondPc** [comment]
> > ![image](https://user-images.githubusercontent.com/15923901/75541905-aaa8cd80-5a59-11ea-871e-0b94209924d7.png)
> > 把这个填进去

已经填了，算出来的还是不对

**Comment by JamesBondPc** [comment]
> print(ScreenUtil().setSp(56)); print(ScreenUtil.screenWidth); print(ScreenUtil.screenHeight); 设置了56px，算出来的sp是21.3333333336与设计稿上面的18.67不一样，请问这是什么原因呢！很奇怪
